objects/Account.object
<CustomObject>
    <fields>
        <fullName>Rating_State__c</fullName>
        <label>Rating State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status defines if the 2-50 customer account is active or termed based on the active file or the term file that it was updated from.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
                <value>
                    <fullName>Migrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>X2_50</fullName>
        <active>true</active>
        <label>2-50</label>
    </recordTypes>
</CustomObject>

objects/Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Contracts__c</fullName>
        <label>Contracts</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Groups__c</fullName>
        <label>Groups</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Business_Indicator__c</fullName>
        <label>New Business Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>Y</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>On_Cycle__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field checks to be true if a record is on-cycle termed when termination date is exactly a month before renewal date provided that it is the same year or if the termination month is 12 and the renewal month is 1. The formula for this field exist on Enrollment_import_2_50 and its mapped here</description>
        <label>On Cycle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Processed_Type__c</fullName>
        <description>Identifies if the record was from the Medical (M) or the Ancillary (A) file</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Processed Type</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Anniversary_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Renewal Anniversary Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporting_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will hold the static data of Reporting_Checkbox_on_cycle__c</description>
        <inlineHelpText>holds the static data of Reporting_Checkbox_formula_on_cycle__c</inlineHelpText>
        <label>Reporting Checkbox_On_Cycle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rpt_Dt__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Rpt Dt</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>System</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <description>This object holds the actual enrollment data which is associated to the opportunity</description>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Enrollments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>X2_50</fullName>
        <active>true</active>
        <description>2-50 Enrollment Record Type</description>
        <label>2-50</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enrollment__c</fullName>
        <label>Enrollment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AON Exchange</fullName>
                </value>
                <value>
                    <fullName>CareFirst Connect</fullName>
                </value>
                <value>
                    <fullName>CF Private Exchange</fullName>
                </value>
                <value>
                    <fullName>DBE/Admin</fullName>
                </value>
                <value>
                    <fullName>Direct Auto</fullName>
                </value>
                <value>
                    <fullName>Direct Plus/CF Hub</fullName>
                </value>
                <value>
                    <fullName>Other/CF Hub</fullName>
                </value>
                <value>
                    <fullName>Paper</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GeneralProducer__c</fullName>
        <inlineHelpText>A GP is an agency that acts as the prim.contact and recipient of compensation and comm. on behalf of mult. brokers and/or agencies that are contracted. GPs are pd fees for their admin. services and commissions for sales made by the brokers they administer</inlineHelpText>
        <label>GeneralProducer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Benefit Design Group, LLC</fullName>
                </value>
                <value>
                    <fullName>BenefitMall</fullName>
                </value>
                <value>
                    <fullName>CBIZ</fullName>
                </value>
                <value>
                    <fullName>Crawford Advisors, LLC</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Employee Benefits Corporation of America</fullName>
                </value>
                <value>
                    <fullName>Group Benefit Services</fullName>
                </value>
                <value>
                    <fullName>Hamilton Insurance Agency</fullName>
                </value>
                <value>
                    <fullName>Insurance Marketing Center, Inc.</fullName>
                </value>
                <value>
                    <fullName>Kelly &amp; Associates Insurance Group</fullName>
                </value>
                <value>
                    <fullName>NCAS</fullName>
                </value>
                <value>
                    <fullName>Potomac Basin Group Assoc., Inc.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Anniversary_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Renewal Anniversary Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Risk_Non_Risk__c</fullName>
        <label>Risk/Non-Risk</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Non-Risk</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>System</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Facets</fullName>
                </value>
                <value>
                    <fullName>NASCO</fullName>
                </value>
                <value>
                    <fullName>National Alliance</fullName>
                </value>
                <value>
                    <fullName>LuminX</fullName>
                </value>
                <value>
                    <fullName>Network Lease</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>X2_50</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <description>2-50 Opportunity Record Type</description>
        <label>2-50</label>
    </recordTypes>
</CustomObject>

classes/EnrollmentDeletionBatchJobTest.cls
/*************************************************************************************************************************************************
*  Date             : 05/30/2018
*  Developer        : Thejaswi Ganesh
*  Purpose          : Test Class for EnrollmentDeletionBatchJob
*
*  Update History:
* ----------------------------------------------------------------------------------------------------------------------------------------------
*  Author          Date-Modified      Tag      Description of Change
* ----------------------------------------------------------------------------------------------------------------------------------------------
* Thejaswi Ganesh  05/30/2018                  Initial Creation
*
************************************************************************************************************/

@isTest
public class EnrollmentDeletionBatchJobTest {
    
    static testMethod void testBatchJob() {
        test.startTest();
        List<Account> accounts = createTestAccounts();
        List<Opportunity> opps = createTestOpportunities( accounts );
        createTestEnrollments( accounts );
        EnrollmentDeletionBatchJob batchJob = new EnrollmentDeletionBatchJob();//default mode
        Database.executeBatch(batchJob);
        EnrollmentDeletionBatchJob batchJob2 = new EnrollmentDeletionBatchJob('initial');
        Database.executeBatch(batchJob2);
        EnrollmentDeletionBatchJob batchJob1 = new EnrollmentDeletionBatchJob('yearly');
        Database.executeBatch(batchJob1);
        test.stopTest();
    }
    
    private static List<Account> createTestAccounts() {
        Account a1 = new Account( Name = 'Test Account',
                                 Rating_State__c = 'M',
                                 RecordTypeId = QueryBase.getRecordtypeId( 'Account', 'X2_50') );
        
        List<Account> lA = new List<Account>();
        lA.add( a1 );
        insert lA;
        return lA;
    }
    
    private static List<Opportunity> createTestOpportunities( List<Account> accounts ) {
        Opportunity o1 = new Opportunity(   AccountId = accounts[0].Id,
                                         RecordTypeId = QueryBase.getRecordtypeId( 'Opportunity', 'X2_50' ),
                                         Name = 'Test Opp 1',
                                         CloseDate = date.newInstance(2013, 1, 1),
                                         Effective_Date__c = date.newInstance(2013, 2, 1),
                                         Contract_End_Date__c = date.newInstance(2013, 12, 31),
                                         StageName = 'Proposal',
                                         System__c = 'Facets',
                                         Risk_Non_Risk__c = 'Non-Risk',
                                         GeneralProducer__c = 'Direct');
        List<Opportunity> lO = new List<Opportunity>();
        lO.add( o1 );
        insert lO;
        return lo;
    }
    
    private static void createTestEnrollments( List<Account> accounts ) {
        
        // Get an Opp
        Opportunity o1 = [SELECT Id, Name, AccountId
                          FROM Opportunity
                          WHERE Account.Rating_State__c = 'M'
                          LIMIT 1];
        
        
        // MD
        List<Enrollment__c> lE = new List<Enrollment__c>();
        Enrollment__c E1 = new Enrollment__c();
        E1.RecordTypeId = QueryBase.getRecordtypeId( 'Enrollment__c', 'X2_50');
        E1.Opportunity__c = o1.Id;
        E1.Processed_Type__c = 'M';
        E1.Rpt_Dt__c = '201312';
        E1.Contracts__c = 100;
        E1.Groups__c = 5;
        E1.Status__c = 'Active';
        E1.On_Cycle__c = true;
        E1.New_Business_Indicator__c = 'N';
        E1.Renewal_Anniversary_Date__c = Date.newInstance( 2013, 12, 01 );
        E1.On_Cycle__c = true;
        E1.Reporting_Checkbox__c = true;
        lE.add( E1 );
        
        Enrollment__c E2 = new Enrollment__c();
        E2.RecordTypeId = QueryBase.getRecordtypeId( 'Enrollment__c', 'X2_50');
        E2.Opportunity__c = o1.Id;
        E2.Processed_Type__c = 'M';
        E2.Rpt_Dt__c = '201512';
        E2.Contracts__c = 100;
        E2.Groups__c = 5;
        E2.Status__c = 'Active';
        E2.On_Cycle__c = true;
        E2.New_Business_Indicator__c = 'N';
        E2.Renewal_Anniversary_Date__c = Date.newInstance( 2013, 12, 01 );
        E2.On_Cycle__c = true;
        E2.Reporting_Checkbox__c = true;
        lE.add( E2 );
        insert lE;
    }
    
}