objects/Account.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <description>This field is technical field which is used in filters of list views</description>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Dedicated Rep</fullName>
                </value>
                <value>
                    <fullName>Account Dedicated Rep Back-up</fullName>
                </value>
                <value>
                    <fullName>Account Executive</fullName>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Actuary</fullName>
                </value>
                <value>
                    <fullName>AE BA</fullName>
                </value>
                <value>
                    <fullName>AIA Admin</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Audit Manager/Supervisor</fullName>
                </value>
                <value>
                    <fullName>BeneFact Coder</fullName>
                </value>
                <value>
                    <fullName>BeneFact Portal Tech</fullName>
                </value>
                <value>
                    <fullName>Benefit Admin Account Set-up</fullName>
                </value>
                <value>
                    <fullName>Benefit Admin Mgr/Sup</fullName>
                </value>
                <value>
                    <fullName>Benefit Admin Workflow Mgmt</fullName>
                </value>
                <value>
                    <fullName>Benefit Contract Manager</fullName>
                </value>
                <value>
                    <fullName>Benefit Contract Specialist</fullName>
                </value>
                <value>
                    <fullName>Benefit NASCO Tester</fullName>
                </value>
                <value>
                    <fullName>Billing Tech</fullName>
                </value>
                <value>
                    <fullName>BlueExchange Coder</fullName>
                </value>
                <value>
                    <fullName>Blue Rewards</fullName>
                </value>
                <value>
                    <fullName>Business Integration Manager</fullName>
                </value>
                <value>
                    <fullName>CAS</fullName>
                </value>
                <value>
                    <fullName>Cede Document Upload</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Contract Coordinator</fullName>
                </value>
                <value>
                    <fullName>Contract Supervisor</fullName>
                </value>
                <value>
                    <fullName>Contract Tech</fullName>
                </value>
                <value>
                    <fullName>Corporate Marketing Communications</fullName>
                </value>
                <value>
                    <fullName>Customer Support</fullName>
                </value>
                <value>
                    <fullName>Enrollment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Segment_New__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>51-199 New Business</fullName>
                </value>
                <value>
                    <fullName>51-199 Renewals</fullName>
                </value>
                <value>
                    <fullName>CFA</fullName>
                </value>
                <value>
                    <fullName>Commercial Business</fullName>
                </value>
                <value>
                    <fullName>FEHBP Account Management</fullName>
                </value>
                <value>
                    <fullName>Labor Affairs</fullName>
                </value>
                <value>
                    <fullName>NCAS</fullName>
                </value>
                <value>
                    <fullName>State &amp; Municipalities</fullName>
                </value>
                <value>
                    <fullName>Healthcare/Education/Par</fullName>
                </value>
                <value>
                    <fullName>Strategic Accounts 1000+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead_Rep_Name_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up will be based off of the Lead Rep Name on the user record to be displayed on the Opportunity object.</description>
        <inlineHelpText>This look-up will be based off of the Lead Rep Name on the user record to be displayed on the Opportunity object.</inlineHelpText>
        <label>Lead Rep Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Lead_Rep__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Rep_Number_User__c</fullName>
        <description>The Lead Rep Number populates from the Lead Rep Name</description>
        <formula>Lead_Rep_Name_User__r.Lead_Rep_Number__c</formula>
        <inlineHelpText>The Lead Rep Number populates from the Lead Rep Name</inlineHelpText>
        <label>Lead Rep Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Rep_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Lead Rep #(s)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NASCO_Acct_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Must be 5 digits and may contain no more than 4 Account numbers</inlineHelpText>
        <label>NASCO Acct. #</label>
        <length>23</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>System</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Facets</fullName>
                </value>
                <value>
                    <fullName>NASCO</fullName>
                </value>
                <value>
                    <fullName>National Alliance</fullName>
                </value>
                <value>
                    <fullName>LuminX</fullName>
                </value>
                <value>
                    <fullName>Network Lease</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity_Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Contact Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>51+</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Firm Executive</fullName>
                    <label>Account Executive</label>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Primary Broker</fullName>
                    <label>Broker Agent of Record</label>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                    <isActive>false</isActive>
                    <label>Administrative</label>
                </value>
                <value>
                    <fullName>Adversary</fullName>
                    <isActive>false</isActive>
                    <label>Adversary</label>
                </value>
                <value>
                    <fullName>Agent</fullName>
                    <isActive>false</isActive>
                    <label>Agent</label>
                </value>
                <value>
                    <fullName>Broker for Client</fullName>
                    <isActive>false</isActive>
                    <label>Broker for Client</label>
                </value>
                <value>
                    <fullName>Consultant to Client</fullName>
                    <isActive>false</isActive>
                    <label>Consultant to Client</label>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                    <isActive>false</isActive>
                    <label>Decision Maker</label>
                </value>
                <value>
                    <fullName>Evaluator</fullName>
                    <isActive>false</isActive>
                    <label>Evaluator</label>
                </value>
                <value>
                    <fullName>Executive Sponsor</fullName>
                    <isActive>false</isActive>
                    <label>Executive Sponsor</label>
                </value>
                <value>
                    <fullName>Full Service Producer</fullName>
                    <isActive>false</isActive>
                    <label>Full Service Producer</label>
                </value>
                <value>
                    <fullName>General Producer</fullName>
                    <isActive>false</isActive>
                    <label>General Producer</label>
                </value>
                <value>
                    <fullName>Group</fullName>
                    <isActive>false</isActive>
                    <label>Group</label>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                    <isActive>false</isActive>
                    <label>Group Administrator</label>
                </value>
                <value>
                    <fullName>Influencer - Positive</fullName>
                    <isActive>false</isActive>
                    <label>Influencer - Positive</label>
                </value>
                <value>
                    <fullName>Surveyor</fullName>
                    <isActive>false</isActive>
                    <label>Surveyor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard_Contact_Role_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Standard Contact Role ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <description>This is a custom object to replicate the standard Opportunity Contact Role. It is created to support the updates to be sent to Broker Hub(632.0 project).</description>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Lead_Rep_Number__c</fullName>
        <description>The Lead Rep Number will be populated for all Lead Reps as a 4 digit number.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Lead Rep Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OpportunityContactRoleTriggerHandler.cls
/*=========================================================================================
 * Date         : 08/21/2016
 * Developer    : Ahilesh Radhakrishnan
 * Purpose      : This is a trigger handler class for custom opportunity contact role object(Opportunity_Contact_Role__c). 
 *                It contains methods called from OpportunityContactRoleTrigger  when the records are inserted and deleted
 *
 *=========================================================================================
 *                                 Update History
 *                                 ---------------
 * Date       Developer         Description
 *===========+============+================================================================

 *=========================================================================================
 */
 
public class OpportunityContactRoleTriggerHandler extends TriggerHandler {

    // This method will be called when there is a before insert operation
    protected override void beforeInsert(){
           
            createStdContactRoleInsert(trigger.new);
    }
    // This method will be called when there is a before update operation
    protected override void beforeUpdate(){
           
            updateStdContactRoleUpdate(trigger.new);
    }
    
    // This method will be called when there is a after insert operation
    protected override void afterInsert(){
           
            processBrokerHubOppContactRoleInsert(trigger.new);
    }
    
    // This method will be called when there is a before delete operation
    protected override void beforeDelete(){
            
            deleteStdContactRoleInsert(trigger.old);
    }
     // This method will be called when there is a after delete operation
    protected override void afterDelete(){
             
          hardDeleteCustomOCR(trigger.old);
    }
    private void hardDeleteCustomOCR(list<Opportunity_Contact_Role__c> ocrList){        
          Database.emptyRecycleBin(ocrList);
    }
    //Method to delete the standard contact role records corresponding to the seleted custom opportunity contact role record
    private void deleteStdContactRoleInsert(list<Opportunity_Contact_Role__c> ocrList){
            try{
                String bccProfileName = 'BCC RUL Custom';//'51+ NPN Management-Custom';    //for all no delete access  
                Set<String> nonBCCProfiles = new Set<String>{'2+ Standard User - Custom','51+ Standard User - Custom'};//if sold & primary no delete option
                String strProfileName = [select u.Profile.Name from User u where u.id = :Userinfo.getUserId()].Profile.Name;
                system.debug('In Trigger strProfileName>>>> '+strProfileName);
                list<OpportunityContactRole> deleteOCRList = new list<OpportunityContactRole>();
                Set<Id> oppIdSet = new Set<Id>();
                for(Opportunity_Contact_Role__c c : ocrList){
                    oppIdSet.add(c.Opportunity__c);
                }
                Map<id, Opportunity> oppMap;
                if(oppIdSet.size()>0){
                    oppMap = new Map<id, Opportunity>([Select id, StageName from Opportunity where id in: oppIdSet]);
                }
                // To retrieve the standard contact roles based on the Standard_Contact_Role_ID__c field in deleted custom contact roles
                for(Opportunity_Contact_Role__c c : ocrList){
                    
                    if(strProfileName == bccProfileName){
                        c.addError('This Profile user dont have access to delete contact role');
                    }else if(nonBCCProfiles.contains(strProfileName) && oppMap != null && oppMap.get(c.Opportunity__c).StageName == 'Sold' && c.Primary__c == true){
                        c.addError('This Profile user dont have access to delete contact role for Primary records');
                    }else{
                        OpportunityContactRole ocr = new OpportunityContactRole(id=c.Standard_Contact_Role_ID__c);
                        deleteOCRList.add(ocr);
                    }
                }
                system.debug('deleteOCRList>>>>>'+deleteOCRList);
                //deleting the standard contact roles
                if(deleteOCRList.size() > 0){
                    delete deleteOCRList;
                }
            }
            catch(Exception e){
                system.debug('***Exception Message***'+e.getMessage());
                for(Opportunity_Contact_Role__c c : ocrList){
                    c.addError('There was a problem deleting the Contact Role');
                }
            }
    }
     //Method to create the standard contact role records corresponding to the newly created custom opportunity contact role record
    private void updateStdContactRoleUpdate(list<Opportunity_Contact_Role__c> ocrList){ 
            try{
                system.debug('In updateStdContactRoleUpdate'+ocrList.size());
                list<OpportunityContactRole> updateOCRList = new list<OpportunityContactRole>();
                list<OpportunityContactRole> currentOCRList= new list<OpportunityContactRole>();
                Set<Id> ocrStndrdIds = new Set<Id>();
                Map<String,Id> ocrIdMap = new Map<String,Id>();
                Database.SaveResult[] srList;
                Map<Id, Opportunity_Contact_Role__c> ocrMap = new Map<Id, Opportunity_Contact_Role__c> ([select Id,Standard_Contact_Role_ID__c,Contact_Name__c,Primary__c,Role__c,Opportunity__r.StageName from Opportunity_Contact_Role__c where id in :ocrList ]);
                system.debug('In updateStdContactRoleUpdate ocrMap>> '+ocrMap);
                if(ocrMap.size() > 0){
                    for(Opportunity_Contact_Role__c c : ocrList){                    
                        if(ocrMap.containsKey(c.id)){
                            system.debug('In updateStdContactRoleUpdate c>> '+c);
                            ocrStndrdIds.add(c.Standard_Contact_Role_ID__c);
                        }
                    }
                    system.debug('In updateStdContactRoleUpdate ocrStndrdIds>> '+ocrStndrdIds);
                    Map<Id,OpportunityContactRole> standaardOCRMap = new Map<Id, OpportunityContactRole> ([select Id,ContactId,IsPrimary,Role from OpportunityContactRole where id in: ocrStndrdIds]);
                    system.debug('In updateStdContactRoleUpdate standaardOCRMap>> '+standaardOCRMap);
                    for(Opportunity_Contact_Role__c c : ocrList){
                        system.debug('In updateStdContactRoleUpdate stndrd c>> '+c);
                        if(standaardOCRMap.containsKey(c.Standard_Contact_Role_ID__c)){
                            OpportunityContactRole stndrdOcr = standaardOCRMap.get(c.Standard_Contact_Role_ID__c);
                            stndrdOcr.ContactId = c.Contact_Name__c;
                            stndrdOcr.Role = c.Role__c;
                            stndrdOcr.IsPrimary = c.Primary__c;
                            updateOCRList.add(stndrdOcr);
                            system.debug('In updateStdContactRoleUpdate stndrdOcr>> '+stndrdOcr);                       
                        }
                    }
                    system.debug('In updateStdContactRoleUpdate updateOCRList.size()>> '+updateOCRList.size()); 
                    //inserting the standard contact roles
                    if(updateOCRList.size() > 0){
                        srList = Database.update(updateOCRList, false);
                    }
                    
                    // iterate the save results list and map the corresponding custom and standard contact role records
                    if(srList != null){
                        for(Database.SaveResult sr : srList){
                                                
                            if (sr.isSuccess()){
                                
                            }
                            else{
                                for(Database.Error err : sr.getErrors()){
                                    System.debug('The following error has occurred.'+err.getMessage());                   
                                }
                            }
                            
                        }
                    }
                }
            }
            catch(Exception e){
                system.debug('***Exception Message***'+e.getMessage());
                for(Opportunity_Contact_Role__c c : ocrList){
                    c.addError('There was a problem updating the Contact Role');
                }
            }
        
    }
    //Method to create the standard contact role records corresponding to the newly created custom opportunity contact role record
    private void createStdContactRoleInsert(list<Opportunity_Contact_Role__c> ocrList){ 
            try{
                list<OpportunityContactRole> insertOCRList = new list<OpportunityContactRole>();
                list<OpportunityContactRole> currentOCRList= new list<OpportunityContactRole>();
                list<Id> oppIds = new list<Id>();
                Map<String,Id> ocrIdMap = new Map<String,Id>();
                Database.SaveResult[] srList;
            
                for(Opportunity_Contact_Role__c c : ocrList){
                    oppIds.add(c.Opportunity__c);
                    OpportunityContactRole ocr = new OpportunityContactRole();
                    
                    // inserts to contact roles
                    ocr = new OpportunityContactRole(ContactId = c.Contact_Name__c,OpportunityId = c.Opportunity__c,Role = c.Role__c);
                    if(c.Role__c == 'Primary Broker'){
                        ocr.IsPrimary = true;
                    }
                      
                    insertOCRList.add(ocr);
                }
                
                //inserting the standard contact roles
                if(insertOCRList.size() > 0){
                    srList = Database.insert(insertOCRList, false);
                }
                
                // iterate the save results list and map the corresponding newly created custom and standard contact role records
                integer i=0,j;
                for(Database.SaveResult sr : srList){
                    j=0;
                    
                    if (sr.isSuccess()){
                        for(Opportunity_Contact_Role__c c : ocrList){
                            if(i == j){
                                // Store the standard Contact role record ID in the custom field Standard_Contact_Role_ID__c on the custom record
                                c.Standard_Contact_Role_ID__c   = sr.getId();
                             }
                             j++;   
                        }
                    }
                    else{
                        for(Database.Error err : sr.getErrors()){
                            System.debug('The following error has occurred.'+err.getMessage());                   
                        }
                    }
                    i++;
                }
            }
            catch(Exception e){
                system.debug('***Exception Message***'+e.getMessage());
                for(Opportunity_Contact_Role__c c : ocrList){
                    c.addError('There was a problem creating the Contact Role');
                }
           }
        
    }
    
    // Call out to the BrokerHubService Class
    private void processBrokerHubOppContactRoleInsert(list<Opportunity_Contact_Role__c> ocrList){
        if(System.isBatch() || System.isFuture()){
            return;
        }   
        else{
            list<Opportunity> oppList = new list<Opportunity>();
            list<Id> oppIds = new list<Id>();
            for(Opportunity_Contact_Role__c ocr : ocrList){
                oppIds.add(ocr.Opportunity__c);
            }
            oppList = [SELECT id,stagename,NASCO_Acct_ID__c,Business_Type__c,Account.AccountNumber,Account.Name,Effective_Date__c,
            Contract_End_Date__c,System__c,Lead_Rep_Name_User__r.Name,Lead_Rep_Number__c,Lead_Rep_Number_User__c,Division__c FROM Opportunity where Id IN: oppIds];
            system.debug('oppList*****'+oppList);
            if(!Test.isRunningTest()){
            BrokerHubServiceNew.processSoldOpportunityDetails(oppList);
            }
        }
    }
    
   
}