objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status defines if the 2-50 customer account is active or termed based on the active file or the term file that it was updated from.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
                <value>
                    <fullName>Migrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Implementation__c.object
<CustomObject>
    <fields>
        <fullName>AIADoc_approval_status__c</fullName>
        <defaultValue>"Not started"</defaultValue>
        <description>This field will contains the value when AIADoc is approved</description>
        <encryptionScheme>None</encryptionScheme>
        <label>AIADoc approval status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Acc_Microsoft_URL_populated__c</fullName>
        <formula>IF(NOT( ISBLANK(( Account__r.Microsite_URL__c )) ),True,False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Acc Microsoft URL populated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BD_approved__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>BD approved</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BRF_Blue_Rewards__c</fullName>
        <formula>Benefit_Request_Form__r.PP_Blue_Rewards__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BRF Blue Rewards</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BRF_CDH_Type__c</fullName>
        <formula>Benefit_Request_Form__r.PP_CDH_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BRF CDH Type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BRF_CDH__c</fullName>
        <formula>Benefit_Request_Form__r.PP_CDH__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BRF CDH</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BRF_Custom_Wellness__c</fullName>
        <formula>Benefit_Request_Form__r.PP_Custom_Wellness__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BRF Custom Wellness</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BRF_FSA_BlueFund__c</fullName>
        <formula>Benefit_Request_Form__r.PP_FSA_BlueFund__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BRF FSA BlueFund</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BRF_Funding_Arrangement__c</fullName>
        <formula>text( Benefit_Request_Form__r.Funding_Arrangements__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BRF Funding Arrangement</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BRF_Integrated_DM_Wellness__c</fullName>
        <formula>Benefit_Request_Form__r.PP_Integrated_DM_Wellness__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BRF Integrated DM/Wellness</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BRF_New_Dental_Products__c</fullName>
        <formula>Benefit_Request_Form__r.Count_of_New_Dental_products__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BRF New Dental Products</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BRF_New_Products__c</fullName>
        <formula>Benefit_Request_Form__r.Count_of_New_products__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BRF New Products</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BRF_New_Rx_Products__c</fullName>
        <formula>Benefit_Request_Form__r.Count_of_New_Rx_products__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BRF New Rx Products</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BRF_New_Vision_Products__c</fullName>
        <formula>Benefit_Request_Form__r.Count_of_New_Vision_Products__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BRF New Vision Products</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BRF_Request_Type__c</fullName>
        <formula>Text(Benefit_Request_Form__r.Request_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BRF Request Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BenefitDesign_Status__c</fullName>
        <defaultValue>"Inprocess"</defaultValue>
        <description>This value is populated whenever the BD status changes</description>
        <encryptionScheme>None</encryptionScheme>
        <label>BenefitDesign Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Benefit_Design_Document_Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be checked when Benefit Design Document is Uploaded</description>
        <label>Benefit Design Document Uploaded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect/New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>NCR</fullName>
                </value>
                <value>
                    <fullName>Off-cycle - Administrative change</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle - Benefit change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Claims_Settlem_Proc_Setup_Updated_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Claims Settlem Proc Setup/Updated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Fully_Insured_Acct_1st_Bill_Release_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Fully-Insured Acct 1st Bill Release Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>GSRF_approved__c</fullName>
        <defaultValue>"Not Approved"</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>GSRF approved</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GS_Status__c</fullName>
        <defaultValue>"Not Started"</defaultValue>
        <description>This field is populated with the GS status</description>
        <encryptionScheme>None</encryptionScheme>
        <label>GS Doc Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>AIA_Post_Sales_Implementation</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Risk_Type__c</fullName>
        <label>Risk Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Settlements_status_of_AIADoc__c</fullName>
        <defaultValue>"Not Approved"</defaultValue>
        <description>This is populated from Approver - Settlements Analyst when approved as approved</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Settlements status of AIADoc</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WPTask_update_number__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This will be incremented by 1 when ever a WPTask is updated to complete</description>
        <label>WPTask update number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>oppMarketSeg__c</fullName>
        <formula>Text(Opportunity__r.Market_Segment_New__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>oppMarketSeg</label>
        <type>Text</type>
    </fields>
    <label>Implementation</label>
    <nameField>
        <displayFormat>IMP-{000000}</displayFormat>
        <label>Implementation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workplan_Task__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Workplan Tasks</relationshipLabel>
        <relationshipName>Workplan_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_SLA__c</fullName>
        <label>Actual SLA</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Workplan Tasks</relationshipLabel>
        <relationshipName>Workplan_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Workplan Tasks</relationshipLabel>
        <relationshipName>Workplan_Tasks_Of_Oppty</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLA_Day_Type__c</fullName>
        <description>Field to check whether to consider Actual days or business days for expected date</description>
        <label>SLA Day Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Calendar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Task assigned date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>AIA - Custom Object used to capture the runtime version of tasks which are created from Workplan Task Template. The status of these tasks can be updated by the users. This object is related to Opportunity and Implementation objects since Pre-Sales &amp; Post-Sales tasks are created in this object and assigned to the user.
This object will replace the old functionality. 
This is implemented for Nov-2017 Release.</description>
    <label>Workplan Task</label>
    <nameField>
        <displayFormat>Workplan Task - {0000}</displayFormat>
        <label>Workplan Task</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Tasks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AIA_WorkPlanTaskTriggerHelper.cls
/*=========================================================================================================
* Date         : 09/15/2017 
* Developer    : Satya Phani Tirumalasetti
* Purpose      : This class is a helper class for WorkplanTaskTriggerHandler with methods for various 
*                functionalities
*===========================================================================================================
*                                 Update History
*                                 ---------------
* Date      | Developer  | Tag  | Description
*===========+============+======+===========================================================================
* 09/15/2017| Satya T    |      | Initial Version                                         
* 09/18/2017| Asif K     | T01  | Adding method to calculate difference between workplan task actual SLA
* 04/26/2018| Gayathri P | T02  | Adding methods to calculate Account team role of the owner and 
                                  Task due date in workplan task and updated Actual SLA day calculation 
                                  with respect to SLA day type 
* 06/06/2018| Gayathri P | T03  | updated the method to populate Task due date based on Total days to 
                                  complete the task
* 06/06/2018| Satya      | T04  | Added methods as a part of US1728, to change status of dependent tasks
*                                 as per the status of primary tasks, if marked as not-required/not-started. 
* 08/26/2018| Rajesh 	 | T05	| Added new fields to implementation query 
			  Nagandla      
* 10/29/2018| Gayathri P | T06  | Added a method to replace a workflow rule to update Task Start date and 
								  Task Assigned date
* 10/31/2018| Gayathri P | T07  | Added a size check for a map to avoid method call when the map is empty.
*===========+============+======+===========================================================================
*/

public with sharing class AIA_WorkPlanTaskTriggerHelper{
    AIA_Utils errLogExp = new AIA_Utils();
      public static final string NOTREQUIRED = 'Not Required';
      public static final string NOTSTARTED = 'Not Started';
       
    /** T01-Start - Method to update the Actual SLA of the workplan task. Method will be called in beforeupdate event **/
    public void updateActualSLAonWorkplanTask(list<Workplan_Task__c> lstWPtask){
        try{
        List<Workplan_Task__c> recordsToUpdate = new  List<Workplan_Task__c>();
        for(Workplan_Task__c wpTask : lstWPtask){
            if(wpTask.Status__c == AIA_Constants.COMPLETED_STATUS){
                wpTask.End_Date__c = system.today();
                //T02 -- Start Adding condition to check SLA day type
                if(wpTask.Start_Date__c != null && wpTask.End_Date__c != null) {
                    if(wpTask.SLA_Day_Type__c == AIA_Constants.CALENDER_TYPE)
                        wpTask.Actual_SLA__c = wpTask.Start_Date__c.daysBetween(wpTask.End_Date__c) ;
                    else
                        wpTask.Actual_SLA__c = AIA_CalculateDaysDiffExcludingHoliday.CalculateWorkingDays(wpTask.Start_Date__c, wpTask.End_Date__c);
                    recordsToUpdate.add(wpTask);
                }		               
            }
        }
        }
        catch(Exception e)
        {
          System.debug('MainERROR:' + e);
          errLogExp.logException(e);
             
        }
         //T02 -- End
    }
    /** T01-End **/
    
    public static void reevaluateTaskStatus(list<Workplan_Task__c> lstWPtask){
       set<id> idset = new set<id>();
       system.debug('Entered Method 3 reevaluateTaskStatus');
        for(Workplan_Task__c wpTask : lstWPtask){
            if(wpTask.Status__c == AIA_Constants.COMPLETED_STATUS){
                if(!string.isBlank(wpTask.Implementation__c)){
                    idset.add(wpTask.Implementation__c);
                }
            }
        }
        /*T05 - Start*/
		Map<id,AIA_Implementation__c> lstImp = new Map<id,AIA_Implementation__c>([Select id,Opportunity__r.AccountID,BRF_Request_Type__c,Account__c,BRF_Funding_Arrangement__c,Claims_Settlem_Proc_Setup_Updated_Date__c,
          Fully_Insured_Acct_1st_Bill_Release_Date__c,Status__c, Opportunity__r.StageName,
          GS_Status__c,BenefitDesign_Status__c,AIADoc_approval_status__c ,Settlements_status_of_AIADoc__c,
          oppMarketSeg__c ,WPTask_update_number__c,Business_Type__c,Risk_Type__c,
          opportunity__r.Business_Type__c,BD_approved__c,GSRF_approved__c,BRF_Blue_Rewards__c,
          Acc_Microsoft_URL_populated__c,BRF_CDH__c,BRF_CDH_Type__c,BRF_Custom_Wellness__c,
          BRF_FSA_BlueFund__c,BRF_Integrated_DM_Wellness__c,BRF_New_Dental_Products__c,Benefit_Design_Document_Uploaded__c,
          BRF_New_Products__c,BRF_New_Rx_Products__c,BRF_New_Vision_Products__c,Date_Implementation_Ended__c,
          BRF_Religious_Accomodation__c,BRF_Rx_Integration__c,BRF_Status__c,AIA_BD_Not_Required__c,AIA_GS_Doc_Not_Required__c,
		  vision_with_platform_indicator__c, BRF_Control_plan_680__c, BRF_FA__c,Opp_Business_Type__c, 
		  BRF_Control_plan__c, Backend_BRF_Effective_Date__c		  
          from AIA_Implementation__c where id in :idset]);
		  /*T05 - End*/
          //T07 Start
          if(lstImp.size()>0)
          //T07 End
          {
          AIA_Workplan_Task_Management wtm = new AIA_Workplan_Task_Management();
          if(!Test.isRunningTest()){
          wtm.createWorkplanTasksForSObject('update',lstImp, 'AIA_Implementation__c');
          }
        }
    }
    //T03 -- Start
    /**T02 -Start- Method to update Task due date -when the status is changed to In progress
                                                  -when the status changed to completed before changing to In progress
                                                  -when the user updates Total days to complete the task manually*/
    public void updateDueDate(Map<id,Workplan_Task__c> oldMap,list<Workplan_Task__c> lstWPtask){
        AIA_CalculateDaysDiffExcludingHoliday achd = new AIA_CalculateDaysDiffExcludingHoliday();
        List<Workplan_Task__c> recordsToUpdate = new List<Workplan_Task__c>();
        for(Workplan_Task__c wpTask:lstWPtask)
        {
            if(oldMap.get(wpTask.Id).Status__c != AIA_Constants.INPROGRESS_STATUS && (wpTask.Status__c == AIA_Constants.INPROGRESS_STATUS || wpTask.Status__c == 'Completed')) 
            {
              wpTask.Start_Date__c = Date.today();
            }
            if(wpTask.Total_Days_to_Complete_Task_SLA__c != null && (oldMap.get(wpTask.Id).Status__c != AIA_Constants.INPROGRESS_STATUS && (wpTask.Status__c == AIA_Constants.INPROGRESS_STATUS || wpTask.Status__c == 'Completed'))
             ||(oldMap.get(wpTask.Id).Total_Days_to_Complete_Task_SLA__c != wpTask.Total_Days_to_Complete_Task_SLA__c && wpTask.Start_Date__c != null)){
              Integer expectedSLA = Integer.valueOf(wpTask.Total_Days_to_Complete_Task_SLA__c);
              if(wpTask.SLA_Day_Type__c == AIA_Constants.CALENDER_TYPE)
              {
                   wpTask.ExpectedDate__c = wpTask.Start_Date__c.addDays(expectedSLA);
                   //Days left to complete the task
                   wpTask.AIA_SLA_Days__c = Date.today().daysBetween(wpTask.ExpectedDate__c);
               }
               else
               {
                   wpTask.ExpectedDate__c = achd.addBussinessDays(wpTask.Start_Date__c, expectedSLA);
                    //Days left to complete the task
                   wpTask.AIA_SLA_Days__c = AIA_CalculateDaysDiffExcludingHoliday.CalculateWorkingDays(Date.Today(),wpTask.ExpectedDate__c);
               }  
             }
         }
    }
    
    /** T06 Method to Update Task Start Date and Task Assignment Date**/
    public void updateTaskAssignedDate(Map<id,Workplan_Task__c> oldMap,list<Workplan_Task__c> lstWPtask)
    {
        for(Workplan_Task__c task: lstWPtask)
        {
            if(task.Status__c == AIA_Constants.INPROGRESS_STATUS && oldMap.get(task.id).Status__c != AIA_Constants.INPROGRESS_STATUS)
            {
               task.Start_Date__c = system.today(); 
            }
            
            if((task.Status__c == AIA_Constants.INPROGRESS_STATUS && oldMap.get(task.id).Status__c != AIA_Constants.INPROGRESS_STATUS) || (task.Status__c == AIA_Constants.INPROGRESS_STATUS && task.OwnerId != oldMap.get(task.id).ownerId))
            {
                task.AIA_Task_Assigned_Date__c = system.today();
            }
        }
    }
    /** T06 End**/ 
    
    //T03 -- End
    //T02 -- Method to check owner of the task on update
    /*public void updateAreaRoleonOwnerChange(Map<id,Workplan_Task__c> oldMap,list<Workplan_Task__c> lstWPtask)
    {
        List<Workplan_Task__c> recordsToUpdate = new List<Workplan_Task__C>();
        for(Workplan_Task__c wpTask:lstWPtask)
        {
            if(oldMap.get(wpTask.Id).OwnerId != wpTask.OwnerId)
            {
               recordsToUpdate.add(wpTask); 
            }
        }
        //When the owner is updated for any task, Account team role should get updated
        if(recordsToUpdate.size()>0)
        {
           updateAreaRole(recordsToUpdate); 
        }
   
    }
    
    //T02 -- Method to update Account area role with respect to the owner of the task
    public void updateAreaRole(List<Workplan_Task__c> lstWPtask)
    {
        try{
        Set<Id> ownerId = new Set<Id>();
        Map<Id,String> areaMapping = new Map<Id,String>();
        for(Workplan_Task__c wpt:lstWPtask)
        {
           ownerId.add(wpt.OwnerId);
        }
        List<AIA_Area_Manager__c> areaLst=[select id,name,Area_Manager__c,Area_Belong_to__c,Areas__c,recordTypeId 
                                           from AIA_Area_Manager__c 
                                           where Area_Manager__c IN:ownerId];
        for(AIA_Area_Manager__c area:areaLst)
        {
          areaMapping.put(area.Area_Manager__c,area.Area_Belong_to__c) ;  
        }
        for(Workplan_Task__c wpt:lstWPtask)
        {
           //wpt.AIA_Account_Team_Role__c = areaMapping.get(wpt.OwnerId);
           if(areaMapping.get(wpt.OwnerId)!=null)
                wpt.Account_Team_Role__c = areaMapping.get(wpt.OwnerId);
        }
        }
        catch(Exception e)
        {
          System.debug('MainERROR:' + e);
          errLogExp.logException(e);
        }
        
    }*/
    /** T02 -- End*/
    
    /**T04 - Changes start**/
    /*This method will be called from Workplan task trigger handler when task status changes to Not-started from Not-required
       If task staus changes, then will update a field in WPlan Task record to indicate the change*/
    public void UpdateWorkplanStatuss(map<id,Workplan_Task__c> newMapWPtask,Map<id,Workplan_Task__c> oldMap){
       system.debug(Logginglevel.ERROR ,'Entered Method 1');
       list<Workplan_Task__c> tasksToUpdate = new list<Workplan_Task__c>();
       
       //Get the list of tasks in the trigger context
       List<Workplan_Task__c> wpList = newMapWPtask.values();
        
        
       //Loop through all the tasks and get the tasks that are changed to Not-started status from not-required status.  
       for(Workplan_Task__c wp: wpList){
       if(wp.Status__c == NOTSTARTED && wp.Status__c != oldMap.get(wp.id).Status__c && oldMap.get(wp.id).Status__c == NOTREQUIRED){
           Workplan_Task__c wpt = new Workplan_Task__c(id=wp.id);
           wpt.NotStartedStatusCheck__c = true;
           tasksToUpdate.add(wpt);
           }
       } 
       
       //if the tasks ID set is not empty, then get the workplan task template of those workplan tasks
       if(!tasksToUpdate.isEmpty()){
          system.debug('Inside Workplan task helper UpdateWorkplanStatuss Update');
          update tasksToUpdate;
                             
        }
    }
     /**T04 - Changes End**/
    
    
}