objects/Account.object
<CustomObject>
    <fields>
        <fullName>Broker_Service_Team__c</fullName>
        <formula>IF(ISPICKVAL(Tier_Level__c,'SELECT'), 'Small Medium Group', 
IF(ISPICKVAL(Tier_Level__c,'Elite'), 'Elite', 
IF(ISPICKVAL(Tier_Level__c,'Premier'), 'Premier', 
IF(ISPICKVAL(Tier_Level__c,'Preferred'), 'Preferred','') 
)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker Service Team</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>X51</fullName>
        <active>true</active>
        <label>51+</label>
    </recordTypes>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Broker_Service_Team__c</fullName>
        <description>Enter which service team the case belongs to</description>
        <label>Broker Service Team</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SLA_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Broker Sales MD</fullName>
                </value>
                <value>
                    <fullName>Broker Sales 4</fullName>
                </value>
                <value>
                    <fullName>Retro activity Request</fullName>
                </value>
                <value>
                    <fullName>SBC Project</fullName>
                </value>
                <value>
                    <fullName>BCS Specialist</fullName>
                </value>
                <value>
                    <fullName>Small Medium Group</fullName>
                </value>
                <value>
                    <fullName>Team Royal</fullName>
                </value>
                <value>
                    <fullName>Team Indigo</fullName>
                </value>
                <value>
                    <fullName>Team Ocean</fullName>
                </value>
                <value>
                    <fullName>Team Sapphire</fullName>
                </value>
                <value>
                    <fullName>Team Sky</fullName>
                </value>
                <value>
                    <fullName>Team Teal</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Broker Escalation</fullName>
                </value>
                <value>
                    <fullName>Elite</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>Preferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facets_Category__c</fullName>
        <label>Facets Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Facets_Subject__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ACYB - CYBERATTACK</fullName>
                </value>
                <value>
                    <fullName>BF01 - BlueFund set up issues</fullName>
                </value>
                <value>
                    <fullName>BF03 - BF link missing on My Account</fullName>
                </value>
                <value>
                    <fullName>BF05 - Blue Rewards Inquiries</fullName>
                </value>
                <value>
                    <fullName>BF07 - Complaint about the vendor</fullName>
                </value>
                <value>
                    <fullName>BF09 - Unable to loc grp/vendor systm</fullName>
                </value>
                <value>
                    <fullName>BF11 - Unable to loc mbr/vendor systm</fullName>
                </value>
                <value>
                    <fullName>BF13 - Welcome Kit Inquiry/HSA only</fullName>
                </value>
                <value>
                    <fullName>BP01 - Communities</fullName>
                </value>
                <value>
                    <fullName>BP02 - Gen Broker Portal Inquiry</fullName>
                </value>
                <value>
                    <fullName>BP03 - Gen Employee Portal Inquiry</fullName>
                </value>
                <value>
                    <fullName>BP04 - Gen Hub Inquiry</fullName>
                </value>
                <value>
                    <fullName>BP05 - Group Set-Up</fullName>
                </value>
                <value>
                    <fullName>BP06 - Provisioning</fullName>
                </value>
                <value>
                    <fullName>BP07 - Quoting</fullName>
                </value>
                <value>
                    <fullName>BSA1 - Prospect Inquiry</fullName>
                </value>
                <value>
                    <fullName>BSA2 - File Update Inquiry</fullName>
                </value>
                <value>
                    <fullName>BSA3 - BOR Inquiry</fullName>
                </value>
                <value>
                    <fullName>BSA4 - Transferred to Sales Rep</fullName>
                </value>
                <value>
                    <fullName>BSA5 - Transferred to another dept</fullName>
                </value>
                <value>
                    <fullName>BSQ1 - Quote-Off Cycle Request</fullName>
                </value>
                <value>
                    <fullName>BSQ2 - Quote-Renewal Request</fullName>
                </value>
                <value>
                    <fullName>BSQ3 - Quote-New Business Request</fullName>
                </value>
                <value>
                    <fullName>BSQ4 - Quote-Late Exception Request</fullName>
                </value>
                <value>
                    <fullName>BSQ5 - Quote-Alternative</fullName>
                </value>
                <value>
                    <fullName>BSQ6 - Quote-On Exchange</fullName>
                </value>
                <value>
                    <fullName>BSQ7 - Transferred to another dept</fullName>
                </value>
                <value>
                    <fullName>DC01 - Processed Correctly</fullName>
                </value>
                <value>
                    <fullName>DC02 - Processed Incorrectly</fullName>
                </value>
                <value>
                    <fullName>DC03 - Pended Claim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facets_Subject__c</fullName>
        <label>Facets Subject</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACYB - CYBERATTACK</fullName>
                </value>
                <value>
                    <fullName>BRCP - CareFirst Portals</fullName>
                </value>
                <value>
                    <fullName>BRSA - Sales Assistance</fullName>
                </value>
                <value>
                    <fullName>BRSQ - Sales Quote</fullName>
                </value>
                <value>
                    <fullName>DCLM - Dental Claims</fullName>
                </value>
                <value>
                    <fullName>MAPP-M Appeal</fullName>
                </value>
                <value>
                    <fullName>MAUT-M Auth/Referral Inquiry</fullName>
                </value>
                <value>
                    <fullName>MBCC - Credit Card Inquiry</fullName>
                </value>
                <value>
                    <fullName>MBEI - EBill Inquiry</fullName>
                </value>
                <value>
                    <fullName>MBEN-M Benefits</fullName>
                </value>
                <value>
                    <fullName>MBFA - M BlueFund Administration</fullName>
                </value>
                <value>
                    <fullName>MBII - Invoice Inquiry</fullName>
                </value>
                <value>
                    <fullName>MBIL-M Billing</fullName>
                </value>
                <value>
                    <fullName>MBMP - Missing Payment</fullName>
                </value>
                <value>
                    <fullName>MBPA - Payment Arrangement</fullName>
                </value>
                <value>
                    <fullName>MBRR - Request to Reinstate</fullName>
                </value>
                <value>
                    <fullName>MBTI - Termination Inquiry</fullName>
                </value>
                <value>
                    <fullName>MCAC-M Credit &amp; Collection</fullName>
                </value>
                <value>
                    <fullName>MCDH-M CDH</fullName>
                </value>
                <value>
                    <fullName>MCHK-M Check Inquiry</fullName>
                </value>
                <value>
                    <fullName>MCLM-M Claim Status</fullName>
                </value>
                <value>
                    <fullName>MCMP-M Complaint Plan/Service</fullName>
                </value>
                <value>
                    <fullName>MCOB-M COB</fullName>
                </value>
                <value>
                    <fullName>MCOR - M Correspondence</fullName>
                </value>
                <value>
                    <fullName>MDED-M Deductible</fullName>
                </value>
                <value>
                    <fullName>MDEM-M Demographics</fullName>
                </value>
                <value>
                    <fullName>MDIQ-M Duplicate Inquiry</fullName>
                </value>
                <value>
                    <fullName>MDOC-M Document Request</fullName>
                </value>
                <value>
                    <fullName>MELG-M Eligibility</fullName>
                </value>
                <value>
                    <fullName>MENR - Enrollment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Group_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>To be used when Group not found in Group Name lookup</inlineHelpText>
        <label>New Group ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolution_Reason__c</fullName>
        <description>Enter External Notes that is to be viewed by external users</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Resolution Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SLA_Category__c</fullName>
        <label>SLA Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Non-Platinum</fullName>
                </value>
                <value>
                    <fullName>Broker Sales Support</fullName>
                </value>
                <value>
                    <fullName>Broker Compliance</fullName>
                </value>
                <value>
                    <fullName>Broker Escalation</fullName>
                </value>
                <value>
                    <fullName>Elite</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>Preferred</fullName>
                </value>
                <value>
                    <fullName>Select</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>SBU_Broker_Support_Internal</fullName>
        <active>true</active>
        <businessProcess>SBU Broker Support Process</businessProcess>
        <description>This record type will be used to support cases for Small/Medium SBU broker support cases</description>
        <label>SBU Broker Support Internal</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Broker_Service_Team__c</fullName>
        <formula>IF(ISBLANK(X2_50_Account__r.Broker_Service_Team__c), X51_Account__r.Broker_Service_Team__c, X2_50_Account__r.Broker_Service_Team__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker Service Team</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
    <recordTypes>
        <fullName>Community_User_Contact</fullName>
        <active>true</active>
        <description>This is the record type that will be used for community User Creation</description>
        <label>Community User Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>X51</fullName>
        <active>true</active>
        <label>51+</label>
    </recordTypes>
</CustomObject>

classes/Trigger_SBU_Attachment_Test.cls
@isTest
private class Trigger_SBU_Attachment_Test {

    static testMethod void Test1() {
        Test.startTest();
        //Create Case
        Case cas   = new Case();
        cas.Origin = 'Email: Broker Sales MD'; 
        cas.Subject = 'Test';
        cas.status = 'Assigned';
        insert cas;
        
        //Create attachment
        Attachment Attach = New Attachment();

        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=cas.id;
        insert attach;
        
        Test.stopTest();        
        System.assert([select ParentId from attachment where parentId=:cas.id].size() == 1);
    }
   
    // Test error condition
    static testMethod void Test2() {
        Test.startTest();
         //Create Account       
        Id rt_acc_51 = QueryBase.getRecordtypeId('Account', 'X51');
        Account a = new Account();
        a.Name = 'SomeTest' + Date.Today();
        a.Type = 'Customer';
        a.RecordTypeId = rt_acc_51;
        a.AccountNumber = '12345';
        insert a;
               //Create Contact
        Id rt_Con_51 = QueryBase.getRecordtypeId('Contact', 'Community_User_Contact');
        Contact con         = new Contact(); 
        con.LastName        = 'LastName';
        con.phone           ='123456789';
        con.RecordTypeId    = rt_Con_51;
        con.email           ='con@email.con';
        con.AccountId       = a.id;
        insert con;
       
        //Create case
        Id rt_Case = QueryBase.getRecordtypeId('case', 'SBU_Broker_Support_Internal');
        Case cas   = new Case();
        cas.Subject = 'Test';
        cas.Origin = 'Email: Retro activity Request';
        cas.Status = 'Closed';
        cas.Description ='testing';
        cas.SLA_Category__c='Broker Compliance';
        cas.Broker_Service_Team__c ='Compliance';
        cas.New_Group_ID__c = '1234';
        cas.Facets_Subject__c = 'MBIL-M Billing';
        cas.Facets_Category__c = 'MB63-Duplicate Bill';
        cas.ContactId = con.id;
        cas.Resolution_Reason__c = 'test reason';
        cas.Reason__c = 'C100-Others';
        cas.Facets_case_Id__c = '12345678';
        cas.RecordTypeId    = rt_Case;
        
        insert cas;
     
        //Create attachment
        Attachment Attach = New Attachment();

        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=cas.id;
        Try{
            insert attach;
            }
            catch(exception e){}
                    
          
       Test.stopTest();        
        System.assert([select ParentId from attachment where parentId=:cas.id].size() == 0);
    }
    
    static testMethod void Test3() {
        Test.startTest();
        //Create Case
        Case cas   = new Case();
        cas.Origin = 'Email: Broker Sales MD'; 
        cas.Subject = 'Test';
        cas.status = 'Assigned';
        insert cas;
        
        //Create attachment
        Attachment Attach = New Attachment();

        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=cas.id;
        insert attach;
        
         try
           {
              delete attach;
              // should throw an exception - the following assertion will cause an error if the code carries on
              System.assert(True);
           }
        catch (DMLException e){}
         
    }
}