objects/Account.object
<CustomObject>
    <fields>
        <fullName>Facets_Account_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Facets Account Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecType_Facets_Account_Number__c</fullName>
        <description>This field will hold the Concatination of Record type name and Facets Account Number Field</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>RecType Facets Account Number</label>
        <length>22</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>This field is technical field which is used in filters of list views</description>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Dedicated Rep</fullName>
                </value>
                <value>
                    <fullName>Account Dedicated Rep Back-up</fullName>
                </value>
                <value>
                    <fullName>Account Executive</fullName>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Actuary</fullName>
                </value>
                <value>
                    <fullName>AE BA</fullName>
                </value>
                <value>
                    <fullName>AIA Admin</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Audit Manager/Supervisor</fullName>
                </value>
                <value>
                    <fullName>BeneFact Coder</fullName>
                </value>
                <value>
                    <fullName>BeneFact Portal Tech</fullName>
                </value>
                <value>
                    <fullName>Benefit Admin Account Set-up</fullName>
                </value>
                <value>
                    <fullName>Benefit Admin Mgr/Sup</fullName>
                </value>
                <value>
                    <fullName>Benefit Admin Workflow Mgmt</fullName>
                </value>
                <value>
                    <fullName>Benefit Contract Manager</fullName>
                </value>
                <value>
                    <fullName>Benefit Contract Specialist</fullName>
                </value>
                <value>
                    <fullName>Benefit NASCO Tester</fullName>
                </value>
                <value>
                    <fullName>Billing Tech</fullName>
                </value>
                <value>
                    <fullName>BlueExchange Coder</fullName>
                </value>
                <value>
                    <fullName>Blue Rewards</fullName>
                </value>
                <value>
                    <fullName>Business Integration Manager</fullName>
                </value>
                <value>
                    <fullName>CAS</fullName>
                </value>
                <value>
                    <fullName>Cede Document Upload</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Contract Coordinator</fullName>
                </value>
                <value>
                    <fullName>Contract Supervisor</fullName>
                </value>
                <value>
                    <fullName>Contract Tech</fullName>
                </value>
                <value>
                    <fullName>Corporate Marketing Communications</fullName>
                </value>
                <value>
                    <fullName>Customer Support</fullName>
                </value>
                <value>
                    <fullName>Enrollment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status defines if the 2-50 customer account is active or termed based on the active file or the term file that it was updated from.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
                <value>
                    <fullName>Migrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>X51</fullName>
        <active>true</active>
        <label>51+</label>
    </recordTypes>
</CustomObject>

objects/FSP_GP__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FSP_GP__c</fullName>
        <label>FSP/GP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FSP</fullName>
                </value>
                <value>
                    <fullName>GP</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                    <isActive>false</isActive>
                    <label>Direct</label>
                </value>
                <value>
                    <fullName>None</fullName>
                    <isActive>false</isActive>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This is a custom object to add new FSP/GPs. It is created to support the updates to be sent to Broker Hub(632.0 project).</description>
    <label>FSP GP</label>
    <nameField>
        <displayFormat>FSPGP-{000000}</displayFormat>
        <label>FSP GP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSP GPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>X51</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <description>51+ Opportunity Record Type</description>
        <label>51+</label>
    </recordTypes>
</CustomObject>

objects/Opportunity_Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Firm Executive</fullName>
                    <label>Account Executive</label>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Primary Broker</fullName>
                    <label>Broker Agent of Record</label>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                    <isActive>false</isActive>
                    <label>Administrative</label>
                </value>
                <value>
                    <fullName>Adversary</fullName>
                    <isActive>false</isActive>
                    <label>Adversary</label>
                </value>
                <value>
                    <fullName>Agent</fullName>
                    <isActive>false</isActive>
                    <label>Agent</label>
                </value>
                <value>
                    <fullName>Broker for Client</fullName>
                    <isActive>false</isActive>
                    <label>Broker for Client</label>
                </value>
                <value>
                    <fullName>Consultant to Client</fullName>
                    <isActive>false</isActive>
                    <label>Consultant to Client</label>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                    <isActive>false</isActive>
                    <label>Decision Maker</label>
                </value>
                <value>
                    <fullName>Evaluator</fullName>
                    <isActive>false</isActive>
                    <label>Evaluator</label>
                </value>
                <value>
                    <fullName>Executive Sponsor</fullName>
                    <isActive>false</isActive>
                    <label>Executive Sponsor</label>
                </value>
                <value>
                    <fullName>Full Service Producer</fullName>
                    <isActive>false</isActive>
                    <label>Full Service Producer</label>
                </value>
                <value>
                    <fullName>General Producer</fullName>
                    <isActive>false</isActive>
                    <label>General Producer</label>
                </value>
                <value>
                    <fullName>Group</fullName>
                    <isActive>false</isActive>
                    <label>Group</label>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                    <isActive>false</isActive>
                    <label>Group Administrator</label>
                </value>
                <value>
                    <fullName>Influencer - Positive</fullName>
                    <isActive>false</isActive>
                    <label>Influencer - Positive</label>
                </value>
                <value>
                    <fullName>Surveyor</fullName>
                    <isActive>false</isActive>
                    <label>Surveyor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This is a custom object to replicate the standard Opportunity Contact Role. It is created to support the updates to be sent to Broker Hub(632.0 project).</description>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Partner__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>None (Direct Sale)</fullName>
                </value>
                <value>
                    <fullName>Actuary</fullName>
                    <isActive>false</isActive>
                    <label>Actuary</label>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                    <isActive>false</isActive>
                    <label>Administrator</label>
                </value>
                <value>
                    <fullName>Branch Office</fullName>
                    <isActive>false</isActive>
                    <label>Branch Office</label>
                </value>
                <value>
                    <fullName>Client</fullName>
                    <isActive>false</isActive>
                    <label>Client</label>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                    <isActive>false</isActive>
                    <label>Wholesaler</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This is a custom object to replicate the standard Partner. It is created to support the updates to be sent to Broker Hub(632.0 project). VF page will replace the existing standard Partner 'New' Page.</description>
    <label>Partner</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Partner Custom Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/NPN_Check_Test.cls
@isTest()
public class NPN_Check_Test{ 
    static testMethod void testFSPGPRelatedList() { 
        List<Opportunity> optyList = new List<Opportunity>();
        FSP_GP__c newFSP = new FSP_GP__c();
        Map<id, Opportunity_Contact_Role__c> ocrMap = new Map<id, Opportunity_Contact_Role__c>();
        
        Account acc = new Account();
        acc.name = 'Test Acc';
        //acc.name = 'Community_User_Account';//Failing in AccountUpdateForCommunityContact.UpdateAccountForCommunityContact: line 17, column 1
        //acc.Sic = '7377';
        //acc.Status__c = 'Active';
        acc.Type = 'Partner';
        acc.RecordTypeId = QueryBase.getRecordTypeId('Account','X51');
        //acc.Facets_Account_Number__c = '0X84';
        //acc.RecType_Facets_Account_Number__c = '2-50_0X84s';
        insert acc;
        
        Contact con =new Contact();
        con.FirstName= 'contact first name';
        con.LastName = 'contact last name';
        con.AccountId = acc.id;
        con.Phone = '364575678';
        con.Email = 'abcd@gnc.com';
        insert con;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp1';
        opp.Contract_End_Date__c = date.newinstance(2016,12, 31);  
        opp.CloseDate = date.newinstance(2016, 9, 30); 
        opp.Effective_Date__c = date.newinstance(2016, 10, 01);
        opp.AccountId = acc.id;
        opp.StageName = 'Proposal';
        opp.Probability = Decimal.valueOf('50');
        opp.Won_Lost_Reason__c = 'Acquisition';
        opp.SBU__c   = 'Small/Medium';
        opp.Market_Segment__c = '2-50';
        opp.Division__c = '2-50 Renewal Business';
        opp.Business_Type__c = 'Renewal';
        opp.Underwriting_Entity__c = 'DC';
        opp.FullServiceProducer__c = 'Kelly & Associates Insurance Group Inc';
        optyList.add(opp);
        insert optyList;
        
        List<Opportunity_Contact_Role__c> a = new List<Opportunity_Contact_Role__c>();
        Opportunity_Contact_Role__c oc = new Opportunity_Contact_Role__c();
        oc.Role__c = 'Primary Broker';
        oc.Opportunity__c= opp.id;
        oc.Contact_Name__c = con.id;
        a.add(oc);
        Opportunity_Contact_Role__c oc1 = new Opportunity_Contact_Role__c();
        oc1.Role__c = 'Broker';
        oc1.Opportunity__c= opp.id;
        oc1.Contact_Name__c = con.id;
        a.add(oc1);
        Insert a;
        
        
        
        
        newFSP.FSP_GP__c = acc.id;                
        newFSP.Opportunity__c = opp.Id;                
        newFSP.Primary__c = true;                
        newFSP.Effective_Date__c = date.newinstance(2016, 3, 1); 
        newFSP.End_Date__c = System.today(); 
        newFSP.FSP_GP__c = 'FSP'; 
        newFSP.Partner__c = 'Kelly & Associates Insurance Group';
        insert newFSP;
        Account acc2 = new Account();
         acc2.Name = 'TESTING2';
        acc2.Type = 'Partner';
        insert acc2;
        
        List<Partner__c> listPrtnrs = new List<Partner__c> ();
        Partner__c  prtnr = new Partner__c ();
        prtnr.Opportunity__c = opp.Id; 
        prtnr.Partner__c = acc2.id;
        prtnr.Role__c = 'Broker';
        prtnr.Primary__c = true;    
        
        
        listPrtnrs.add(prtnr);
        insert listPrtnrs;
        
        
        NPN_Check npn = new NPN_Check();
        npn.updateNPN(optyList);
        
        
        con.Phone = '1234546';
        con.Email = 'dfsc@ghj.com';
        update con;
        
    }
    
    static testMethod void testFSPGPRelatedList1() { 
        List<Opportunity> optyList = new List<Opportunity>();
        FSP_GP__c newFSP = new FSP_GP__c();
        Map<id, Opportunity_Contact_Role__c> ocrMap = new Map<id, Opportunity_Contact_Role__c>();
        
        Account acc = new Account();
        acc.name = 'Test Acc';
        //acc.name = 'Community_User_Account';//Failing in AccountUpdateForCommunityContact.UpdateAccountForCommunityContact: line 17, column 1
        //acc.Sic = '7377';
        //acc.Status__c = 'Active';
        acc.Type = 'Partner';
        acc.RecordTypeId = QueryBase.getRecordTypeId('Account','X51');
        //acc.Facets_Account_Number__c = '0X84';
        //acc.RecType_Facets_Account_Number__c = '2-50_0X84s';
        insert acc;
        
        Contact con =new Contact();
        con.FirstName= 'contact first name';
        con.LastName = 'contact last name';
        con.AccountId = acc.id;
        con.Phone = '364575678';
        con.Email = 'abcd@gnc.com';
        insert con;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp1';
        opp.Contract_End_Date__c = date.newinstance(2016,12, 31);  
        opp.CloseDate = date.newinstance(2016, 9, 30); 
        opp.Effective_Date__c = date.newinstance(2016, 10, 01);
        opp.AccountId = acc.id;
        opp.StageName = 'Proposal';
        opp.Probability = Decimal.valueOf('50');
        opp.Won_Lost_Reason__c = 'Acquisition';
        opp.SBU__c   = 'Small/Medium';
        opp.Market_Segment__c = '2-50';
        opp.Division__c = '2-50 Renewal Business';
        opp.Business_Type__c = 'Renewal';
        opp.Underwriting_Entity__c = 'DC';
        opp.FullServiceProducer__c = 'Kelly & Associates Insurance Group Inc';
        optyList.add(opp);
        insert optyList;
        
        List<Opportunity_Contact_Role__c> a = new List<Opportunity_Contact_Role__c>();
        Opportunity_Contact_Role__c oc = new Opportunity_Contact_Role__c();
        oc.Role__c = 'Primary Broker';
        oc.Opportunity__c= opp.id;
        oc.Contact_Name__c = con.id;
        oc.Primary__c = True;
        a.add(oc);
        Insert a;
        
        
        
        NPN_Check npn = new NPN_Check();
        npn.updateNPN(optyList);
        
        
        con.Phone = '1234546';
        con.Email = 'dfsc@ghj.com';
        update con;
        
    }
    
    
}