objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Legal_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Team__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AccountTeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TeamMemberRole__c</fullName>
        <label>Team Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Dedicated Representative</fullName>
                </value>
                <value>
                    <fullName>Account Executive</fullName>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Actuary</fullName>
                </value>
                <value>
                    <fullName>AIA Admin</fullName>
                </value>
                <value>
                    <fullName>AIA User</fullName>
                </value>
                <value>
                    <fullName>Auditor</fullName>
                </value>
                <value>
                    <fullName>Automated Enrollment Tech</fullName>
                </value>
                <value>
                    <fullName>BCM Coordinator</fullName>
                </value>
                <value>
                    <fullName>BeneFact Coder</fullName>
                </value>
                <value>
                    <fullName>BeneFact Portal Tech</fullName>
                </value>
                <value>
                    <fullName>BeneFact Tester</fullName>
                </value>
                <value>
                    <fullName>Benefit Admin Manager</fullName>
                </value>
                <value>
                    <fullName>Benefit Coder</fullName>
                </value>
                <value>
                    <fullName>Benefit Contract Specialist</fullName>
                </value>
                <value>
                    <fullName>Benefit Design Approvers</fullName>
                </value>
                <value>
                    <fullName>Benefit Tester</fullName>
                </value>
                <value>
                    <fullName>Billing Tech</fullName>
                </value>
                <value>
                    <fullName>BlueFund</fullName>
                </value>
                <value>
                    <fullName>Blue Rewards Tech</fullName>
                </value>
                <value>
                    <fullName>Cede Document Tech</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Client Advisory Services</fullName>
                </value>
                <value>
                    <fullName>Contract Coordinator</fullName>
                </value>
                <value>
                    <fullName>Contract Manager</fullName>
                </value>
                <value>
                    <fullName>Contract Tech</fullName>
                </value>
                <value>
                    <fullName>Enrollment Tech</fullName>
                </value>
                <value>
                    <fullName>Facets Migration Contact</fullName>
                </value>
                <value>
                    <fullName>Implementation Coordinator</fullName>
                </value>
                <value>
                    <fullName>Implementation Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AccountTeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Team</label>
    <nameField>
        <displayFormat>ATM-{000000}</displayFormat>
        <label>AccountTeamMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Configurations__mdt.object
<CustomObject>
    <fields>
        <fullName>Parameter_Value__c</fullName>
        <label>Parameter Value</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <description>This is used to store the Large Group AIA Configurations</description>
    <label>AIA Configuration</label>
    <pluralLabel>AIA Configurations</pluralLabel>
</CustomObject>

objects/AIA_Document__c.object
<CustomObject>
    <fields>
        <fullName>Account_Executive_Account_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>US171 Account Executive (Account Team)</description>
        <label>Account Executive (Account Team)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AIA_Documents9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Legal_Name__c</fullName>
        <formula>Account__r.Account_Legal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Approvals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BAA_Customized_Email_Body__c</fullName>
        <formula>"Please Review and electronically sign the Business Associate Agreement by clicking the Review Document above. " &amp; BR()&amp; BR() &amp; "Thank You" &amp; BR() &amp;    submitter__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BAA Customized Email Body</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Benefit_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Request Form</label>
        <referenceTo>Benfit_Request_Form__c</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Docusign_Recipient_user_email__c</fullName>
        <formula>IF( Text(Document_Type__c)=='Custom BAA' , Implementation__r.DocuSign_Recipient_Email__c  ,'')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Docusign Recipient user email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Docusign_send_user_name__c</fullName>
        <formula>IF( Text(Document_Type__c)=='Custom BAA' ,Implementation__r.DocuSign_Recipient_Name__c  ,'')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Docusign Recipient user name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>AIA Documents</relationshipLabel>
        <relationshipName>AIA_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AIA Document</label>
    <nameField>
        <displayFormat>FD-{000000}</displayFormat>
        <label>AIA Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AIA Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Recordtype for all AIA Documents other than Docusign documents like BAA, BAC etc</description>
        <label>Standard</label>
    </recordTypes>
</CustomObject>

objects/AIA_Implementation__c.object
<CustomObject>
    <fields>
        <fullName>Account_Legal_Name__c</fullName>
        <formula>Account__r.Account_Legal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Benefit_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Request Form</label>
        <referenceTo>Benfit_Request_Form__c</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Implementation</label>
    <nameField>
        <displayFormat>IMP-{000000}</displayFormat>
        <label>Implementation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Benfit_Request_Form__c.object
<CustomObject>
    <fields>
        <fullName>Account_Executive_Account_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>B-03719 used to populate Account Executive added at BRF's related Account</description>
        <label>Account Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Benefit_Request_Forms_AE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Legal_Name__c</fullName>
        <formula>Opportunity__r.Account.Account_Legal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Manager_Account_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>B-03719 used to populate Account Manager added at BRF's related Account</description>
        <label>Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Benefit_Request_Forms_AM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Request Forms</relationshipLabel>
        <relationshipName>Benfit_Request_Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager_Account_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>populate Implementation Manager added at BRF's related Account</description>
        <label>Implementation Manager (Account Team)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Benefit_Request_FormseosX</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <formula>TEXT(Opportunity__r.Business_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Type</label>
        <type>Text</type>
    </fields>
    <description>New object for AIA - This object stores the information that is needed for a quote</description>
    <label>Benefit Request Form</label>
    <nameField>
        <displayFormat>BRF-{000000}</displayFormat>
        <label>Benefit Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Request Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AIA_Send_Customized_BAA_For_Docusign.cls
/*=======================================================================================================
* Date         : 11/29/2017
* Developer    : Satya Tirumalasetti
* Purpose      : Controller for the VF page which is called when Send For Docusign button is clicked
*                on the AIA Document record. This will redirect the page to Docusign page.
*=======================================================================================================
*                                 Update History
*                                 ---------------
* Date      +  Developer   + Tag + Description
*===========+==============+============================================================================
* 11/29/2017|  Satya       |     | Initial Version.
* 12/01/2017|  Satya       | T01 | Added skip validation rules hasSkipVRs_CustPerm, so for users having 
*                                  this permission set, won't get any VR error 
* 12/26/2017|  Satya       | T02 | Changes as a part of US527. Replaced Imp Manger to IMP PM. Also changed 
 *                                  code to get roles directly from Acc Team roles (Earlier used to get 
 *                                  from BRF.) 
* 01/30/2019 | Satya T     | T03 | Replaced standard Account Team Member with Custom Account Team Member.            
*===========+==============+=====+======================================================================
*/

public without sharing class AIA_Send_Customized_BAA_For_Docusign {
    public Id DocID {get;set;}
    public AIA_Document__c DocObject;
    public Id UserId;
    public string Profile;
    public string Email;
    public string UserName;
   // public list<AccountTeamMember> accteamlst; T03
    public list<Account_Team__c> accteamlst; //T03
    public set<string> teamuidNew = new set<string>(); //New business
    public set<string> teamuidRenewal = new set<string>(); //Renewal business
    public final string SYSADMIN ='System Administrator';
    Public final string F2SYSADMIN ='System Administrator 2FA - custom';
    Public final string APPROVED ='Approved';
    Public final string ERRORMSG ='This User is not authorized to send document for signature';
    public static boolean hasSkipVRs_CustPerm = CF_CustomPermissionsReader_Helper.Permissions.Docusign_ignoreVRs;//T01
    //Constructor
    public AIA_Send_Customized_BAA_For_Docusign(ApexPages.StandardController controller){
        DocID =controller.getId();
        //get the AIA Document record in context
        DocObject =[select id,Approval_Status__c,Name,Account_Legal_Name__c,Implementation__r.Benefit_Request_Form__c,Implementation__r.Benefit_Request_Form__r.Opportunity_Type__c,
                            Implementation__r.Benefit_Request_Form__r.Implementation_Manager_Account_Team__c,Implementation__r.Benefit_Request_Form__r.Account_Executive_Account_Team__c,
                            Implementation__r.Benefit_Request_Form__r.Account_Manager_Account_Team__c,BAA_Customized_Email_Body__c,Docusign_Recipient_user_email__c,Docusign_send_user_name__c,
                            Implementation__r.Account__c
                    from AIA_Document__c 
                    where id =:DocID ];
        //Get the current user details
        UserId =UserInfo.getUserId();
        Profile =[select id, name from profile where Id =:UserInfo.getProfileId()].Name;
        Email =UserInfo.getUserEmail();
        UserName =UserInfo.getName();
        /* T03 -- Start*/
        /* //T02 changes starts
      accteamlst = [SELECT UserId,TeamMemberRole 
                      FROM AccountTeamMember 
                      WHERE AccountId =: DocObject.Implementation__r.Account__c And 
                            (TeamMemberRole ='Account Executive' OR 
                             TeamMemberRole ='Implementation Manager' OR 
                             TeamMemberRole ='Account Manager')];
       
           for(AccountTeamMember acteam:accteamlst){
                // put the Account team members id in set
                If(acteam.TeamMemberRole == 'Implementation Manager'){teamuidNew.add(acteam.UserId);}
                If(acteam.TeamMemberRole != 'Implementation Manager'){teamuidRenewal.add(acteam.UserId);}   
                
           } 
           //T02  changes ends*/
            accteamlst = [SELECT UserId__c,TeamMemberRole__c,AccountId__c
                      FROM Account_Team__c
                      WHERE AccountId__c =: DocObject.Implementation__r.Account__c And 
                            (TeamMemberRole__c ='Account Executive' OR 
                             TeamMemberRole__c ='Implementation Manager' OR 
                             TeamMemberRole__c ='Account Manager')];
       
           for(Account_Team__c acteam:accteamlst){
                // put the Account team members id in set
                If(acteam.TeamMemberRole__c == 'Implementation Manager'){teamuidNew.add(acteam.UserId__c);}
                If(acteam.TeamMemberRole__c != 'Implementation Manager'){teamuidRenewal.add(acteam.UserId__c);}   
                
           } 
            /* T03 -- End*/
    }
    //method to redirect to Docusign page upon succesful validation check
    public PageReference sendToBAADocusign(){
        string name =DocObject.Account_Legal_Name__c ;
        string sourceId =DocObject.id ;
        string remail = DocObject.Docusign_Recipient_user_email__c;
        string rname = DocObject.Docusign_send_user_name__c;
        string msg = DocObject.BAA_Customized_Email_Body__c; 
        msg = (!String.isBlank(msg))?msg.replaceAll('<br>', '\n'):'';
        
        string VPName;
        string VPEmail;
        
        For(AIA_Configurations__mdt DName :[Select id,DeveloperName,Parameter_Value__c from AIA_Configurations__mdt where (DeveloperName ='Docusign_VP_Name' OR DeveloperName ='Docusign_VP_Email' )]){
            if(DName.DeveloperName == 'Docusign_VP_Name'){VPName = DName.Parameter_Value__c ;}
            if(DName.DeveloperName == 'Docusign_VP_Email'){VPEmail = DName.Parameter_Value__c;}
        }
        string RC='';
        string RSL='';
        string RSRO='';
        string RROS='';
        string CCRM='';
        string CCTM='';
        string CCNM='';
        string CRL='Email~'+remail+';LastName~'+rname+';RoutingOrder~1;Role~Signer 1,Email~'+VPEmail+';LastName~'+VPName+';RoutingOrder~3;Role~Signer 3';
        string CRCL='';  //string CRL='Email~'+remail+';LastName~'+rname+';RoutingOrder~1;Role~Signer 1,Email~lakshmianusha.adabala@carefirst.com;LastName~Lakshmi;RoutingOrder~3;Role~Signer 3';
        string OCO='';
        string DST='';
        string LA='';
        string CEM=msg;
        string CES='Business Associate Agreement (BAA) for ';
        string STB='';
        string SSB='';
        string SES='';
        string SEM='';
        string SRS='';
        string SCS ='';
        string RES='';
        //to send document for signature, current user should be one of IM/AE/AM role
        system.debug('DocObject.Approval_Status__c==APPROVED' + DocObject.Approval_Status__c);
        system.debug('DocObject.Approval_Status__c==APPROVED' + APPROVED);
        system.debug('DocObject.Approval_Status__c==APPROVED' + (DocObject.Approval_Status__c==APPROVED));
        system.debug('DocObject.Implementation__r.Benefit_Request_Form__c!=null' + DocObject.Implementation__r.Benefit_Request_Form__c!=null);
        system.debug('UserId ==DocObject.Implementation__r.Benefit_Request_Form__r.Implementation_Manager_Account_Team__c' + (UserId ==DocObject.Implementation__r.Benefit_Request_Form__r.Implementation_Manager_Account_Team__c));
        system.debug('DocObject.Implementation__r.Benefit_Request_Form__r.Opportunity_Type__c ==' + (DocObject.Implementation__r.Benefit_Request_Form__r.Opportunity_Type__c=='New'));
        
        if(DocObject.Approval_Status__c==APPROVED && 
           DocObject.Implementation__r.Benefit_Request_Form__c!=null && 
           ((DocObject.Implementation__r.Benefit_Request_Form__r.Opportunity_Type__c =='New' && 
             (teamuidNew.contains(UserId) || hasSkipVRs_CustPerm)) || 
            (DocObject.Implementation__r.Benefit_Request_Form__r.Opportunity_Type__c =='Renewal' && 
             (teamuidRenewal.contains(UserId)|| hasSkipVRs_CustPerm )))) //T01,T02
        {
            String pgRefURL = '/apex/dsfs__DocuSign_CreateEnvelope?DSEID=0&SourceID='+sourceId;
            pgRefURL = pgRefURL + '&RC='+RC+'&RSL='+RSL+'&RSRO='+RSRO+'&RROS='+RROS+'&CCRM='+CCRM+'&CCTM='+CCTM+'&CRCL='+CRCL+'&CRL='+CRL;
            pgRefURL = pgRefURL + '&OCO='+OCO+'&DST='+DST+'&CCNM='+CCNM+'&LA='+LA+'&CEM='+CEM+'&CES='+CES+name;
            pgRefURL = pgRefURL + '&SRS='+SRS+'&STB='+STB+'&SSB='+SSB+'&SES='+SES+'&SEM='+SEM+'&SRS='+SRS+'&SCS='+SCS+'&RES='+RES;
            //to redirect user to Docusign page 
            PageReference pgRef =new PageReference(pgRefURL);   
            pgRef.setRedirect(true); 
            return pgRef;
        }else{
            ApexPages.Message myMsg =new ApexPages.Message(ApexPages.severity.error,ERRORMSG);
            ApexPages.AddMessage(myMsg);
        }
        return null; 
    }
    //method to go back to AIA Document record
    public PageReference Back(){
        return new PageReference('/'+DocObject.id);
    }
}