objects/Account.object
<CustomObject>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <label>Jurisdiction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>VA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>CEDE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rating_State__c</fullName>
        <label>Rating State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status defines if the 2-50 customer account is active or termed based on the active file or the term file that it was updated from.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
                <value>
                    <fullName>Migrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>X2_50</fullName>
        <active>true</active>
        <label>2-50</label>
    </recordTypes>
    <recordTypes>
        <fullName>X51</fullName>
        <active>true</active>
        <label>51+</label>
    </recordTypes>
</CustomObject>

objects/DynamicCodeDataStore__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>NOTE: The name field should be updated with caution as code may be referencing its value.  The email field should be a valid email address.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Text_255__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Text_255</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Used as a general dynamic data store for code to use as opposed to hard coding values</description>
    <label>Dynamic Code Data Store</label>
</CustomObject>

objects/Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>Nasco number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contracts__c</fullName>
        <label>Contracts</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Groups__c</fullName>
        <label>Groups</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Business_Indicator__c</fullName>
        <label>New Business Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>Y</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>On_Cycle__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field checks to be true if a record is on-cycle termed when termination date is exactly a month before renewal date provided that it is the same year or if the termination month is 12 and the renewal month is 1. The formula for this field exist on Enrollment_import_2_50 and its mapped here</description>
        <label>On Cycle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Processed_Type__c</fullName>
        <description>Identifies if the record was from the Medical (M) or the Ancillary (A) file</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Processed Type</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Anniversary_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Renewal Anniversary Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporting_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will hold the static data of Reporting_Checkbox_on_cycle__c</description>
        <inlineHelpText>holds the static data of Reporting_Checkbox_formula_on_cycle__c</inlineHelpText>
        <label>Reporting Checkbox_On_Cycle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rpt_Dt__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Rpt Dt</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary_Checkbox__c</fullName>
        <description>This field checks true if either the status is active and the rpt_dt__c is a specified numbers/dates for the same Renewal anniversary year as the Year of the Rpt_dt, or status is termed and is on cycle.  
Note: This field is being used by Joe for the block report. this check box also looks at december 2013 active file</description>
        <formula>if(
	OR(
		AND(
			AND(
				(Rpt_Dt__c="201412" || (Rpt_Dt__c="201312") || Rpt_Dt__c="201512" || Rpt_Dt__c="201612" || Rpt_Dt__c="201712" || Rpt_Dt__c="201812"|| Rpt_Dt__c="201904"), 
				(Left(Rpt_Dt__c,4) = TEXT(YEAR(Renewal_Anniversary_Date__c)))
			),
			ISBLANK(Termination_Date__c) ),
      			(
				AND(
					NOT(ISBLANK(Termination_Date__c)),
					On_Cycle__c = True)
			)
	),
True,False
)



/**********************************************************/
/*if(OR(AND(Rpt_Dt__c="201412", ISBLANK(Termination_Date__c)), 
      AND(Rpt_Dt__c="201312", ISBLANK(Termination_Date__c)),
     (AND(NOT(ISBLANK(Termination_Date__c)),On_Cycle__c = True))),True,False)
*/
/*
if( OR(AND(Rpt_Dt__c="201412" || (Rpt_Dt__c="201312") ,  ISBLANK(Termination_Date__c) ),
      (AND(NOT(ISBLANK(Termination_Date__c)),On_Cycle__c = True))),True,False)
*/</formula>
        <label>Summary_Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <description>This object holds the actual enrollment data which is associated to the opportunity</description>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Enrollments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>X2_50</fullName>
        <active>true</active>
        <description>2-50 Enrollment Record Type</description>
        <label>2-50</label>
    </recordTypes>
    <recordTypes>
        <fullName>X51</fullName>
        <active>true</active>
        <description>51+ Enrollment Record Type</description>
        <label>51+</label>
    </recordTypes>
</CustomObject>

objects/Enrollment_Summary_51_Terms__c.object
<CustomObject>
    <fields>
        <fullName>Contracts__c</fullName>
        <description>Holds the current Termed Contract count for 51+.</description>
        <inlineHelpText>Holds the current Termed Contract count for 51+.</inlineHelpText>
        <label>Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Groups__c</fullName>
        <description>Holds the current value of Termed Groups for 51+.</description>
        <inlineHelpText>Holds the current Termed Contract count for 51+.</inlineHelpText>
        <label>Groups</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <description>Jurisdiction to which the total pertains.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Jurisdiction to which the total pertains.</inlineHelpText>
        <label>Jurisdiction</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the current # of Termed Contracts and Groups for 51+.</description>
    <label>Enrollment Summary 51+ Terms</label>
</CustomObject>

objects/Enrollment_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <description>Report Date, format is YYYYMM.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Report Date, format is YYYYMM.</inlineHelpText>
        <label>Date</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <label>Jurisdiction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>VA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>On_Cycle_Contracts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>On Cycle Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>On_Cycle_Groups__c</fullName>
        <defaultValue>0</defaultValue>
        <label>On Cycle Groups</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>On_Cycle_Termed_Contracts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>On Cycle Termed Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Contracts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Groups__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Groups</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Termed_Contracts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Termed Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Termed_Groups__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Termed Groups</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <description>Unique ID to be used for upserting records.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID to be used for upserting records.</inlineHelpText>
        <label>Unique ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Enrollment Summary</label>
    <nameField>
        <displayFormat>SE-{00000}</displayFormat>
        <label>Enrollment Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>X2_50</fullName>
        <active>true</active>
        <label>2-50</label>
    </recordTypes>
    <recordTypes>
        <fullName>X51</fullName>
        <active>true</active>
        <label>51+</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Enrollment__c</fullName>
        <label>Enrollment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AON Exchange</fullName>
                </value>
                <value>
                    <fullName>CareFirst Connect</fullName>
                </value>
                <value>
                    <fullName>CF Private Exchange</fullName>
                </value>
                <value>
                    <fullName>DBE/Admin</fullName>
                </value>
                <value>
                    <fullName>Direct Auto</fullName>
                </value>
                <value>
                    <fullName>Direct Plus/CF Hub</fullName>
                </value>
                <value>
                    <fullName>Other/CF Hub</fullName>
                </value>
                <value>
                    <fullName>Paper</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Segment_New__c</fullName>
        <description>This field is replacing the old Market_Segment__c field.  The old field label was changed to Market Segment History</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SBU__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>2-50</fullName>
                </value>
                <value>
                    <fullName>51-199</fullName>
                </value>
                <value>
                    <fullName>200-999</fullName>
                </value>
                <value>
                    <fullName>1000+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Anniversary_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Renewal Anniversary Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBU__c</fullName>
        <label>SBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Small/Medium</fullName>
                </value>
                <value>
                    <fullName>Large</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
                <value>
                    <fullName>FEHBP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>X2_50</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <description>2-50 Opportunity Record Type</description>
        <label>2-50</label>
    </recordTypes>
    <recordTypes>
        <fullName>X51</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <description>51+ Opportunity Record Type</description>
        <label>51+</label>
    </recordTypes>
</CustomObject>

classes/Enrollment_2_50_Batch_Summary.cls
/**********************************************************************************************************
* Name        - Enrollment_2_50_Batch_Summary
* Description - Batch class to handle Summarizing the 2-50 Enrollment records
*               into the Summary object, so we can do some reporting.
*               This is how you call it:
*               List<Enrollment__c> lE = [SELECT Id FROM Enrollment__c LIMIT 5];
*               database.executebatch(new Enrollment_2_50_Batch_Summary(lE));
*                   
* Modification Log :
* ---------------------------------------------------------------------------------------------------------
* Developer            Date         Tag       Description
* ---------------------------------------------------------------------------------------------------------
* jmasters (EP)        12-09-2014           Created 
* Tom Barrett (TPB)    08/18/2015   TPB     Updated to remove hard coded email reference
*                                           and commented out Error check because we
*                                           want an email sent when job completes 
*                                           whether it passes or fails.   
*                            
* Tom Barrett (TPB)    03/26/2016   TPB     Made changes to handle a new custom setting field that will allow for
*                                           muliple email addresses to be entered dynamically without changing code
* Thejaswi Ganesh      05/30/2018   T01     Added StartDate condition to the query for 
*                                           Enrollment Deletion Batch Job Evolution.                                            
************************************************************************************************************/
global without sharing class Enrollment_2_50_Batch_Summary implements Database.Batchable<sObject> {
    //BEGIN CHANGE TPB 03/26/2016 - Commented code between 08/18/2015 Changes
    // BEGIN CHANGE TPB 08/18/2015    
    //private static DynamicCodeDataStore__c cs = DynamicCodeDataStore__c.getInstance('sfdcTeamEmail');
    //private static string notificationRecipientEmail = cs.Email__c;
    // END CHANGE TPB 08/18/2015
    private static DynamicCodeDataStore__c cs = DynamicCodeDataStore__c.getInstance('EmailSupportTeams');
    private static string[] toAddresses = cs.Text_255__c.Split(',');
    // END CHANGE TPB 03/26/2016
    // NOTE: When testing comment out static varible line above and uncomment line below
    //private static string notificationRecipientEmail = 'someone@carefirst.com';
    private string enrollment2_50RecordTypeID = '';
    private string enrollment51RecordTypeId = '';
    private string summary2_50RecordTypeID = '';
    private string summary51RecordTypeID = '';
    
    // Map for the Totals
    // ex: 20140101MD, 5103
    global Map<String, Decimal> totalContracts = new Map<String, Decimal>();        // line 1
    global Map<String, Decimal> onCycleContracts = new Map<String, Decimal>();      // lines 2 & 3
    global Map<String, Decimal> termedContracts = new Map<String, Decimal>();       // line 4
    global Map<String, Decimal> onCycleContractTerms = new Map<String, Decimal>();  // lines 5 & 6
    global Map<String, Decimal> newContracts = new Map<String, Decimal>();          // line 7
    
    global Map<String, Decimal> totalGroups = new Map<String, Decimal>();           // line 1
    global Map<String, Decimal> onCycleGroups = new Map<String, Decimal>();         // lines 2 & 3
    global Map<String, Decimal> termedGroups = new Map<String, Decimal>();          // line 4
    global Map<String, Decimal> onCycleGroupTerms = new Map<String, Decimal>();     // lines 5 & 6
    global Map<String, Decimal> newGroups = new Map<String, Decimal>();             // line 7
    
    // 12-12-2014 jhm: This is our core query.    
    String StartDate = String.valueOf(System.Today().year()-2)+'-01-01';//T01
    private string query = 'SELECT Rpt_Dt__c, Opportunity__r.Account.Rating_State__c, Contracts__c, Groups__c, On_Cycle__c, ' +
        'New_Business_Indicator__c, Status__c, RecordTypeId, Renewal_Anniversary_Date__c, ' +
        'Reporting_Checkbox__c, Summary_Checkbox__c ' +
        'FROM Enrollment__c ' +
        'WHERE Processed_Type__c = \'M\' ' +
        'AND Opportunity__r.Account.Rating_State__c != null ' +
        'AND Account_Number__c NOT IN (\'1RA7\', \'1RA8\', \'1RA9\') '+
        'AND Rpt_Dt__c >= \''+StartDate+'\''; //T01 
    //'AND Opportunity__r.Account.Rating_State__c = \'V\' ' +
    //'AND Account_Number__c NOT IN (\'1RA7\', \'1RA8\', \'1RA9\') '+//;
    //'AND (Rpt_Dt__c = \'201311\' OR Renewal_Anniversary_Date__c = 2013-11-01)';  
    
    
    // Constructor
    global Enrollment_2_50_Batch_Summary( List<Enrollment__c> enrollments ) {
        // get the Record Type ID
        enrollment2_50RecordTypeID = (string)QueryBase.getRecordtypeId('Enrollment__c', 'X2_50' );
        enrollment51RecordTypeID = (string)QueryBase.getRecordtypeId('Enrollment__c', 'X51' );
        // Add the record type to the query
        //query += 'AND RecordTypeID = \'' + enrollment2_50RecordTypeID + '\'';
        
        // get the summary record types
        summary2_50RecordTypeId = (string)QueryBase.getRecordtypeId( 'Enrollment_Summary__c', 'X2_50' );
        summary51RecordTypeId = (string)QueryBase.getRecordtypeId( 'Enrollment_Summary__c', 'X51' );
    }
    
    global Database.QueryLocator start( Database.BatchableContext BC ) {
        // Clear out existing data
        deleteExistingSummaryData();
        // Get the 51+ Termed magic number
        get51PlusMagicNumbers();
        
        return Database.getQueryLocator(query);
    }
    
    global void execute( Database.BatchableContext Info, List<Sobject> batch) {
        // repopulate the maps, so we total everything; not just one batch.
        rePopulateMaps();
        // do some stuff with the batch
        summarizeBatch( batch );
    }
    
    global void finish( Database.BatchableContext BC ) {
        // Get the record for this job
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                          FROM AsyncApexJob
                          WHERE Id = :BC.getJobId()];
        
        //TPB 08/18/2015        if( a.NumberOfErrors > 0 ) {       
        // If so, let someone know about them.
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        // BEGIN CHANGE TPB 03/26/2016
        //String[] toAddresses = new String[] {notificationRecipientEmail};  // Add others, if necessary.
        // END CHANGE TPB 03/26/2016
        
        mail.setToAddresses( toAddresses );
        mail.setSubject( 'Batch Enrollment Summary Job ' + a.Status );
        mail.setPlainTextBody( 'The batch job processed ' + a.TotalJobItems + ' batches with ' + a.NumberOfErrors + ' failures.' );
        Messaging.sendEmail( new Messaging.SingleEmailMessage[] {mail} );
        //TPB 08/18/2015       }       
    }
    
    // Delete existing data
    private void deleteExistingSummaryData() {
        // Clear everything out.
        List<Enrollment_Summary__c> lES = [SELECT Id FROM Enrollment_Summary__c];
        delete lES;
    }
    
    // Add any other methods we need to actually do some work.
    public void summarizeBatch( List<sObject> batch ) {
        List<Enrollment__c> enrollments = (List<Enrollment__c>)batch;
        
        for( Enrollment__c e : enrollments ) {
            // Maryland
            if( e.Opportunity__r.Account.Rating_State__c == 'M' ||
               e.Opportunity__r.Account.Rating_State__c == 'R' ) {
                   if( enrollment2_50RecordTypeId == e.RecordTypeId ) {
                       if( 'N' == e.New_Business_Indicator__c ) {
                           // See if there's already a TOTAL entry for this date/jurisdiction
                           if( 'Active' == e.Status__c  ) {
                               if( totalContracts.containsKey( e.Rpt_Dt__c + 'MD' + e.RecordTypeId ) ) {
                                   // update
                                   if( null != e.Contracts__c ) {
                                       totalContracts.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, totalContracts.get(e.Rpt_Dt__c + 'MD' + e.RecordTypeId) + e.Contracts__c );
                                   }
                               } else {
                                   // create it
                                   if( null != e.Contracts__c ) {
                                       totalContracts.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, e.Contracts__c );
                                   }
                               }
                               // total groups, too
                               if( totalGroups.containsKey( e.Rpt_Dt__c + 'MD' + e.RecordTypeId ) ) {
                                   // update
                                   if( null != e.Groups__c ) {
                                       totalGroups.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, totalGroups.get(e.Rpt_Dt__c + 'MD' + e.RecordTypeId) + e.Groups__c );
                                   }
                               } else {
                                   // create it
                                   if( null != e.Groups__c ) {
                                       totalGroups.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, e.Groups__c );
                                   }
                               }
                               // See if there's already an ON-CYCLE entry for this date/jurisdiction
                               // 12-15-2014 jhm: Can't use the check-box determine on/off cycle, per Salman
                               // 12-16-2014 jhm: Use different check-box and Renewal Anniversary Date, instead.
                               if( null != e.Renewal_Anniversary_Date__c && true == e.Summary_Checkbox__c ) {
                                   String sDate = formatDate( e.Renewal_Anniversary_Date__c );
                                   if( onCycleContracts.containsKey( formatDate( e.Renewal_Anniversary_Date__c ) + 'MD' + e.RecordTypeId ) ) {
                                       // update
                                       if( null != e.Contracts__c ) {
                                           onCycleContracts.put( formatDate( e.Renewal_Anniversary_Date__c ) + 'MD' + e.RecordTypeId, onCycleContracts.get(formatDate( e.Renewal_Anniversary_Date__c ) + 'MD' + e.RecordTypeId) + e.Contracts__c );
                                       }
                                   } else {
                                       // create it
                                       if( null != e.Contracts__c ) {
                                           onCycleContracts.put( formatDate( e.Renewal_Anniversary_Date__c ) + 'MD' + e.RecordTypeId, e.Contracts__c );
                                       }
                                   }
                                   // groups, too
                                   if( onCycleGroups.containsKey( formatDate( e.Renewal_Anniversary_Date__c ) + 'MD' + e.RecordTypeId ) ) {
                                       // update
                                       if( null != e.Groups__c ) {
                                           onCycleGroups.put( formatDate( e.Renewal_Anniversary_Date__c ) + 'MD' + e.RecordTypeId, onCycleGroups.get(formatDate( e.Renewal_Anniversary_Date__c ) + 'MD' + e.RecordTypeId) + e.Groups__c );
                                       }
                                   } else {
                                       // create it
                                       if( null != e.Groups__c ) {
                                           onCycleGroups.put( formatDate( e.Renewal_Anniversary_Date__c ) + 'MD' + e.RecordTypeId, e.Groups__c );
                                       }
                                   }
                               }
                           } else if( ( 'Termed' == e.Status__c && enrollment2_50RecordTypeID == e.RecordTypeId ) ||       // <-- 2-50 criteria
                                     ( enrollment51RecordTypeID == e.RecordTypeId && e.Opportunity__r.StageName == 'Dead' ) ) {
                                         //( enrollment51RecordTypeID == e.RecordTypeId && e.Opportunity__r.StageName == 'Dead' &&
                                         // The below criteria, provided by Salman, yield no results.
                                         //e.Opportunity__r.SBU__c == 'Small/Medium' && e.Opportunity__r.Market_Segment_New__c == '51-199' ) ) {
                                         // See if there's already a TERMED entry for this date/jurisdiction
                                         if( termedContracts.containsKey( e.Rpt_Dt__c + 'MD' + e.RecordTypeId ) ) {
                                             // update
                                             if( null != e.Contracts__c ) {
                                                 termedContracts.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, termedContracts.get(e.Rpt_Dt__c + 'MD' + e.RecordTypeId) + e.Contracts__c );
                                             }
                                         } else {
                                             // create it
                                             if( null != e.Contracts__c ) {
                                                 termedContracts.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, e.Contracts__c );
                                             }
                                         }
                                         // groups, too
                                         if( termedGroups.containsKey(e.Rpt_Dt__c + 'MD' + e.RecordTypeId ) ) {
                                             // update
                                             if( null != e.Groups__c ) {
                                                 termedGroups.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, termedGroups.get(e.Rpt_Dt__c + 'MD' + e.RecordTypeId) + e.Groups__c );
                                             }
                                         } else {
                                             // create it
                                             if( null != e.Groups__c ) {
                                                 termedGroups.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, e.Groups__c );
                                             }
                                         }
                                         // See if there's already an on-cycle TERMED entry for this date/jurisdiction
                                         // 12-15-2014 jhm: Can't use the check-box determine on/off cycle, per Salman
                                         // 12-16-2014 jhm: Use different check-box and Renewal Anniversary Date, instead.
                                         if( null != e.Renewal_Anniversary_Date__c && true == e.Summary_Checkbox__c ) {
                                             if( true == e.Reporting_Checkbox__c || true == e.Summary_Checkbox__c ) {        // ON CYCLE
                                                 if( onCycleContractTerms.containsKey( formatDate(e.Renewal_Anniversary_Date__c) + 'MD' + e.RecordTypeId ) ) {
                                                     // update
                                                     if( null != e.Contracts__c ) {
                                                         onCycleContractTerms.put( formatDate(e.Renewal_Anniversary_Date__c) + 'MD' + e.RecordTypeId, onCycleContractTerms.get(formatDate(e.Renewal_Anniversary_Date__c) + 'MD' + e.RecordTypeId) + e.Contracts__c );
                                                     }
                                                 } else {
                                                     // create it
                                                     if( null != e.Contracts__c ) {
                                                         onCycleContractTerms.put( formatDate(e.Renewal_Anniversary_Date__c) + 'MD' + e.RecordTypeId, e.Contracts__c );
                                                     }
                                                 }
                                                 // groups, too
                                                 if( onCycleGroupTerms.containsKey(formatDate(e.Renewal_Anniversary_Date__c) + 'MD' + e.RecordTypeId ) ) {
                                                     // update
                                                     if( null != e.Groups__c ) {
                                                         onCycleGroupTerms.put( formatDate(e.Renewal_Anniversary_Date__c) + 'MD' + e.RecordTypeId, onCycleGroupTerms.get(formatDate(e.Renewal_Anniversary_Date__c) + 'MD' + e.RecordTypeId) + e.Groups__c );
                                                     }
                                                 } else {
                                                     // create it
                                                     if( null != e.Groups__c ) {
                                                         onCycleGroupTerms.put( formatDate(e.Renewal_Anniversary_Date__c) + 'MD' + e.RecordTypeId, e.Groups__c );
                                                     }
                                                 }
                                             }
                                         }
                                     } // termed
                       }  // new business
                       if('Y' == e.New_Business_Indicator__c ) {
                           if( newContracts.containsKey( e.Rpt_Dt__c + 'MD' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Contracts__c ) {
                                   newContracts.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, newContracts.get(e.Rpt_Dt__c + 'MD' + e.RecordTypeId) + e.Contracts__c );
                               }
                           } else {
                               // create it
                               if( null != e.Contracts__c ) {
                                   newContracts.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, e.Contracts__c );
                               }
                           }
                           // Groups
                           if( newGroups.containsKey( e.Rpt_Dt__c + 'MD' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Groups__c ) {
                                   newGroups.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, newGroups.get(e.Rpt_Dt__c + 'MD' + e.RecordTypeId) + e.Groups__c );
                               }
                           } else {
                               // create it
                               if( null != e.Groups__c ) {
                                   newGroups.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, e.Groups__c );
                               }
                           }
                       }
                       // For 51+, the New Business Indicator and Status are apparently irrelevant
                   } else if( enrollment51RecordTypeId == e.RecordTypeId ) {
                       if( 'N' == e.New_Business_Indicator__c ) {
                           if( totalContracts.containsKey( e.Rpt_Dt__c + 'MD' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Contracts__c ) {
                                   totalContracts.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, totalContracts.get(e.Rpt_Dt__c + 'MD' + e.RecordTypeId) + e.Contracts__c );
                               }
                           } else {
                               // create it
                               if( null != e.Contracts__c ) {
                                   totalContracts.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, e.Contracts__c );
                               }
                           }
                       } else if( 'Y' == e.New_Business_Indicator__c ){    // New Business
                           if( newContracts.containsKey( e.Rpt_Dt__c + 'MD' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Contracts__c ) {
                                   newContracts.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, newContracts.get(e.Rpt_Dt__c + 'MD' + e.RecordTypeId) + e.Contracts__c );
                               }
                           } else {
                               // create it
                               if( null != e.Contracts__c ) {
                                   newContracts.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, e.Contracts__c );
                               }
                           }
                           // Groups
                           if( newGroups.containsKey( e.Rpt_Dt__c + 'MD' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Groups__c ) {
                                   newGroups.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, newGroups.get(e.Rpt_Dt__c + 'MD' + e.RecordTypeId) + e.Groups__c );
                               }
                           } else {
                               // create it
                               if( null != e.Groups__c ) {
                                   newGroups.put( e.Rpt_Dt__c + 'MD' + e.RecordTypeId, e.Groups__c );
                               }
                           }
                       }
                   }
                   // DC
               } else if( e.Opportunity__r.Account.Rating_State__c == 'D' ) {
                   if( enrollment2_50RecordTypeId == e.RecordTypeId ) {
                       if( 'N' == e.New_Business_Indicator__c ) {
                           // See if there's already a TOTAL entry for this date/jurisdiction
                           if( 'Active' == e.Status__c  ) {
                               if( totalContracts.containsKey( e.Rpt_Dt__c + 'DC' + e.RecordTypeId ) ) {
                                   // update
                                   if( null != e.Contracts__c ) {
                                       totalContracts.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, totalContracts.get(e.Rpt_Dt__c + 'DC' + e.RecordTypeId) + e.Contracts__c );
                                   }
                               } else {
                                   // create it
                                   if( null != e.Contracts__c ) {
                                       totalContracts.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, e.Contracts__c );
                                   }
                               }
                               // total groups, too
                               if( totalGroups.containsKey( e.Rpt_Dt__c + 'DC' + e.RecordTypeId ) ) {
                                   // update
                                   if( null != e.Groups__c ) {
                                       totalGroups.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, totalGroups.get(e.Rpt_Dt__c + 'DC' + e.RecordTypeId) + e.Groups__c );
                                   }
                               } else {
                                   // create it
                                   if( null != e.Groups__c ) {
                                       totalGroups.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, e.Groups__c );
                                   }
                               }
                               // See if there's already an ON-CYCLE entry for this date/jurisdiction
                               // 12-15-2014 jhm: Can't use the check-box determine on/off cycle, per Salman
                               // 12-16-2014 jhm: Use different check-box and Renewal Anniversary Date, instead.
                               if( null != e.Renewal_Anniversary_Date__c && true == e.Summary_Checkbox__c ) {
                                   String sDate = formatDate( e.Renewal_Anniversary_Date__c );
                                   if( onCycleContracts.containsKey( formatDate( e.Renewal_Anniversary_Date__c ) + 'DC' + e.RecordTypeId ) ) {
                                       // update
                                       if( null != e.Contracts__c ) {
                                           onCycleContracts.put( formatDate( e.Renewal_Anniversary_Date__c ) + 'DC' + e.RecordTypeId, onCycleContracts.get(formatDate( e.Renewal_Anniversary_Date__c ) + 'DC' + e.RecordTypeId) + e.Contracts__c );
                                       }
                                   } else {
                                       // create it
                                       if( null != e.Contracts__c ) {
                                           onCycleContracts.put( formatDate( e.Renewal_Anniversary_Date__c ) + 'DC' + e.RecordTypeId, e.Contracts__c );
                                       }
                                   }
                                   // groups, too
                                   if( onCycleGroups.containsKey( formatDate( e.Renewal_Anniversary_Date__c ) + 'DC' + e.RecordTypeId ) ) {
                                       // update
                                       if( null != e.Groups__c ) {
                                           onCycleGroups.put( formatDate( e.Renewal_Anniversary_Date__c ) + 'DC' + e.RecordTypeId, onCycleGroups.get(formatDate( e.Renewal_Anniversary_Date__c ) + 'DC' + e.RecordTypeId) + e.Groups__c );
                                       }
                                   } else {
                                       // create it
                                       if( null != e.Groups__c ) {
                                           onCycleGroups.put( formatDate( e.Renewal_Anniversary_Date__c ) + 'DC' + e.RecordTypeId, e.Groups__c );
                                       }
                                   }
                               }
                           } else if( 'Termed' == e.Status__c && enrollment2_50RecordTypeID == e.RecordTypeId ) {
                               // See if there's already a TERMED entry for this date/jurisdiction
                               if( termedContracts.containsKey( e.Rpt_Dt__c + 'DC' + e.RecordTypeId ) ) {
                                   // update
                                   if( null != e.Contracts__c ) {
                                       termedContracts.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, termedContracts.get(e.Rpt_Dt__c + 'DC' + e.RecordTypeId) + e.Contracts__c );
                                   }
                               } else {
                                   // create it
                                   if( null != e.Contracts__c ) {
                                       termedContracts.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, e.Contracts__c );
                                   }
                               }
                               // groups, too
                               if( termedGroups.containsKey(e.Rpt_Dt__c + 'DC' + e.RecordTypeId ) ) {
                                   // update
                                   if( null != e.Groups__c ) {
                                       termedGroups.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, termedGroups.get(e.Rpt_Dt__c + 'DC' + e.RecordTypeId) + e.Groups__c );
                                   }
                               } else {
                                   // create it
                                   if( null != e.Groups__c ) {
                                       termedGroups.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, e.Groups__c );
                                   }
                               }
                               // See if there's already an on-cycle TERMED entry for this date/jurisdiction
                               // 12-15-2014 jhm: Can't use the check-box determine on/off cycle, per Salman
                               // 12-16-2014 jhm: Use different check-box and Renewal Anniversary Date, instead.
                               if( null != e.Renewal_Anniversary_Date__c && (true == e.Reporting_Checkbox__c || true == e.Summary_Checkbox__c ) ) {
                                   if( true == e.Reporting_Checkbox__c || true == e.Summary_Checkbox__c ) {        // ON CYCLE
                                       if( onCycleContractTerms.containsKey( formatDate(e.Renewal_Anniversary_Date__c) + 'DC' + e.RecordTypeId ) ) {
                                           // update
                                           if( null != e.Contracts__c ) {
                                               onCycleContractTerms.put( formatDate(e.Renewal_Anniversary_Date__c) + 'DC' + e.RecordTypeId, onCycleContractTerms.get(formatDate(e.Renewal_Anniversary_Date__c) + 'DC' + e.RecordTypeId) + e.Contracts__c );
                                           }
                                       } else {
                                           // create it
                                           if( null != e.Contracts__c ) {
                                               onCycleContractTerms.put( formatDate(e.Renewal_Anniversary_Date__c) + 'DC' + e.RecordTypeId, e.Contracts__c );
                                           }
                                       }
                                       // groups, too
                                       if( onCycleGroupTerms.containsKey(formatDate(e.Renewal_Anniversary_Date__c) + 'DC' + e.RecordTypeId ) ) {
                                           // update
                                           if( null != e.Groups__c ) {
                                               onCycleGroupTerms.put( formatDate(e.Renewal_Anniversary_Date__c) + 'DC' + e.RecordTypeId, onCycleGroupTerms.get(formatDate(e.Renewal_Anniversary_Date__c) + 'DC' + e.RecordTypeId) + e.Groups__c );
                                           }
                                       } else {
                                           // create it
                                           if( null != e.Groups__c ) {
                                               onCycleGroupTerms.put( formatDate(e.Renewal_Anniversary_Date__c) + 'DC' + e.RecordTypeId, e.Groups__c );
                                           }
                                       }
                                   }
                               }
                           } // termed
                       }  // new business
                       if('Y' == e.New_Business_Indicator__c ) {
                           if( newContracts.containsKey( e.Rpt_Dt__c + 'DC' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Contracts__c ) {
                                   newContracts.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, newContracts.get(e.Rpt_Dt__c + 'DC' + e.RecordTypeId) + e.Contracts__c );
                               }
                           } else {
                               // create it
                               if( null != e.Contracts__c ) {
                                   newContracts.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, e.Contracts__c );
                               }
                           }
                           // Groups
                           if( newGroups.containsKey( e.Rpt_Dt__c + 'DC' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Groups__c ) {
                                   newGroups.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, newGroups.get(e.Rpt_Dt__c + 'DC' + e.RecordTypeId) + e.Groups__c );
                               }
                           } else {
                               // create it
                               if( null != e.Groups__c ) {
                                   newGroups.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, e.Groups__c );
                               }
                           }
                       }
                       // For 51+, the New Business Indicator and Status are apparently irrelevant
                   } else if( enrollment51RecordTypeId == e.RecordTypeId ) {
                       if( 'N' == e.New_Business_Indicator__c ) {
                           if( totalContracts.containsKey( e.Rpt_Dt__c + 'DC' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Contracts__c ) {
                                   totalContracts.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, totalContracts.get(e.Rpt_Dt__c + 'DC' + e.RecordTypeId) + e.Contracts__c );
                               }
                           } else {
                               // create it
                               if( null != e.Contracts__c ) {
                                   totalContracts.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, e.Contracts__c );
                               }
                           }
                       } else if( 'Y' == e.New_Business_Indicator__c ){    // New Business
                           if( newContracts.containsKey( e.Rpt_Dt__c + 'DC' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Contracts__c ) {
                                   newContracts.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, newContracts.get(e.Rpt_Dt__c + 'DC' + e.RecordTypeId) + e.Contracts__c );
                               }
                           } else {
                               // create it
                               if( null != e.Contracts__c ) {
                                   newContracts.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, e.Contracts__c );
                               }
                           }
                           // Groups
                           if( newGroups.containsKey( e.Rpt_Dt__c + 'DC' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Groups__c ) {
                                   newGroups.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, newGroups.get(e.Rpt_Dt__c + 'DC' + e.RecordTypeId) + e.Groups__c );
                               }
                           } else {
                               // create it
                               if( null != e.Groups__c ) {
                                   newGroups.put( e.Rpt_Dt__c + 'DC' + e.RecordTypeId, e.Groups__c );
                               }
                           }
                       }
                   }
                   // Virginia
               } else if( e.Opportunity__r.Account.Rating_State__c == 'V' ) {
                   if( enrollment2_50RecordTypeId == e.RecordTypeId ) {
                       if( 'N' == e.New_Business_Indicator__c ) {
                           // See if there's already a TOTAL entry for this date/jurisdiction
                           if( 'Active' == e.Status__c  ) {
                               if( totalContracts.containsKey( e.Rpt_Dt__c + 'VA' + e.RecordTypeId ) ) {
                                   // update
                                   if( null != e.Contracts__c ) {
                                       totalContracts.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, totalContracts.get(e.Rpt_Dt__c + 'VA' + e.RecordTypeId) + e.Contracts__c );
                                   }
                               } else {
                                   // create it
                                   if( null != e.Contracts__c ) {
                                       totalContracts.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, e.Contracts__c );
                                   }
                               }
                               // total groups, too
                               if( totalGroups.containsKey( e.Rpt_Dt__c + 'VA' + e.RecordTypeId ) ) {
                                   // update
                                   if( null != e.Groups__c ) {
                                       totalGroups.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, totalGroups.get(e.Rpt_Dt__c + 'VA' + e.RecordTypeId) + e.Groups__c );
                                   }
                               } else {
                                   // create it
                                   if( null != e.Groups__c ) {
                                       totalGroups.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, e.Groups__c );
                                   }
                               }
                               // See if there's already an ON-CYCLE entry for this date/jurisdiction
                               // 12-15-2014 jhm: Can't use the check-box determine on/off cycle, per Salman
                               // 12-16-2014 jhm: Use different check-box and Renewal Anniversary Date, instead.
                               if( null != e.Renewal_Anniversary_Date__c && true == e.Summary_Checkbox__c ) {
                                   String sDate = formatDate( e.Renewal_Anniversary_Date__c );
                                   if( onCycleContracts.containsKey( formatDate( e.Renewal_Anniversary_Date__c ) + 'VA' + e.RecordTypeId ) ) {
                                       // update
                                       if( null != e.Contracts__c ) {
                                           onCycleContracts.put( formatDate( e.Renewal_Anniversary_Date__c ) + 'VA' + e.RecordTypeId, onCycleContracts.get(formatDate( e.Renewal_Anniversary_Date__c ) + 'VA' + e.RecordTypeId) + e.Contracts__c );
                                       }
                                   } else {
                                       // create it
                                       if( null != e.Contracts__c ) {
                                           onCycleContracts.put( formatDate( e.Renewal_Anniversary_Date__c ) + 'VA' + e.RecordTypeId, e.Contracts__c );
                                       }
                                   }
                                   // groups, too
                                   if( onCycleGroups.containsKey( formatDate( e.Renewal_Anniversary_Date__c ) + 'VA' + e.RecordTypeId ) ) {
                                       // update
                                       if( null != e.Groups__c ) {
                                           onCycleGroups.put( formatDate( e.Renewal_Anniversary_Date__c ) + 'VA' + e.RecordTypeId, onCycleGroups.get(formatDate( e.Renewal_Anniversary_Date__c ) + 'VA' + e.RecordTypeId) + e.Groups__c );
                                       }
                                   } else {
                                       // create it
                                       if( null != e.Groups__c ) {
                                           onCycleGroups.put( formatDate( e.Renewal_Anniversary_Date__c ) + 'VA' + e.RecordTypeId, e.Groups__c );
                                       }
                                   }
                               }
                           } else if( 'Termed' == e.Status__c && enrollment2_50RecordTypeID == e.RecordTypeId ) {
                               // See if there's already a TERMED entry for this date/jurisdiction
                               if( termedContracts.containsKey( e.Rpt_Dt__c + 'VA' + e.RecordTypeId ) ) {
                                   // update
                                   if( null != e.Contracts__c ) {
                                       termedContracts.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, termedContracts.get(e.Rpt_Dt__c + 'VA' + e.RecordTypeId) + e.Contracts__c );
                                   }
                               } else {
                                   // create it
                                   if( null != e.Contracts__c ) {
                                       termedContracts.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, e.Contracts__c );
                                   }
                               }
                               // groups, too
                               if( termedGroups.containsKey(e.Rpt_Dt__c + 'VA' + e.RecordTypeId ) ) {
                                   // update
                                   if( null != e.Groups__c ) {
                                       termedGroups.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, termedGroups.get(e.Rpt_Dt__c + 'VA' + e.RecordTypeId) + e.Groups__c );
                                   }
                               } else {
                                   // create it
                                   if( null != e.Groups__c ) {
                                       termedGroups.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, e.Groups__c );
                                   }
                               }
                               // See if there's already an on-cycle TERMED entry for this date/jurisdiction
                               // 12-15-2014 jhm: Can't use the check-box determine on/off cycle, per Salman
                               // 12-16-2014 jhm: Use different check-box and Renewal Anniversary Date, instead.
                               if( null != e.Renewal_Anniversary_Date__c && (true == e.Reporting_Checkbox__c || true == e.Summary_Checkbox__c ) ) {
                                   if( true == e.Reporting_Checkbox__c || true == e.Summary_Checkbox__c ) {        // ON CYCLE
                                       if( onCycleContractTerms.containsKey( formatDate(e.Renewal_Anniversary_Date__c) + 'VA' + e.RecordTypeId ) ) {
                                           // update
                                           if( null != e.Contracts__c ) {
                                               onCycleContractTerms.put( formatDate(e.Renewal_Anniversary_Date__c) + 'VA' + e.RecordTypeId, onCycleContractTerms.get(formatDate(e.Renewal_Anniversary_Date__c) + 'VA' + e.RecordTypeId) + e.Contracts__c );
                                           }
                                       } else {
                                           // create it
                                           if( null != e.Contracts__c ) {
                                               onCycleContractTerms.put( formatDate(e.Renewal_Anniversary_Date__c) + 'VA' + e.RecordTypeId, e.Contracts__c );
                                           }
                                       }
                                       // groups, too
                                       if( onCycleGroupTerms.containsKey(formatDate(e.Renewal_Anniversary_Date__c) + 'VA' + e.RecordTypeId ) ) {
                                           // update
                                           if( null != e.Groups__c ) {
                                               onCycleGroupTerms.put( formatDate(e.Renewal_Anniversary_Date__c) + 'VA' + e.RecordTypeId, onCycleGroupTerms.get(formatDate(e.Renewal_Anniversary_Date__c) + 'VA' + e.RecordTypeId) + e.Groups__c );
                                           }
                                       } else {
                                           // create it
                                           if( null != e.Groups__c ) {
                                               onCycleGroupTerms.put( formatDate(e.Renewal_Anniversary_Date__c) + 'VA' + e.RecordTypeId, e.Groups__c );
                                           }
                                       }
                                   }
                               }
                           } // termed
                       }  // new business
                       if('Y' == e.New_Business_Indicator__c ) {
                           if( newContracts.containsKey( e.Rpt_Dt__c + 'VA' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Contracts__c ) {
                                   newContracts.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, newContracts.get(e.Rpt_Dt__c + 'VA' + e.RecordTypeId) + e.Contracts__c );
                               }
                           } else {
                               // create it
                               if( null != e.Contracts__c ) {
                                   newContracts.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, e.Contracts__c );
                               }
                           }
                           // Groups
                           if( newGroups.containsKey( e.Rpt_Dt__c + 'VA' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Groups__c ) {
                                   newGroups.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, newGroups.get(e.Rpt_Dt__c + 'VA' + e.RecordTypeId) + e.Groups__c );
                               }
                           } else {
                               // create it
                               if( null != e.Groups__c ) {
                                   newGroups.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, e.Groups__c );
                               }
                           }
                       }
                       // For 51+, the New Business Indicator and Status are apparently irrelevant
                   } else if( enrollment51RecordTypeId == e.RecordTypeId ) {
                       if( 'N' == e.New_Business_Indicator__c ) {
                           if( totalContracts.containsKey( e.Rpt_Dt__c + 'VA' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Contracts__c ) {
                                   totalContracts.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, totalContracts.get(e.Rpt_Dt__c + 'VA' + e.RecordTypeId) + e.Contracts__c );
                               }
                           } else {
                               // create it
                               if( null != e.Contracts__c ) {
                                   totalContracts.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, e.Contracts__c );
                               }
                           }
                       } else if( 'Y' == e.New_Business_Indicator__c ){    // New Business
                           if( newContracts.containsKey( e.Rpt_Dt__c + 'VA' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Contracts__c ) {
                                   newContracts.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, newContracts.get(e.Rpt_Dt__c + 'VA' + e.RecordTypeId) + e.Contracts__c );
                               }
                           } else {
                               // create it
                               if( null != e.Contracts__c ) {
                                   newContracts.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, e.Contracts__c );
                               }
                           }
                           // Groups
                           if( newGroups.containsKey( e.Rpt_Dt__c + 'VA' + e.RecordTypeId ) ) {
                               // update
                               if( null != e.Groups__c ) {
                                   newGroups.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, newGroups.get(e.Rpt_Dt__c + 'VA' + e.RecordTypeId) + e.Groups__c );
                               }
                           } else {
                               // create it
                               if( null != e.Groups__c ) {
                                   newGroups.put( e.Rpt_Dt__c + 'VA' + e.RecordTypeId, e.Groups__c );
                               }
                           }
                       }
                   }
               }
        }  // for
        System.debug( '--------> totalContracts has this many records: ' + totalContracts.size() );
        
        // put in the DB
        upsertSummaryData();        
    }
    
    // insert the data
    public void upsertSummaryData() {
        
        // Now spin back through my maps to build up the table.
        // Total Contracts
        Set<String> sTotalDates = totalContracts.keySet();
        List<Enrollment_Summary__c> lE1 = new List<Enrollment_Summary__c>();
        for( String s : sTotalDates ) {
            Enrollment_Summary__c e = new Enrollment_Summary__c(    Date__c = s.substring(0,6),
                                                                Jurisdiction__c = s.substring(6,8),
                                                                Unique_ID__c = s,
                                                                Total_Contracts__c = totalContracts.get(s) );
            if( enrollment2_50RecordTypeID == s.substring(8,26) ) {
                e.RecordTypeId = summary2_50RecordTypeId;
            } else {
                e.RecordTypeId = summary51RecordTypeId;
            }
            lE1.add(e);         
        }
        System.debug( 'upserting records: ' + lE1.size() );
        upsert lE1 Unique_ID__c;
        // On Cycle Contracts
        // 12-15-2014 jhm: Can't use the check-box determine on/off cycle, per Salman
        Set<String> sOnCycleContractDates = onCycleContracts.keySet();
        List<Enrollment_Summary__c> lE2 = new List<Enrollment_Summary__c>();
        for( String s : sOnCycleContractDates ) {
            Enrollment_Summary__c e = new Enrollment_Summary__c(    Date__c = s.substring(0,6),
                                                                Jurisdiction__c = s.substring(6,8),
                                                                Unique_ID__c = s,
                                                                On_Cycle_Contracts__c = onCycleContracts.get(s) );
            if( enrollment2_50RecordTypeID == s.substring(8,26) ) {
                e.RecordTypeId = summary2_50RecordTypeId;
            } else {
                e.RecordTypeId = summary51RecordTypeId;
            }
            lE2.add(e);         
        }
        System.debug( 'upserting records: ' + lE2.size() );
        upsert lE2 Unique_ID__c;
        // Contract Terms
        Set<String> sContractTerms = termedContracts.keySet();
        List<Enrollment_Summary__c> lE3 = new List<Enrollment_Summary__c>();
        for( String s : sContractTerms ) {
            Enrollment_Summary__c e = new Enrollment_Summary__c(    Date__c = s.substring(0,6),
                                                                Jurisdiction__c = s.substring(6,8),
                                                                Unique_ID__c = s,
                                                                Total_Termed_Contracts__c = termedContracts.get(s) );
            if( enrollment2_50RecordTypeID == s.substring(8,26) ) {
                e.RecordTypeId = summary2_50RecordTypeId;
            } else {
                e.RecordTypeId = summary51RecordTypeId;
            }
            lE3.add(e);         
        }
        System.debug( 'upserting records: ' + lE3.size() );
        upsert lE3 Unique_ID__c;
        // On Cycle Terms
        Set<String> sOnCycleTerms = onCycleContractTerms.keySet();
        List<Enrollment_Summary__c> lE4 = new List<Enrollment_Summary__c>();
        for( String s : sOnCycleTerms ) {
            Enrollment_Summary__c e = new Enrollment_Summary__c(    Date__c = s.substring(0,6),
                                                                Jurisdiction__c = s.substring(6,8),
                                                                Unique_ID__c = s,
                                                                On_Cycle_Termed_Contracts__c = onCycleContractTerms.get(s) );
            if( enrollment2_50RecordTypeID == s.substring(8,26) ) {
                e.RecordTypeId = summary2_50RecordTypeId;
            } else {
                e.RecordTypeId = summary51RecordTypeId;
            }
            lE4.add(e);         
        }
        System.debug( 'upserting records: ' + lE4.size() );
        upsert lE4 Unique_ID__c;
        // Total Groups
        Set<String> sTotalGroupDates = totalGroups.keySet();
        List<Enrollment_Summary__c> lE5 = new List<Enrollment_Summary__c>();
        for( String s : sTotalGroupDates ) {
            Enrollment_Summary__c e = new Enrollment_Summary__c(    Date__c = s.substring(0,6),
                                                                Jurisdiction__c = s.substring(6,8),
                                                                Unique_ID__c = s,
                                                                Total_Groups__c = totalGroups.get(s) );
            if( enrollment2_50RecordTypeID == s.substring(8,26) ) {
                e.RecordTypeId = summary2_50RecordTypeId;
            } else {
                e.RecordTypeId = summary51RecordTypeId;
            }
            lE5.add(e);         
        }
        System.debug( 'upserting records: ' + lE5.size() );
        upsert lE5 Unique_ID__c;
        // On Cycle Groups
        Set<String> sOnCycleGroupDates = onCycleGroups.keySet();
        List<Enrollment_Summary__c> lE6 = new List<Enrollment_Summary__c>();
        for( String s : sOnCycleGroupDates ) {
            Enrollment_Summary__c e = new Enrollment_Summary__c(    Date__c = s.substring(0,6),
                                                                Jurisdiction__c = s.substring(6,8),
                                                                Unique_ID__c = s,
                                                                On_Cycle_Groups__c = onCycleGroups.get(s) );
            if( enrollment2_50RecordTypeID == s.substring(8,26) ) {
                e.RecordTypeId = summary2_50RecordTypeId;
            } else {
                e.RecordTypeId = summary51RecordTypeId;
            }
            lE6.add(e);         
        }
        System.debug( 'upserting records: ' + lE6.size() );
        upsert lE6 Unique_ID__c;
        // Group Terms
        Set<String> sGroupTerms = termedGroups.keySet();
        List<Enrollment_Summary__c> lE7 = new List<Enrollment_Summary__c>();
        for( String s : sGroupTerms ) {
            Enrollment_Summary__c e = new Enrollment_Summary__c(    Date__c = s.substring(0,6),
                                                                Jurisdiction__c = s.substring(6,8),
                                                                Unique_ID__c = s,
                                                                Total_Termed_Groups__c = termedGroups.get(s) );
            if( enrollment2_50RecordTypeID == s.substring(8,26) ) {
                e.RecordTypeId = summary2_50RecordTypeId;
            } else {
                e.RecordTypeId = summary51RecordTypeId;
            }
            lE7.add(e);         
        }
        System.debug( 'upserting records: ' + lE7.size() );
        upsert lE7 Unique_ID__c;
        // On Cycle Group Terms
        Set<String> sOnCycleGroupTerms = onCycleGroupTerms.keySet();
        List<Enrollment_Summary__c> lE8 = new List<Enrollment_Summary__c>();
        for( String s : sOnCycleGroupTerms ) {
            Enrollment_Summary__c e = new Enrollment_Summary__c(    Date__c = s.substring(0,6),
                                                                Jurisdiction__c = s.substring(6,8),
                                                                Unique_ID__c = s,
                                                                On_Cycle_Termed_Groups__c = onCycleGroupTerms.get(s) );
            if( enrollment2_50RecordTypeID == s.substring(8,26) ) {
                e.RecordTypeId = summary2_50RecordTypeId;
            } else {
                e.RecordTypeId = summary51RecordTypeId;
            }
            lE8.add(e);         
        }
        System.debug( 'upserting records: ' + lE8.size() );
        upsert lE8 Unique_ID__c;
        // New Contracts
        Set<String> sNewContracts = newContracts.keySet();
        List<Enrollment_Summary__c> lE9 = new List<Enrollment_Summary__c>();
        for( String s : sNewContracts ) {
            Enrollment_Summary__c e = new Enrollment_Summary__c(    Date__c = s.substring(0,6),
                                                                Jurisdiction__c = s.substring(6,8),
                                                                Unique_ID__c = s,
                                                                New_Contracts__c = newContracts.get(s) );
            if( enrollment2_50RecordTypeID == s.substring(8,26) ) {
                e.RecordTypeId = summary2_50RecordTypeId;
            } else {
                e.RecordTypeId = summary51RecordTypeId;
            }
            lE9.add(e);         
        }
        System.debug( 'upserting records: ' + lE9.size() );
        upsert lE9 Unique_ID__c;
        // New Groups
        Set<String> sNewGroups = newGroups.keySet();
        List<Enrollment_Summary__c> lE10 = new List<Enrollment_Summary__c>();
        for( String s : sNewGroups ) {
            Enrollment_Summary__c e = new Enrollment_Summary__c(    Date__c = s.substring(0,6),
                                                                Jurisdiction__c = s.substring(6,8),
                                                                Unique_ID__c = s,
                                                                New_Groups__c = newGroups.get(s) );
            if( enrollment2_50RecordTypeID == s.substring(8,26) ) {
                e.RecordTypeId = summary2_50RecordTypeId;
            } else {
                e.RecordTypeId = summary51RecordTypeId;
            }
            lE10.add(e);            
        }
        System.debug( 'upserting records: ' + lE10.size() );
        upsert lE10 Unique_ID__c;
    }
    
    // 12-12-2014 jhm: Batch variables are apparently reinitialized with each batch, so I have to reload them each time.    
    public void rePopulateMaps() {
        List<Enrollment_Summary__c> lES = [SELECT Name, Date__c, Jurisdiction__c, Total_Contracts__c, Total_Groups__c,
                                           On_Cycle_Contracts__c, On_Cycle_Groups__c, Total_Termed_Contracts__c, Total_Termed_Groups__c,
                                           On_Cycle_Termed_Contracts__c, On_Cycle_Termed_Groups__c, New_Contracts__c, New_Groups__c,
                                           Unique_Id__c     
                                           FROM Enrollment_Summary__c];
        for( Enrollment_Summary__c ES : lES ) {
            
            totalContracts.put(         ES.Unique_Id__c,    ES.Total_Contracts__c );
            onCycleContracts.put(       ES.Unique_Id__c,    ES.On_Cycle_Contracts__c );
            termedContracts.put(        ES.Unique_Id__c,    ES.Total_Termed_Contracts__c );
            onCycleContractTerms.put(   ES.Unique_Id__c,    ES.On_Cycle_Termed_Contracts__c );
            newContracts.put(           ES.Unique_Id__c,    ES.New_Contracts__c );
            
            totalGroups.put(            ES.Unique_Id__c,    ES.Total_Groups__c );
            onCycleGroups.put(          ES.Unique_Id__c,    ES.On_Cycle_Groups__c );
            termedGroups.put(           ES.Unique_Id__c,    ES.Total_Termed_Groups__c );
            onCycleGroupTerms.put(      ES.Unique_Id__c,    ES.On_Cycle_Termed_Groups__c );
            newGroups.put(              ES.Unique_Id__c,    ES.New_Groups__c );
        }
    }
    
    //  Returns the date in the same format as the Report Date
    public string formatDate( Date dt ) {
        String sDate = string.valueOf(dt.year());
        if( string.valueOf( dt.month()).length() == 1 ) {
            sDate += '0';
        }
        sDate += string.valueOf( dt.Month() );
        /* We don't want the day, anyway */
        /*
if( string.valueof( dt.Day() ).length == 1 ) {
sDate += '0';
}
sDate += string.valueOf( dt.Day() );
*/
        return sDate;
    }
    
    private void get51PlusMagicNumbers() {
        
        AggregateResult[] fiftyOnePlus = [SELECT Account.Rating_State__c State, Count(Id) Groups, SUM(Account.Latest_Medical_Enrollment__c) Contracts
                                          FROM Opportunity
                                          WHERE Account.RecordTypeID = :QueryBase.getRecordtypeId( 'Account', 'X51')
                                          AND StageName = 'Dead'
                                          AND Account.Rating_State__c != null
                                          GROUP BY Account.Rating_State__c];
        
        // delete existing record
        List<Enrollment_Summary_51_Terms__c> oldSettings = [SELECT Id FROM Enrollment_Summary_51_Terms__c];
        if( 0 < oldSettings.size() && !Test.isRunningTest() ) {
            delete oldSettings;
        }
        
        // 12-17-2014 jhm: Put new values in our custom setting
        List<Enrollment_Summary_51_Terms__c> newSettings = new List<Enrollment_Summary_51_Terms__c>();
        for( AggregateResult ar : fiftyOnePlus ) {
            Enrollment_Summary_51_Terms__c setting = new Enrollment_Summary_51_Terms__c();
            String Jurisdiction = '';
            if( String.valueOf( ar.get('State') ) == 'M' ||
               String.valueOf( ar.get('State') ) == 'R' ) {
                   
                   Jurisdiction = 'MD';
               } else if( String.valueOf( ar.get('State') ) == 'V' ) {
                   Jurisdiction = 'VA';
               } else if( String.valueOf( ar.get('State') ) == 'D' ) {
                   Jurisdiction = 'DC';
               }
            setting.name = string.valueOf(Date.Today() + '_' + Jurisdiction );
            setting.Jurisdiction__c = Jurisdiction;
            setting.Contracts__c = Integer.valueOf( ar.get('Groups') );
            setting.Groups__c = Integer.valueOf( ar.get('Contracts') );
            newSettings.add( setting );
        }
        insert newSettings;
    } 
}