objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Legal_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_date_format__c</fullName>
        <description>Formula field for handling mm dd yy for GSM email templates</description>
        <formula>LPAD(TEXT(MONTH(Account_Effective_Date__c)), 2, '0')+"/" +LPAD(TEXT(DAY(Account_Effective_Date__c)), 2, '0')+"/" 
+ MID(TEXT(YEAR(Account_Effective_Date__c)), 3, 4)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Effective date format</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status defines if the 2-50 customer account is active or termed based on the active file or the term file that it was updated from.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
                <value>
                    <fullName>Migrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Group_Structure_Request_Form__c.object
<CustomObject>
    <fields>
        <fullName>Account_Legal_Name__c</fullName>
        <formula>Implementation__r.Account__r.Account_Legal_Name__c</formula>
        <label>Account Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Base_Group_Impact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Does Group Structure have new group impacts?</inlineHelpText>
        <label>Base Group Impact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_date_format__c</fullName>
        <formula>LPAD(TEXT(MONTH(Effective_Date__c)), 2, '0')+"/" +LPAD(TEXT(DAY(Effective_Date__c)), 2, '0')+"/" 
+ MID(TEXT(YEAR(Effective_Date__c)), 3, 4)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Effective date format</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Group Structure Request Forms</relationshipLabel>
        <relationshipName>Group_Structure_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rejected_comments_by_Account__c</fullName>
        <description>US 117 Reject comments under GSRF when rejected by account</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Rejected Comments By Account</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft - New</fullName>
                    <default>true</default>
                    <label>Draft - New</label>
                </value>
                <value>
                    <fullName>Assigned to MAST</fullName>
                </value>
                <value>
                    <fullName>Approved by Internal Team</fullName>
                </value>
                <value>
                    <fullName>Rejected by Internal Team</fullName>
                </value>
                <value>
                    <fullName>Draft - Incomplete</fullName>
                </value>
                <value>
                    <fullName>Approved by Account</fullName>
                </value>
                <value>
                    <fullName>Rejected by Account</fullName>
                </value>
                <value>
                    <fullName>Awaiting Internal Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Group Structure Request Form</label>
    <nameField>
        <displayFormat>GSRF-{000000}</displayFormat>
        <label>Group Structure Request Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Structure Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Implementation__c.object
<CustomObject>
    <fields>
        <fullName>AIA_Group_Structure_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To populate the group structure request form under implementation</description>
        <label>Group Structure Request Form</label>
        <referenceTo>AIA_Group_Structure_Request_Form__c</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Legal_Name__c</fullName>
        <formula>Account__r.Account_Legal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Implementation</label>
    <nameField>
        <displayFormat>IMP-{000000}</displayFormat>
        <label>Implementation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AIA_GSRF_StatusByAccount.cls
/*===================================================================================================================
* Date       : 09/27/2017
* Developer  : Raviteja
* Purpose    : US-117,US-106 This is controller class for VF pages AIA_GSM_RejectedByAccount, AIA_GSM_ApprovedByAccount.
               Allow user to modify Group structure status to Approved by Account/Rejected by Account.
               Checking some validations Before changing to Approved by Account/Rejected by Account.
               Posting chatter notification on Approved by Account.
*                                 Update History
*                                 ---------------
* Date       |      Developer        | Tag |   Description
*============+============+=========================================================================================
* 09/27/2017 |      Raviteja         |     | Initial Version
* 02/09/2018 | Rajesh Nagandla       | T01 | Added SLDS to all components in page
*============+============+=========================================================================================
*/

public class AIA_GSRF_StatusByAccount {
    //T01  -   start
    public Boolean getIsClassic() {
        return AIA_Utils.isClassic();
    }
    //T01  -   end
    AIA_Group_Structure_Request_Form__c rec;
    public static string errorGSRF='';
    public static boolean showError=false;
    public AIA_GSRF_StatusByAccount(ApexPages.StandardController stdController) {
        //id = apexpages.currentpage().getparameters().get('id');    
         rec = (AIA_Group_Structure_Request_Form__c)stdController.getRecord();
        
    
    }
    //This method is called when Account by Account is clicked
    public pagereference saveRecForApproved(){
        //check the conditions and then change status to Approved by Account
        if(rec.Status__c=='Approved by Internal Team'){
            rec.Status__c='Approved by Account';  
            }
        else{
            errorGSRF='Incorrect Status selected';
            showError=true;
        }
        //If it is not one of the above statuses,then throw error
        if(showError==true){
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,errorGSRF);
            ApexPages.addMessage(msg);
            return null;
        }else{
            try{
                 update rec;
                 postFeedonAccount();
            }
            catch(Exception e){
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage());
                ApexPages.addMessage(msg);
                return null;
            }
         PageReference pr = new PageReference('/'+rec.id );
         pr.setRedirect(true);
         return pr;      
        }
    }
    
    //This method is called when Rejected by Account is clicked
    public pagereference saveRecForRejected(){
        //check the conditions and then change status to Approved by Account
         if(rec.Status__c=='Approved by Internal Team'){
           if(!String.isEmpty(rec.Rejected_comments_by_Account__c)){
                rec.Status__c='Rejected by Account';  
           }
           else{
                errorGSRF='Please provide reject Comments by Account.';
                showError=true;
           }
       }
       else{
           errorGSRF='Incorrect Status selected';
           showError=true;
       }
        
        //If it is not one of the above statuses,then throw error
        if(showError==true){
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,errorGSRF);
            ApexPages.addMessage(msg);
            return null;
        }else{
            update rec;
            PageReference pr = new PageReference('/'+rec.id );
            pr.setRedirect(true);
            return pr;      
        }
    }
    
    //send chatter notification on account
    public void postFeedonAccount(){
        String yesno='';
                if(rec.Base_Group_Impact__c==True){
                    yesno='Y';
                }
                else{
                    yesno='N'; 
                }
        //String subject= rec.Account_Legal_Name__c+' - Effective Date '+
         //               rec.Effective_date_format__c+' - Approved group structure for distribution\n';
        String message= rec.Account_Legal_Name__c+' - Effective Date '+
                        rec.Effective_date_format__c+', BGI = '+yesno+' - Approved group structure for distribution.\n';
        //String url='GSRF - '+system.URL.getSalesforceBaseUrl().toExternalForm()+'/'+rec.Id; as per us 251
        system.debug('message'+message);
        AIA_Implementation__c imp = [select Account__c from AIA_Implementation__c where id =: rec.Implementation__c];
    
    // Bulk post to the account feeds.

    List<ConnectApi.BatchInput> batchInputs = new List<ConnectApi.BatchInput>();
        
        ConnectApi.FeedItemInput input = new ConnectApi.FeedItemInput();
        
        input.subjectId = imp.Account__c;
        
        ConnectApi.MessageBodyInput body = new ConnectApi.MessageBodyInput();
        body.messageSegments = new List<ConnectApi.MessageSegmentInput>();

        ConnectApi.TextSegmentInput textSegment = new ConnectApi.TextSegmentInput();
        textSegment.text = message;

        body.messageSegments.add(textSegment);
        input.body = body;

        ConnectApi.BatchInput batchInput = new ConnectApi.BatchInput(input);
        batchInputs.add(batchInput);
    

    ConnectApi.ChatterFeeds.postFeedElementBatch(Network.getNetworkId(), batchInputs);
            
            
            
    }
    public pagereference backtogsrf(){
        PageReference pref = new PageReference('/'+rec.id );
        pref.setRedirect(true);
        return pref;
    }
    
}