objects/Account.object
<CustomObject>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <label>Jurisdiction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>VA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>CEDE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status defines if the 2-50 customer account is active or termed based on the active file or the term file that it was updated from.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
                <value>
                    <fullName>Migrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Team__c.object
<CustomObject>
    <fields>
        <fullName>TeamMemberRole__c</fullName>
        <label>Team Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Dedicated Representative</fullName>
                </value>
                <value>
                    <fullName>Account Executive</fullName>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Actuary</fullName>
                </value>
                <value>
                    <fullName>AIA Admin</fullName>
                </value>
                <value>
                    <fullName>AIA User</fullName>
                </value>
                <value>
                    <fullName>Auditor</fullName>
                </value>
                <value>
                    <fullName>Automated Enrollment Tech</fullName>
                </value>
                <value>
                    <fullName>BCM Coordinator</fullName>
                </value>
                <value>
                    <fullName>BeneFact Coder</fullName>
                </value>
                <value>
                    <fullName>BeneFact Portal Tech</fullName>
                </value>
                <value>
                    <fullName>BeneFact Tester</fullName>
                </value>
                <value>
                    <fullName>Benefit Admin Manager</fullName>
                </value>
                <value>
                    <fullName>Benefit Coder</fullName>
                </value>
                <value>
                    <fullName>Benefit Contract Specialist</fullName>
                </value>
                <value>
                    <fullName>Benefit Design Approvers</fullName>
                </value>
                <value>
                    <fullName>Benefit Tester</fullName>
                </value>
                <value>
                    <fullName>Billing Tech</fullName>
                </value>
                <value>
                    <fullName>BlueFund</fullName>
                </value>
                <value>
                    <fullName>Blue Rewards Tech</fullName>
                </value>
                <value>
                    <fullName>Cede Document Tech</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Client Advisory Services</fullName>
                </value>
                <value>
                    <fullName>Contract Coordinator</fullName>
                </value>
                <value>
                    <fullName>Contract Manager</fullName>
                </value>
                <value>
                    <fullName>Contract Tech</fullName>
                </value>
                <value>
                    <fullName>Enrollment Tech</fullName>
                </value>
                <value>
                    <fullName>Facets Migration Contact</fullName>
                </value>
                <value>
                    <fullName>Implementation Coordinator</fullName>
                </value>
                <value>
                    <fullName>Implementation Manager</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>QA Auditor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Team</label>
    <nameField>
        <displayFormat>ATM-{000000}</displayFormat>
        <label>AccountTeamMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Implementation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Benefit_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Request Form</label>
        <referenceTo>Benfit_Request_Form__c</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Generate_Workplan_Stages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate Workplan Stages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Implementation_Plan_Timeline_Days__c</fullName>
        <label>Implementation Plan Timeline (Days)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>AIA_Post_Sales_Implementation</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Risk_Type__c</fullName>
        <label>Risk Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Implementation</label>
    <nameField>
        <displayFormat>IMP-{000000}</displayFormat>
        <label>Implementation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Benfit_Request_Form__c.object
<CustomObject>
    <fields>
        <fullName>ARC_Approval_Status__c</fullName>
        <description>ARC Approval Status</description>
        <label>ARC Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved by Committee</fullName>
                </value>
                <value>
                    <fullName>Rejected by Committee</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>No Decision</fullName>
                </value>
                <value>
                    <fullName>Auto-Approved by System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Request Forms</relationshipLabel>
        <relationshipName>Benfit_Request_Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Benefit_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Benefit Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Count__c</fullName>
        <label>Contract Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Escalated_to_Senior_Management__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalated to Senior Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <label>Jurisdiction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>VA</fullName>
                </value>
                <value>
                    <fullName>Other - Cede Required</fullName>
                </value>
                <value>
                    <fullName>CEDE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Benefit Request Forms</relationshipLabel>
        <relationshipName>Benfit_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Benefit Request Form Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Revised Approved</fullName>
                </value>
                <value>
                    <fullName>Sold-Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>New object for AIA - This object stores the information that is needed for a quote</description>
    <label>Benefit Request Form</label>
    <nameField>
        <displayFormat>BRF-{000000}</displayFormat>
        <label>Benefit Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Request Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>ASO</fullName>
        <active>true</active>
        <description>ASO Layout</description>
        <label>ASO</label>
    </recordTypes>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AIA_ContractTriggerHandler_Test.cls
/*****************************************************************************************************

*=========================================================================================
* Update History
* Date         Developer       Tag          Description
*==================================================================================

*06/08/2018    raj kiran      T01       Added code for role updates
*02/08/2019     Chaithra     |T02|      Replaced std object AccountTeamMember with custom obj Account_Team__c as part of US6713
*==================================================================================

*******************************************************************************************************/


@isTest
private class AIA_ContractTriggerHandler_Test{


   @testSetup static void CreateUserData(){
      //Create Account
        Account acc =AIA_TestUtil.createAccount('TestOEMAcc');
        //Create Opportunity
        Opportunity opp =AIA_TestUtil.AIA_createopportunity(acc.id);     
        //Create testusers
        List<user> userList = new list<user>();
        user u1 = AIA_TestUtil.AIA_createUser('alias1');
        userList.add(u1);
        user u2 = AIA_TestUtil.AIA_createUser('alias2');
        userList.add(u2);        
        user u3 = AIA_TestUtil.AIA_createUser('alias3');
        userList.add(u3);        
        user u4 = AIA_TestUtil.AIA_createUser('alias4');
        userList.add(u4);        
        user u5 = AIA_TestUtil.AIA_createUser('alias5');
        userList.add(u5); 
        user u6 = AIA_TestUtil.AIA_createUser('alias66');
        userList.add(u6);
        user u7 = AIA_TestUtil.AIA_createUser('alias5');
        userList.add(u7);
        insert userList;       
        
        //Create Account teams for all the relevant roles
        AIA_TestUtil.AIA_createAccountTeamMember(acc.Id, u1.id, 'Auditor'); //t06
        //AIA_createAccountTeamMember(acc.Id, u2.id, 'C&C Contact');
        AIA_TestUtil.AIA_createAccountTeamMember(acc.Id, u3.id, 'Contract Manager');
        AIA_TestUtil.AIA_createAccountTeamMember(acc.Id, u4.id, 'Legal');
        //AIA_createAccountTeamMember(acc.Id, u5.id, 'Sales Service Rep');   
        AIA_TestUtil.AIA_createAccountTeamMember(acc.Id, u6.id, 'Benefit Contract Specialist');  
        AIA_TestUtil.AIA_createAccountTeamMember(acc.Id, u7.id, 'Account Manager');
        
    /*
        AIA_createAccountTeamMember(acc.Id, u1.id, 'Ancillary Analyst');
        AIA_createAccountTeamMember(acc.Id, u2.id,  'Benefact Coder');
        AIA_createAccountTeamMember(acc.Id, u3.id,  'Contract Tech');
        AIA_createAccountTeamMember(acc.Id, u4.id,  'QA Auditor');
        AIA_createAccountTeamMember(acc.Id, u5.id,  'Ancillary Analyst');        
    */
        test.startTest();
        Benfit_Request_Form__c nbrf = new Benfit_Request_Form__c();
        nbrf.recordTypeId=QueryBase.getRecordtypeId('Benfit_Request_Form__c', 'ASO');
        nbrf.Contract_Count__c = 123;
        nbrf.Benefit_Effective_Date__c = system.today();
        nbrf.Account__c = acc.id;
        nbrf.ARC_Approval_Status__c = 'Approved by Committee';
        nbrf.Escalated_to_Senior_Management__c = true;
        nbrf.Status__c = 'new';
        nbrf.Opportunity__c = opp.id;
        nbrf.Jurisdiction__c = 'MD';
        
        insert nbrf;    
        
        //Create an Implementation
        AIA_Implementation__c Imp = new AIA_Implementation__c();
        Imp.Name__c = 'testprf';
        Imp.Opportunity__c = opp.Id;
        Imp.account__c = acc.id;
      /*R1 changes to false*/  
      //Imp.Generate_Workplan_Stages__c = false;
        Imp.Effective_Date__c = system.today();
        Imp.Implementation_Plan_Timeline_Days__c = '60';
        Imp.Risk_Type__c='ASO';
         Imp.Benefit_Request_Form__c = nbrf.id;
      
        insert Imp;
        
        //Create the contract
        contract contractRec = new contract();
        contractRec.accountId=acc.Id;
        contractRec.StartDate=system.today();
        contractRec.ContractTerm=3;
        contractRec.Implementation__c=imp.id;
        insert contractRec;
   
   test.stopTest();
   
   }

    static testMethod void testValidateContract(){
        test.startTest();
        try{
        //AIA_TestUtil.createContract(); 
        //AccountTeamMember atm = [select id,TeamMemberRole from accountteammember where TeamMemberRole  = 'Auditor' limit 1]; //T01//T02 commented
        Account_Team__c atm = [select id,TeamMemberRole__c from Account_Team__c where TeamMemberRole__c  = 'Auditor' limit 1]; //T02
        delete atm;
        contract c = [select id,ContractTerm from contract limit 1];
        c.ContractTerm=4;
        AIA_ContractTriggerHandler.firstrun=false;        
        update c;
        
        }
        catch(exception e){}
        test.stopTest();
    }
    
    static testmethod void testValidateContract2(){
         test.startTest();
        try{
        //AIA_TestUtil.createContract();
       //accountteammember atm = [select id,TeamMemberRole from accountteammember where TeamMemberRole  = 'Benefit Contract Specialist' limit 1];//T02
       Account_Team__c atm= [select id,TeamMemberRole__c from Account_Team__c where TeamMemberRole__c  = 'Benefit Contract Specialist' limit 1]; //T02
        delete atm;
        contract c = [select id,ContractTerm from contract limit 1];
        c.ContractTerm=4;
        AIA_ContractTriggerHandler.firstrun=false;
        update c;
        }
        catch(exception e){}
        test.stopTest();
    }
    static testmethod void testValidateContract3(){
         test.startTest();
        try{
        //AIA_TestUtil.createContract();
       //accountteammember atm = [select id,TeamMemberRole from accountteammember where TeamMemberRole  = 'Contract Manager' limit 1];T02
       Account_Team__c atm= [select id,TeamMemberRole__c from Account_Team__c where TeamMemberRole__c  = 'Contract Manager' limit 1]; //T02
        delete atm;
        contract c = [select id,ContractTerm from contract limit 1];
        c.ContractTerm=4;
        AIA_ContractTriggerHandler.firstrun=false;
        update c;
        }
        catch(exception e){}
        test.stopTest();
    }
    
    static testmethod void testValidateContract4(){
         test.startTest();
        try{
        //AIA_TestUtil.createContract();
       //accountteammember atm = [select id,TeamMemberRole from accountteammember where TeamMemberRole  = 'Legal' limit 1];T02
       Account_Team__c atm= [select id,TeamMemberRole__c from Account_Team__c where TeamMemberRole__c  = 'Legal' limit 1]; //T02
        delete atm;
        contract c = [select id,ContractTerm from contract limit 1];
        c.ContractTerm=4;
        AIA_ContractTriggerHandler.firstrun=false;
        update c;
        }
        catch(exception e){}
        test.stopTest();
    }
    
    static testmethod void testValidateContract5(){
         test.startTest();
        try{
        //AIA_TestUtil.createContract();
       //accountteammember atm = [select id,TeamMemberRole from accountteammember where TeamMemberRole  = 'Account Manager' limit 1];T02
       Account_Team__c atm= [select id,TeamMemberRole__c from Account_Team__c where TeamMemberRole__c  = 'Account Manager' limit 1]; //T02
        delete atm;
        contract c = [select id,ContractTerm from contract limit 1];
        c.ContractTerm=4;
        AIA_ContractTriggerHandler.firstrun=false;
        update c;
        }
        catch(exception e){}
        test.stopTest();
    }
    static testmethod void testValidateContract6(){
        test.startTest();
        try{
            //AIA_TestUtil.createContract();
            account acc = [select id from account limit 1];
            /*User uT6 = AIA_TestUtil.AIA_createUser('aliasT6');
            insert uT6;
            AIA_TestUtil.AIA_createAccountTeamMember(acc.Id, uT6.id, 'Auditor'); //T01*/
            Account_Team__c atm = [select id,TeamMemberRole__c from Account_Team__c where TeamMemberRole__c  = 'Auditor' limit 1];
            contract c = [select id,ContractTerm from contract limit 1];
            c.ContractTerm=4;
            AIA_ContractTriggerHandler.firstrun=false;
            update c;
        }
        catch(exception e){}
        test.stopTest();            
    }
        
    static testmethod void testValidateContract7(){
        test.startTest();
        try{
           // AIA_TestUtil.createContract();
            account acc = [select id from account limit 1];
            /*User u6 = AIA_TestUtil.AIA_createUser('alias6');
            insert u6;
            AIA_TestUtil.AIA_createAccountTeamMember(acc.Id, u6.id, 'Benefit Contract Specialist');*/
            Account_Team__c atm = [select id,TeamMemberRole__c from Account_Team__c where TeamMemberRole__c  = 'Benefit Contract Specialist' limit 1];
            contract c = [select id,ContractTerm from contract limit 1];
            c.ContractTerm=4;
            AIA_ContractTriggerHandler.firstrun=false;
            update c;
        }
        catch(exception e){}
        test.stopTest();                
    }   
    static testmethod void testValidateContract8(){
        test.startTest();
        try{
            //AIA_TestUtil.createContract();
            account acc = [select id from account limit 1];
            /*User u6 = AIA_TestUtil.AIA_createUser('alias6');
            insert u6;
            AIA_TestUtil.AIA_createAccountTeamMember(acc.Id, u6.id, 'Contract Manager');*/
            Account_Team__c atm = [select id,TeamMemberRole__c from Account_Team__c where TeamMemberRole__c  = 'Contract Manager' limit 1];
            contract c = [select id,ContractTerm from contract limit 1];
            c.ContractTerm=4;
            AIA_ContractTriggerHandler.firstrun=false;
            update c;
        }
        catch(exception e){}
        test.stopTest();                
    }
    static testmethod void testValidateContract9(){
        test.startTest();
        try{
           // AIA_TestUtil.createContract();
            account acc = [select id from account limit 1];
            /*User u6 = AIA_TestUtil.AIA_createUser('alias6');
            insert u6;
            AIA_TestUtil.AIA_createAccountTeamMember(acc.Id, u6.id, 'Legal');*/
            Account_Team__c atm = [select id,TeamMemberRole__c from Account_Team__c where TeamMemberRole__c  = 'Legal' limit 1];
            contract c = [select id,ContractTerm from contract limit 1];
            c.ContractTerm=4;
            AIA_ContractTriggerHandler.firstrun=false;
            update c;
        }
        catch(exception e){}
        test.stopTest();                
    }
    static testmethod void testValidateContract10(){
        test.startTest();
        try{
            //AIA_TestUtil.createContract();
            account acc = [select id from account limit 1];
            /*User u6 = AIA_TestUtil.AIA_createUser('alias6');
            insert u6;
            AIA_TestUtil.AIA_createAccountTeamMember(acc.Id, u6.id, 'Account Manager');*/
            Account_Team__c atm = [select id,TeamMemberRole__c from Account_Team__c where TeamMemberRole__c  = 'Account Manager' limit 1];
            contract c = [select id,ContractTerm from contract limit 1];
            c.ContractTerm=4;
            AIA_ContractTriggerHandler.firstrun=false;
            update c;
        }
        catch(exception e){}
        test.stopTest();                
    }
    
}