objects/Account.object
<CustomObject>
    <fields>
        <fullName>Facets_Account_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Facets Account Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Facets_Category__c</fullName>
        <label>Facets Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Facets_Subject__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ACYB - CYBERATTACK</fullName>
                </value>
                <value>
                    <fullName>BF01 - BlueFund set up issues</fullName>
                </value>
                <value>
                    <fullName>BF03 - BF link missing on My Account</fullName>
                </value>
                <value>
                    <fullName>BF05 - Blue Rewards Inquiries</fullName>
                </value>
                <value>
                    <fullName>BF07 - Complaint about the vendor</fullName>
                </value>
                <value>
                    <fullName>BF09 - Unable to loc grp/vendor systm</fullName>
                </value>
                <value>
                    <fullName>BF11 - Unable to loc mbr/vendor systm</fullName>
                </value>
                <value>
                    <fullName>BF13 - Welcome Kit Inquiry/HSA only</fullName>
                </value>
                <value>
                    <fullName>BP01 - Communities</fullName>
                </value>
                <value>
                    <fullName>BP02 - Gen Broker Portal Inquiry</fullName>
                </value>
                <value>
                    <fullName>BP03 - Gen Employee Portal Inquiry</fullName>
                </value>
                <value>
                    <fullName>BP04 - Gen Hub Inquiry</fullName>
                </value>
                <value>
                    <fullName>BP05 - Group Set-Up</fullName>
                </value>
                <value>
                    <fullName>BP06 - Provisioning</fullName>
                </value>
                <value>
                    <fullName>BP07 - Quoting</fullName>
                </value>
                <value>
                    <fullName>BSA1 - Prospect Inquiry</fullName>
                </value>
                <value>
                    <fullName>BSA2 - File Update Inquiry</fullName>
                </value>
                <value>
                    <fullName>BSA3 - BOR Inquiry</fullName>
                </value>
                <value>
                    <fullName>BSA4 - Transferred to Sales Rep</fullName>
                </value>
                <value>
                    <fullName>BSA5 - Transferred to another dept</fullName>
                </value>
                <value>
                    <fullName>BSQ1 - Quote-Off Cycle Request</fullName>
                </value>
                <value>
                    <fullName>BSQ2 - Quote-Renewal Request</fullName>
                </value>
                <value>
                    <fullName>BSQ3 - Quote-New Business Request</fullName>
                </value>
                <value>
                    <fullName>BSQ4 - Quote-Late Exception Request</fullName>
                </value>
                <value>
                    <fullName>BSQ5 - Quote-Alternative</fullName>
                </value>
                <value>
                    <fullName>BSQ6 - Quote-On Exchange</fullName>
                </value>
                <value>
                    <fullName>BSQ7 - Transferred to another dept</fullName>
                </value>
                <value>
                    <fullName>DC01 - Processed Correctly</fullName>
                </value>
                <value>
                    <fullName>DC02 - Processed Incorrectly</fullName>
                </value>
                <value>
                    <fullName>DC03 - Pended Claim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facets_Satisfaction_Level__c</fullName>
        <description>This field translates the SLA Category on a case to a Facets Satisfaction Level Code that is included when creating a Facets case from the Salesforce to Facets integration component. ( Request: CSSC.satifactionLevel.  Corresponds to Facets.MCTR_SATS table)</description>
        <formula>IF(   ISPICKVAL(SLA_Category__c,'Non-Platinum'), 'BR60', 
   IF(ISPICKVAL(SLA_Category__c,'Broker Escalation'), 'BR61', 
   IF(ISPICKVAL(SLA_Category__c,'Broker Compliance'), 'BR6C', 
   IF(ISPICKVAL(SLA_Category__c,'Platinum'), 'BR6P',
   IF(ISPICKVAL(SLA_Category__c,'Elite'), 'BR6E',
   IF(ISPICKVAL(SLA_Category__c,'Premier'), 'BRP1',
   IF(ISPICKVAL(SLA_Category__c,'Preferred'), 'BRP2', 
   IF(ISPICKVAL(SLA_Category__c,'Select'), 'BR60', 
   IF(ISPICKVAL(SLA_Category__c,'Broker Sales Support'), 'BR6S', 'Unrecognized SLA Category!')
))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field translates the SLA Category on a case to a Facets Satisfaction Level Code that is included when creating a Facets case from the Salesforce to Facets integration component. ( Request: CSSC.satifactionLevel.  Corresponds to Facets.MCTR_SATS table</inlineHelpText>
        <label>Facets Satisfaction Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facets_Subject__c</fullName>
        <label>Facets Subject</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACYB - CYBERATTACK</fullName>
                </value>
                <value>
                    <fullName>BRCP - CareFirst Portals</fullName>
                </value>
                <value>
                    <fullName>BRSA - Sales Assistance</fullName>
                </value>
                <value>
                    <fullName>BRSQ - Sales Quote</fullName>
                </value>
                <value>
                    <fullName>DCLM - Dental Claims</fullName>
                </value>
                <value>
                    <fullName>MAPP-M Appeal</fullName>
                </value>
                <value>
                    <fullName>MAUT-M Auth/Referral Inquiry</fullName>
                </value>
                <value>
                    <fullName>MBCC - Credit Card Inquiry</fullName>
                </value>
                <value>
                    <fullName>MBEI - EBill Inquiry</fullName>
                </value>
                <value>
                    <fullName>MBEN-M Benefits</fullName>
                </value>
                <value>
                    <fullName>MBFA - M BlueFund Administration</fullName>
                </value>
                <value>
                    <fullName>MBII - Invoice Inquiry</fullName>
                </value>
                <value>
                    <fullName>MBIL-M Billing</fullName>
                </value>
                <value>
                    <fullName>MBMP - Missing Payment</fullName>
                </value>
                <value>
                    <fullName>MBPA - Payment Arrangement</fullName>
                </value>
                <value>
                    <fullName>MBRR - Request to Reinstate</fullName>
                </value>
                <value>
                    <fullName>MBTI - Termination Inquiry</fullName>
                </value>
                <value>
                    <fullName>MCAC-M Credit &amp; Collection</fullName>
                </value>
                <value>
                    <fullName>MCDH-M CDH</fullName>
                </value>
                <value>
                    <fullName>MCHK-M Check Inquiry</fullName>
                </value>
                <value>
                    <fullName>MCLM-M Claim Status</fullName>
                </value>
                <value>
                    <fullName>MCMP-M Complaint Plan/Service</fullName>
                </value>
                <value>
                    <fullName>MCOB-M COB</fullName>
                </value>
                <value>
                    <fullName>MCOR - M Correspondence</fullName>
                </value>
                <value>
                    <fullName>MDED-M Deductible</fullName>
                </value>
                <value>
                    <fullName>MDEM-M Demographics</fullName>
                </value>
                <value>
                    <fullName>MDIQ-M Duplicate Inquiry</fullName>
                </value>
                <value>
                    <fullName>MDOC-M Document Request</fullName>
                </value>
                <value>
                    <fullName>MELG-M Eligibility</fullName>
                </value>
                <value>
                    <fullName>MENR - Enrollment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facets_case_ID__c</fullName>
        <description>Enter Facets Case ID</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Facets Case ID</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Group_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Group ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to tie a case to a 2-50 Group Account based on Facets Account Number. this is used in the back end for 360 degree view of case</description>
        <label>2-50 Group Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <infoMessage>Please enter name or Group Id and Check "All fields" to find the Group you are looking for</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Group Cases(2-50)</relationshipLabel>
        <relationshipName>Group_Cases_2_50</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Group_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>To be used when Group not found in Group Name lookup</inlineHelpText>
        <label>New Group ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Internal Reason Code</description>
        <label>Internal Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>C001-Closed First Contact</fullName>
                </value>
                <value>
                    <fullName>C002-Questions(s) Answered</fullName>
                </value>
                <value>
                    <fullName>C003-Adjustment Completed</fullName>
                </value>
                <value>
                    <fullName>C004-Materials/Documents Sent</fullName>
                </value>
                <value>
                    <fullName>C005-Information Received</fullName>
                </value>
                <value>
                    <fullName>C006-Information Not Received</fullName>
                </value>
                <value>
                    <fullName>C007-Letter Sent</fullName>
                </value>
                <value>
                    <fullName>C008-E-mail Response</fullName>
                </value>
                <value>
                    <fullName>C009-Executive Level Response</fullName>
                </value>
                <value>
                    <fullName>C010-No Response Necessary</fullName>
                </value>
                <value>
                    <fullName>C011-Returned Call</fullName>
                </value>
                <value>
                    <fullName>C012-No Record of Inquiry</fullName>
                </value>
                <value>
                    <fullName>C013-Received in Central Appeals</fullName>
                </value>
                <value>
                    <fullName>C014-Referred to Carefirst.com</fullName>
                </value>
                <value>
                    <fullName>C100-Other</fullName>
                </value>
                <value>
                    <fullName>CO01-Approved Exception</fullName>
                </value>
                <value>
                    <fullName>CO03-Billing discrepancies</fullName>
                </value>
                <value>
                    <fullName>CO06-Claim rejected in error</fullName>
                </value>
                <value>
                    <fullName>CO09-Corrected claim received</fullName>
                </value>
                <value>
                    <fullName>CO12-Enrollment discrepancies</fullName>
                </value>
                <value>
                    <fullName>CO15-EOB received</fullName>
                </value>
                <value>
                    <fullName>CO18-No Authorization of file</fullName>
                </value>
                <value>
                    <fullName>CO21-PAR Medical Rev-pay rej lines</fullName>
                </value>
                <value>
                    <fullName>CO24-Waiting period removed</fullName>
                </value>
                <value>
                    <fullName>CO25-CF Primary/newly identified</fullName>
                </value>
                <value>
                    <fullName>CO26-CF Secondary/newly identified</fullName>
                </value>
                <value>
                    <fullName>CO27-CF Primary/Prev identified</fullName>
                </value>
                <value>
                    <fullName>CO28-CF Secondary/Prev identified</fullName>
                </value>
                <value>
                    <fullName>CO29-Other, See Task Notes</fullName>
                </value>
                <value>
                    <fullName>CU01-Claim paid correctly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_Reason__c</fullName>
        <description>Enter External Notes that is to be viewed by external users</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Resolution Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Facets_User_ID__c</fullName>
        <description>Stores the Facets user id. This is used by the Facets Integration when submitting case create/update requests</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Stores the Facets user id. This is used by the Facets Integration when submitting case create/update requests</inlineHelpText>
        <label>Facets User ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/FCI_UpdateCaseRequest.cls
/*=========================================================================================
 * Date		: 11/6/15
 * Developer	: Ken Gill
 * Purpose   	:  
 *               This class represents changes to between a new and old version of a Salesforce 
 *               case record. It assumes the SF case ID for the record is identical and limits to 
 *               checking for changes on a limited set of fields: Facets Subject, Category, SF Status,
 *               and Resolution Reason.
 *
 *=========================================================================================
 *                                 Update History
 *                                 ---------------
 * Date       Developer         Description
 *===========+============+================================================================
 * 11/6/15   |  KG    |	Initial Version                                         
 *   	     |        | 
 *=========================================================================================
 */
 
public with sharing class FCI_UpdateCaseRequest extends FCI_Message {

	 // used for logging related records used to build request data
	public Map<String,String> relatedRecords { get; set; }	

	public Id caseId {get;set;}
	public String facetsCaseId { get; set; }	
	public Case caseObject { get; set; }
	public CaseComment caseCommentObject { get; set; }
    
	Map<String,String> updateFields = new Map<String,String>();

/*************************************************************************************
 * Purpose   : Default no-arg constructor. Useful for writing test code without requiring a Case object
 *             for instantiation
 * Parameters: None
 *
 * Return    : None
 *************************************************************************************/
	   
	public FCI_UpdateCaseRequest() {
	 super();
	 this.msgType = IntegrationMessage.REQUEST;
	 this.isValid = false;	// by default
	}

/*************************************************************************************
 * Purpose   : Creates an update object that represents the difference among selected fields
 *             of a Salesforce case record between old and new version of the record. The compared
 *             fields are limited to requirements defined fields for which updates should be sent to the
 *             Facets system. (Facets Subject, Facets Category, SF Status and Resolution reason)
 *             
 * Parameters: Case newVersion - modified instance of SF Case record 
 *             Case oldVersion - pre-modification baseline copy of SF Case record
 * Return    : None
 *************************************************************************************/
	
	public FCI_UpdateCaseRequest( Case newVersion, Case oldVersion) {
		super();
		this.msgType = IntegrationMessage.REQUEST;
		if( newVersion == null || oldVersion == null || String.isBlank(newVersion.Facets_case_ID__c) ) {
			this.isValid = false;
			System.debug('Received a null Case argument to FCI_UpdateCaseRequest(Case c) constructor');
			return;
		}
	
		this.isValid = true;	// by default
	 	caseObject = newVersion;
		caseID = newVersion.Id;
		facetsCaseId = newVersion.facets_case_ID__c; 
		
		String notes = ' ';
		
		if( newVersion.Description != null 
		    	&& 
		    !newVersion.Description.equals(oldVersion.Description)) {
		    	
			String header;
			if( String.isBlank(oldVersion.Description)) {
				header = '\n====Description ====\n\n';
			} else {
				header = '\n====Description Updated====\n\n';
			}
			notes = notes + header + newVersion.Description;			
		}

		if( newVersion.Resolution_Reason__c != null 
		    	&& 
		    !newVersion.Resolution_Reason__c.equals(oldVersion.Resolution_Reason__c)) {
		    	
			String header;
			if( String.isBlank(oldVersion.Resolution_Reason__c)) {
				header = '\n====Resolution ====\n\n';
			} else {
				header = '\n====Resolution Updated====\n\n';
			}
			notes = notes + header + newVersion.Resolution_Reason__c;			
		}

		if( !String.isBlank(notes)) {
			updateFields.put('Notes', notes);
		}
				
		
		if( ! newVersion.Facets_Category__c.equals(oldVersion.Facets_Category__c)) {
			updateFields.put('Category', get4LetterPrefixCode(newVersion.Facets_Category__c));
		}
		if( ! newVersion.Facets_Subject__c.equals(oldVersion.Facets_Subject__c)) {
			updateFields.put('Subject', get4LetterPrefixCode(newVersion.Facets_Subject__c));			
		}
		if( newVersion.Reason__c !=null && ! newVersion.Reason__c.equals(oldVersion.Reason__c)) {
			updateFields.put('Reason', get4LetterPrefixCode(newVersion.Reason__c));			
		}
		
		// SLA Category change detection. The related formula field Facets_Satisfaction_Level__c will hold the mapped value from Salesforce 
		// SLA Category picklist selection to Facets satisfaction level (which is what we need to send to Facets).  
		if( ! newVersion.Facets_Satisfaction_Level__c.equals(oldVersion.Facets_Satisfaction_Level__c)) {
			updateFields.put('CSSC_SLACategory', newVersion.Facets_Satisfaction_Level__c);			
		}
				
		// TBD - Clarify which status is meant by IAD
		if( ! newVersion.Status.equals(oldVersion.Status)) {
			String newFacetsStatus = 'OP';	// Default. The Facets code for Open status
			if( newVersion.Status.StartsWith('Closed')) {
				newFacetsStatus = 'CL'; 	// Code for Facets Closed status
				updateFields.put('closedDate', FCI_Util.getDateTimeAsMMDDYYYY(DateTime.now()) );
			} 
			
			updateFields.put('Status', newFacetsStatus);
			updateFields.put('POC', FCI_Util.mapCaseStatusToProofOfClosureCode(newVersion.Status));
		}
		
		// ---Start: Subject line edited  ---------------		
		if( !String.isBlank(newVersion.Subject )  && ! newVersion.Subject.equals(oldVersion.Subject)) {
			updateFields.put('Summary', newVersion.Subject);
		}
		
		// ---Start: Group lookup and Group ID manual override edit handling ---------------

		// Manually entered Group Id field changed. Group ID here refers to the Facets Account number for a Group.
		// if new field value not empty and different from previous value
		// Note - Group_ID__c (when manual entry field is used) is the Facets account number for the group
		if( !String.isBlank(newVersion.New_Group_ID__c )  && ! newVersion.New_Group_ID__c.equals(oldVersion.New_Group_ID__c)) {
			updateFields.put('groupID', newVersion.New_Group_ID__c);
		}

		// Group account lookup changed, only process this if manually entered Group_Id__c override field is empty
		// Field:Group_Name__c is a lookup field i.e. Id field
		// Group ID refers to Facets account number for a Group
		System.debug( 'newVersion.New_Group_ID__c=' + newVersion.New_Group_ID__c);
		System.debug( 'newVersion.Group_Name__c=' + newVersion.Group_Name__c);
		System.debug( 'oldVersion.Group_Name__c=' + oldVersion.Group_Name__c);
		if( String.isBlank( newVersion.New_Group_ID__c) && 
                    ( !String.isBlank(newVersion.Group_Name__c) &&  !newVersion.Group_Name__c.equals(oldVersion.Group_Name__c))) {
			Account a = [ select Id, Facets_Account_Number__c from Account where Id = :newVersion.Group_Name__c];
			updateFields.put('groupID', a.Facets_Account_Number__c);
		}

		// -----Case Owner Change ------------------------------------------------------------------
		// When case owner is changed, send the Facets User ID of the new case owner
		if( newVersion.OwnerID != oldVersion.OwnerID) {
			User u = [ Select Id, Facets_User_ID__c, Email from User where Id = :newVersion.OwnerID];
			updateFields.put('caseOwnerID', u.Facets_User_ID__c);
			updateFields.put('caseOwnerEmailID', u.Email);			
		}
				
		// -----Case Broker Agent Contact Replacement and Contact Modification handling------------------------
		
			// if Broker Agent contact was replaced with another Broker Agent contact
		if( !String.isBlank(newVersion.Broker_Agent__c) && ( newVersion.Broker_Agent__c != oldVersion.Broker_Agent__c) ) {
			Contact c = [SELECT Id, Entity_ID__c from Contact where Id = :newVersion.Broker_Agent__c ];
			if( String.isBlank(c.Entity_ID__c)) {
				System.debug( 'New Broker Contact does not have a value for EntityID populated. New Broker Agent Contact record=' + String.valueOf(c));
			} else {
			updateFields.put('CSSC_BrokerID', c.Entity_ID__c);
			}
		}
		
		//---------------------Case Broker Agent Contact Modified----------------------------------------------------------------------
			// if Broker Agent Contact was not changed but just modified, that scenario is handled by Contact trigger using the constructor 
			// version that takes the relatedCase and Contact new,old records
			
			
		//---------------------Case Contact Changed to a different Contact --------------------------------------------------
		// Note: This handles change of Case Contact to a different Contact. This is different from modifying existing Case 
		// Contact fields which is handled via ContactTriggerHandler
		if( newVersion.contactId != oldVersion.contactId) {
			updateFields.putAll( FCI_Util.getContactChangeFields( new Contact( Id = newVersion.contactId)));
		}
		
		
		//-------------------------------------------------------------------------------------------
		
		if( !updateFields.isEmpty()) {
			// Anytime there is an update, regardless of change, add lastModifiedDate as a updatefield
			updateFields.put('lastModifiedDate', FCI_Util.getDateTimeAsMMDDYYYY(DateTime.now()));
			
			// There is a relevant change to send
			// Create the update request
			System.debug('Found case updates to send to Facets=' + String.ValueOf(updateFields));
			// TBD - Create a FCI_UpdateCaseRequest and send it
			
		} else {
			System.debug('Found no eligible case updates to send to Facets');
		}					
	}

/*************************************************************************************
 * Purpose   : Constructor version that creates a new update message based on a new Case Comment
 *             being added to a Case.
 *             this
 * Parameters: CaseComment comment - a new comment added to a SF case
 *             Case parentCase - related Case on which the comment was added
 *
 * Return    : None
 *************************************************************************************/

	public FCI_UpdateCaseRequest( CaseComment comment, Case parentCase) {
	 super();
	 this.msgType = IntegrationMessage.REQUEST;
	 if( comment == null || comment.parentId == null || parentCase == null || String.isBlank(parentCase.Facets_case_ID__c) ) {
	 	this.isValid = false;
	 	System.debug('Received a null CaseComment, parent Case argument or parent Case.Facets_case_ID__c to FCI_UpdateCaseRequest(CaseComment comment) constructor');
	 	return;
	 }
	 
	 try {	 	 
	     caseObject = parentCase;
	     caseId = comment.parentId;
	     facetsCaseId = caseObject.facets_case_ID__c;
	     updateFields.put( 'Notes', comment.CommentBody);
	     this.isValid = true;
	 } catch (Exception e) {
		System.debug('Exception when executing DML to retrieve related Case from CaseComment with parentId=' + comment.parentId);
		this.isValid = false;
	 }	
	}	

/*************************************************************************************
 * Purpose   : Constructor version that creates a new update message based on a Case Contact
 *             (i.e. Broker Contact) being updated. The new (updated) and old versions of the
 *             Case's broker Contact are used to detect which fields were updated.
 *
 * Parameters: Case relatedCase - the Case record related to the Contact being modified 
 *             Contact newVersion - the new Contact record with modified fields
 *             Contact oldVersion - the old Contact record with pre-modification field values 
 *
 * Return    : None
 *************************************************************************************/
	public FCI_UpdateCaseRequest( Case relatedCase, Contact newVersion, Contact oldVersion ) {
	 super();
	 this.msgType = IntegrationMessage.REQUEST;
	 if( newVersion == null || newVersion.Id == null || relatedCase == null || String.isBlank(relatedCase.Facets_case_ID__c) ) {
	 	this.isValid = false;
	 	System.debug('Received a null or empty Case object, Contact newVersion or Case.Facets_case_ID__c to FCI_UpdateCaseRequest(Case relatedCase, Contact newVersion, Contact oldVersion) constructor');
	 	return;
	 }
	 
	 try {
	     caseObject = relatedCase;
	     caseId = relatedCase.Id;
	     facetsCaseId = caseObject.facets_case_ID__c;
	     updateFields.putAll( FCI_Util.getContactChangeFields( newVersion, oldVersion) );
	     this.isValid = true;
	 } catch (Exception e) {
		System.debug('Exception in method FCI_UpdateCaseRequest( Case relatedCase, Contact newVersion, Contact oldVersion ) = ' + e.getMessage());
		this.isValid = false;
	 }	
	}	
	
/*************************************************************************************
 * Purpose   : Boolean check method to denote if the message is valid. Does various checks on 
 *             received constructor arguments to determine if message is valid.
 *             
 * Parameters: None
 *
 * Return    : None
 *************************************************************************************/
// validate Facets update case request
public FCI_Validation validateRequest() {
	FCI_Validation validation = new FCI_Validation();
	if( String.isBlank(facetsCaseID) || updateFields == null || updateFields.isEmpty()) {
		validation.isValid = false;
		validation.addFieldValidationError('Fields', 'Missing facetsCaseID or updateFields is null or empty');
		return validation;
	}
	
	validation.isValid = true; 	// default
	return validation;
}

/*************************************************************************************
 * Purpose   : Extract 4-letter prefix from given input string.
 *             
 * Parameters: String s - the string from which to extract 4-letter code.
 *
 * Return    : None
 *************************************************************************************/
	
	public String get4LetterPrefixCode(String s) { return s == null? null : s.subString(0,4); }
	
	public Map<String,String> getCaseUpdates() { return updateFields; }
	   
}