objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status defines if the 2-50 customer account is active or termed based on the active file or the term file that it was updated from.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
                <value>
                    <fullName>Migrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Implementation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>AIA_Post_Sales_Implementation</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Implementation</label>
    <nameField>
        <displayFormat>IMP-{000000}</displayFormat>
        <label>Implementation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Benfit_Request_Form__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Request Forms</relationshipLabel>
        <relationshipName>Benfit_Request_Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Benefit_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Benefit Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Count__c</fullName>
        <label>Contract Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Escalated_to_Senior_Management__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalated to Senior Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Benefit Request Forms</relationshipLabel>
        <relationshipName>Benfit_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect/New</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Renew As-is</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle - Administrative Change</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle - Benefit Change</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle - Administrative and Benefit Change</fullName>
                </value>
                <value>
                    <fullName>Renewal - Administrative Changes</fullName>
                </value>
                <value>
                    <fullName>Renewal - Benefit Changes</fullName>
                </value>
                <value>
                    <fullName>Renewal - Admin and Benefit Changes</fullName>
                </value>
                <value>
                    <fullName>Set-up Change - Administrative Changes</fullName>
                </value>
                <value>
                    <fullName>Set-up Change - Benefit Changes</fullName>
                </value>
                <value>
                    <fullName>Set-up Change - Admin and Benefit Changes</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Benefit Request Form Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Revised Approved</fullName>
                </value>
                <value>
                    <fullName>Sold-Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>New object for AIA - This object stores the information that is needed for a quote</description>
    <label>Benefit Request Form</label>
    <nameField>
        <displayFormat>BRF-{000000}</displayFormat>
        <label>Benefit Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Request Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>ASO</fullName>
        <active>true</active>
        <description>ASO Layout</description>
        <label>ASO</label>
    </recordTypes>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Process__c.object
<CustomObject>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Process</relationshipLabel>
        <relationshipName>Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <description>Used to identify the Sequence number of the record for sorting</description>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to identify the status of the record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Run time Object used for AIA workplan 
AIA - Custom object used to store the Stage, type &amp; status of Runtime Process. This object is a Parent object for Run time AIA Workplan. 
This is implemented for JUNE-2018 Release.</description>
    <label>Process</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Sub_Process__c.object
<CustomObject>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Sub Process</relationshipLabel>
        <relationshipName>Sub_Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Sub Process</relationshipLabel>
        <relationshipName>Sub_Processes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <description>Used to identify the Sequence number of the record for sorting</description>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to identify the status of the record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Run time Object used for AIA workplan Stage
AIA - Custom object used to store the Stage, type &amp; status of Runtime Sub Process. This object is a child object for Run time Process object. 
This is implemented for JUNE-2018 Release.</description>
    <label>Sub Process</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Sub Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Workplan_Task__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Workplan Tasks</relationshipLabel>
        <relationshipName>Workplan_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ExpectedDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Task Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Workplan Tasks</relationshipLabel>
        <relationshipName>Workplan_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Workplan Tasks</relationshipLabel>
        <relationshipName>Workplan_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Process</label>
        <referenceTo>Sub_Process__c</referenceTo>
        <relationshipLabel>Workplan Tasks</relationshipLabel>
        <relationshipName>Workplan_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Task Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Days_to_Complete_Task_SLA__c</fullName>
        <description>This field value will store the expected SLA days, the task needs to be completed</description>
        <label>Total Days to Complete Task (SLA)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>AIA - Custom Object used to capture the runtime version of tasks which are created from Workplan Task Template. The status of these tasks can be updated by the users. This object is related to Opportunity and Implementation objects since Pre-Sales &amp; Post-Sales tasks are created in this object and assigned to the user.
This object will replace the old functionality. 
This is implemented for Nov-2017 Release.</description>
    <label>Workplan Task</label>
    <nameField>
        <displayFormat>Workplan Task - {0000}</displayFormat>
        <label>Workplan Task</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Tasks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AIA_Custom_Task_ControllerTest.cls
/*=========================================================================================
* Date         : 04/18/18
* Developer    : Arshia Gulati
* Purpose      : This class contains unit tests for AIA_Custom_Task_Controller
*=========================================================================================
*                                 Update History
*                                 ---------------
* Date       Developer         Description
*===========+============+================================================================
* 04/18/18  |  AG    |     |This class is used to test AIA_Custom_Task_Controller
* 05/03/2018|Gayathri|  T01|Added a test method to chec create custom task in BRF as part of US228 
* 05/08/2018|AG      |  T03|Added a test method to assign team role and member US1790
* 05/14/2018|AG      |  T04|Add test to check number of active tasks assigned to team members US1691
* 06/05/2018|AG      |  T05| Updated to populate SLA Days based on Due Date US890 enhancement
* 02/24/2019|Chaithra|  T06| Changed reference from Standard obj to Custom Obj
*=========================================================================================
*/
@isTest
public class AIA_Custom_Task_ControllerTest {
    //T03-Start
    //Create test data
    @testSetup static void testdata() {
        
        Profile nonAdminProfile = [select id from profile where name='AIA 200+ Standard User - Custom'];
        Profile adminProfile = [select id from profile where name='System Administrator'];
        
        //Creating User Test Data 
        List<user> userList = new list<user>();
        
        user u1 = AIA_TestUtil.AIA_createUser('alias1');
        u1.LastName = 'alias1';
        u1.ProfileId= nonAdminProfile.Id;
        userList.add(u1); 
        
        user u2 = AIA_TestUtil.AIA_createUser('alias2');
        u2.LastName = 'alias2';
        u2.ProfileId =nonAdminProfile.Id;
        userList.add(u2);
        
        user u3 = AIA_TestUtil.AIA_createUser('alias3');
        u3.LastName = 'alias3';
        u3.ProfileId=nonAdminProfile.Id;
        userList.add(u3); 
        
        user u4 = AIA_TestUtil.AIA_createUser('alias4');
        u4.LastName = 'alias4';
        u4.ProfileId=AdminProfile.Id;
        userList.add(u4);
        
        user u5 = AIA_TestUtil.AIA_createUser('alias5');
        u5.LastName = 'alias5';
        u5.ProfileId=nonAdminProfile.Id;
        userList.add(u5);
        
        user u6 = AIA_TestUtil.AIA_createUser('alias6');
        u6.LastName = 'alias6';
        u6.ProfileId=nonAdminProfile.Id;
        userList.add(u6);
        
        user u7 = AIA_TestUtil.AIA_createUser('alias7');
        u7.LastName = 'alias7';
        u7.ProfileId=AdminProfile.Id;
        userList.add(u7);
        
        insert userList;
        
        AIA_TestUtil.CreateAreaManager(u1.id, 'Implementation Manager;BeneFact Coder;BeneFact Tester', 'BeneFact Coder;BeneFact Tester', 'alias1', 'Manager');
        AIA_TestUtil.CreateAreaManager(u2.id, 'BeneFact Coder', '', 'alias2', 'Non-Manager');
        AIA_TestUtil.CreateAreaManager(u3.id, 'BeneFact Coder;BeneFact Tester', '', 'alias3', 'Non-Manager');
        AIA_TestUtil.CreateAreaManager(u4.id, 'AIA Admin;BeneFact Tester', 'BeneFact Tester;AIA Admin', 'alias4', 'Manager');
        AIA_TestUtil.CreateAreaManager(u5.id, 'BeneFact Tester', '', 'alias5', 'Non-Manager');
        AIA_TestUtil.CreateAreaManager(u6.id, 'AIA Admin;BeneFact Tester', 'AIA Admin', 'alias6', 'Manager');
        
        //T05 - Start
        Account acc = AIA_TestUtil.CreateAccount('TestAccount');       
        //List<AccountTeamMember> acctMbrList = new List<AccountTeamMember>();//T06
        List<Account_Team__c> acctMbrList = new List<Account_Team__c>();//t06
        acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(acc.Id,u1.id,'Account Executive')); 
        acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(acc.Id,u2.id,'Proposal Specialist')); 
        acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(acc.Id,u3.id,'Account Manager'));
        insert acctMbrList;        
        Opportunity opp = AIA_TestUtil.CreateOpportunity(acc.Id);
        AIA_Implementation__c objImpl = AIA_TestUtil.CreateImplementation(opp.Id);        
        List<Process__c> objProcess = AIA_TestUtil.CreateProcessList(objImpl.Id);        
        List<Sub_Process__c> objSubProc = AIA_TestUtil.CreateSubProcessList(objImpl.Id,objProcess[0].Id);
        //T05 - End
        
    }
    //Create task as Implementation Manager - Assign Task to team members who belongs to the area managed by the IP-Manager
    @isTest static void test_CreateTaskAsManager() {
        AIA_Implementation__c  objImpl = [SELECT id  from AIA_Implementation__c Limit 1]; //T05 
        User  u1 = [SELECT id  from User where LastName = 'alias1' Limit 1];  
        User  u2 = [SELECT id  from User where LastName = 'alias2' Limit 1]; 
        User  u3 = [SELECT id  from User where LastName = 'alias3' Limit 1]; 
        
        Test.startTest();
        System.runAs(u1){
            AIA_Custom_Task_Controller cntl = new AIA_Custom_Task_Controller(new Apexpages.StandardController(objImpl));        
            
            //Test for Task Name validation
            cntl.SaveTask();
            System.Debug('AG ApexPages.getMessages()' +ApexPages.getMessages());
            System.assertEquals( ApexPages.getMessages()[0].getDetail(),'Please enter New Task Name.');
            
            //Test for SubProcess List
            List<SelectOption> lstSubProcess = cntl.getSubprocessList();
            System.assertNotEquals(null, lstSubProcess);
            
            //Test for Task Description validation
            cntl.objTask.Task_Name__c = 'New Test Task';
            cntl.SaveTask();        
            System.Debug('AG ApexPages.getMessages()' +ApexPages.getMessages());
            System.assertEquals( ApexPages.getMessages()[1].getDetail(),'Please enter Task Description.');
            
            //Test for Team Member Name validation
            cntl.objTask.Description__c = 'New Task Description';
            System.Debug('AG ApexPages.getMessages()' +ApexPages.getMessages());
            
            //Test for Due Date validation   
            cntl.selected_TeamRole = 'BeneFact Coder';
            cntl.SelectTeamMember();
            cntl.selected_TeamMember = u2.Id;
            cntl.SaveTask();
            System.assertEquals( ApexPages.getMessages()[2].getDetail(),'Please enter Total Days to Complete Task (SLA).'); //T05 
            
            //Test for SLA Edit by 'Business' DayType        
            Date dt = System.today();        
            //T05 - Start
            cntl.objTask.Total_Days_to_Complete_Task_SLA__c = 10;//dt.addDays(10);
            cntl.SetDueDate();
            AIA_CalculateDaysDiffExcludingHoliday calDate = new AIA_CalculateDaysDiffExcludingHoliday();
            System.assertEquals(String.valueOf(calDate.addBussinessDays(dt,Integer.valueOf(cntl.objTask.Total_Days_to_Complete_Task_SLA__c))),String.valueOf(cntl.objTask.ExpectedDate__c)); 
            
            //Test for SLA Edit by 'Calendar' DayType
            cntl.daytype='Calendar';
            cntl.SetDueDate();
            System.assertEquals(String.valueOf(dt.addDays(10)),String.valueOf(cntl.objTask.ExpectedDate__c)); 
            //T05 - End  
            
            //Test for Task Creation
            cntl.SaveTask();  
            WorkPlan_Task__c objTsk = [select Id,Sequence_Number__c,Implementation__c 
                                       from WorkPlan_Task__c 
                                       where Implementation__c =:objImpl.Id 
                                       and Task_Name__c = 'New Test Task' LIMIT 1]; 
            System.assertNotEquals(null,objTsk.Id);
            
            //Test for Cancel Screen
            PageReference  returnedPage = cntl.CancelTask();
            PageReference  expectedpage = new PageReference( '/' + objImpl.Id);
            System.assertEquals(returnedPage.getUrl(),expectedpage.getUrl());
            
            //T04 - Start - Test Active Tasks are assigned to the User
            AIA_Custom_Task_Controller cntl2 = new AIA_Custom_Task_Controller(new Apexpages.StandardController(objImpl));                
            cntl2.selected_TeamRole = 'BeneFact Coder';
            cntl2.SelectTeamMember();
            System.assertEquals(cntl2.mapUserIDToTasksCount.get(u2.Id),1);
            System.assertEquals((cntl2.TeamMemberList.get(2)).getLabel(),'alias2#1 Active tasks');
            System.assertEquals((cntl2.TeamMemberList.get(3)).getLabel(),'alias3#No Active tasks');
            //T04 - End  
        }
        Test.stopTest();
    }
    //T03-End
    
    @isTest static void test_CreateTaskAsAdmin() {
        
        AIA_Implementation__c  objImpl = [SELECT id  from AIA_Implementation__c Limit 1]; //T05 
        User  u1 = [SELECT id  from User where LastName = 'alias4' Limit 1];  
        User  u2 = [SELECT id  from User where LastName = 'alias5' Limit 1]; 
        
        Test.startTest();
        System.runAs(u1){
            AIA_Custom_Task_Controller cntl = new AIA_Custom_Task_Controller(new Apexpages.StandardController(objImpl));        
            
            //Test for Task Name validation
            cntl.SaveTask();
            System.Debug('AG ApexPages.getMessages()' +ApexPages.getMessages());
            System.assertEquals( ApexPages.getMessages()[0].getDetail(),'Please enter New Task Name.');
            
            //Test for SubProcess List
            List<SelectOption> lstSubProcess = cntl.getSubprocessList();
            System.assertNotEquals(null, lstSubProcess);
            
            //Test for Task Description validation
            cntl.objTask.Task_Name__c = 'New Test Task';
            cntl.SaveTask();        
            System.Debug('AG ApexPages.getMessages()' +ApexPages.getMessages());
            System.assertEquals( ApexPages.getMessages()[1].getDetail(),'Please enter Task Description.');
            
            //Test for Team Member Name validation
            cntl.objTask.Description__c = 'New Task Description';
            System.Debug('AG ApexPages.getMessages()' +ApexPages.getMessages());
            
            //Test for Due Date validation   
            cntl.selected_TeamRole = 'BeneFact Tester';//(cntl.TeamRoleList.get(1)).getValue(); 
            cntl.SelectTeamMember();
            cntl.selected_TeamMember = u2.Id;
            cntl.SaveTask();
            System.assertEquals( ApexPages.getMessages()[2].getDetail(),'Please enter Total Days to Complete Task (SLA).'); //T05 
            
            //Test for SLA Edit by 'Business' DayType        
            Date dt = System.today();        
            //T05 - Start
            cntl.objTask.Total_Days_to_Complete_Task_SLA__c = 10;
            cntl.SetDueDate();
            AIA_CalculateDaysDiffExcludingHoliday calDate = new AIA_CalculateDaysDiffExcludingHoliday();
            System.assertEquals(String.valueOf(calDate.addBussinessDays(dt,Integer.valueOf(cntl.objTask.Total_Days_to_Complete_Task_SLA__c))),String.valueOf(cntl.objTask.ExpectedDate__c)); 
            
            //Test for SLA Edit by 'Calendar' DayType
            cntl.daytype='Calendar';
            cntl.SetDueDate();
            System.assertEquals(String.valueOf(dt.addDays(10)),String.valueOf(cntl.objTask.ExpectedDate__c)); 
            //T05 - End
            
            //Test for Task Creation
            cntl.SaveTask();  
            WorkPlan_Task__c objTsk = [select Id,Sequence_Number__c,Implementation__c 
                                       from WorkPlan_Task__c 
                                       where Implementation__c =:objImpl.Id 
                                       and Task_Name__c = 'New Test Task' LIMIT 1]; 
            System.assertNotEquals(null,objTsk.Id);
            
            //Test for Cancel Screen
            PageReference  returnedPage = cntl.CancelTask();
            PageReference  expectedpage = new PageReference( '/' + objImpl.Id);
            System.assertEquals(returnedPage.getUrl(),expectedpage.getUrl());
        }
        Test.stopTest();
    }
    
    @isTest static void test_CreateTaskAsAdminRole() {
        
        AIA_Implementation__c  objImpl = [SELECT id  from AIA_Implementation__c Limit 1]; //T05 
        User  u1 = [SELECT id  from User where LastName = 'alias6' Limit 1];  
        User  u2 = [SELECT id  from User where LastName = 'alias5' Limit 1]; 
        
        Test.startTest();
        System.runAs(u1){
            AIA_Custom_Task_Controller cntl = new AIA_Custom_Task_Controller(new Apexpages.StandardController(objImpl));        
            
            //Test for SubProcess List
            List<SelectOption> lstSubProcess = cntl.getSubprocessList();
            System.assertNotEquals(null, lstSubProcess);
            
            cntl.objTask.Task_Name__c = 'New Test Task3';
            cntl.objTask.Description__c = 'New Task Description';
            cntl.selected_TeamRole = 'BeneFact Tester';
            cntl.SelectTeamMember();
            Date dt = System.today();        
            //T05 - Start
            cntl.objTask.Total_Days_to_Complete_Task_SLA__c = 10;
            cntl.SetDueDate();
            //T05 - End
            cntl.SaveTask();  
            System.Debug('AG ApexPages.getMessages()' +ApexPages.getMessages());
            System.assertEquals( ApexPages.getMessages()[0].getDetail(),'Please select Team Member.');
            
            cntl.selected_TeamMember = u2.Id;
            cntl.SaveTask();
            
            WorkPlan_Task__c objTsk = [select Id,Sequence_Number__c,Implementation__c 
                                       from WorkPlan_Task__c 
                                       where Implementation__c =:objImpl.Id 
                                       and Task_Name__c = 'New Test Task3' LIMIT 1]; 
            System.assertNotEquals(null,objTsk.Id);        
        }
        Test.stopTest();
    }
    
    @isTest static void test_CreateBRFTask() {
         Test.StartTest(); 
        //T05 - Start
        Account  acc = [SELECT id  from Account Limit 1]; 
        Opportunity  opp = [SELECT id  from Opportunity Limit 1]; 
        //T05 - End
        Benfit_Request_Form__c brf = new Benfit_Request_Form__c();
        brf.Request_Type__c = 'Renew As-is';
        brf.recordTypeId=QueryBase.getRecordtypeId('Benfit_Request_Form__c', 'ASO');
        brf.Contract_Count__c = 123;
        brf.Benefit_Effective_Date__c = system.today();
        brf.Account__c = acc.id;
        brf.Escalated_to_Senior_Management__c = true;
        brf.Status__c = 'new';
        brf.Opportunity__c = opp.id;
        brf.Jurisdiction__c = 'MD';
        brf.Enrollment_Type__c = 'Cafeteria';
        //brf.MHP_Test_Result__c = 'Pass';
        brf.EGWP_Picklist__c = 'Yes';
        brf.FlexLink_Picklist__c = 'Yes';
        brf.Benefit_Effective_Date__c = system.today();
        brf.Benefit_Period__c = 'Contract';
        brf.Control_Plan__c = '690';
        brf.Sales_Segment_Size__c = 'Commercial 200-999';
        brf.Contract_Period__c = 'Standard - 12 Months';
        brf.Grandfathered_Status__c = 'Non-Grandfathered';
        brf.Grandfathered_PPACA_Status__c = 'Yes';
        brf.Stop_Loss__c = 'Carefirst';
        brf.Broker_Consultant_Compensation__c = 'Commission (%)';
        brf.Broker_Consultant_Amount__c = 50;
        brf.Identity_Protection__c = 'Yes';
        brf.Enrollment_Type__c = 'Parallel';
        brf.Funding_Arrangements__c = 'ASO';
        insert brf;
        //Test.startTest();
        
        
        Test.stopTest();
    }   
    @isTest
    private static void testClass()
    {
        Test.StartTest(); 
        PageReference pageRef = Page.AIA_CreateCustomTask;
        Account  acc = [SELECT id  from Account Limit 1]; 
        Opportunity  opp = [SELECT id  from Opportunity Limit 1]; 
        //T05 - End
        Benfit_Request_Form__c brf = new Benfit_Request_Form__c();
        brf.Request_Type__c = 'Renew As-is';
        brf.recordTypeId=QueryBase.getRecordtypeId('Benfit_Request_Form__c', 'ASO');
        brf.Contract_Count__c = 123;
        brf.Benefit_Effective_Date__c = system.today();
        brf.Account__c = acc.id;
        brf.Escalated_to_Senior_Management__c = true;
        brf.Status__c = 'new';
        brf.Opportunity__c = opp.id;
        brf.Jurisdiction__c = 'MD';
        brf.Enrollment_Type__c = 'Cafeteria';
        //brf.MHP_Test_Result__c = 'Pass';
        brf.EGWP_Picklist__c = 'Yes';
        brf.FlexLink_Picklist__c = 'Yes';
        brf.Benefit_Effective_Date__c = system.today();
        brf.Benefit_Period__c = 'Contract';
        brf.Control_Plan__c = '690';
        brf.Sales_Segment_Size__c = 'Commercial 200-999';
        brf.Contract_Period__c = 'Standard - 12 Months';
        brf.Grandfathered_Status__c = 'Non-Grandfathered';
        brf.Grandfathered_PPACA_Status__c = 'Yes';
        brf.Stop_Loss__c = 'Carefirst';
        brf.Broker_Consultant_Compensation__c = 'Commission (%)';
        brf.Broker_Consultant_Amount__c = 50;
        brf.Identity_Protection__c = 'Yes';
        brf.Enrollment_Type__c = 'Parallel';
        brf.Funding_Arrangements__c = 'ASO';
        insert brf;
       
        
        
       
      // Test.StartTest(); 
        AIA_Custom_Task_Controller testAccPlan = new AIA_Custom_Task_Controller();
        
        
        //testAccPlan.save(); call all your function here
        Test.StopTest();
        
    }
    @isTest
    private static void testClass2()
    {
        Test.StartTest(); 
        Pagereference pageRef1 = Page.AIA_CreateCustomTask;   
        Account  acc = [SELECT id  from Account Limit 1]; 
        Opportunity  opp = [SELECT id  from Opportunity Limit 1]; 
        //T05 - End
        Benfit_Request_Form__c brf = new Benfit_Request_Form__c();
        brf.Request_Type__c = 'Renew As-is';
        brf.recordTypeId=QueryBase.getRecordtypeId('Benfit_Request_Form__c', 'ASO');
        brf.Contract_Count__c = 123;
        brf.Benefit_Effective_Date__c = system.today();
        brf.Account__c = acc.id;
        brf.Escalated_to_Senior_Management__c = true;
        brf.Status__c = 'new';
        brf.Opportunity__c = opp.id;
        brf.Jurisdiction__c = 'MD';
        brf.Enrollment_Type__c = 'Cafeteria';
        //brf.MHP_Test_Result__c = 'Pass';
        brf.EGWP_Picklist__c = 'Yes';
        brf.FlexLink_Picklist__c = 'Yes';
        brf.Benefit_Effective_Date__c = system.today();
        brf.Benefit_Period__c = 'Contract';
        brf.Control_Plan__c = '690';
        brf.Sales_Segment_Size__c = 'Commercial 200-999';
        brf.Contract_Period__c = 'Standard - 12 Months';
        brf.Grandfathered_Status__c = 'Non-Grandfathered';
        brf.Grandfathered_PPACA_Status__c = 'Yes';
        brf.Stop_Loss__c = 'Carefirst';
        brf.Broker_Consultant_Compensation__c = 'Commission (%)';
        brf.Broker_Consultant_Amount__c = 50;
        brf.Identity_Protection__c = 'Yes';
        brf.Enrollment_Type__c = 'Parallel';
        brf.Funding_Arrangements__c = 'ASO';
        insert brf;
        
               //Test.StartTest(); 

            PageReference pageRef = Page.AIA_CreateCustomTask; // Add your VF page Name here
            pageRef.getParameters().put('brfid', brf.id);
            pageRef.getParameters().put('brfid', String.valueOf(brf.Id));
            Test.setCurrentPage(pageRef);

            AIA_Custom_Task_Controller testAccPlan = new AIA_Custom_Task_Controller();
            //testAccPlan.redirctPage();    
        Test.StopTest();
    }
}