objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Legal_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_County_Code__c</fullName>
        <label>Billing County Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AA-Anne Arundel</fullName>
                </value>
                <value>
                    <fullName>AL-Allegany</fullName>
                </value>
                <value>
                    <fullName>BA-Baltimore County</fullName>
                </value>
                <value>
                    <fullName>BC-Baltimore City</fullName>
                </value>
                <value>
                    <fullName>CA-Carroll</fullName>
                </value>
                <value>
                    <fullName>CE-Cecil</fullName>
                </value>
                <value>
                    <fullName>CO-Caroline</fullName>
                </value>
                <value>
                    <fullName>CR-Charles</fullName>
                </value>
                <value>
                    <fullName>CV-Calvert</fullName>
                </value>
                <value>
                    <fullName>DO-Dorchester</fullName>
                </value>
                <value>
                    <fullName>FR-Frederick</fullName>
                </value>
                <value>
                    <fullName>GA-Garrett</fullName>
                </value>
                <value>
                    <fullName>HA-Harford</fullName>
                </value>
                <value>
                    <fullName>HO-Howard</fullName>
                </value>
                <value>
                    <fullName>KE-Kent</fullName>
                </value>
                <value>
                    <fullName>MO-Montgomery</fullName>
                </value>
                <value>
                    <fullName>PG-Prince George's</fullName>
                </value>
                <value>
                    <fullName>QA-Queen Anne's</fullName>
                </value>
                <value>
                    <fullName>SM-Saint Mary's</fullName>
                </value>
                <value>
                    <fullName>SO-Somerset</fullName>
                </value>
                <value>
                    <fullName>TA-Talbot</fullName>
                </value>
                <value>
                    <fullName>WA-Washington</fullName>
                </value>
                <value>
                    <fullName>WI-Wicomico</fullName>
                </value>
                <value>
                    <fullName>WO-Worcester</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EIN__c</fullName>
        <description>This is a replacement for SAN.  It is unique to each company.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>EIN #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Anniversary_Month__c</fullName>
        <description>The month that the current carrier's product comes up for potential renewal.  This is a good time to get back with the Account.</description>
        <label>Renewal Anniversary Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Jan</fullName>
                </value>
                <value>
                    <fullName>Feb</fullName>
                </value>
                <value>
                    <fullName>Mar</fullName>
                </value>
                <value>
                    <fullName>Apr</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>Jun</fullName>
                </value>
                <value>
                    <fullName>Jul</fullName>
                </value>
                <value>
                    <fullName>Aug</fullName>
                </value>
                <value>
                    <fullName>Sep</fullName>
                </value>
                <value>
                    <fullName>Oct</fullName>
                </value>
                <value>
                    <fullName>Nov</fullName>
                </value>
                <value>
                    <fullName>Dec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Workplan_Type__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Used_For__c</fullName>
        <label>Used For</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Sales</fullName>
                </value>
                <value>
                    <fullName>Implementation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Workplan_Type__c</fullName>
        <label>Workplan Condition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Workplan Type</label>
    <nameField>
        <displayFormat>WPT-{000000}</displayFormat>
        <label>Workplan Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Segment_New__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>51-199 New Business</fullName>
                </value>
                <value>
                    <fullName>51-199 Renewals</fullName>
                </value>
                <value>
                    <fullName>CFA</fullName>
                </value>
                <value>
                    <fullName>Commercial Business</fullName>
                </value>
                <value>
                    <fullName>FEHBP Account Management</fullName>
                </value>
                <value>
                    <fullName>Labor Affairs</fullName>
                </value>
                <value>
                    <fullName>NCAS</fullName>
                </value>
                <value>
                    <fullName>State &amp; Municipalities</fullName>
                </value>
                <value>
                    <fullName>Healthcare/Education/Par</fullName>
                </value>
                <value>
                    <fullName>Strategic Accounts 1000+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EIN__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>EIN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FullServiceProducer__c</fullName>
        <inlineHelpText>FSP is an agency that bills prem. &amp; remits pd prem. to CF on behalf of grps or members. FSP serves as the prim. contact for compensation &amp; communication on behalf of multi contracted brokers/agencies. FSP is pd fees for services &amp; commissions for brokers</inlineHelpText>
        <label>FullServiceProducer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Benefit Design Group, LLC</fullName>
                </value>
                <value>
                    <fullName>BenefitMall</fullName>
                </value>
                <value>
                    <fullName>Crawford Advisors, LLC</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Group Benefit Services</fullName>
                </value>
                <value>
                    <fullName>Hamilton Insurance Agency</fullName>
                </value>
                <value>
                    <fullName>Kelly &amp; Associates Insurance Group</fullName>
                </value>
                <value>
                    <fullName>NCAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Account_Name_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Legal Account Name Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_Segment_New__c</fullName>
        <description>This field is replacing the old Market_Segment__c field.  The old field label was changed to Market Segment History</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SBU__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>2-50</fullName>
                </value>
                <value>
                    <fullName>51-199</fullName>
                </value>
                <value>
                    <fullName>200-999</fullName>
                </value>
                <value>
                    <fullName>1000+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Underwriting_Entity__c</fullName>
        <description>Where Underwriting is performed.  Usually the location of the company headquarters.</description>
        <label>Underwriting Entity</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>CFA</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>NCAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Workplan_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workplan Type</label>
        <referenceTo>AIA_Workplan_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SLDSTaskLookupController_Test.cls
@isTest
 Public class SLDSTaskLookupController_Test  {
 
 
  public static user createTestRecords(){
    
    User u = new User(
     ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
     LastName = 'last',
     Email = 'Test@Care.com',
     Username = 'Test@Care.com' + System.currentTimeMillis(),
     CompanyName = 'TEST',
     Title = 'title',
     Alias = 'alias',
     TimeZoneSidKey = 'America/Los_Angeles',
     EmailEncodingKey = 'UTF-8',
     LanguageLocaleKey = 'en_US',
     LocaleSidKey = 'en_US'
    );
  
    insert u;
     return u;
 
  }

private static testMethod void generateUniqueComponentIdTest() {

   User u = new User();
   u= SLDSTaskLookupController_Test.createTestRecords();
   
   system.runAs(u){  
      
       
       SLDSTaskLookupController c=new SLDSTaskLookupController();
       c.Label = 'opportunity';
       c.objectName = 'Opportunity';         
       System.assertEquals('opportunity', c.uniqueComponentId);
       
    }
  
  }
    
    


private static testmethod void searchTest(){

   User u = new User();
   u= SLDSDynamicLookupControllerTest.createTestRecords();
   
   system.runAs(u){ 

        //Removing per Us210
        /*AIA_Workplan_Type__c wpt = new AIA_Workplan_Type__c();
        wpt.Used_For__c ='Pre-Sales';
        wpt.Workplan_Type__c = 'Renewal';
        wpt.Active__c=true;
        insert wpt;*/
            
        Account acct = new Account(); 
        acct.Name = 'Test10';
        acct.NumberOfEmployees = 45; // Num employees should always be <= 50
        acct.Sic = '0111';
        acct.EIN__c = '123456789'; // Has field validation, cannot be longer than 9 chars
        acct.BillingStreet = '1660 International Drive St. #518 Ste.500e ' +
        '1660 International Drive St. #518 Ste.500e' +
        '1660 International Drive St. #518 Ste.500e';
        acct.BillingCity = 'McLean123456789012345678902345678901';
        acct.BillingState = 'VA';
        acct.BillingPostalCode = '22102-4501'; // Has a validation rule in place 
        //acct.Billing_County_Code__c = 'MD';
        acct.Renewal_Anniversary_Month__c = 'Nov';
        acct.Account_Legal_Name__c= 'test Account';
        insert acct;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test opp';
        opp.FullServiceProducer__c = 'BenefitMall'; // Validation rule where I cannot leave this blank
        opp.StageName = 'Proposal';
        opp.CloseDate = Date.today() + 7;
        opp.AccountId = Acct.Id;
        opp.Market_Segment_New__c = '51-199';
        opp.Business_type__c = 'Renewal';
        opp.Division__c = '51-199 New Business';
        opp.Legal_Account_Name_Verified__c =true;
        opp.Underwriting_Entity__c = 'NCAS';
        opp.Effective_Date__c =  Date.newInstance(2014,10,1);  // validation rule requires effective date be 1st of month
        opp.CloseDate = opp.Effective_Date__c.addDays(-11);  // validation rule requires effective date be after close date i.e. effective > closedate
        opp.Contract_End_Date__c = opp.Effective_Date__c.addMonths(1);  // VR requires contract_end_date > effective_date and contract_end_date be last day of a month
        opp.Contract_End_Date__c = opp.Contract_End_Date__c.addDays(-1);
        //opp.Workplan_Type__c = wpt.id;
        insert opp;
                  
        
        
        //List<SLDSTaskLookupController.Wrapper> lst2 = SLDSTaskLookupController.search('opportunity', 'Account.name','Name2','url->www.google.com','Test');
   
List<SLDSTaskLookupController.Wrapper> lst3 = SLDSTaskLookupController.search('opportunity', 'Account.name','Name','url->www.google.com','Test');
List<SLDSTaskLookupController.Wrapper> lst4 = SLDSTaskLookupController.search('opportunity', 'Account.name','Name','field->Name','Test');
     
        }
    

 
 
     
    }

 
 }