objects/Account.object
<CustomObject>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <label>Jurisdiction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>VA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>CEDE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Workplan_Type__c.object
<CustomObject>
    <label>Workplan Type</label>
    <nameField>
        <displayFormat>WPT-{000000}</displayFormat>
        <label>Workplan Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rpt_Dt__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Rpt Dt</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <description>This object holds the actual enrollment data which is associated to the opportunity</description>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Enrollments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <description>Report Date, format is YYYYMM.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Report Date, format is YYYYMM.</inlineHelpText>
        <label>Date</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <label>Jurisdiction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>VA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Summary</label>
    <nameField>
        <displayFormat>SE-{00000}</displayFormat>
        <label>Enrollment Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Segment_New__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>51-199 New Business</fullName>
                </value>
                <value>
                    <fullName>51-199 Renewals</fullName>
                </value>
                <value>
                    <fullName>CFA</fullName>
                </value>
                <value>
                    <fullName>Commercial Business</fullName>
                </value>
                <value>
                    <fullName>FEHBP Account Management</fullName>
                </value>
                <value>
                    <fullName>Labor Affairs</fullName>
                </value>
                <value>
                    <fullName>NCAS</fullName>
                </value>
                <value>
                    <fullName>State &amp; Municipalities</fullName>
                </value>
                <value>
                    <fullName>Healthcare/Education/Par</fullName>
                </value>
                <value>
                    <fullName>Strategic Accounts 1000+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enrollment__c</fullName>
        <label>Enrollment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AON Exchange</fullName>
                </value>
                <value>
                    <fullName>CareFirst Connect</fullName>
                </value>
                <value>
                    <fullName>CF Private Exchange</fullName>
                </value>
                <value>
                    <fullName>DBE/Admin</fullName>
                </value>
                <value>
                    <fullName>Direct Auto</fullName>
                </value>
                <value>
                    <fullName>Direct Plus/CF Hub</fullName>
                </value>
                <value>
                    <fullName>Other/CF Hub</fullName>
                </value>
                <value>
                    <fullName>Paper</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FullServiceProducer__c</fullName>
        <inlineHelpText>FSP is an agency that bills prem. &amp; remits pd prem. to CF on behalf of grps or members. FSP serves as the prim. contact for compensation &amp; communication on behalf of multi contracted brokers/agencies. FSP is pd fees for services &amp; commissions for brokers</inlineHelpText>
        <label>FullServiceProducer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Benefit Design Group, LLC</fullName>
                </value>
                <value>
                    <fullName>BenefitMall</fullName>
                </value>
                <value>
                    <fullName>Crawford Advisors, LLC</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Group Benefit Services</fullName>
                </value>
                <value>
                    <fullName>Hamilton Insurance Agency</fullName>
                </value>
                <value>
                    <fullName>Kelly &amp; Associates Insurance Group</fullName>
                </value>
                <value>
                    <fullName>NCAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Account_Name_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Legal Account Name Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_Segment_New__c</fullName>
        <description>This field is replacing the old Market_Segment__c field.  The old field label was changed to Market Segment History</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SBU__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>2-50</fullName>
                </value>
                <value>
                    <fullName>51-199</fullName>
                </value>
                <value>
                    <fullName>200-999</fullName>
                </value>
                <value>
                    <fullName>1000+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Off_Cycle_Term_Date__c</fullName>
        <description>This field is used to only when the opportunity termed prior to the effective date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Off Cycle Term Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Underwriting_Entity__c</fullName>
        <description>Where Underwriting is performed.  Usually the location of the company headquarters.</description>
        <label>Underwriting Entity</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>CFA</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>NCAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Summary_Enrollment_Jurisdiction__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Summary Enrollment Jurisdiction</label>
</CustomObject>

classes/enrollmentFilters2_199_Test.cls
/*****************************************************************************************************

*=========================================================================================
* 								Update History
* Date         Developer       Tag          Description
*==================================================================================

*03/15/2019    Rajesh      T01       Commented out lines that are not reffered
*==================================================================================

*******************************************************************************************************/
@isTest 
public class enrollmentFilters2_199_Test {
     public static Enrollment_Summary__c Test1() {
         PageReference pageRef = Page.EnrollmentsSummarized2_199;
         Test.setCurrentPageReference(pageRef);
         TestUtil.Create_Enrollment_Import();
          Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
                     User u = new User(Alias = 'standt', Email='spmss.process@carefirst.com.xxx', 
                     EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                     LocaleSidKey='en_US', ProfileId = p.Id, 
                     TimeZoneSidKey='America/Los_Angeles', UserName='spmss.process@carefirst.com.xxx');
            //Test.StartTest(); 
            System.runAs(u) {
         TestUtil.Create_Enrolment_Import_2_50_Data();
         Summary_Enrollment_Jurisdiction__c cc=new Summary_Enrollment_Jurisdiction__c();
         cc.name='VA';
         insert cc;
         }
         Map<String, Schema.SObjectType> sObjectMap = Schema.getGlobalDescribe() ;
         Schema.SObjectType s = sObjectMap.get('Enrollment_Summary__c') ; 
         Schema.DescribeSObjectResult resSchema = s.getDescribe() ;
         Map<String,Schema.RecordTypeInfo> recordTypeInfo = resSchema.getRecordTypeInfosByName();
         /** T01 Since ES2 and sums are not referred any where commenting out referreded lines.
         List<Enrollment_Summary__c> sums = new List<Enrollment_Summary__c>();
         **/
         Enrollment_Summary__c ES1 = new Enrollment_Summary__c(
               Date__c = '201401',
               RecordTypeId = recordTypeInfo.get('2-50').getRecordTypeId(),
               Jurisdiction__c = 'VA');
               insert ES1;
         /** T01 Since ES2 and sums are not referred any where commenting out referreded lines.
         sums.add(ES1);
               
         Enrollment_Summary__c ES2 = new Enrollment_Summary__c(
               Date__c = '201702',
               RecordTypeId = recordTypeInfo.get('51+').getRecordTypeId(),
               Jurisdiction__c = 'VA');
         
         sums.add(ES2);
         
         insert sums;
         system.debug('--sums----'+sums);
         Account TestAcc = AIA_Testutil.createAccount('Test Account'); **/
         //Removing per US210
         /*AIA_Workplan_Type__c WpType =AIA_Testutil.AIA_CreateWorkPlan();
         insert WpType;*/
        /** T01 Since opp is not referred any where commenting out these lines.
        Opportunity opp = new Opportunity();
        opp.Name = 'Test opp';
        opp.FullServiceProducer__c = 'BenefitMall'; // Validation rule where I cannot leave this blank
        opp.StageName = 'RFP';
        opp.CloseDate = Date.today() + 7;
        opp.AccountId = TestAcc.id;
        opp.Market_Segment_New__c = '51-199';
        // opp.Business_type__c = 'Off-Cycle';
        opp.Division__c = '51-199 New Business';
        opp.Legal_Account_Name_Verified__c =true;
        opp.Underwriting_Entity__c = 'NCAS';
        Date tday = system.today();
        opp.Effective_Date__c =Date.newInstance(tday.Year(),tday.month(),1);  //Date.newInstance(2014,10,1);  // validation rule requires effective date be 1st of month
        opp.CloseDate = opp.Effective_Date__c.addDays(-11);  // validation rule requires effective date be after close date i.e. effective > closedate
        opp.Contract_End_Date__c = opp.Effective_Date__c.addMonths(1);  // VR requires contract_end_date > effective_date and contract_end_date be last day of a month
        opp.Contract_End_Date__c = opp.Contract_End_Date__c.addDays(-1);            
        opp.Off_Cycle_Term_Date__c = opp.Effective_Date__c.addDays(-1);     
        Id opptwohundredplusId = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('200+').RecordTypeId;
        opp.RecordTypeId = opptwohundredplusId;            
            
        insert opp;**/
         /**T01 Since eobj and eobj2 are not referred any where commenting out these lines.
         enrollment__c  eobj = new enrollment__c();
         eobj.RecordTypeId = Schema.SObjectType.Enrollment__c.RecordTypeInfosByName.get('2-50').RecordTypeId;
         eobj.Opportunity__c = opp.id;
         eobj.Rpt_dt__c='201412';
         insert eobj;
         enrollment__c  eobj2 = new enrollment__c();
         eobj2.RecordTypeId = Schema.SObjectType.Enrollment__c.RecordTypeInfosByName.get('51+').RecordTypeId;
         eobj2.Opportunity__c = opp.id;
         eobj2.Rpt_dt__c='201412';
         insert eobj2;
         **/
         return ES1;
    }
    
    static testMethod void Test2() {
        
        Enrollment_Summary__c ES1 = enrollmentFilters2_199_Test.Test1();
        Test.startTest();            
        ApexPages.StandardController sc = new ApexPages.standardController(ES1);
        enrollmentFilters2_199 con = new enrollmentFilters2_199(sc);  
        con.recType = '2-50';   
        con.month = '12';
        con.year = '2014';
        con.go();
        List<enrollmentFilters2_199.ResultsWrapper> wlist = new List<enrollmentFilters2_199.ResultsWrapper>();
        enrollmentFilters2_199.ResultsWrapper wobj = new enrollmentFilters2_199.ResultsWrapper();
        wobj.startingBalance =10;
        wobj.newCount=10;
        wobj.termed=10;
        wobj.monthEndBalance =10;
        wlist.add(wobj);
        con.calcTotals(wlist,'startingBalance');
        con.calcTotals(wlist,'newCount');
        con.calcTotals(wlist,'termed');
        con.calcTotals(wlist,'monthEndBalance');
        Test.stopTest(); 
    }
    static testMethod void Test3() {
        Enrollment_Summary__c ES1 = enrollmentFilters2_199_Test.Test1();
        Test.startTest();
        ApexPages.StandardController sc2 = new ApexPages.standardController(ES1);
        enrollmentFilters2_199 con2 = new enrollmentFilters2_199(sc2);  
        con2.recType = '51+';   
        con2.month = '12';
        con2.year = '2014';
        con2.go();
        Test.stopTest();
    }
}