objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status defines if the 2-50 customer account is active or termed based on the active file or the term file that it was updated from.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
                <value>
                    <fullName>Migrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Implementation__c.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect/New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>NCR</fullName>
                </value>
                <value>
                    <fullName>Off-cycle - Administrative change</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle - Benefit change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Implementation</label>
    <nameField>
        <displayFormat>IMP-{000000}</displayFormat>
        <label>Implementation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PRF__c.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <formula>TEXT( RFP_Name__r.Opportunity_Name__r.Business_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This object is used to store the Proposal Request Forms for the RFP process.</description>
    <label>Proposal Request Form</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PRF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposal Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Process__c.object
<CustomObject>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Process</relationshipLabel>
        <relationshipName>Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to identify the status of the record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Run time Object used for AIA workplan 
AIA - Custom object used to store the Stage, type &amp; status of Runtime Process. This object is a Parent object for Run time AIA Workplan. 
This is implemented for JUNE-2018 Release.</description>
    <label>Process</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Sub_Process__c.object
<CustomObject>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Sub Process</relationshipLabel>
        <relationshipName>Sub_Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Sub Process</relationshipLabel>
        <relationshipName>Sub_Processes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to identify the status of the record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Run time Object used for AIA workplan Stage
AIA - Custom object used to store the Stage, type &amp; status of Runtime Sub Process. This object is a child object for Run time Process object. 
This is implemented for JUNE-2018 Release.</description>
    <label>Sub Process</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Sub Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Workplan_Task__c.object
<CustomObject>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Workplan Tasks</relationshipLabel>
        <relationshipName>Workplan_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Workplan Tasks</relationshipLabel>
        <relationshipName>Workplan_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Process</label>
        <referenceTo>Sub_Process__c</referenceTo>
        <relationshipLabel>Workplan Tasks</relationshipLabel>
        <relationshipName>Workplan_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>AIA - Custom Object used to capture the runtime version of tasks which are created from Workplan Task Template. The status of these tasks can be updated by the users. This object is related to Opportunity and Implementation objects since Pre-Sales &amp; Post-Sales tasks are created in this object and assigned to the user.
This object will replace the old functionality. 
This is implemented for Nov-2017 Release.</description>
    <label>Workplan Task</label>
    <nameField>
        <displayFormat>Workplan Task - {0000}</displayFormat>
        <label>Workplan Task</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Tasks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AIA_Impl_TileBoard_ControllerTest.cls
/*******************************************************************************************************************************
*Date: 06/07/2018
*Developer: Raviteja
*Purpose: US-463 Test class is to validate AIA_Impl_TileBoard_Controller
*===============================================================================================================================
* Update History
* Date         Developer         Tag        Description
*===============================================================================================================================
*06/07/2018    Raviteja                     Initial Development
===============================================================================================================================

*******************************************************************************************************************************/
@isTest
public class AIA_Impl_TileBoard_ControllerTest {
    static Schema.DescribeSObjectResult objResult = Schema.SObjectType.Opportunity; 
    static Map<String,Schema.RecordTypeInfo> objRecordType = objResult.getRecordTypeInfosByName(); 
    static Id opp200RecTypId = objRecordType !=NULL && objRecordType.containsKey('200+') ? objRecordType.get('200+').getRecordTypeId() : NULL;  
    
    @testsetup static void CreateTestData(){
       
        User u = AIA_TestUtil.createTestUser();
        System.runAs(u) {  
            // Create Account
            AIA_Implementation__c Imp;
            Account a = AIA_TestUtil.CreateAccount('TestAccount');
            system.assertNotEquals(null,a.id);
            
            // Create Opportunity
            Opportunity o = AIA_TestUtil.AIA_createopportunity(a.Id);
            system.assertNotEquals(null,o.id);
            system.debug('Opp'+o);
            o.recordTypeId = opp200RecTypId;
            o.Business_Type__c = 'RFP';
            update o;
            
            // Create PRF
            PRF__c p = AIA_TestUtil.CreatePRF(o.Id);
            system.assertNotEquals(null,p.id);
             test.startTest();
            List<AIA_Implementation__c> aiaImpList = AIA_TestUtil.CreateImpList(o.id);
            system.assertNotEquals(0,aiaImpList.size());
            
            Imp = AIA_TestUtil.UpdateImp(o.id);             
            update Imp;
            Process__c p1=new Process__c();
            p1.Implementation__c=Imp.id;
            
            insert p1;
            Sub_Process__c s1=new Sub_Process__c();
            s1.Implementation__c=Imp.id;
            s1.Process__c=p1.id;      
            insert s1;
            Workplan_Task__c wp1=new Workplan_Task__c();
            wp1.Sub_Process__c=s1.id;
            wp1.Status__c='Completed';
            insert wp1;
            
            test.stopTest();
        }
       
    }
    static testmethod void testImplTileBoard(){
       
        AIA_Implementation__c testImpl = [Select Id,Business_Type__c From AIA_Implementation__c limit 1];
        Process__c process=[Select Id from Process__c limit 1];
        PageReference pref = Page.AIA_Implementation_Dashboard;
        Test.setCurrentPage(pref);
         test.startTest();
        ApexPages.StandardController con = new ApexPages.StandardController(testImpl);
        ApexPages.currentPage().getParameters().put('Id',testImpl.id);
        AIA_Implementation_Dashboard_Extn impt=new AIA_Implementation_Dashboard_Extn(con);
        AIA_Impl_TileBoard_Controller impt1=new AIA_Impl_TileBoard_Controller();
        impt1.setprocessID(process.Id); 
        impt1.getprocessID();
        impt1.getFullListOfTiles();
        impt1.displayTaskListModalSetter();
        impt1.closeTaskListModal();
        system.assertEquals(1,impt1.lstName.size());    
        test.stopTest();        
    }
}