objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>X51</fullName>
        <active>true</active>
        <label>51+</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>Read</sharingModel>
    <recordTypes>
        <fullName>X51</fullName>
        <active>true</active>
        <label>51+</label>
    </recordTypes>
</CustomObject>

objects/Protemoi__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Protemoi</relationshipLabel>
        <relationshipName>Protemoi</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Protemoi</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Protemoi ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Protemoi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProtemoiAccountUpdate_Test.cls
/*=========================================================================================
 * Date         : 10/19/2016
 * Developer    : Rajesh Pennam
 * Purpose      : This class is used to test the functionlaity of the ProtemoiAccountUpdate
 *=========================================================================================
 *                                 Update History
 *                                 ---------------
 * Date       Developer         Description
 *===========+============+================================================================
 * 07/14/16  |  Rajesh Pennam   | Initial Version                                         
 *           |        | 
 *=========================================================================================
 */
@isTest
public class ProtemoiAccountUpdate_Test{
    public static testmethod void test() {

        Test.startTest();
        //create Accounts
        Id rt_acc_51 = QueryBase.getRecordtypeId('Account', 'X51');
        Account a = new Account();
        a.Name = 'SomeTest' + Date.Today();
        a.Type = 'Customer';
        a.RecordTypeId = rt_acc_51;
        insert a;
        
        //create Contact
        Contact con = new Contact();
        con.LastName = 'Test';
        con.Phone = '1234567891';
        con.Email = 'test@gmail.com';
        con.AccountId       = a.id;
        insert con;  
        
        
        //create Protemoi
        Protemoi__c p = new Protemoi__c();
        p.Contact_Name__c = con.Id;
        insert p;
        update p;
 
        //system.assertequals(2,lst.size());
        Test.stopTest();
    }
}