objects/Account.object
<CustomObject>
    <fields>
        <fullName>NASCO_Account_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>NASCO Account Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Team__c.object
<CustomObject>
    <label>Account Team</label>
    <nameField>
        <displayFormat>ATM-{000000}</displayFormat>
        <label>AccountTeamMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Group_Structure_Request_Form__c.object
<CustomObject>
    <fields>
        <fullName>Alpha_Prefix_is_missing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>US 63 - shows if the Alpha Prefix is missing in relaed Groups</description>
        <label>Alpha Prefixes Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <formula>Implementation__r.Benefit_Request_Form__r.Benefit_Effective_Date__c</formula>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Group Structure Request Forms</relationshipLabel>
        <relationshipName>Group_Structure_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NASCO_Account_Number__c</fullName>
        <formula>Implementation__r.Account__r.NASCO_Account_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NASCO Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Par_Plan__c</fullName>
        <inlineHelpText>Plan Code 690 to be used for Alt Net and or FlexLink
Plan Code 580 to be used for Alt Net</inlineHelpText>
        <label>Par Plan</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>580-DC zipcode range&amp;690 for all others</fullName>
                </value>
                <value>
                    <fullName>690-MD zipcode range&amp;580 for all others</fullName>
                </value>
                <value>
                    <fullName>Plan code 580 for DC</fullName>
                </value>
                <value>
                    <fullName>Plan code 690 for MD</fullName>
                </value>
                <value>
                    <fullName>Plan code 700 for MA</fullName>
                </value>
                <value>
                    <fullName>Plan code 710 for MI</fullName>
                </value>
                <value>
                    <fullName>Plan code 780 for NJ</fullName>
                </value>
                <value>
                    <fullName>Plan code 580</fullName>
                </value>
                <value>
                    <fullName>Plan code 690</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Processing_Type__c</fullName>
        <label>Processing Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Complex</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Group Structure Request Form</label>
    <nameField>
        <displayFormat>GSRF-{000000}</displayFormat>
        <label>Group Structure Request Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Structure Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Implementation__c.object
<CustomObject>
    <fields>
        <fullName>AIA_Group_Structure_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To populate the group structure request form under implementation</description>
        <label>Group Structure Request Form</label>
        <referenceTo>AIA_Group_Structure_Request_Form__c</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Benefit_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Request Form</label>
        <referenceTo>Benfit_Request_Form__c</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Generate_Workplan_Stages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate Workplan Stages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Implementation_Plan_Timeline_Days__c</fullName>
        <label>Implementation Plan Timeline (Days)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>AIA_Post_Sales_Implementation</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Risk_Type__c</fullName>
        <label>Risk Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Implementation</label>
    <nameField>
        <displayFormat>IMP-{000000}</displayFormat>
        <label>Implementation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Workplan_Type__c.object
<CustomObject>
    <label>Workplan Type</label>
    <nameField>
        <displayFormat>WPT-{000000}</displayFormat>
        <label>Workplan Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AIA_GSM_CustomNewlistbuttonConTest.cls
@isTest
public class AIA_GSM_CustomNewlistbuttonConTest {
     @testSetup static void testdata() {
        //Creating Account Test Data 
        Account accnt = AIA_TestUtil.acc();
        accnt.NASCO_Account_Number__c='1234';   
        update accnt;
           
        //Creating WorkPlan Type Test Data 
        AIA_Workplan_Type__c wpt =AIA_TestUtil.wrkPln('Pre-Sales'); 
        
        //Creating User Test Data 
        List<user> userList = new list<user>();
        user u1 = AIA_TestUtil.AIA_createUser('alias1');
        /**/  userList.add(u1); 
        user u2 = AIA_TestUtil.AIA_createUser('alias2');
        /**/  userList.add(u2);
        user u7 =AIA_TestUtil.AIA_createUser('alias7');
        userList.add(u7);
        user u8 =AIA_TestUtil.AIA_createUser('alias8');
        userList.add(u8);        
        user u3 = AIA_TestUtil.AIA_createUser('alias3');
        userList.add(u3);        
        user u4 = AIA_TestUtil.AIA_createUser('alias4');
        userList.add(u4);        
        user u5 = AIA_TestUtil.AIA_createUser('alias5');
        userList.add(u5); 
        user u6 = AIA_TestUtil.AIA_createUser('alias6');
        userList.add(u6);
        user u9 = AIA_TestUtil.AIA_createUser('alias9');
        userList.add(u9);
        user u10 = AIA_TestUtil.AIA_createUser('alias10');
        userList.add(u10);
        user u11 = AIA_TestUtil.AIA_createUser('alias11');
        userList.add(u11); 
        user u12 = AIA_TestUtil.AIA_createUser('alias11');
        userList.add(u12);
     user u13 = AIA_TestUtil.AIA_createUser('alias11');
        userList.add(u13); 
        user u14 = AIA_TestUtil.AIA_createUser('alias11');
        userList.add(u14);
     
        user u15 = AIA_TestUtil.AIA_createUser('alias6');
        userList.add(u15);
        insert userList;
        
        //Creating AccountMember Test Data 
        //List<AccountTeamMember> acctMbrList = new List<AccountTeamMember>();
        List<Account_Team__c> acctMbrList = new List<Account_Team__c>();//T02 replaced standard AccountTeamMember with custom
        //acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(accnt.Id,u7.id,'NASCO Benefit Coder')); 
        acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(accnt.Id,u8.id,'BeneFact Coder')); 
        //acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(accnt.Id,u3.id,'Ancillary Analyst')); 
        acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(accnt.Id,u5.id,'MAST Tech'));   
        acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(accnt.Id,u1.id,'Underwriter')); 
        acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(accnt.Id,u2.id,'QA Auditor'));
        acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(accnt.Id,u9.id,'Account Manager'));
        acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(accnt.Id,u10.id,'Billing Tech'));
        //acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(accnt.Id,u11.id,'Settlements'));
        //acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(accnt.Id,u12.id,'AE BA'));
        acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(accnt.Id,u4.id,'Contract Tech'));
        acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(accnt.Id,u13.id,'Account Executive'));
        acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(accnt.Id,u14.id,'Proposal Specialist'));
        acctMbrList.add(AIA_TestUtil.SD_CreateAccountTeamMember(accnt.Id,u15.id,'Implementation Manager'));
        insert acctMbrList;
        
        //Creating Opportunity Test Data   
        Opportunity o = AIA_TestUtil.opp(accnt.Id,wpt.id);
        
        AIA_Implementation__c Imp = new AIA_Implementation__c();
        Imp.Name__c = 'testprf';
        Imp.Opportunity__c = o.id;
        Imp.Account__c = accnt.id;
        Imp.Generate_Workplan_Stages__c = true;
        Imp.Effective_Date__c = system.today();
        Imp.Implementation_Plan_Timeline_Days__c = '60';
        //Imp.Benefit_Request_Form__c=brf.id;
        Imp.Risk_Type__c='ASO';
        insert Imp;
    }
   
 public static testMethod void testGSRFRejectedAccValid()
    {
        
        Test.startTest();
        
        //Querying data for test
         //Querying data for test
        List<AIA_Implementation__c> imp=[select id from AIA_Implementation__c limit 1];
        AIA_Group_Structure_Request_Form__c gsrf=new AIA_Group_Structure_Request_Form__c();
        gsrf.Implementation__c=imp[0].Id;
         gsrf.Alpha_Prefix_is_missing__c=true;
        gsrf.Par_Plan__c='580-DC zipcode range&690 for all others';
        gsrf.Processing_Type__c='Standard';
        insert gsrf;

        PageReference pref = Page.AIA_GSM_CustomNewlistbutton;
        Test.setCurrentPage(pref);
        ApexPages.currentPage().getParameters().put('gsrfid',gsrf.id);
        ApexPages.currentPage().getParameters().put('type','Group');
        ApexPages.StandardController con = new ApexPages.StandardController(gsrf);
        AIA_GSM_CustomNewlistbuttonController gsrfa=new AIA_GSM_CustomNewlistbuttonController(con);
        gsrfa.parentislocked();
        gsrfa.backtogsrf();
        ApexPages.currentPage().getParameters().put('gsrfid',gsrf.id);
        ApexPages.currentPage().getParameters().put('type','Package');
        ApexPages.StandardController con5 = new ApexPages.StandardController(gsrf);
        AIA_GSM_CustomNewlistbuttonController gsrfa5=new AIA_GSM_CustomNewlistbuttonController(con5);
        gsrfa5.parentislocked();
        ApexPages.currentPage().getParameters().put('gsrfid',gsrf.id);
        ApexPages.currentPage().getParameters().put('type','Department');
        ApexPages.StandardController con1 = new ApexPages.StandardController(gsrf);
        AIA_GSM_CustomNewlistbuttonController gsrfa1=new AIA_GSM_CustomNewlistbuttonController(con1);
        gsrfa1.parentislocked();
        ApexPages.currentPage().getParameters().put('gsrfid',gsrf.id);
        ApexPages.currentPage().getParameters().put('type','Facet');
        ApexPages.StandardController con2 = new ApexPages.StandardController(gsrf);
        AIA_GSM_CustomNewlistbuttonController gsrfa2=new AIA_GSM_CustomNewlistbuttonController(con2);
        gsrfa2.parentislocked();
        ApexPages.currentPage().getParameters().put('gsrfid',gsrf.id);
        ApexPages.currentPage().getParameters().put('type','FacetsubGroup');
        ApexPages.StandardController con3 = new ApexPages.StandardController(gsrf);
        AIA_GSM_CustomNewlistbuttonController gsrfa3=new AIA_GSM_CustomNewlistbuttonController(con3);
        gsrfa3.parentislocked();
        ApexPages.currentPage().getParameters().put('gsrfid',gsrf.id);
        ApexPages.currentPage().getParameters().put('type','Facetclass');
        ApexPages.StandardController con4 = new ApexPages.StandardController(gsrf);
        AIA_GSM_CustomNewlistbuttonController gsrfa4=new AIA_GSM_CustomNewlistbuttonController(con4);
        gsrfa4.parentislocked();
        Test.stopTest();
        
    }
}