objects/Adjustment__c.object
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>AN-{00000}</displayFormat>
        <label>Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Benefits__c.object
<CustomObject>
    <label>Benefit</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Benefit #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AIA_Grouper__c.object
<CustomObject>
    <label>Grouper</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Grouper Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grouper</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_PCS_Transaction_Table__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>AIA PCS Translation Table</label>
</CustomObject>

objects/AIA_Plan__c.object
<CustomObject>
    <fields>
        <fullName>BDF_Configuration_Last_Updated__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>BDF Configuration Last Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Configuration_Last_Updated__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>BRF Configuration Last Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Plan_Id__c</fullName>
        <description>Unique Key in PCS</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>PCS Plan Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Last_Updated_String_Format__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Last Updated String Format</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <description>AIA Object - Object used to store plans send from PCS</description>
    <label>Plan</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>SFDC Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Plan_Copay_Type__c.object
<CustomObject>
    <label>Plan Copay Type</label>
    <nameField>
        <displayFormat>PCT-{000000}</displayFormat>
        <label>Plan Copay Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Copay Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Plan_Limitation__c.object
<CustomObject>
    <label>Plan Limitation</label>
    <nameField>
        <displayFormat>PL-{00000}</displayFormat>
        <label>Plan Limitation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Limitation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Plan_Network__c.object
<CustomObject>
    <description>AIA Object - Networks associated with a plan</description>
    <label>Plan Network</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Plan Network Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Network</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AIA_Batch_SandboxDataDeletion.cls
/*=================================================================================================================
 * Date         : 02/15/2017
 * Developer    : Asif Kutagulla 
 * Purpose      : Batch class to be run only in sandbox environments. This job will purge data in related to Plan 
 *                Setup & Runtime objects and also Adjustment object. This is created for the purpose of keeping 
 *                the data within maximum storage limits.
 *=================================================================================================================
 *                                 Update History
 *                                 ---------------
 *   Date        Developer       Tag   Description
 *============+================+=====+=============================================================================
 * 02/15/2017 | Asif Kutagulla |     | Initial Version                                         
 *===========+=================+=====+=============================================================================
 */
global class AIA_Batch_SandboxDataDeletion implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
    global final String Query = 'SELECT id FROM AIA_PCS_Transaction_Table__c LIMIT 7';
    global Integer iterationCount = 1;
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(SchedulableContext sc) {
        AIA_Batch_SandboxDataDeletion DataDelJob = new AIA_Batch_SandboxDataDeletion();
        database.executebatch(DataDelJob,1);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        if(UserInfo.getUserName().containsIgnoreCase('spmss.process@carefirst.com'))
        {
            if(iterationCount == 1 || Test.isRunningTest()) {
                list<Adjustment__c> lstAdjustment = [SELECT Id 
                                                     FROM Adjustment__c 
                                                     WHERE createddate < LAST_N_DAYS:4 
                                                     LIMIT 10000];
                delete(lstAdjustment);            
            }
            if(iterationCount == 2 || Test.isRunningTest()) {
                list<AIA_Grouper__c> lstGrouper = [SELECT Id 
                                                   FROM AIA_Grouper__c 
                                                   WHERE createddate < LAST_N_DAYS:4
                                                   LIMIT 10000];
                delete lstGrouper;
            }
            if(iterationCount == 3 || Test.isRunningTest()) {
                list<AIA_Plan_Network__c> lstPlanNetwork = [SELECT Id 
                                                            FROM AIA_Plan_Network__c 
                                                            WHERE createddate < LAST_N_DAYS:4
                                                            LIMIT 10000];
                delete lstPlanNetwork;
            }
            if(iterationCount == 4 || Test.isRunningTest()) {
                AIA_Plan__c RefPlan = [SELECT Id 
                                       FROM AIA_Plan__c 
                                       WHERE Plan_Id__c = 'PLAN-1382'];
                delete RefPlan;
            }
            if(iterationCount == 5 || Test.isRunningTest()) {
                list<AIA_Plan_Copay_Type__c> lstPlanCopayType = [SELECT id 
                                                                 FROM AIA_Plan_Copay_Type__c 
                                                                 WHERE createddate < LAST_N_DAYS:4
                                                                 LIMIT 10000];
                delete lstPlanCopayType;
            }
            if(iterationCount == 6 || Test.isRunningTest()) {
                list<AIA_Plan_Limitation__c> lstPlanLimitation = [SELECT id 
                                                                  FROM AIA_Plan_Limitation__c 
                                                                  WHERE createddate < LAST_N_DAYS:4
                                                                  LIMIT 10000];
                delete lstPlanLimitation;
            }
            if(iterationCount == 7 || Test.isRunningTest()) {
                list<AIA_Benefits__c> lstBenefit = [SELECT id 
                                                    FROM AIA_Benefits__c 
                                                    WHERE createddate < LAST_N_DAYS:4
                                                    LIMIT 10000];
                delete lstBenefit;
            }

        }
        iterationCount++;
    }
    
    global void finish(Database.BatchableContext BC){
        StaticResource sr = [select id,body from StaticResource Where Name = 'BenefitSummaryJSONBRF'];
        String jsonStr=sr.body.toString();
        AIA_PCS_BenefitSummary apbroot=AIA_PCS_BenefitSummary.parse(jsonStr);
        AIA_PlanTemplateMapper mapper = new AIA_PlanTemplateMapper();
        mapper.saveToSetUp(apbroot,'BRF');
        
        StaticResource sr1 = [select id,body from StaticResource Where Name = 'BenefitSummaryJSONBDD'];
        String jsonStr1=sr1.body.toString();
        AIA_PCS_BenefitSummary apbroot1=AIA_PCS_BenefitSummary.parse(jsonStr1);
        AIA_PlanTemplateMapper mapper1 = new AIA_PlanTemplateMapper();
        mapper1.saveToSetUp(apbroot1,'BDD');        
                
        AIA_Plan__c RefPlan = [SELECT Id,Product_Last_Updated_String_Format__c,BDF_Configuration_Last_Updated__c,Configuration_Last_Updated__c 
                               FROM AIA_Plan__c 
                               WHERE Plan_Id__c = 'PLAN-1382'];
        RefPlan.Product_Last_Updated_String_Format__c = '2017-02-06  07:59:58 PM';
        RefPlan.Configuration_Last_Updated__c = DateTime.newInstance(2017, 1, 1);
        RefPlan.BDF_Configuration_Last_Updated__c = DateTime.newInstance(2017, 1, 1);
        update RefPlan;
    }

}