objects/AIA_Workplan_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Workplan Assignment</relationshipLabel>
        <relationshipName>Workplan_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>AIA_Workplan_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal Request Form</label>
        <referenceTo>PRF__c</referenceTo>
        <relationshipName>AIA_Workplan_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Workplan Assignment</label>
    <nameField>
        <displayFormat>WT-{000000}</displayFormat>
        <label>Workplan Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PRF__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposal Request Forms</relationshipLabel>
        <relationshipName>Proposal_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This object is used to store the Proposal Request Forms for the RFP process.</description>
    <label>Proposal Request Form</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PRF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposal Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AIA_WPAController.cls
//===================================================================================
//Date: 04/19/2016
//Developer: Sree Harsha Akkala
//Purpose: Saves the Workplan Assignment and links it with Proposal Request Form.
//=========================================================================================
// Update History
// Date         Developer               Description
//==================================================================================
//04/19/2016    Sree Harsha Akkala      Initial Development
//04/16/2018    Gayathri           T01  Commented the lines related to WP Assignment
//    								  	as part of US 209
//==================================================================================
public with sharing class AIA_WPAController {
    
    //public AIA_Workplan_Assignment__c wpa{get;set;}//T01
    /**
     * Sets the owner to current user.  
     * @Constructor AIA_WPAController    
    */
    /* T01 -- Start
    public AIA_WPAController(ApexPages.StandardController controller) {
        
        wpa = new AIA_Workplan_Assignment__c();
        wpa.ownerId=userinfo.getuserId();
		
    }
  T01 -- End*/
     /**
     * Saves the Workplan Assignment and links it with Proposal Request Form.   
     * @method save  
    */ 
     /*T01 - Start
    public pagereference save(){
       
        try{
            id prfId = apexpages.currentpage().getparameters().get('PRFid');
            wpa.Proposal_Request_Form__c= prfId;
            PRF__c prf=[select opportunity__c,Opportunity__r.AccountId from PRF__c where id =: prfId];
            wpa.Account__c = prf.Opportunity__r.AccountId;
            insert wpa;
        }
        catch(exception e){
            system.debug(e.getMessage());
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Error while creating the Workplan Assignment'));
        }        
        return new pagereference('/'+wpa.id); 
		
        return null;//Added as part of US209
    }    
    T01 -- End*/        
}