objects/AIA_Document__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Approvals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Benefit_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Request Form</label>
        <referenceTo>Benfit_Request_Form__c</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Acount Cancellation Termination and Transfer Request Form</fullName>
                    <label>Account Cancellation Termination and Transfer Request Form</label>
                </value>
                <value>
                    <fullName>Account Implementation Workplan (Internal)</fullName>
                </value>
                <value>
                    <fullName>Account Impmentation Milestone Workplan (External)</fullName>
                </value>
                <value>
                    <fullName>Account Kick-off</fullName>
                </value>
                <value>
                    <fullName>Account Review Committee</fullName>
                </value>
                <value>
                    <fullName>Additional Documentation</fullName>
                </value>
                <value>
                    <fullName>Administrative Service Agreement</fullName>
                </value>
                <value>
                    <fullName>Administrative Services Agreement (ASA)</fullName>
                </value>
                <value>
                    <fullName>AIA Account Issue Documentation</fullName>
                </value>
                <value>
                    <fullName>Benefit Design Document</fullName>
                </value>
                <value>
                    <fullName>Benefit EDC</fullName>
                </value>
                <value>
                    <fullName>Benefit Request Form</fullName>
                </value>
                <value>
                    <fullName>Benefits Contracts</fullName>
                </value>
                <value>
                    <fullName>Billing Information Form</fullName>
                </value>
                <value>
                    <fullName>BlueFund</fullName>
                </value>
                <value>
                    <fullName>BlueRewards Wellness</fullName>
                </value>
                <value>
                    <fullName>Business Associate Agreement (BAA)</fullName>
                </value>
                <value>
                    <fullName>Business Associate Confirmation (BAC)</fullName>
                </value>
                <value>
                    <fullName>CAG (Carrier Account Group)</fullName>
                </value>
                <value>
                    <fullName>Cede Document</fullName>
                </value>
                <value>
                    <fullName>Census Information</fullName>
                </value>
                <value>
                    <fullName>Client Letters</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Custom BAA</fullName>
                </value>
                <value>
                    <fullName>Custom Funding Letter</fullName>
                </value>
                <value>
                    <fullName>CVS Sales Support Request Form</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Department Notes</fullName>
                </value>
                <value>
                    <fullName>Department Number Notes</fullName>
                </value>
                <value>
                    <fullName>Enrollment Data Card (EDC)</fullName>
                </value>
                <value>
                    <fullName>Signed Quote</fullName>
                </value>
                <value>
                    <fullName>Unsigned Quote</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal Request Form</label>
        <referenceTo>PRF__c</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AIA Document</label>
    <nameField>
        <displayFormat>FD-{000000}</displayFormat>
        <label>AIA Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AIA Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Benfit_Request_Form__c.object
<CustomObject>
    <fields>
        <fullName>ARC_Approval_Required__c</fullName>
        <formula>IF(ISPICKVAL(Request_Type__c,"Renewal - Administrative Changes"),False,

(Count_of_Custom_Products__c &gt; 0 || text(EGWP_Picklist__c)= 'Yes' || text(FlexLink_Picklist__c) = 'Yes' || Rx_Integration_PP__c &gt; 0) 

&amp;&amp; 

(((zzzMHP_Required__c = "Yes" ) &amp;&amp; ( zzzMHP_Test_Result__c = "Pass")) 

|| 
( (zzzMHP_Required__c = 'Yes') &amp;&amp; (zzzMHP_Test_Result__c = 'Deferred') || NOT(zzzMHP_Required__c = 'Yes')))

)</formula>
        <label>ARC Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ARC_Approval_Status__c</fullName>
        <description>ARC Approval Status</description>
        <label>ARC Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved by Committee</fullName>
                </value>
                <value>
                    <fullName>Rejected by Committee</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>No Decision</fullName>
                </value>
                <value>
                    <fullName>Auto-Approved by System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BRF_Sold_Date_field__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>BRF Sold Date field</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Clone_count__c</fullName>
        <label>Clone count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deep_clone_check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deep clone check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Escalated_to_Senior_Management__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalated to Senior Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>File_Net_Doc_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>File Net Doc Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Benefit Request Forms</relationshipLabel>
        <relationshipName>Benfit_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PRF__c</fullName>
        <formula>Proposal_Request_Form__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PRF</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposal_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal Request Form</label>
        <referenceTo>PRF__c</referenceTo>
        <relationshipLabel>Benefit Request Forms</relationshipLabel>
        <relationshipName>Benefit_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect/New</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Renew As-is</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle - Administrative Change</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle - Benefit Change</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle - Administrative and Benefit Change</fullName>
                </value>
                <value>
                    <fullName>Renewal - Administrative Changes</fullName>
                </value>
                <value>
                    <fullName>Renewal - Benefit Changes</fullName>
                </value>
                <value>
                    <fullName>Renewal - Admin and Benefit Changes</fullName>
                </value>
                <value>
                    <fullName>Set-up Change - Administrative Changes</fullName>
                </value>
                <value>
                    <fullName>Set-up Change - Benefit Changes</fullName>
                </value>
                <value>
                    <fullName>Set-up Change - Admin and Benefit Changes</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Senior_Management_Approved_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Senior Management Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Benefit_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Benefit Request Form Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Revised Approved</fullName>
                </value>
                <value>
                    <fullName>Sold-Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Who_Marks_Sold__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who_Marks_Sold</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Benefit_Request_Forms1</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>New object for AIA - This object stores the information that is needed for a quote</description>
    <label>Benefit Request Form</label>
    <nameField>
        <displayFormat>BRF-{000000}</displayFormat>
        <label>Benefit Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Request Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PRF__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposal Request Forms</relationshipLabel>
        <relationshipName>Proposal_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This object is used to store the Proposal Request Forms for the RFP process.</description>
    <label>Proposal Request Form</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PRF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposal Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AIA_BRFTriggerHandler.cls
/****************************************************************************************************************************
 *  Class            : AIA_BRFTriggerHandler
 *  Author           : Rajesh Pennam
 *  Version History  : 1.0
 *  Creation         : 05/09/16
 *  Description      : This class will have the logic for trigger (BRF Trigger). If the BRF form is
 *                     created from Proposal Request form then the Opportunity of the PRF will be 
 *                     populated to the Opportunity of BRF  
 *
 *  Modification Log:
 * ---------------------------------------------------------------------------------------------------------------------------
 *  Author          Date-Modified      Tag      Description of Change
 * ---------------------------------------------------------------------------------------------------------------------------
 * Rajesh Pennam     05/09/2016                 Initial Creation
 * Asif Kutagulla    11/16/2016        T01      Add changes to exclude validation rule for users enabled with permission set 
 *                                              Skip BRF Validation Rules 
 * Sree Harsha       03/15/2017        T02      Added check in ValidateSoldBRF method to check if Request type is Off-Cycle - 
                                                Administrative Change then don't need signed or unsigned quote to mark BRF as sold.
 * Sree Harsha       03/17/2017        T03      Added code to call method updateStatus from class AIA_BRFTriggerHelper. 
 * Bill Dodson       03/03/2017        T04      Add call to AIA_AdjustmentSummaryUtils.populateAdjustmentSummary in after update.   
 *                                              Add flags so that adjustment records not created on recursion. 
 * Asif Kutagulla    04/22/2017        T05      Added recursion check for method calls in beforeupdate method  
 * Bill Dodson       04/25/2017        T06      Modify afterUpdate to send all BRF records to adjustment summary.
 * Sree Harsha       05/15/2017        T07      Change of error message
 * Bill Dodson       07/19/2017        T08      Generate Adjustment Summary records for Sold BRFs.
 * Bill Dodson       08/03/2017        T08      Disable Adjustment Summary record creation.
 * Raviteja          13/10/2017      | T10 |    Commented code as part of US 209
 * Goutham Rapolu    10/12/2017        T011     Added method to check if AccountTeamMember is available before inserting/Updating Benefit Request Form. US230
 * Goutham Rapolu    10/12/2017        T012     Updated beforeUpdateTeamMember method to AIA_Verify_AccountTeamMember.
 *                                              so commented beforeUpdateTeamMember method.
 * Goutham Rapolu    12/21/2017      | T13 |    US 510 Call ARC Approval once Salesmanagement is Approved for Off Cycle request Type.
  * satya             9/12/2017      |T14 |     Added methods for workplan tasks assignment
  * satya             6/11/2018      |T15 |     Commented the workplan task method since we no longer has Wplans for pre-sale
 *****************************************************************************************************************************/

public class AIA_BRFTriggerHandler  extends TriggerHandler {
public Static Boolean beforeUpdateRecursive=false;
 public static string Inserts = 'Insert';
    Public static string Updates = 'Update';
    public static string BrfRec = 'Benfit_Request_Form__c';
@TestVisible public Static Boolean AfterUpdateRecursive=false; // T04 added TestVisible.
public Static Boolean AfterinsertRecursive=false;
public Static Boolean hasSkipBRFVRs_CustPerm = CF_CustomPermissionsReader_Helper.Permissions.skipBRFVRs;//T01 
@TestVisible private static Boolean adjustmentPreviouslyCalled = false; // T04
private static Boolean otherTriggersRunning = false; // T04

   
     public AIA_BRFTriggerHandler() {}


  
        /* context override */
    protected override void beforeInsert() {
        otherTriggersRunning = true; // T04
        //if(checkRecursive.runOnce())//T05 begin
        //{
        updateSeniorManagement((list<Benfit_Request_Form__c>) trigger.new);
        AIA_BRFTriggerHelper.populateBrokerNamefromOpptyconRole((list<Benfit_Request_Form__c>) trigger.new,(Map<id,Benfit_Request_Form__c>) trigger.oldMap);
        AIA_BRFTriggerHelper.accountNameUpdate((list<Benfit_Request_Form__c>) trigger.new,(Map<id,Benfit_Request_Form__c>) trigger.oldMap);
       //T012 - START -
       // AIA_BRFTriggerHelper.beforeUpdateTeamMember((list<Benfit_Request_Form__c>) trigger.new);
       //T012 - END -
       //T011 - START -
        AIA_BRFTriggerHelper.AIA_Verify_AccountTeamMember((list<Benfit_Request_Form__c>) trigger.new);
       //T011 - END -  
        AIA_BRFTriggerHelper.updateStatus((list<Benfit_Request_Form__c>) trigger.new); //T03
        AIA_BRFTriggerHelper.soldStatusCheck((list<Benfit_Request_Form__c>) trigger.new); 
        AIA_BRFTriggerHelper.PopulateRxcarveout((list<Benfit_Request_Form__c>) trigger.new ,(Map<id,Benfit_Request_Form__c>) trigger.newMap);
        AIA_BRFTriggerHelper.updateJurisdiction((list<Benfit_Request_Form__c>) trigger.new);
       // }
        otherTriggersRunning = false; // T04
    }
    
    protected override void beforeUpdate() {  
        otherTriggersRunning = true; // T04  
        //if(checkRecursive.runOnce())//T05 begin
        //{
            system.debug('trigger.new=='+trigger.new);
            system.debug('AIA_ProposedProductsHandler.firstRun =='+AIA_ProposedProductsHandler.firstRun);
            
            for(Benfit_Request_Form__c brf :(list<Benfit_Request_Form__c>)trigger.new)
            {
                system.debug('brf=='+brf );
                if(brf.Deep_clone_check__c == true)
                {
                   
                   brf.Clone_count__c += 1;
                }
                
            }
            updateSeniorManagement((list<Benfit_Request_Form__c>) trigger.new);
            AIA_BRFTriggerHelper.populateBrokerNamefromOpptyconRole((list<Benfit_Request_Form__c>) trigger.new,(Map<id,Benfit_Request_Form__c>) trigger.oldMap);
            ValidateSoldBRF((list<Benfit_Request_Form__c>) trigger.new,(Map<id,Benfit_Request_Form__c>) trigger.newmap,(Map<id,Benfit_Request_Form__c>) trigger.oldmap);
            AIA_BRFTriggerHelper.accountNameUpdate((list<Benfit_Request_Form__c>) trigger.new,(Map<id,Benfit_Request_Form__c>) trigger.oldMap);
        
            //T012 - START -
            // AIA_BRFTriggerHelper.beforeUpdateTeamMember((list<Benfit_Request_Form__c>) trigger.new);
            //T012 - END -
            //T011 - START -
            AIA_BRFTriggerHelper.AIA_Verify_AccountTeamMember((list<Benfit_Request_Form__c>) trigger.new);
            //T011 - END -
            
            AIA_BRFTriggerHelper.updateStatus((list<Benfit_Request_Form__c>) trigger.new); //T03
            AIA_BRFTriggerHelper.soldStatusCheck((list<Benfit_Request_Form__c>) trigger.new); 
        //}//T05 end
        otherTriggersRunning = false; // T04
    }
        
    
    protected override void afterInsert() {
        otherTriggersRunning = true; // T04
        ValidateSoldBRF((list<Benfit_Request_Form__c>) trigger.new,(Map<id,Benfit_Request_Form__c>) trigger.newmap,(Map<id,Benfit_Request_Form__c>) trigger.oldmap);
        updateOpportunityOnBRF((list<Benfit_Request_Form__c>) trigger.new);
        //AIA_BRFTriggerHelper.accountNameUpdate((list<Benfit_Request_Form__c>) trigger.new,(Map<id,Benfit_Request_Form__c>) trigger.oldMap);
        if(AIA_BRFTriggerHelper.BRFListForEmail != null && AIA_BRFTriggerHelper.BRFListForEmail.size()>0 && AIA_BRFTriggerHelper.accIDs != null && AIA_BRFTriggerHelper.accIDs.size()>0)
        AIA_BRFTriggerHelper.processEmail(AIA_BRFTriggerHelper.BRFListForEmail,AIA_BRFTriggerHelper.accIDs);  
        //AIA_BRFTriggerHelper.populateAdjustmentSummaryInsert((list<Benfit_Request_Form__c>) trigger.new);//satya
      /* T15 Changes//T14 --Start---
        if(!test.isrunningtest()){ 
        AIA_Workplan_Task_Management wtm = new AIA_Workplan_Task_Management();
            
        wtm.createWorkplanTasksForSObject(Inserts, trigger.newMap, BrfRec);
                    
        }
        //t14--End T15 Changes  */
        otherTriggersRunning = false; // T04
    }
    
    protected override void afterUpdate() {
        system.debug('In after update brf trigger handler');
   // if(checkRecursive.runOnce())//T05 begin
   //{
      /* T15 Changes//T14--START--
       if(!test.isrunningtest()){            
        AIA_Workplan_Task_Management wtm = new AIA_Workplan_Task_Management();
           //T15
        wtm.createWorkplanTasksForSObject(Updates, trigger.newMap, BrfRec);
           //T15
        AIA_WorkPlanTasks_Completion WTC = new  AIA_WorkPlanTasks_Completion();
        WTC.completionWorkplanTasksForSObject(Updates, trigger.new, BrfRec);
        
       } 
       //T14--END--T15 Changes */ 
       
       //T13 START
        //method call to submit for next approval
        AIA_BRFTriggerHelper.Send_For_SalesMgmt_or_ARC_or_UW_Approval((list<Benfit_Request_Form__c>) trigger.new,(Map<id,Benfit_Request_Form__c>) trigger.oldmap);
       //T13 END
     
        if(!otherTriggersRunning && !adjustmentPreviouslyCalled) { // T04 begin
            // T06, removed code that filtered records prior to call.               
            AIA_AdjustmentSummaryUtils.populateAdjustmentSummary(trigger.new, trigger.oldMap);//Bill
            System.debug('In after update brf trigger handler, returned from populateAdjustmentSummary');
            adjustmentPreviouslyCalled = true;
            // T08 Commented Code Removed
            // If the status changes to Sold then generate Adjustment Summary records.
                       
        } 
        else {
            System.debug('In after update brf trigger handler, populateAdjustmentSummary NOT called' +
                         ', otherTriggersRunning: ' + otherTriggersRunning +
                         ', adjustmentPreviouslyCalled: ' + adjustmentPreviouslyCalled);
        } // T04 end 
    //}
   } 
    /**
    * @Author : Rajesh Pennam
    * @param  : This method is used to update the oppotunity of BRF from PRF
    * @param  : List<Benfit_Request_Form__c> brflst
    * @Output : This method inserts the opportunity on BRF from PRF
    * @return the list of lineitem sobjects 
    */  
    public static List<Benfit_Request_Form__c> UpdateBRFLst = new List<Benfit_Request_Form__c>();
    public static set<Id> PRFids = new set<Id>();
    public static List<PRF__c> PRFLst = new List<PRF__c>();
     
   public static void updateOpportunityOnBRF(List<Benfit_Request_Form__c> brflst){
        for(Benfit_Request_Form__c brf: brflst){
            PRFids.add(brf.Proposal_Request_Form__c);
        }
        
        //PRF List will have the id and the Opportunity of PRF
        PRFLst = [select id,Opportunity__c from PRF__c where id IN :PRFids];
        
        //This loop makes the Opportunity of PRF to Populate to Opportunity of BRF
        for(Benfit_Request_Form__c brf: brflst){
            for(PRF__c prf: PRFLst){
                system.debug('PRF opportunity is '+prf.Opportunity__c);
                if(prf.Opportunity__c != null && brf.Proposal_Request_Form__c != null && brf.Proposal_Request_Form__c == prf.id){
                    Benfit_Request_Form__c nbrf = new Benfit_Request_Form__c();
                    nbrf.id = brf.id;
                    nbrf.Proposal_Request_Form__c = prf.id;
                    nbrf.Opportunity__c = prf.Opportunity__c;
                    UpdateBRFLst.add(nbrf);
                }
            }
        }
        
        //Exception Handling
        
        try{
            if(UpdateBRFLst.size()>0 && UpdateBRFLst != null)
                update UpdateBRFLst;
        }catch(DMLException ex){
            system.debug(ex+'');
        }
    }
    
    /**
* @Author: Sree Harsha Akkala
* @This Method is called from BRFTrigger during insertion or updation of BRF
* @This method - The method tracks who has set the ARC approval status 
* @param -  list<Benfit_Request_Form__c> 
* @Output - Sets the Senior Management Approved by to the current user
*/    
public static void updateSeniorManagement(list<Benfit_Request_Form__c> brfList){
     for(Benfit_Request_Form__c brf:brfList){        
        if((brf.ARC_Approval_Status__c == AIA_Constants.APPROVED_BY_COMMITTEE || brf.ARC_Approval_Status__c==AIA_Constants.REJECTED_BY_COMMITTEE) &&(brf.Escalated_to_Senior_Management__c)){            
            brf.Senior_Management_Approved_By__c = userinfo.getuserId(); //Sets the seniormanagement approved by to current user
        }
        if(brf.status__c=='Sold'){
            brf.Who_Marks_Sold__c   = userinfo.getuserid(); //tracks who has set the brf to Sold(used in email alert of approval process) 
            brf.BRF_Sold_Date_field__c =   system.today();        
        }      
    }
}


/**
* @Author: Sree Harsha Akkala
* @This Method is called from BRFTrigger during insertion or updation of BRF
* @This method - The method validates when the BRF has to be set to sold
* @param -  list<Benfit_Request_Form__c> 
* @Output - Display an error message if set to sold without signed Quote or Approved Unsigned quote
*/
public static void ValidateSoldBRF(list<Benfit_Request_Form__c> newbrfList,Map<id,Benfit_Request_Form__c> newBRFMap,Map<id,Benfit_Request_Form__c> oldBRFMap){
    System.debug('Enter ValidateSoldBRF: '+'Hello');
    list<Benfit_Request_Form__c> brfList = new list<Benfit_Request_Form__c>();
    set<id> brfIdSet = new set<id>();
    for(Benfit_Request_Form__c brf:newbrfList){
        if(oldBRFMap!=null){
        if(oldBRFMap.get(brf.id).status__c=='Sold'){
                //T01 - Start - Added if check
                if(!hasSkipBRFVRs_CustPerm)
                {
                    brf.addError('The Benefit Request Form cannot be modified after it has been sold'); //T07
                }
                //T01 - End - Added if check
            }
        }
        if(brf.Status__c=='Sold'){          
        brfList.add(brf);
        brfIdSet.add(brf.id);
        }
    }
        
    list<Benfit_Request_Form__c> existingBRFList = [select id,name,ARC_Approval_Required__c, Request_Type__c,
                                                           ARC_Approval_Status__c,
                                                           (select id,name,Document_Type__c,Approval_Status__c 
                                                            from File_Net_Documents__r 
                                                            where Document_Type__c!=null) 
                                                    from Benfit_Request_Form__c 
                                                    where id in:BRFIdSet];
    system.debug('existingBRFList::'+existingBRFList);
    if(existingBRFList.size()>0){
     boolean setTOSoldForARC=false;         
        for(Benfit_Request_Form__c brf:existingBRFList){
        if(brf.ARC_Approval_Status__c =='Auto-Approved by System' || brf.ARC_Approval_Status__c =='Approved by Committee'){     
                setTOSoldForARC = true;     
            } 
            boolean setToSold=false;
            if(brf.File_Net_Documents__r.size()>0){        
                for(AIA_Document__c fd:brf.File_Net_Documents__r){
                    if((fd.Document_Type__c=='Signed Quote' ||  (fd.Document_Type__c=='Unsigned Quote' && fd.Approval_Status__c=='Approved')) ){
                        if((newBRFMap.get(brf.id).ARC_Approval_Required__c==true && (newBRFMap.get(brf.id).ARC_Approval_Status__c==AIA_Constants.APPROVED_BY_COMMITTEE || newBRFMap.get(brf.id).ARC_Approval_Status__c== 'Auto-Approved by System'))|| newBRFMap.get(brf.id).ARC_Approval_Required__c==false){
                            brf.File_Net_Doc_Id__c=fd.id;
                            newBRFMap.get(brf.id).File_Net_Doc_Id__c=fd.id;
                            setToSold=true;
                        }                       
                    }
                                       
                }
                if(!setToSold){
                    //T01 - Start - Added if check
                    if(!hasSkipBRFVRs_CustPerm)
                    {
                         If(brf.Request_Type__c!='Off-Cycle - Administrative Change' && brf.Request_Type__c!='Set-up Change - Administrative Changes'){ //T02
                        newBRFMap.get(brf.id).addError('The Benefit Request Form must have either a signed quote or an approved unsigned quote attached to it before it can be marked as Sold.');
                        }
                    }
                    //T01 - End - Added if check
                    
                }
                    
            }
            else{                
                //T01 - Start - Added if check
                if(!hasSkipBRFVRs_CustPerm)
                {    
                    If(brf.Request_Type__c!='Off-Cycle - Administrative Change' && brf.Request_Type__c!='Set-up Change - Administrative Changes'){    //T02
                    newBRFMap.get(brf.id).addError('The Benefit Request Form must have either a signed quote or an approved unsigned quote attached to it before it can be marked as Sold.');
                    }
                }
                //T01 - End - Added if check
            }  
                if(setTOSoldForARC == false){       
                 if(!hasSkipBRFVRs_CustPerm){       
                    newBRFMap.get(brf.id).addError('The Benefit Request Form must be either Auto-Approved or Approved by Committee before it can be marked as Sold.');      
                 }
               }              
            }          
        }
    }
}