objects/AIA_Benefit_Design__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Request Form</label>
        <referenceTo>Benfit_Request_Form__c</referenceTo>
        <relationshipLabel>Benefit Design</relationshipLabel>
        <relationshipName>Benefit_Design</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BlueFund_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BlueFund Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Both_Checker__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Both Checker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Compatible_Checker__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Compatible Checker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Benefit Design</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Benefit Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Design</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Benfit_Request_Form__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Benefit Request Form Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Revised Approved</fullName>
                </value>
                <value>
                    <fullName>Sold-Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>New object for AIA - This object stores the information that is needed for a quote</description>
    <label>Benefit Request Form</label>
    <nameField>
        <displayFormat>BRF-{000000}</displayFormat>
        <label>Benefit Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Request Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Both</fullName>
        <active>true</active>
        <description>Both Layout</description>
        <label>Both</label>
    </recordTypes>
</CustomObject>

objects/Proposed_Products__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Request_Form__c</fullName>
        <label>Benefit Request Form</label>
        <referenceTo>Benfit_Request_Form__c</referenceTo>
        <relationshipLabel>Proposed Products</relationshipLabel>
        <relationshipName>Proposed_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CDH_Fund_Type__c</fullName>
        <label>CDH Fund Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CDH__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BlueFund</fullName>
                </value>
                <value>
                    <fullName>Compatible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Medical_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Medical Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Proposed_Products__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Medical_Risk</value>
            </filterItems>
            <filterItems>
                <field>Proposed_Products__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Medical_ASO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Proposed_Products__c</referenceTo>
        <relationshipLabel>Related Ancillary Products</relationshipLabel>
        <relationshipName>Proposed_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Proposed Products</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Proposed Products Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposed Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Medical</fullName>
        <active>true</active>
        <description>Medical Layout</description>
        <label>Medical</label>
    </recordTypes>
</CustomObject>

classes/AIA_BD_CDHFundType_Checker.cls
/*************************************************************************************************************************************************
*  Class            : AIA_BD_CDHFundType_Checker
*  Author           : Rajesh Pennam
*  Version History  : 1.0
*  Creation         : 07/27/2017
*  Description      : This class is used to check the CDHFundType in associated Meical PP for BRF and update the checkbox in BD
*
*  Modification Log:
* ----------------------------------------------------------------------------------------------------------------------------------------------
*  Author          Date-Modified      Tag      Description of Change
* ----------------------------------------------------------------------------------------------------------------------------------------------
* Rajesh Pennam     07/27/2017               Initial Development

*************************************************************************************************************************************************/
Public class AIA_BD_CDHFundType_Checker{

    public static void updateBDCheck(list<AIA_Benefit_Design__c> lstabd){
    
        Id rt_PP_Medical= QueryBase.getRecordtypeId('Proposed_Products__c', 'Medical');
        //This map is used to store the BRF and BD, key = BRF and value = BD
        map<id,AIA_Benefit_Design__c> mapbrfbd=new map<id,AIA_Benefit_Design__c>();
        for(AIA_Benefit_Design__c bb: lstabd){
            mapbrfbd.put(bb.Benefit_Request_Form__c,bb);
             system.debug('-1--mapbrfbd-----'+mapbrfbd);
        }
        if(!mapbrfbd.isEmpty()){
         system.debug('-12--mapbrfbd-----'+mapbrfbd);
         //Below query to get the Medical PP for the the associated BRF
            for(Benfit_Request_Form__c brf :[select id,name,(select id,name,Benefit_Request_Form__c,CDH_Fund_Type__c from Proposed_Products__r where recordtypeid=:rt_PP_Medical) from Benfit_Request_Form__c where id IN:mapbrfbd.keyset() and Status__c='Sold']){
                system.debug('-13--mapbrfbd---size--'+brf.Proposed_Products__r.size());
                //if(brf.Proposed_Products__r.size()==1){
                 system.debug('-13--mapbrfbd-----'+mapbrfbd);
                 //If PP for the associated BRF has CDHType as 'BlueFund' then BlueFund Checkbox in BD will be marked
                    for(Proposed_Products__c pp:brf.Proposed_Products__r){
                        if(pp.CDH_Fund_Type__c=='BlueFund'){
                         system.debug('-14--mapbrfbd-----'+mapbrfbd);
                            mapbrfbd.get(pp.Benefit_Request_Form__c).BlueFund_Checkbox__c=true;  
                             system.debug('-15--mapbrfbd-----'+mapbrfbd);  
                        }
                        //If PP for the associated BRF has CDHType as 'Compatible' then Compatible Checkbox in BD will be marked
                         if(pp.CDH_Fund_Type__c=='Compatible'){
                         system.debug('-14--mapbrfbd-----'+mapbrfbd);
                            mapbrfbd.get(pp.Benefit_Request_Form__c).Compatible_Checker__c=true;  
                             system.debug('-15--mapbrfbd-----'+mapbrfbd);  
                        }
                    ////If PP for the associated BRF has CDHType as 'BlueFund' and 'Compatible' then Both Checkbox in BD will be marked
                    if(mapbrfbd.get(pp.Benefit_Request_Form__c).BlueFund_Checkbox__c==true && mapbrfbd.get(pp.Benefit_Request_Form__c).Compatible_Checker__c==true){
                        mapbrfbd.get(pp.Benefit_Request_Form__c).BlueFund_Checkbox__c=false;
                        mapbrfbd.get(pp.Benefit_Request_Form__c).Compatible_Checker__c=false;
                        mapbrfbd.get(pp.Benefit_Request_Form__c).Both_Checker__c=true;
                        system.debug('-15--mapbrfbd-----'+mapbrfbd);  
                    }
                }    
            }
            
            
            }
        }
        
        
        
        
    
}