objects/AIA_Benefit_Design__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Benefit Design</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Benefit Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Design</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Drawloop_Package_ID__c.object
<CustomObject>
    <fields>
        <fullName>DDP_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DDP ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>AIA Drawloop Package ID</label>
</CustomObject>

classes/AIA_ExportAdjustmentSummary.cls
public class AIA_ExportAdjustmentSummary {
    AIA_Benefit_Design__c rec=new AIA_Benefit_Design__c();
    public Boolean displaypopup{get;set;}
    public string msg {get;set;}
    public final AIA_Drawloop_Package_ID__c ddppackage;
    public PageReference pageref;
    public String ddpid ='';
    public AIA_ExportAdjustmentSummary (ApexPages.StandardController controller) {
		rec = (AIA_Benefit_Design__c)controller.getRecord();
        ddppackage = AIA_Drawloop_Package_ID__c.getValues(AIA_Constants.BD_ADJUSTMENT_DDPNAME);
    }
    
    public Pagereference isApproved(){
        if(rec.Status__c!=AIA_Constants.BD_STATUS_APPROVED){
         	displayPopUp=true;
            msg=AIA_Constants.BDDDPmsg;
            return null;
        }
        else{
        	ddpid = ddppackage.DDP_ID__c;
            pageref = new PageReference('/apex/loop__looplus?sessionId='+UserInfo.getSessionId()+'&eid='+rec.id+'&ddpIds='+ddpid);
         	pageref.setRedirect(true);
         	return pageref; 
        }
    }
    
    //Page redirection to gsrf.
    public pagereference backtoBD(){
        PageReference pref = new PageReference('/'+rec.Id);
        pref.setRedirect(true);
        return pref;
    }

}