objects/AIA_Implementation__c.object
<CustomObject>
    <fields>
        <fullName>Workplan_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workplan Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AIA_Workplan_Type__c.Used_For__c</field>
                <operation>equals</operation>
                <value>Implementation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AIA_Workplan_Type__c</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Implementation</label>
    <nameField>
        <displayFormat>IMP-{000000}</displayFormat>
        <label>Implementation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Workplan_Type__c.object
<CustomObject>
    <fields>
        <fullName>Workplan_Type__c</fullName>
        <label>Workplan Condition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Workplan Type</label>
    <nameField>
        <displayFormat>WPT-{000000}</displayFormat>
        <label>Workplan Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Workplan_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workplan Type</label>
        <referenceTo>AIA_Workplan_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AIA_WorkplantypeTriggerHandler_Test.cls
@isTest
public class AIA_WorkplantypeTriggerHandler_Test {

    public static testmethod void beforeDeleteTest(){
     /*  commented as per US 210
       Test.startTest();
        Account acc= AIA_TestUtil.createAccount('Test12398');
        List<Opportunity> oppList=AIA_TestUtil.createOpps(acc.id);
        AIA_TestUtil.CreateImplementation(oppList.get(0).Id);
        try{
            List<AIA_Workplan_Type__c> workplanList=[select id from AIA_Workplan_Type__c  where id in(select Workplan_Type__c from AIA_Implementation__c)];
            delete workplanList;
        }catch(DmlException e){
            
        }
         Test.stopTest();
*/
    }

    
}