objects/AIA_Benefit_Design_Form__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Design__c</fullName>
        <label>Benefit Design</label>
        <referenceTo>AIA_Benefit_Design__c</referenceTo>
        <relationshipLabel>Benefit Design Form</relationshipLabel>
        <relationshipName>Benefit_Design_Form</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Benefit Design Form</label>
    <nameField>
        <displayFormat>BDF-{00000}</displayFormat>
        <label>Benefit Design Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Design Form</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AIA_Benefit_Design_Product__c.object
<CustomObject>
    <fields>
        <fullName>AIA_Dollar_Penalty__c</fullName>
        <inlineHelpText>To be completed for self-insured medical plans.  Enter the dollar penalty amount.</inlineHelpText>
        <label>Dollar Penalty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AIA_INN_Contracted_Provider_Penalty__c</fullName>
        <label>INN or Contracted Provider Penalty</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>100% BC provider</fullName>
                </value>
                <value>
                    <fullName>Same as  OON member penalty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AIA_Magellan_Behavioral_Health__c</fullName>
        <label>Magellan Behavioral Health</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BlueChoice</fullName>
                </value>
                <value>
                    <fullName>BlueChoice ADV</fullName>
                </value>
                <value>
                    <fullName>BluePreferred</fullName>
                </value>
                <value>
                    <fullName>HealthyBlue 2.0</fullName>
                </value>
                <value>
                    <fullName>HealthyBlue ADV</fullName>
                </value>
                <value>
                    <fullName>HealthyBlue HMO</fullName>
                </value>
                <value>
                    <fullName>HealthyBlue PPO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AIA_Percent_Penalty__c</fullName>
        <inlineHelpText>To be completed for self-insured medical plans.  Select a percentage penalty value.</inlineHelpText>
        <label>Percentage Penalty</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No member penalty</fullName>
                </value>
                <value>
                    <fullName>20% penalty</fullName>
                </value>
                <value>
                    <fullName>50% penalty</fullName>
                </value>
                <value>
                    <fullName>100% penalty</fullName>
                </value>
                <value>
                    <fullName>Other Nonstandard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AIA_Percent_and_Dollar_Penalty__c</fullName>
        <inlineHelpText>To be completed for self-insured medical plans.  Select a percentage and dollar penalty value.</inlineHelpText>
        <label>Percentage and Dollar Penalty</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No member penalty</fullName>
                </value>
                <value>
                    <fullName>20% penalty</fullName>
                </value>
                <value>
                    <fullName>50% penalty</fullName>
                </value>
                <value>
                    <fullName>100% penalty</fullName>
                </value>
                <value>
                    <fullName>Other Nonstandard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AIA_Up_to__c</fullName>
        <inlineHelpText>To be completed for self-insured medical plans.  Enter the up to dollar penalty amount.</inlineHelpText>
        <label>Up to $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Benefit_Design_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Design Form</label>
        <referenceTo>AIA_Benefit_Design_Form__c</referenceTo>
        <relationshipLabel>Benefit Design Products</relationshipLabel>
        <relationshipName>Benefit_Design_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Benefit_Design__c</fullName>
        <label>Benefit Design</label>
        <referenceTo>AIA_Benefit_Design__c</referenceTo>
        <relationshipLabel>Benefit Design Products</relationshipLabel>
        <relationshipName>BD_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fully_Insured__c</fullName>
        <label>Member Penalty</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No member penalty</fullName>
                </value>
                <value>
                    <fullName>50% penalty</fullName>
                </value>
                <value>
                    <fullName>20% penalty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percentage_Penalty_Other_Nonstandard__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Percentage Penalty Other Nonstandard</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Percentage_and_Dollar_Penalty_Other_Nons__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Percentage And Dollar Penalty Other Nonstandard</inlineHelpText>
        <label>Percent&amp;Dollar Penalty Other Nonstandard</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Product_Name__c</fullName>
        <formula>Plan_Name__r.Plan_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Plan Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SelectBDP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for providing panality details</description>
        <label>SelectBDP</label>
        <type>Checkbox</type>
    </fields>
    <label>Benefit Design Product</label>
    <nameField>
        <displayFormat>BDP -{0000}</displayFormat>
        <label>Benefit Design Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Design Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AIA_Drawloop_Package_ID__c.object
<CustomObject>
    <fields>
        <fullName>DDP_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DDP ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>AIA Drawloop Package ID</label>
</CustomObject>

classes/AIA_MCP_SavepageController.cls
/*=========================================================================================
 * Purpose      : This is the controller class for the VF AIA_MCP_SavePage.
 *=========================================================================================
 *                                 Update History
 *                                 ---------------
 * Date        Developer          Tag        Description
 *============+=================+=====+===========================================================
 * 01/17/2018 | Gayathri        | T01 | Added a method to differentiate classic and lightning
 * 02/28/2018 | Debkanti        | T02 | Added Logic to display different button for "MCP - Non Standard" and "MCP - Full Managed Care"
 *=========================================================================================
 */

public class AIA_MCP_SavepageController {
    public id bdid;
    public id mcpid;
    public AIA_Benefit_Design_Form__c rec{get; set;}
    public list<AIA_Benefit_Design_Product__c> lstbdp{get;set;}
    public boolean exportddp{get; set;}
    public boolean exportMcpFull{get; set;} //T02
    public final string MCPFullManaged = 'MCP - Full Managed Care';
    public final string MCPNonStandard = 'MCP - Non Standard';
    public AIA_MCP_SavepageController(ApexPages.StandardController controller) {
        //System checks weather logedin user has AIA_Admin permissionset
        Map<ID,Schema.RecordTypeInfo> bdfrtmap = AIA_Benefit_Design_Form__c.sObjectType.getDescribe().getRecordTypeInfosById();
        List<PermissionSetAssignment> lstcurrentUserPerSet = [SELECT Id, PermissionSet.Name,AssigneeId FROM PermissionSetAssignment WHERE AssigneeId =: Userinfo.getUserId() ];
        Boolean userhasadminpermission = false;
        for ( PermissionSetAssignment psa : lstcurrentUserPerSet ){
            System.debug('##psa.PermissionSet.Name' + psa.PermissionSet.Name);
            if ( psa.PermissionSet.Name.equals('AIA_Admin') ) {
                userhasadminpermission = true;
            }
        }
        //Gets loggedin user profile name.
        Id profileId=userinfo.getProfileId();
        String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
        
        rec = new AIA_Benefit_Design_Form__c();
        lstbdp = new list<AIA_Benefit_Design_Product__c>();
        mcpid = apexpages.currentpage().getparameters().get('id');
        rec = (AIA_Benefit_Design_Form__c)controller.getRecord();
        if(bdfrtmap.get(rec.recordtypeid).getName() == 'MCP - Full Managed Care' ){
            exportMcpFull = true;//T02
        }
        if(bdfrtmap.get(rec.recordtypeid).getName() == 'MCP - Full Managed Care' && (userhasadminpermission == true || profileName == 'System Administrator')){
            exportddp = true;
        }
        else if(bdfrtmap.get(rec.recordtypeid).getName() == 'MCP - Non Standard'  && (userhasadminpermission == true || profileName == 'System Administrator')){
            exportddp = false;
        }
        getselectedBDPs(rec.Benefit_Design__c);
    }
    //T01--Start--Method to check whether the page is in Classic or lightning
    public Boolean getIsClassic() {
        return AIA_Utils.isClassic();
    }
    //T01--End
    public void getselectedBDPs(id bdid){
        lstbdp = [select id, name,Plan_Product_Name__c, SelectBDP__c, AIA_Magellan_Behavioral_Health__c, AIA_INN_Contracted_Provider_Penalty__c,
            Fully_Insured__c, AIA_Percent_and_Dollar_Penalty__c, AIA_Dollar_Penalty__c, 
            Percentage_and_Dollar_Penalty_Other_Nons__c, AIA_Percent_Penalty__c, AIA_Up_to__c,
            Percentage_Penalty_Other_Nonstandard__c from AIA_Benefit_Design_Product__c where Benefit_Design__c=:bdid
            AND SelectBDP__c = true and Benefit_Design_Form__c =: mcpid] ;
    }
    public PageReference export(){
        string ddpIds='';
        Map<ID,Schema.RecordTypeInfo> bdfrtmap = AIA_Benefit_Design_Form__c.sObjectType.getDescribe().getRecordTypeInfosById();
        //T01--Start updated the ddpIds based on the record type
        if(bdfrtmap.get(rec.recordtypeid).getName() == 'MCP - Full Managed Care')
        {
            //ddpIds='a19V0000001QvpU';
             AIA_Drawloop_Package_ID__c ddppackage = AIA_Drawloop_Package_ID__c.getValues(MCPFullManaged);
             ddpIds=ddppackage.DDP_ID__c;
             
        }
        else if(bdfrtmap.get(rec.recordtypeid).getName() == 'MCP - Non Standard')
        {
            //ddpIds='a190R0000001IveQAE';
            AIA_Drawloop_Package_ID__c ddppackage = AIA_Drawloop_Package_ID__c.getValues(MCPNonStandard);
            ddpIds=ddppackage.DDP_ID__c;
        }
        //T01--End 
      PageReference   pageref = new PageReference('/apex/loop__looplus?sessionId={!$Api.Session_ID}&eid='+rec.id+'&hidecontact=true&ddpIds='+ddpIds);
            pageref.setRedirect(true);
            return pageRef;
    }
    public PageReference mcpedit(){
      string mcpmode = 'edit';
      PageReference pageref = new PageReference('/apex/AIA_MCP_BDP_SelectionPage?bdid='+rec.Benefit_Design__c+'&RecordType='+rec.recordtypeid+'&mcpmode='+mcpmode+'&mcpid='+rec.id);
            pageref.setRedirect(true);
            return pageRef;
    }
     
     
}