objects/AIA_Benefits__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Benefit Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoInsurance_AmountValueSelected__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>CoInsurance-AmountValueSelected</inlineHelpText>
        <label>INN CoInsurance</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copay_Max_Payment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Copay Max Payment</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copay_Min_Payment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Copay Min Payment</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copay_Type_1_AmountValueSelected__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Copay_Type_1_AmountValueSelected</inlineHelpText>
        <label>INN Copay 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copay_Type_1_IsCovered__c</fullName>
        <inlineHelpText>Copay Type 1 - IsCovered</inlineHelpText>
        <label>INN Copay IsCovered</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cost_Share_SelectedAmount__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Cost Share - SelectedAmount</inlineHelpText>
        <label>INN Cost Share</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grouper__c</fullName>
        <label>Grouper</label>
        <referenceTo>AIA_Grouper__c</referenceTo>
        <relationshipLabel>Benefit</relationshipLabel>
        <relationshipName>Benefit</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Benefit</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Benefit #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Proposed_Product</fullName>
        <active>true</active>
        <label>Proposed Product</label>
    </recordTypes>
</CustomObject>

objects/AIA_Grouper__c.object
<CustomObject>
    <fields>
        <fullName>Proposed_Products__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Proposed Products</label>
        <referenceTo>Proposed_Products__c</referenceTo>
        <relationshipLabel>Grouper</relationshipLabel>
        <relationshipName>PPGrouper</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grouper</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Grouper Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grouper</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Proposed_Proposed</fullName>
        <active>true</active>
        <label>Proposed Product</label>
    </recordTypes>
</CustomObject>

objects/Proposed_Products__c.object
<CustomObject>
    <fields>
        <fullName>Integrated_Deductible_Integrator__c</fullName>
        <label>Integrated Deductible Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Integrated_OOP_Integration__c</fullName>
        <label>Integrated OOP Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan_Product_Name__c</fullName>
        <formula>Plan_Name__r.Plan_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Plan Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Parent_Name__c</fullName>
        <formula>Plan_Name__r.Full_Plan_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Full Name</label>
        <type>Text</type>
    </fields>
    <label>Proposed Products</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Proposed Products Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposed Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Drug</fullName>
        <active>true</active>
        <description>Drug Layout</description>
        <label>Drug</label>
    </recordTypes>
</CustomObject>

classes/AIA_GetCustomRxPlanName.cls
/*=================================================================================================================
* Date         : 03/14/2017
* Developer    : Ramakrishna
* Purpose      : This class contains logic to derive custom Rx plan name for Drug products.
*=================================================================================================================
*                                 Update History
*                                 ---------------
*   Date        Developer       Tag   Description
*============+================+=====+=============================================================================
* 03/14/2017 | Ramakrishna    | T04 | Initial Version. 
* 2/21/2018  | Satya T        | T05 | Made changes as a part of Defect 38775. Added to accomodate the grouper that 
*                                     are with and without ' - ' in their name
*===========+============+========================================================================================*/
public class AIA_GetCustomRxPlanName {
    String CustRxPlanName;
    public String CustomRxPlanName(String propProdId){
        string a='NC'+'/'+ 'NC' +'/'+ 'NC' +'/'+ 'NC';
        string b='NC'+'/'+ 'NC' +'/'+ 'NC' +'/'+ 'NC';
        string c='NC'+'/'+ 'NC' +'/'+ 'NC' +'/'+ 'NC';
        string d='NC'+'/'+ 'NC' +'/'+ 'NC' +'/'+ 'NC';
        string Indoop = 'NC';
        string Foop = 'NC';
        string IndDed = 'NC';
        string FDed = 'NC';   
        
        Proposed_Products__c ppRec = [select Id,name, Integrated_Deductible_Integrator__c, Integrated_OOP_Integration__c, Plan_Product_Name__c,Product_Parent_Name__c
                                      from Proposed_Products__c 
                                      where Id =:propProdId];
        list<AIA_Grouper__c> grouper = [select Id, name 
                                        from AIA_Grouper__c 
                                        where (Name like '%Retail NonMaintenance%' OR Name like '%Retail Non-Maintenance%') and
                                            Proposed_Products__c =:propProdId and
                                            RecordType.DeveloperName = 'Proposed_Proposed' 
                                        limit 1]; 
        if(grouper.size()>0){                            
            List<AIA_Benefits__c> BenList = [select Id,Benefit_Name__c,Copay_Type_1_AmountValueSelected__c, CoInsurance_AmountValueSelected__c, 
                                                    Copay_Min_Payment__c, Copay_Max_Payment__c,Copay_Type_1_IsCovered__c 
                                             from AIA_Benefits__c 
                                             where Grouper__c =:grouper[0].Id];
            // and RecordType.DeveloperName = 'Proposed_Product'];
            if(BenList!=null && BenList.size()>0){
                for(AIA_Benefits__c Ben : BenList){
                    String copay = checkInvalidValues(Ben.Copay_Type_1_AmountValueSelected__c)?'NC':('$'+Ben.Copay_Type_1_AmountValueSelected__c);
                    String coInsur = checkInvalidValues(Ben.CoInsurance_AmountValueSelected__c)?'NC':(Ben.CoInsurance_AmountValueSelected__c+'%');
                    String copayMin = checkInvalidValues(Ben.Copay_Min_Payment__c)?'NC':('$'+ Ben.Copay_Min_Payment__c + ' ' + 'Min Pay');
                    String copayMax = checkInvalidValues(Ben.Copay_Max_Payment__c)?'NC':('$'+ Ben.Copay_Max_Payment__c + ' ' + 'Max Pay');    
                    
                    //T05 changes start                
                                    
                    if((Ben.Benefit_Name__c == 'Retail NonMaintenance Generic' || Ben.Benefit_Name__c == 'Retail Non-Maintenance Generic') && Ben.Copay_Type_1_IsCovered__c =='Yes'){
                        a = copay + '/' + coInsur + '/' + copayMin + '/' + copayMax ;   
                    }
                    else if((Ben.Benefit_Name__c == 'Retail NonMaintenance Generic' || Ben.Benefit_Name__c == 'Retail Non-Maintenance Generic') && Ben.Copay_Type_1_IsCovered__c =='No')
                        a = 'NC' + '/' + 'NC' + '/' + 'NC' + '/' + 'NC' ; 
                    
                    if((Ben.Benefit_Name__c == 'Retail NonMaintenance NonPreferred Brand' || Ben.Benefit_Name__c == 'Retail Non-Maintenance Non-Preferred Brand') && Ben.Copay_Type_1_IsCovered__c =='Yes'){
                        b = copay + '/' + coInsur + '/' + copayMin + '/' + copayMax;
                    }
                    else if((Ben.Benefit_Name__c == 'Retail NonMaintenance NonPreferred Brand' || Ben.Benefit_Name__c == 'Retail Non-Maintenance Non-Preferred Brand') && Ben.Copay_Type_1_IsCovered__c =='No')
                        b = 'NC' + '/' + 'NC' + '/' + 'NC' + '/' + 'NC' ;
                    
                    if((Ben.Benefit_Name__c == 'Retail NonMaintenance Preferred Brand'|| Ben.Benefit_Name__c == 'Retail Non-Maintenance Preferred Brand') && Ben.Copay_Type_1_IsCovered__c =='Yes'){
                        c = copay + '/' + coInsur + '/' + copayMin + '/' + copayMax;
                    }
                    else if((Ben.Benefit_Name__c == 'Retail NonMaintenance Preferred Brand' || Ben.Benefit_Name__c == 'Retail Non-Maintenance Preferred Brand') && Ben.Copay_Type_1_IsCovered__c =='No')
                        c = 'NC' + '/' + 'NC' + '/' + 'NC' + '/' + 'NC' ;
                    
                    if((Ben.Benefit_Name__c == 'Retail NonMaintenance Self-Injectable' || Ben.Benefit_Name__c == 'Retail Non-Maintenance Self-Injectable') && Ben.Copay_Type_1_IsCovered__c =='Yes'){
                        d = copay + '/' + coInsur + '/' + copayMin + '/' + copayMax;
                    }
                    else if((Ben.Benefit_Name__c == 'Retail NonMaintenance Self-Injectable' || Ben.Benefit_Name__c == 'Retail Non-Maintenance Self-Injectable') && Ben.Copay_Type_1_IsCovered__c =='No')
                        d = 'NC' + '/' + 'NC' + '/' + 'NC' + '/' + 'NC' ;
                }
            }
        } //T05 changes end
        
        List<AIA_Grouper__c> CostSharegrouper = [select Id, name 
                                                 from AIA_Grouper__c 
                                                 where Name = 'CostShareRanges' 
                                                         and Proposed_Products__c =:propProdId
                                                         and RecordType.DeveloperName = 'Proposed_Proposed' limit 1];
        if(CostSharegrouper!=null && CostSharegrouper.size()>0){                                      
            List<AIA_Benefits__c> CostshareBenList = [select Id,Benefit_Name__c,Cost_Share_SelectedAmount__c
                                                      from AIA_Benefits__c 
                                                      where Grouper__c =:CostSharegrouper[0].Id];
            if(CostshareBenList!=null && CostshareBenList.size()>0){                                                     
                for(AIA_Benefits__c CostBen : CostshareBenList){
                    String CostShare =checkInvalidValues(CostBen.Cost_Share_SelectedAmount__c)?'NC':('$'+CostBen.Cost_Share_SelectedAmount__c);                                   
                        
                    if(CostBen.Benefit_Name__c == 'Individual Out Of Pocket'){
                        Indoop = checkInvalidValues(CostBen.Cost_Share_SelectedAmount__c)?'NC':('$'+CostBen.Cost_Share_SelectedAmount__c);  
                    } 
                    if(CostBen.Benefit_Name__c == 'Family Out Of Pocket'){
                        Foop = checkInvalidValues(CostBen.Cost_Share_SelectedAmount__c)?'NC':('$'+CostBen.Cost_Share_SelectedAmount__c);
                    }
                    if(CostBen.Benefit_Name__c == 'Individual Deductible'){
                        IndDed = checkInvalidValues(CostBen.Cost_Share_SelectedAmount__c)?'NC':('$'+CostBen.Cost_Share_SelectedAmount__c);
                    }
                    if(CostBen.Benefit_Name__c == 'Family Deductible'){
                        FDed = checkInvalidValues(CostBen.Cost_Share_SelectedAmount__c)?'NC':('$'+CostBen.Cost_Share_SelectedAmount__c);
                    }   
                }
            }
        }
        
        If(ppRec.Integrated_Deductible_Integrator__c == 'Yes' && ppRec.Integrated_OOP_Integration__c == 'Yes'){   
            if(grouper.size()>0){
                CustRxPlanName = 'Rx' + ' ' + a + ' ' + b + ' ' + c + ' ' + d;
            }
            else
                CustRxPlanName = ppRec.Product_Parent_Name__c; 
        }else
            if(ppRec.Integrated_Deductible_Integrator__c == 'No' && ppRec.Integrated_OOP_Integration__c == 'Yes'){
                if(grouper.size()>0){
                    CustRxPlanName = 'Rx'  + ' ' +  Indoop +'/'+ Foop + ' ' + 'OOP'  + ' ' +  a  + ' ' +  b  + ' ' +  c  + ' ' +  d;
                }else 
                    CustRxPlanName = ppRec.Product_Parent_Name__c;
            }else
                if(ppRec.Integrated_Deductible_Integrator__c == 'No' && ppRec.Integrated_OOP_Integration__c == 'No'){
                    if(grouper.size()>0){
                        CustRxPlanName = 'Rx'  + ' ' +  IndDed +'/'+ FDed + ' ' + 'DED' + ' ' + Indoop +'/'+ Foop + ' ' + 'OOP'  + ' ' +  a  + ' ' +  b  + ' ' +  c  + ' ' +  d;
                    } else 
                        CustRxPlanName = ppRec.Product_Parent_Name__c;
                }  
        return CustRxPlanName;        
    }  
    
    /**Method returns True for Invalid Value and False for Valid Values**/
    public Boolean checkInvalidValues(String selectedValue){
        if(String.isBlank(selectedValue) || selectedValue == 'N/A' || selectedValue == 'NA') {
            return True;
        }
        return False;
    }
    
}