objects/AIA_Implementation__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Implementation</label>
    <nameField>
        <displayFormat>IMP-{000000}</displayFormat>
        <label>Implementation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Process__c.object
<CustomObject>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Process</relationshipLabel>
        <relationshipName>Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ZZZProcess Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Used to identify the Stage of the Process Record</description>
        <label>Process Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Benefit Request</fullName>
                </value>
                <value>
                    <fullName>ARC Approval</fullName>
                </value>
                <value>
                    <fullName>Underwriting</fullName>
                </value>
                <value>
                    <fullName>Quote Delivered</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Group Structure &amp; Admin Setup</fullName>
                </value>
                <value>
                    <fullName>Benefit Design &amp; Creation of NAEGS</fullName>
                </value>
                <value>
                    <fullName>Benefit Coding, Loading, &amp; Testing</fullName>
                </value>
                <value>
                    <fullName>Open Enrollment, Materials, &amp; Support</fullName>
                </value>
                <value>
                    <fullName>Enrollment &amp; ID Card Generation</fullName>
                </value>
                <value>
                    <fullName>Post Sales Document Generation</fullName>
                </value>
                <value>
                    <fullName>Billing (Monthly) Invoices</fullName>
                </value>
                <value>
                    <fullName>Account &amp; Member Tools</fullName>
                </value>
                <value>
                    <fullName>Accm Cnt Svcs</fullName>
                </value>
                <value>
                    <fullName>Account Financial Contracts</fullName>
                </value>
                <value>
                    <fullName>Account Kick-off Meeting</fullName>
                </value>
                <value>
                    <fullName>BAA</fullName>
                </value>
                <value>
                    <fullName>BR Wellness</fullName>
                </value>
                <value>
                    <fullName>Benefit Design Doc</fullName>
                </value>
                <value>
                    <fullName>Benefit Setup</fullName>
                </value>
                <value>
                    <fullName>CSR</fullName>
                </value>
                <value>
                    <fullName>CYC</fullName>
                </value>
                <value>
                    <fullName>Carve-out RX</fullName>
                </value>
                <value>
                    <fullName>Create Benefit Contract</fullName>
                </value>
                <value>
                    <fullName>EDC</fullName>
                </value>
                <value>
                    <fullName>Generate Post Sale SBCs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to identify the status of the record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Run time Object used for AIA workplan 
AIA - Custom object used to store the Stage, type &amp; status of Runtime Process. This object is a Parent object for Run time AIA Workplan. 
This is implemented for JUNE-2018 Release.</description>
    <label>Process</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Sub_Process__c.object
<CustomObject>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Sub Process</relationshipLabel>
        <relationshipName>Sub_Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Sub Process</relationshipLabel>
        <relationshipName>Sub_Processes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Used to identify the Stage of the Sub Process Record</description>
        <label>Sub Process Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Group Structure</fullName>
                </value>
                <value>
                    <fullName>Enrollment Data Card</fullName>
                </value>
                <value>
                    <fullName>Benefit Setup</fullName>
                </value>
                <value>
                    <fullName>Change System Request</fullName>
                </value>
                <value>
                    <fullName>Performance Guarantee</fullName>
                </value>
                <value>
                    <fullName>Summary of Benefits and Coverage</fullName>
                </value>
                <value>
                    <fullName>Account Kick-off Meeting</fullName>
                </value>
                <value>
                    <fullName>Marketing Materials</fullName>
                </value>
                <value>
                    <fullName>Blue Rewards and Wellness</fullName>
                </value>
                <value>
                    <fullName>Setup Vision</fullName>
                </value>
                <value>
                    <fullName>Setup Magellan</fullName>
                </value>
                <value>
                    <fullName>Process Enrollment</fullName>
                </value>
                <value>
                    <fullName>Par Plan Custom Letters</fullName>
                </value>
                <value>
                    <fullName>Accommodation of Contraceptive Services</fullName>
                </value>
                <value>
                    <fullName>Benefit Contract</fullName>
                </value>
                <value>
                    <fullName>Implementation Plan</fullName>
                </value>
                <value>
                    <fullName>Benefit Design</fullName>
                </value>
                <value>
                    <fullName>CYC</fullName>
                </value>
                <value>
                    <fullName>Setup Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Setup Dental</fullName>
                </value>
                <value>
                    <fullName>Carve-Out Pharmacy</fullName>
                </value>
                <value>
                    <fullName>ID Cards</fullName>
                </value>
                <value>
                    <fullName>Administrative Service Agreement</fullName>
                </value>
                <value>
                    <fullName>Business Associate Agreement and Confirmation (BAA/BAC)</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Benefit Request</fullName>
                </value>
                <value>
                    <fullName>ARC Approval</fullName>
                </value>
                <value>
                    <fullName>Underwriting</fullName>
                </value>
                <value>
                    <fullName>Quote Delivered</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to identify the status of the record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Run time Object used for AIA workplan Stage
AIA - Custom object used to store the Stage, type &amp; status of Runtime Sub Process. This object is a child object for Run time Process object. 
This is implemented for JUNE-2018 Release.</description>
    <label>Sub Process</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Sub Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sub_Process_Type__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to identify the status of the record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Setup Objects used for AIA Workplan 
AIA - Custom object used to store the Stage, type &amp; status of Sub Process Template . This object is a child to Process Template for AIA Workplan. 
This object will replace the old functionality of AIA WorkPlan Type Stage. 
This is implemented for JUNE-2018 Release.</description>
    <label>Sub Process Template</label>
    <nameField>
        <displayFormat>SPT-{000000}</displayFormat>
        <label>Sub Process Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sub Process Template</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AIA_Implementation_Dashboard_Extn.cls
/*====================================================================================================================
* Date       : 05/20/2018
* Developer  : Asif Kutagulla
* Purpose    : Extension for Visualforce page AIA_Implementation_Dashboard to show Implmentation Dashboard on the   
*              Implementation record. The VF page is added as a layout component on Implemenation lightning record page. 
*              Story:US463. This gives an Implemenation a comprehensive view of the current status of an Implementation.
*                               ========[Update History]=======
*                     -----------------------------------------------------
* Date         Developer    Tag         Description
*====================================================================================================================
* 05/20/2018 | Asif K     |     | Initial version
*====================================================================================================================*/
public without sharing class AIA_Implementation_Dashboard_Extn {
    AIA_Implementation__c aiaImpl = new AIA_Implementation__c();
    public list<Process__c> lstProcesses {get; set;}
    Static Final String TASK_NOT_GEN_ERROR = 'Tasks are not generated for this Implementation. Please click on the Start Implementation button on this page.';
    Static Final String TASK_PROCESS_COUNT_ERROR = 'Number of processes generated for this Implementation is not correct, please raise a ticket  in OneStop';
    Static Final String STATUS_COMPLETED = 'Completed';
    Static Final String STATUS_PROGRESS ='In-Progress';
    
    public AIA_Implementation_Dashboard_Extn(ApexPages.StandardController impCon) {
        system.debug('In AIA_Implementation_Dashboard_Extn constructor');
        lstProcesses = new list<Process__c>();
        aiaImpl = (AIA_Implementation__c)impCon.getrecord();
        populateProcessesList();
    }
    
    public void populateProcessesList() {
        String implID = ApexPages.currentPage().getParameters().get('Id');
        AIA_Implementation__c imp = [Select id, Status__c from AIA_Implementation__c where id=:implID];
        lstProcesses.addAll([SELECT Id, Name, Process_Name__c, Stage__c,
                                   (SELECT Name, Process__c, Active__c, Stage__c, Sub_Process_Type__c, Total_Task_Count__c,
                                           Parent_Process_Stage__c, AIA_Number_of_Completed_tasks__c, AIA_Number_of_Not_Required_Tasks__c 
                                    FROM Sub_Processes__r
                                    ORDER BY Sequence_Number__c ASC), 
                                   Active__c, Used_For__c, Status__c, Implementation__c 
                            FROM Process__c 
                            WHERE Implementation__c = :implID
                            ORDER BY Sequence_Number__c ASC NULLS LAST]);
        if(lstProcesses!=NULL && lstProcesses.isEmpty() && imp.Status__c != STATUS_COMPLETED && imp.Status__c != STATUS_PROGRESS) {
            ApexPages.Message msg = new Apexpages.Message(ApexPages.Severity.INFO, TASK_NOT_GEN_ERROR);
            ApexPages.addmessage(msg);
            return;
        }
        else if(lstProcesses.size()!=8 && imp.Status__c != STATUS_COMPLETED) {
            ApexPages.Message msg = new Apexpages.Message(ApexPages.Severity.ERROR, TASK_PROCESS_COUNT_ERROR);
            ApexPages.addmessage(msg);
            return;
        }
    }
}