objects/AIA_Document__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Request Form</label>
        <referenceTo>Benfit_Request_Form__c</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Acount Cancellation Termination and Transfer Request Form</fullName>
                    <label>Account Cancellation Termination and Transfer Request Form</label>
                </value>
                <value>
                    <fullName>Account Implementation Workplan (Internal)</fullName>
                </value>
                <value>
                    <fullName>Account Impmentation Milestone Workplan (External)</fullName>
                </value>
                <value>
                    <fullName>Account Kick-off</fullName>
                </value>
                <value>
                    <fullName>Account Review Committee</fullName>
                </value>
                <value>
                    <fullName>Additional Documentation</fullName>
                </value>
                <value>
                    <fullName>Administrative Service Agreement</fullName>
                </value>
                <value>
                    <fullName>Administrative Services Agreement (ASA)</fullName>
                </value>
                <value>
                    <fullName>AIA Account Issue Documentation</fullName>
                </value>
                <value>
                    <fullName>Benefit Design Document</fullName>
                </value>
                <value>
                    <fullName>Benefit EDC</fullName>
                </value>
                <value>
                    <fullName>Benefit Request Form</fullName>
                </value>
                <value>
                    <fullName>Benefits Contracts</fullName>
                </value>
                <value>
                    <fullName>Billing Information Form</fullName>
                </value>
                <value>
                    <fullName>BlueFund</fullName>
                </value>
                <value>
                    <fullName>BlueRewards Wellness</fullName>
                </value>
                <value>
                    <fullName>Business Associate Agreement (BAA)</fullName>
                </value>
                <value>
                    <fullName>Business Associate Confirmation (BAC)</fullName>
                </value>
                <value>
                    <fullName>CAG (Carrier Account Group)</fullName>
                </value>
                <value>
                    <fullName>Cede Document</fullName>
                </value>
                <value>
                    <fullName>Census Information</fullName>
                </value>
                <value>
                    <fullName>Client Letters</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Custom BAA</fullName>
                </value>
                <value>
                    <fullName>Custom Funding Letter</fullName>
                </value>
                <value>
                    <fullName>CVS Sales Support Request Form</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Department Notes</fullName>
                </value>
                <value>
                    <fullName>Department Number Notes</fullName>
                </value>
                <value>
                    <fullName>Enrollment Data Card (EDC)</fullName>
                </value>
                <value>
                    <fullName>Marked Up Benefit Summary</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposed_Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposed Products</label>
        <referenceTo>Proposed_Products__c</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AIA Document</label>
    <nameField>
        <displayFormat>FD-{000000}</displayFormat>
        <label>AIA Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AIA Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Recordtype for all AIA Documents other than Docusign documents like BAA, BAC etc</description>
        <label>Standard</label>
    </recordTypes>
</CustomObject>

objects/AIA_Grouper__c.object
<CustomObject>
    <fields>
        <fullName>Cloned_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cloned From</label>
        <referenceTo>AIA_Grouper__c</referenceTo>
        <relationshipLabel>Grouper</relationshipLabel>
        <relationshipName>Grouper</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>The product category</description>
        <formula>Text(Benefit_Design_Product__r.Product_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The product category</inlineHelpText>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposed_Products__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Proposed Products</label>
        <referenceTo>Proposed_Products__c</referenceTo>
        <relationshipLabel>Grouper</relationshipLabel>
        <relationshipName>PPGrouper</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grouper</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Grouper Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grouper</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Has_Benefit_Summary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Benefit Summary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Plan Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>CareFirst Private Exchange</fullName>
                </value>
                <value>
                    <fullName>Drug</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>AIA Object - Object used to store plans send from PCS</description>
    <label>Plan</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>SFDC Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Benfit_Request_Form__c.object
<CustomObject>
    <fields>
        <fullName>Blue_Rewards_Drawloop__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>BlueRewards Drawloop</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Arrangements__c</fullName>
        <label>Funding Arrangement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MHP_Test_Result__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>MHP Test Result</label>
        <type>TextArea</type>
    </fields>
    <description>New object for AIA - This object stores the information that is needed for a quote</description>
    <label>Benefit Request Form</label>
    <nameField>
        <displayFormat>BRF-{000000}</displayFormat>
        <label>Benefit Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Request Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>ASO</fullName>
        <active>true</active>
        <description>ASO Layout</description>
        <label>ASO</label>
    </recordTypes>
    <recordTypes>
        <fullName>Both</fullName>
        <active>true</active>
        <description>Both Layout</description>
        <label>Both</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <description>Other Layout</description>
        <label>Other</label>
    </recordTypes>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <description>Risk Layout</description>
        <label>Risk</label>
    </recordTypes>
</CustomObject>

objects/Proposed_Products__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Request_Form__c</fullName>
        <label>Benefit Request Form</label>
        <referenceTo>Benfit_Request_Form__c</referenceTo>
        <relationshipLabel>Proposed Products</relationshipLabel>
        <relationshipName>Proposed_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Blue_Rewards__c</fullName>
        <label>Blue Rewards</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Funding_Arrangement__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cloned_From__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Cloned From</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_New__c</fullName>
        <label>Customization Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Non - Standard</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deductible__c</fullName>
        <label>Family Deductible</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Stacked</fullName>
                </value>
                <value>
                    <fullName>Unstacked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Has_Benefit_Details__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will check if Proposed product has Benefits saved in Run Time</description>
        <label>Has Benefit Details</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Integrated_Non_Integrated__c</fullName>
        <label>RX Integration</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Integrated_Deductible_Integrator__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Integrated</fullName>
                </value>
                <value>
                    <fullName>Integrated - Carved-Out</fullName>
                </value>
                <value>
                    <fullName>Non-Integrated</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Out_of_Pocket_Max__c</fullName>
        <label>Family Out-of-Pocket</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Stacked</fullName>
                </value>
                <value>
                    <fullName>Unstacked</fullName>
                </value>
                <value>
                    <fullName>Non-Stacked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Name</label>
        <referenceTo>AIA_Plan__c</referenceTo>
        <relationshipLabel>Proposed Products</relationshipLabel>
        <relationshipName>Proposed_Products_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Medical_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Medical Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Proposed_Products__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Medical_Risk</value>
            </filterItems>
            <filterItems>
                <field>Proposed_Products__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Medical_ASO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Proposed_Products__c</referenceTo>
        <relationshipLabel>Related Ancillary Products</relationshipLabel>
        <relationshipName>Proposed_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Proposed Products</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Proposed Products Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposed Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Drug</fullName>
        <active>true</active>
        <description>Drug Layout</description>
        <label>Drug</label>
    </recordTypes>
    <recordTypes>
        <fullName>Medical</fullName>
        <active>true</active>
        <description>Medical Layout</description>
        <label>Medical</label>
    </recordTypes>
    <recordTypes>
        <fullName>Medical_Risk</fullName>
        <active>true</active>
        <description>Medical Risk Layout</description>
        <label>Medical Risk</label>
    </recordTypes>
</CustomObject>

classes/AIA_ProposedProductsHandler.cls
/*================================================================================================================================================
* Date       :  05/04/2016
* Developer  :  Sree Harsha Akkala
* Purpose    :  Proposed Product Class includes method which MHP updates the MHP Test result field on proposed product 
*                                       Update History
*=================================================================================================================================================
*   Date        Developer       Tag   Description
*============+================+=====+=============================================================================================================
* 05/04/2016 | Sree Harsha    |     | Initial Development
* 02/27/2017 | Goutham Rapolu |     | updateBRFMHPTestResult Method(): If the Proposal Request form form is created from BRF then the BRF MPH Test                                         
*                                     Result field will be updated Based on Proposal request Form.
*                                     validationForCustomCheck Mthod() : To check whether there is an AIA Document (Document Type =  "Marked 
*                                     Up Benefit Summary") attached to the Proposed Product, when the custom flag on the Proposed Product is true
* 11/29/2016 | Indira Das     | T01 | updated validationForCustomCheck Mthod() : To check whether there is an AIA Document (Document Type =  
*                                     "Marked Up Benefit Summary") attached to the Proposed Product, when the custom flag on the Proposed Product 
*                                     is true and related Plan HAs benefit Summary is False
* 03/10/2017 | Goutham Rapolu | T02 | Removed code as not required when MHP Test Result is null on the PP
*                                     MHP Test Result on BRF also will be null. 
* 03/06/2017 | Sree Harsha    |     | Added UpdateRelatedDrugPP method to update the fields in drug PP based on the related Medical PP
* 03/23/2017 | Bill Dodson    | T03 | Merge in adjustment summary code and flags.
* 03-24-2017 | Bill Dodson    | N/A | Uncomment out adjustment summary code that someone 
*                                     commented out.
* 03/20/2017 | Sree Harsha    | T05 | Added method call UpdateRelatedDrugPP to beforeInsert 
* 03/27/2017 | Sree Harsha    | T04 | Added method UpdateRelatedDrugPP_Insert to run for Drug PP Insert.
* 04/28/2017 | Bill Dodson    | T05 | Remove firstRun that surrounds adjustment summary code.
* 10/17/2017 | satya          | T06 | Added as a part of workplan tasks
** 4/4/2018  | Sajitha        | T07 | moved code fix for cloning issue 
* 09/04/2018 | Arshia	      |	T08 | Commented MHP Update for US-771
==================================================================================================================================================
*/
public class AIA_ProposedProductsHandler extends TriggerHandler {

    public AIA_ProposedProductsHandler(){}
    public static boolean firstRun=false;
    public static boolean afterInsert=false;
    public static boolean afterUpdate=false;
    @TestVisible private static Boolean adjustmentPreviouslyCalled = false; // T03
    private static Boolean otherTriggersRunning = false; // T03
     //T07- start
    public static boolean MHPran = false;
     //T07 - End
    public static Final String errorMsg = label.AIA_PP_Error_Msg;

    protected override void afterInsert() {
         // T07- Added check as part of cloning issue
        if(!afterInsert && MHPran == false && !test.isrunningtest())
        {
      //  updateMHPTest((list<Proposed_Products__c>) trigger.new,(Map<id,Proposed_Products__c>) trigger.oldMap);  //T08
      //  updateBRFMHPTestResult((list<Proposed_Products__c>) trigger.new,(Map<id,Proposed_Products__c>) trigger.oldMap);	//T08
        MHPran = true;
        afterInsert = true;
        }
        if(!firstRun){otherTriggersRunning = true; // T03  
        UpdateRelatedDrugPP((list<Proposed_Products__c>) trigger.new, (Map<id,Proposed_Products__c>) trigger.oldMap); //T05
        UpdateRelatedDrugPP_Insert(trigger.new); //T04
        updateBRFBlueRewards((List<Proposed_Products__c>) trigger.new);//Satya
        System.debug('In AIA_ProposedProductsHandler, at bottom of afterInsert'); // T03
        otherTriggersRunning = false; // T03
        afterInsert = true;
        }
    }
    protected override void afterUpdate() {
        // T03 begin
         // T07 - Added check as part of cloning issue
      if(afterUpdate == false && MHPran == false && !test.isrunningtest()) {
       // updateMHPTest((list<Proposed_Products__c>) trigger.new,(Map<id,Proposed_Products__c>) trigger.oldMap);	//T08
       // updateBRFMHPTestResult((list<Proposed_Products__c>) trigger.new,(Map<id,Proposed_Products__c>) trigger.oldMap);	//T08
        afterUpdate = true;MHPran = true;
        }
      if(!firstRun){ // T05, commented out
      
        otherTriggersRunning = true; // T03  
        
        UpdateRelatedDrugPP((list<Proposed_Products__c>) trigger.new,(Map<id,Proposed_Products__c>) trigger.oldMap);
        updateBRFBlueRewards((List<Proposed_Products__c>) trigger.new);//Satya
        otherTriggersRunning = false; // T03  
        System.debug('In AIA_ProposedProductsHandler, at bottom of afterUpdate'); // T03
        }
        System.debug('In AIA_ProposedProductsHandler, at top of afterUpdate');
        if(!otherTriggersRunning && !adjustmentPreviouslyCalled){
            populateAdjustmentSummary(trigger.new,trigger.oldMap);
            System.debug('In AIA_ProposedProductsHandler, returned from populateAdjustmentSummary');
            adjustmentPreviouslyCalled = true;
        }
        else {
            System.debug('In AIA_ProposedProductsHandler, otherTriggersRunning: ' + otherTriggersRunning +
                         ', adjustmentPreviouslyCalled: ' + adjustmentPreviouslyCalled);
        } 
       
        // T03 end
       afterUpdate = true;
        
    }
    protected override void beforeInsert() {
      if(!firstRun){  
        otherTriggersRunning = true; // T03 
        UpdateRelatedDrugPP((list<Proposed_Products__c>) trigger.new,(Map<id,Proposed_Products__c>) trigger.oldMap); 
        otherTriggersRunning = false; // T03  
        }
    }

    /**     
    * @Author: Sree Harsha      
    * @This Method is called from ProposedProducts and it updates       
    * @ MHP Test result field on proposed products.     
    * @param -  list<Proposed_Products__c>          
    * @param - Map<id,Proposed_Products__c>     
    * @Output - Updates MHP Test result field on proposed product       
    */ 
    // Updates the completed by and completed date on the proposed products when the MHP Test Result is updated
    public static void updateMHPTest(list<Proposed_Products__c> newPPList,Map<id,Proposed_Products__c> oldPPMap){
	//T08-Start
        /*
        // Get list of products if the BRF is MHP required
        list<Proposed_Products__c> ppList = [select id,name,MHP_Test_Result__c,Benefit_Request_Form__r.MHP_Required__c from Proposed_Products__c where id in:newPPList ];
        system.debug('@@ppList'+ppList);
        if(ppList.size()>0){
                   for(Proposed_Products__c pp: ppList){
                if(oldPPMap!=null){
                   //if(oldPPMap.get(pp.id).MHP_Test_Result__c!=null && pp.MHP_Test_Result__c!=null){
                    if(oldPPMap.get(pp.id).MHP_Test_Result__c!=pp.MHP_Test_Result__c){
                        pp.MHP_Test_Completed_Date__c = system.now();
                        pp.MHP_Test_Completed_By__c=userInfo.getUserId();  
                        system.debug('@@pp.MHP_Test_Completed_By__coldmap'+pp.MHP_Test_Completed_By__c);             
                    }
                    //}
                }
                else{
                    if(pp.MHP_Test_Result__c!=null){
                        pp.MHP_Test_Completed_Date__c = system.now();
                        pp.MHP_Test_Completed_By__c=userInfo.getUserId();
                        system.debug('@@pp.MHP_Test_Completed_By__cnewmap'+pp.MHP_Test_Completed_By__c);
                    }
                }
            }

            firstRun=true;
            // T07 - Start
            afterUpdate = true;
            afterInsert = true;
            MHPran = true;
             //T07 - End
            try{
                update ppList;
            }
            catch(exception e){}
        }
*/
        //T08-End
    }

    /**
    * @Author: Goutham Rapolu
    * @This Method is called from Proposed Products trigger
    * @This method - If the Proposal Request form form is created from BRF then the BRF MPH Test Result field will be 
    *                updated Based on Proposal request Form
    * @param -  list<Proposed_Products__c> ,list<Proposed_Products__c>
    * @Output - Update the BRF based on PP's Records
    */

    public static void updateBRFMHPTestResult(list<Proposed_Products__c> newPPList,Map<id,Proposed_Products__c> oldPPMap){
//T08-Start
        /*
        Map<Id,boolean> failMapPP = new Map<Id,boolean>(); // To store Fail value from MHP_Test_Result__c fields
        Map<Id,boolean> passMapPP = new Map<Id,boolean>(); // To store pass value from MHP_Test_Result__c fields
        Map<Id,boolean> blankMapPP = new Map<Id,boolean>(); // To store blank value from MHP_Test_Result__c fields
        Map<Id,boolean> deferredMapPP = new Map<Id,boolean>(); // To store deferred value from MHP_Test_Result__c fields
        integer totalPP = 0; // to store all Proposed Products count
        integer totalPassPP = 0; // to store total pass Proposed Products count
        list<Proposed_Products__c> ppList = new list<Proposed_Products__c>();// to store Proposed Products records
        list<Benfit_Request_Form__c> brfList = new list<Benfit_Request_Form__c>(); // to store BRF records
        Set<String> BRFIds = new Set<String>();

        // Get record type for Medical
        Id rt_PP_Medical= QueryBase.getRecordtypeId('Proposed_Products__c', 'Medical');

        // Get all Medical Proposed Products
        if(rt_PP_Medical != null)
            ppList = [select id,name,MHP_Test_Result__c,Benefit_Request_Form__r.Funding_Arrangements__c,
                             Benefit_Request_Form__r.MHP_Test_Result__c,Benefit_Request_Form__c 
                      from Proposed_Products__c 
                      where id in:newPPList and recordtypeId =: rt_PP_Medical];
        system.debug('@@MHP_Test_Result__c inside updateBRFMHPTestResult');
        system.debug('@@MHP_Test_Result__c ppList  '+ppList );
        if(ppList.size()>0){      
            for(Proposed_Products__c pp: ppList){
                boolean isUpdate = false;
                boolean isInsert = false;
                BRFIds.add(pp.Benefit_Request_Form__c);
                system.debug('pp.Benefit_Request_Form__c'+ pp.Benefit_Request_Form__c);
                if(oldPPMap == null){//insert
                    isInsert = true;
                    system.debug('@@MHP_Test_Result__c isInsert ');
                }
                else{if(oldPPMap.get(pp.id).MHP_Test_Result__c != pp.MHP_Test_Result__c || oldPPMap.get(pp.id).MHP_Test_Result__c != null){isUpdate = true;
                        system.debug('@@MHP_Test_Result__c isUpdate ');
                    }
                }

                if((isUpdate || isInsert) && pp.Benefit_Request_Form__r.Funding_Arrangements__c == 'ASO'){
                   system.debug('@@MHP_Test_Result__c ASO');
                    if(pp.MHP_Test_Result__c == 'Fail')
                        failMapPP.put(pp.Benefit_Request_Form__c,true); 
                    if(String.isBlank(pp.MHP_Test_Result__c))
                        blankMapPP.put(pp.Benefit_Request_Form__c,true);
                    if(pp.MHP_Test_Result__c == 'Deferred')
                        deferredMapPP.put(pp.Benefit_Request_Form__c,true); 
                    if(pp.MHP_Test_Result__c == 'Pass'){
                        passMapPP.put(pp.Benefit_Request_Form__c,true);
                        totalPassPP ++;
                    }

                }
                 if((isUpdate || isInsert) && (pp.Benefit_Request_Form__r.Funding_Arrangements__c == 'Risk' || pp.Benefit_Request_Form__r.Funding_Arrangements__c == 'Both' || pp.Benefit_Request_Form__r.Funding_Arrangements__c == 'Other')){
                   system.debug('@@MHP_Test_Result__c Not ASO');
                    if(pp.MHP_Test_Result__c == 'Fail')
                        failMapPP.put(pp.Benefit_Request_Form__c,true); 
                    if(String.isBlank(pp.MHP_Test_Result__c))
                        blankMapPP.put(pp.Benefit_Request_Form__c,true);
                    if(pp.MHP_Test_Result__c == 'Pass'){
                        passMapPP.put(pp.Benefit_Request_Form__c,true);
                        totalPassPP ++;
                    }

                }
                totalPP ++;
            }

        
//T02//
             if(BRFIds != null && BRFIds.size() > 0){
            for(Benfit_Request_Form__c BRF: [select id,Funding_Arrangements__c,MHP_Test_Result__c,MHP_Required__c from Benfit_Request_Form__c where id =: BRFIds]){
              system.debug('@@MHP_Test_Result__c BRF');
                if(failMapPP != null && failMapPP.size()>0){
                    BRF.MHP_Test_Result__c = 'Fail';
                    system.debug('@@MHP_Test_Result__c fail');
                }else if(blankMapPP != null && blankMapPP.size()>0){
                    BRF.MHP_Test_Result__c = 'Pending';
                    system.debug('@@MHP_Test_Result__c pending');
                }else if(blankMapPP != null && blankMapPP.size()>0){ BRF.MHP_Test_Result__c = null;  
                    system.debug('@@MHP_Test_Result__c null');  
                }else if(deferredMapPP != null && deferredMapPP.size()>0){
                    BRF.MHP_Test_Result__c = 'Deferred';
                    system.debug('@@MHP_Test_Result__c Deferred');
                }else if(passMapPP != null && passMapPP.size()>0){
                    if(totalPassPP == totalPP)
                    BRF.MHP_Test_Result__c = 'Pass';
                    system.debug('@@MHP_Test_Result__c pass');
                }else if(BRF.MHP_Required__c == 'No' || BRF.MHP_Required__c == null){ BRF.MHP_Test_Result__c = null;}brfList.add(BRF); //Added BRF.MHP_Required__c == 'No' 3/13/17 - T02
            }
          }
        }
        else{for(Benfit_Request_Form__c BRF: [select id,Funding_Arrangements__c,MHP_Test_Result__c from Benfit_Request_Form__c where id =: BRFIds]){BRF.MHP_Test_Result__c = '';}
      }
        //T07 - start
        afterUpdate = true;
        afterInsert = true;
        MHPran = true;
         //T07 - End
        try{ 
            if(brfList != null && brfList.size()>0){
                firstRun=true;
                update brfList;
            }
        }catch(Exception e){
        }
 */
        //T08-End
    }

    /**
    * @Author: Goutham Rapolu
    * @This Method is called from Proposed Products trigger
    * @This method - To check whether there is an AIA Document (Document Type = "Marked Up Benefit Summary") attached 
    *             to the Proposed Product, when the custom flag on the Proposed Product is true
    * @param -  list<Proposed_Products__c> ,Map<id,Proposed_Products__c>
    * @Output - Through an error if condition is not meet 
    */

  /*  public static void validationForCustomCheck(list<Proposed_Products__c> newPPList,Map<id,Proposed_Products__c> oldPPMap){
        //T01 ---Start
        map<id,Proposed_Products__c> ppMap = new map<id,Proposed_Products__c>([SELECT Custom_new__c,Id,Plan_Name__r.Has_Benefit_Summary__c,Has_Benefit_Details__c ,
                                                                               (select id, Document_Type__c from File_Net_Documents__r
                                                                                where Document_Type__c ='Marked Up Benefit Summary') ,(select id ,name from PPGrouper__r)
                                                                               FROM Proposed_Products__c where id in:newPPList]);
        system.debug('errorMsg---'+errorMsg);
        //T01 ---END
        system.debug('ppMap'+ ppMap);
        if(ppMap != null && ppMap.size()>0){
            for(Proposed_Products__c pp: newPPList){
                system.debug('pp.Custom_New__c'+ pp.Custom_New__c +'----pp.Plan_Name__r.Has_Benefit_Summary__c---'+pp.Plan_Name__r.Has_Benefit_Summary__c);
                //T01 ---Start
                if(pp.Custom_New__c == 'Custom' && pp.Cloned_From__c == null && ((oldPPMap!=null && (oldPPMap.get(pp.id).Custom_new__c!=pp.Custom_new__c || oldPPMap.get(pp.id).Plan_Name__c!=pp.Plan_Name__c)) || oldPPMap==null)
                   && (ppMap.get(pp.id).Plan_Name__r.Has_Benefit_Summary__c ==false 
                       || (ppMap.get(pp.id).Plan_Name__r.Has_Benefit_Summary__c ==true && ppMap.get(pp.Id).PPGrouper__r.size()<1))) //T01 ---End
                {  
                    system.debug('ppMap.get(pp.Id).File_Net_Documents__r.size()'+  ppMap.get(pp.Id).File_Net_Documents__r.size());
                    if(ppMap.containsKey(pp.Id) && ppMap.get(pp.Id).File_Net_Documents__r.size() == 0){
                        pp.adderror(errorMsg);
                    }
                }
            }
        }
    } */

    /**
    * @Author: Satya
    * @This Method is called from ProposedProducts
    * @This method - This method is to Create AdjustmentRecord when any ProposedProducts field is updated
    * @param -  list<Proposed_Products__c>  
    * @param - Map<id,Proposed_Products__c>
    * @Output -
    */
    public static void populateAdjustmentSummary(List<sObject> lstPP,Map<id,sObject> PPOldMap)
    {
        AIA_AdjustmentSummaryUtils.populateAdjustmentSummary(lstPP, PPOldMap);
        firstRun=true;
    }


    /**
    * @Author: Sree Harsha 
    * @This Method is called from ProposedProducts
    * @This method - Updates Drug PP's fields based on related Medical PP's fields
    * @param -  list<Proposed_Products__c>  
    * @param - Map<id,Proposed_Products__c>
    * @Output - Updates out of pocket and deductible options fields
    */  
    public static void UpdateRelatedDrugPP(list<Proposed_Products__c> newPPList,Map<id,Proposed_Products__c> oldPPMap){
 
        list<Proposed_Products__c> ppListMedical = new list<Proposed_Products__c>();// to store Proposed Products records
        list<Proposed_Products__c> ppListDrug = new list<Proposed_Products__c>();

        // Get record type for Medical
        Id rt_PP_Medical= QueryBase.getRecordtypeId('Proposed_Products__c', 'Medical_Risk');	//T08
        
        // Get all Medical Proposed Products
        if(rt_PP_Medical != null){
            ppListMedical = [select id, Integrated_Non_Integrated__c, Deductible__c, Out_of_Pocket_Max__c from Proposed_Products__c where id in:newPPList and recordtypeId =: rt_PP_Medical];
        }
        
        Id rt_PP_Drug= QueryBase.getRecordtypeId('Proposed_Products__c', 'Drug');
        
        system.debug('newPPList---'+newPPList);
        system.debug('ppListMedical---'+ppListMedical);
        
        if(rt_PP_Drug != null){
            ppListDrug = [select id, Related_Medical_Product__r.Deductible__c,Related_Medical_Product__r.Out_of_Pocket_Max__c,Integrated_Non_Integrated__c, Deductible__c, 
            Related_Medical_Product__r.Integrated_Non_Integrated__c,Out_of_Pocket_Max__c from Proposed_Products__c where Related_Medical_Product__r.id in:ppListMedical and recordtypeId =: rt_PP_Drug];
        }
          if(ppListDrug.size()>0){
            for(Proposed_Products__c pp: ppListDrug){
                if(pp.Related_Medical_Product__r.Integrated_Non_Integrated__c == 'Integrated' || pp.Related_Medical_Product__r.Integrated_Non_Integrated__c == 'Integrated - Carved-Out'){
                    pp.Deductible__c = pp.Related_Medical_Product__r.Deductible__c;
                    pp.Out_of_Pocket_Max__c = pp.Related_Medical_Product__r.Out_of_Pocket_Max__c;
                   }
                }
        }
        firstRun=true;
            try{
                update ppListDrug;
            }
            catch(exception e){}
        }    


    /**
    * @Author: Sree Harsha 
    * @This Method is called from ProposedProducts on insert
    * @ and it updates couple of fields from the from medical 
    * @ to associated drug proposed products
    * @param -  list<Proposed_Products__c>  
    * @Output - Updates out of pocket and deductible options fields
    */      
        public void UpdateRelatedDrugPP_Insert(list<Proposed_Products__c> newPPList){
            list<Proposed_Products__c> ppListDrug = new list<Proposed_Products__c>();
            Id rt_PP_Drug= QueryBase.getRecordtypeId('Proposed_Products__c', 'Drug');
            if(rt_PP_Drug != null){
                ppListDrug = [select id, Related_Medical_Product__r.Deductible__c,Related_Medical_Product__r.Out_of_Pocket_Max__c,Integrated_Non_Integrated__c, Deductible__c, 
            Related_Medical_Product__r.Integrated_Non_Integrated__c,Out_of_Pocket_Max__c from Proposed_Products__c where id in:newPPList and recordtypeId =: rt_PP_Drug];
            }
            for(Proposed_Products__c pp : ppListDrug){                  
                if(pp.Related_Medical_Product__r.Integrated_Non_Integrated__c == 'Integrated' || pp.Related_Medical_Product__r.Integrated_Non_Integrated__c == 'Integrated - Carved-Out'){
                    pp.Deductible__c = pp.Related_Medical_Product__r.Deductible__c;
                    pp.Out_of_Pocket_Max__c = pp.Related_Medical_Product__r.Out_of_Pocket_Max__c;                                                            
                }                   
            }
           firstRun=true;
              try{
                update ppListDrug;
            }
            catch(exception e){}
                
        }

    /**
    * @Author: Satya 
    * @This Method is called from Proposed Products trigger
    * @This method - Update Blue_Rewards_Drawloop__c in BRF value form proposed product
    * @param -  list<Proposed_Products__c> ,list<Proposed_Products__c>
    * @Output - Update the BRF based on PP's Records
    */

    public static void updateBRFBlueRewards(list<Proposed_Products__c> newPPList){
        Set<Id> brfIdSet = new Set<Id>();
        for(Proposed_Products__c pp : newPPList){
            brfIdSet.add(pp.Benefit_Request_Form__c);           
        }
        
        Map<id,Integer> standrdCountMap = new Map<id,Integer>();        
        Map<id,Integer> customCountMap = new Map<id,Integer>();
        Map<id,Integer> noCountMap = new Map<id,Integer>();
        Map<id,Integer> fsaBlueFundMap = new Map<id,Integer>();        
        Map<id,Integer> CDHMap = new Map<id,Integer>();
        Map<id,Integer> CDHTypeMap = new Map<id,Integer>();
        Map<id,Integer> CustomWellnessMap = new Map<id,Integer>();
        Map<id,Integer> CustomCoreDMWellnessMap = new Map<id,Integer>();
        Map<id,Integer> BlueRewardsMap = new Map<id,Integer>();
        Map<id,Integer> IntegratedNonIntegratedMap = new Map<id,Integer>();
        List<Proposed_Products__c> ppList = [Select Id,Benefit_Request_Form__c,Blue_Rewards__c,Product_Category__c,FSA_BlueFund__c,CDH__c,CDH_Type__c,Custom_Wellness__c,Custom_Core_DM_Wellness__c,Integrated_Non_Integrated__c from Proposed_Products__c where Benefit_Request_Form__c in : brfIdSet];
        
        for(Proposed_Products__c pp : ppList){
            If(pp.Product_Category__c == 'Medical'){
                if(pp.Blue_Rewards__c == 'Standard'){
                    if(!standrdCountMap.containsKey(pp.Benefit_Request_Form__c)){
                        standrdCountMap.put(pp.Benefit_Request_Form__c,1);
                        BlueRewardsMap.put(pp.Benefit_Request_Form__c,1);
                    }else{standrdCountMap.put(pp.Benefit_Request_Form__c,standrdCountMap.get(pp.Benefit_Request_Form__c)+1);
                    }   
                }else if(pp.Blue_Rewards__c == 'Custom'){
                    if(!customCountMap.containsKey(pp.Benefit_Request_Form__c)){
                        customCountMap.put(pp.Benefit_Request_Form__c,1);
                        BlueRewardsMap.put(pp.Benefit_Request_Form__c,1);
                    }else{customCountMap.put(pp.Benefit_Request_Form__c,customCountMap.get(pp.Benefit_Request_Form__c)+1);}
                }else if(pp.Blue_Rewards__c == 'No'){
                    if(!noCountMap.containsKey(pp.Benefit_Request_Form__c)){
                        noCountMap.put(pp.Benefit_Request_Form__c,1);
                    }else{noCountMap.put(pp.Benefit_Request_Form__c,noCountMap.get(pp.Benefit_Request_Form__c)+1);}
                }
                //t06 changes start
                if(pp.FSA_BlueFund__c == true){
                    if(!fsaBlueFundMap.containsKey(pp.Benefit_Request_Form__c)){
                        fsaBlueFundMap.put(pp.Benefit_Request_Form__c,1);
                    }
                }
                if(pp.CDH__c == 'Yes'){
                    if(!CDHMap.containsKey(pp.Benefit_Request_Form__c)){
                        CDHMap.put(pp.Benefit_Request_Form__c,1);
                    }
                }
                if(pp.CDH_Type__c == 'HRA Integrated'){
                    if(!CDHTypeMap.containsKey(pp.Benefit_Request_Form__c)){
                        CDHTypeMap.put(pp.Benefit_Request_Form__c,1);
                    }
                }
                if(pp.Custom_Wellness__c == true){
                    if(!CustomWellnessMap.containsKey(pp.Benefit_Request_Form__c)){
                        CustomWellnessMap.put(pp.Benefit_Request_Form__c,1);
                    }
                }
                if(pp.Custom_Core_DM_Wellness__c == true){
                    if(!CustomCoreDMWellnessMap.containsKey(pp.Benefit_Request_Form__c)){
                        CustomCoreDMWellnessMap.put(pp.Benefit_Request_Form__c,1);
                    }
                }               
                if(pp.Integrated_Non_Integrated__c == 'Integrated - Carved-Out'){
                    if(!IntegratedNonIntegratedMap.containsKey(pp.Benefit_Request_Form__c)){
                        IntegratedNonIntegratedMap.put(pp.Benefit_Request_Form__c,1);
                    } //t06 ends
                }
            }
        }
        
        //List<Benfit_Request_Form__c> brfList = [Select Id,Blue_Rewards_Drawloop__c from Benfit_Request_Form__c where id in : brfIdSet];
        Benfit_Request_Form__c brfToUpdate;
        list<Benfit_Request_Form__c> brfList = new list<Benfit_Request_Form__c>();
        for(Id brfid : brfIdSet){
            brfToUpdate = new Benfit_Request_Form__c(Id = brfid);
            if(customCountMap.containsKey(brfid)){
                brfToUpdate.Blue_Rewards_Drawloop__c = 'Custom';
            }else if(standrdCountMap.containsKey(brfid) && !customCountMap.containsKey(brfid)){
                brfToUpdate.Blue_Rewards_Drawloop__c = 'Standard';
            }else if(noCountMap.containsKey(brfid) && !customCountMap.containsKey(brfid) && !standrdCountMap.containsKey(brfid)){
                brfToUpdate.Blue_Rewards_Drawloop__c = 'No';
            }
            //T06 changes start
            if(fsaBlueFundMap.containsKey(brfid)){
                brfToUpdate.PP_FSA_BlueFund__c = true;
            }
            if(CDHMap.containsKey(brfid)){
                brfToUpdate.PP_CDH__c = true;
            }
            if(CDHTypeMap.containsKey(brfid)){
                brfToUpdate.PP_CDH_Type__c = true;
            }
            if(CustomWellnessMap.containsKey(brfid)){
                brfToUpdate.PP_Custom_Wellness__c = true;
            }
            if(CustomCoreDMWellnessMap.containsKey(brfid)){
                brfToUpdate.PP_Integrated_DM_Wellness__c = true;
            }
            if(BlueRewardsMap.containsKey(brfid)){
                brfToUpdate.PP_Blue_Rewards__c = true;
            }
            if(IntegratedNonIntegratedMap.containsKey(brfid)){
                brfToUpdate.PP_Rx_Integration__c = true;
            }
            //T06 ends
            brfList.add(brfToUpdate);
        }
        if(!brfList.isEmpty()) { update brfList; }
        firstRun=true;
    }
        
        
}