objects/AIA_Implementation__c.object
<CustomObject>
    <fields>
        <fullName>Workplan_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workplan Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AIA_Workplan_Type__c.Used_For__c</field>
                <operation>equals</operation>
                <value>Implementation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AIA_Workplan_Type__c</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Implementation</label>
    <nameField>
        <displayFormat>IMP-{000000}</displayFormat>
        <label>Implementation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Workplan_Type__c.object
<CustomObject>
    <label>Workplan Type</label>
    <nameField>
        <displayFormat>WPT-{000000}</displayFormat>
        <label>Workplan Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Workplan_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workplan Type</label>
        <referenceTo>AIA_Workplan_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AIA_WorkplanTypeTriggerHandler.cls
/*=========================================================================================
 * Date     : 07/22/2016
 * Developer    : Sandeep S
 * Purpose      : This class is the extension point of the Trigger Framework for adding Workplantype trigger handlers.
 *                
 *               
 *
 *=========================================================================================
 *                                 Update History
 *                                 ---------------
 * Date       Developer         Description
 *===========+============+================================================================
 * 07/22/2016|  Sandeep   			|			  | Initial Version                                         
 * 10/17/2017|  Raviteja Vadapalli  |	T-01      | Commented lines as per US 209
 *===========+============+================================================================
 */
 
/*@Author: Sandeep S
* @Purpose: This class is completly for AIA- workplan type trigger framework
*/
 public with sharing class AIA_WorkplanTypeTriggerHandler extends TriggerHandler{
/*	T-01
    protected override void beforeDelete(){
     
        List<AIA_Workplan_Type__c> oldWptList=Trigger.old;
        List<AIA_Workplan_Type__c> workPlanTypeList=[select id,(select id from Opportunities__r),(select id from Implementations__r) from AIA_Workplan_Type__c where id=:oldWptList];
        
        for(AIA_Workplan_Type__c awt:workPlanTypeList){
         List<Opportunity> oppList=awt.Opportunities__r;
         List<AIA_Implementation__c> impList=awt.Implementations__r;
         Boolean flag=false;
            If(oppList!=null && oppList.size()>0){
                flag=true;
            }
            
            if(impList!=null && impList.size()>0){
                flag=true;
            }
            
            if(flag){
                If(Trigger.oldMap!=null && Trigger.oldMap.containsKey(awt.Id)){
                   AIA_Workplan_Type__c aw=(AIA_Workplan_Type__c)Trigger.oldMap.get(awt.Id);
               	   aw.addError('Error Message - In process workplan can\'t be deleted ');
                }
            }
            
        }
	
    }T-01 - end */
}