objects/AIA_Benefit_Design__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Design</relationshipLabel>
        <relationshipName>Benefit_Design</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Benefit_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Request Form</label>
        <referenceTo>Benfit_Request_Form__c</referenceTo>
        <relationshipLabel>Benefit Design</relationshipLabel>
        <relationshipName>Benefit_Design</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipName>Benefit_Design_c</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Benefit Design</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Benefit Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Design</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AIA_Benefit_Design_Form__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Design__c</fullName>
        <label>Benefit Design</label>
        <referenceTo>AIA_Benefit_Design__c</referenceTo>
        <relationshipLabel>Benefit Design Form</relationshipLabel>
        <relationshipName>Benefit_Design_Form</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Child_Dependents_Limit_Age_4a__c</fullName>
        <defaultValue>26</defaultValue>
        <inlineHelpText>Limiting age is 26 for Fully-insured accounts.</inlineHelpText>
        <label>All Child Dependents Limiting Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Child_Dependents_Removal_Method_4a__c</fullName>
        <label>All Child Dependents Removal Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>End of Calendar Month</fullName>
                </value>
                <value>
                    <fullName>On Birthday</fullName>
                </value>
                <value>
                    <fullName>End of Calendar Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Review_Processing_Comments__c</fullName>
        <defaultValue>"Note: Regarding nonfederal governmental accounts: Effective 7/1/11, CareFirst counsel believes nonfederal governmental accounts may be subject to the state external review process, however, accounts should obtain independent legal advice before choosing an external review process."</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>External Review Processing Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Michelle_s_Law_4a__c</fullName>
        <inlineHelpText>Federal Mandate - Applies to both fully-insured and self-insured accounts that provide a limiting age for student dependents that is greater than age 26.</inlineHelpText>
        <label>Michelle's Law</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Michelle_s_Law_Waiver_4a__c</fullName>
        <inlineHelpText>Applies to fully-insured accounts that provide Dependent coverage.  Self-insured accounts may select</inlineHelpText>
        <label>Michelle's Law Waiver</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_Of_Eligibles__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>New Business Only</inlineHelpText>
        <label>Number Of Eligibles</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_time_Students_with_Disabilities_4a__c</fullName>
        <inlineHelpText>Part Time Students with Disabilities</inlineHelpText>
        <label>PT Students w/ Disabilities</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Students_Limit_Age_4a__c</fullName>
        <defaultValue>26</defaultValue>
        <inlineHelpText>Complete a Limiting Age for student Dependents only if the Limiting Age for student Dependents exceeds age 26.</inlineHelpText>
        <label>Students Limit Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Students_Removal_Method_4a__c</fullName>
        <label>Students Removal Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>End of Calendar Month</fullName>
                </value>
                <value>
                    <fullName>On Birthday</fullName>
                </value>
                <value>
                    <fullName>End of Calendar Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Benefit Design Form</label>
    <nameField>
        <displayFormat>BDF-{00000}</displayFormat>
        <label>Benefit Design Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Design Form</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AIA_Config__c.object
<CustomObject>
    <fields>
        <fullName>Run__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Uncheck this field if the code block/method/trigger should not be executed.</description>
        <label>Run</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>It will be used to control execution of apex code block,methods or entire trigger itself.</description>
    <label>AIA Config</label>
</CustomObject>

classes/AIA_Test_BD_DeepClone_Utl.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
//=========================================================================================
// Date: 07/28/2017
// Developer: Goutham Rapolu
// Purpose: Used to create test class for AIA_BD_DeepClone Class
//
//=========================================================================================

@IsTest
public class AIA_Test_BD_DeepClone_Utl {
    
    //Creating Test Data for AIA_Config__c
    public static AIA_Config__c conf(){
        AIA_Config__c aiaCon =  new AIA_Config__c();
        aiaCon.Run__c = true;
        aiaCon.Name = 'BDTHelper.createBenefitDesignProduct';
        Insert aiaCon;
        Return aiaCon;
    }
    //Creating Test data for AIA_Benefit_Design_Form__c
    Public Static AIA_Benefit_Design_Form__c aiaBenf(String bend){
    AIA_Benefit_Design_Form__c aiaBDF = new AIA_Benefit_Design_Form__c();       
    aiaBDF.Benefit_Design__c = bend;        
    aiaBDF.Michelle_s_Law_4a__c = 'Yes';        
    aiaBDF.Child_Dependents_Limit_Age_4a__c =26;        
    aiaBDF.Michelle_s_Law_Waiver_4a__c = 'Yes';     
    aiaBDF.Students_Limit_Age_4a__c = 26;       
    aiaBDF.Child_Dependents_Removal_Method_4a__c = 'End of Calendar Month';     
    aiaBDF.Students_Removal_Method_4a__c = 'End of Calendar Month';     
    aiaBDF.Part_time_Students_with_Disabilities_4a__c ='No';      
    aiaBDF.Number_Of_Eligibles__c='10';
    //aiaBDF.External_Review_Processing_Comments__c = 'Hello';
    insert aiaBDF;
    Return aiaBDF;
    }
    
    Public Static AIA_Benefit_Design_Form__c aiaBenf1(){
    AIA_Benefit_Design_Form__c aiaBDF = new AIA_Benefit_Design_Form__c();       
    //aiaBDF.Benefit_Design__c = bend;        
    aiaBDF.Michelle_s_Law_4a__c = 'Yes';        
    aiaBDF.Child_Dependents_Limit_Age_4a__c =26;        
    aiaBDF.Michelle_s_Law_Waiver_4a__c = 'Yes';     
    aiaBDF.Students_Limit_Age_4a__c = 26;       
    aiaBDF.Child_Dependents_Removal_Method_4a__c = 'End of Calendar Month';     
    aiaBDF.Students_Removal_Method_4a__c = 'End of Calendar Month';     
    aiaBDF.Part_time_Students_with_Disabilities_4a__c ='No';      
    aiaBDF.Number_Of_Eligibles__c='10';
    //aiaBDF.External_Review_Processing_Comments__c = 'Hello';
    //insert aiaBDF;
    Return aiaBDF;
    }
    //Creating Test data for AIA_Benefit_Design__c
    Public Static AIA_Benefit_Design__c aiaBen(String imp, String acc, String benrf){
    AIA_Benefit_Design__c aiaBD = new AIA_Benefit_Design__c();
    aiaBD.Implementation__c = imp;
    aiaBD.Account__c = acc;
    aiaBD.Benefit_Request_Form__c = benrf;
    insert aiaBD;
    Return aiaBD;
    }

}