objects/Broker_Import_2_50__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Name of Entity</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Address Line</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City of Entity Address</description>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>County of Entity Address</description>
        <encryptionScheme>None</encryptionScheme>
        <label>County</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Entity Email Address</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entity_ID__c</fullName>
        <description>Corresponding Entity Identifier</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Entity ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <description>Type of the Entity (SB, AG, GP,FSP)</description>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>FSP</fullName>
                </value>
                <value>
                    <fullName>GP</fullName>
                </value>
                <value>
                    <fullName>SB</fullName>
                </value>
                <value>
                    <fullName>PDB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First Name when Entity Type is SB</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last Name when Entity type is SB</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Entity Phone Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State of Entity Address</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <description>Zipcode of Entity Address</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Zipcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <description>Holds the Broker Activity data</description>
    <label>Broker Import 2-50</label>
    <nameField>
        <displayFormat>BI2-50-{00000}</displayFormat>
        <label>Broker Import 2-50  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Import_2_50</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BrokerActivitytContactsProcess_TEST.cls
// this test class will run BrokerActivityContactProcess
// 7/21/2014 : Ashish Ojha / Tom Barrett

// 11/10/2014: Tom Barrett (TPB) - add call to TestUtil.createTestOpportunities()
// 04/03/2016 : Ashish Ojha updated running user profile 
//              from 'System Administrator' to 'System Administrator - Custom'

@isTest
public class BrokerActivitytContactsProcess_TEST{
    static testMethod void testBatch(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator - Custom']; 
                     User u = new User(Alias = 'standt', Email='spmss.process@carefirst.com.xxx', 
                     EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                     LocaleSidKey='en_US', ProfileId = p.Id, 
                     TimeZoneSidKey='America/Los_Angeles', UserName='spmss.process@carefirst.com.xxx');

            System.runAs(u) {
                TestUtil.createTestAccounts();                
                TestUtil.createTestOpportunities();    // 11/10/2014 TPB   
                TestUtil.createTestContacts();               
                TestUtil.CreateBrokerActivityData(); 
            }

            Test.StartTest(); 
            try {     
                BrokerActivityContactsProcess bacp = new BrokerActivityContactsProcess(null);
                database.executeBatch(bacp);
                Test.StopTest();
                System.assert(TRUE); //We should not get here
            }catch( exception e ){
                RETURN;   
            }                      
    }
     static testMethod void testBatch1(){
               
                Test.StartTest(); 
                Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
                User u = new User(Alias = 'standt', Email='spmss.process@carefirst.com.dev', 
                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US', ProfileId = p.Id, 
                TimeZoneSidKey='America/Los_Angeles', UserName='spmss.process@carefirst.com.dev');

                  System.runAs(u) {
                    String Query = 'Select id, Name, Account_Name__c, Address_Line__c, Last_Name__c, First_Name__c,City__c, County__c, Email__c, Entity_ID__c, Entity_Type__c, Phone__c, State__c, Zipcode__c FROM Broker_Import_2_50__c where Entity_Type__c = \'SB\' limit 1';
                    BrokerActivityContactsProcess brcp = new BrokerActivityContactsProcess(Query);
                    database.executeBatch(brcp);
                    Test.StopTest();
                    System.assert(TRUE); //We should not get here 
                }
                                  
        }
   /*     static testMethod void testBatch2(){
               
                Test.StartTest(); 
                Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
                User u = new User(Alias = 'standt', Email='spmss.process@carefirst.com.dev', 
                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US', ProfileId = p.Id, 
                TimeZoneSidKey='America/Los_Angeles', UserName='spmss.process@carefirst.com.dev');
                Broker_Import_2_50__c bkt = new Broker_Import_2_50__c();
                bkt.Entity_Id__c = '1211123';
                bkt.Account_Name__c = 'test';
                bkt.Entity_type__c ='AG';
                insert bkt;
                
                  System.runAs(u) {
                    String Query = 'Select id, Name, Account_Name__c, Address_Line__c, Last_Name__c, First_Name__c,City__c, County__c, Email__c, Entity_ID__c, Entity_Type__c, Phone__c, State__c, Zipcode__c FROM Broker_Import_2_50__c where Entity_Type__c = \'SB\' order by Name desc limit 1';
                    BrokerActivityContactsProcess brcp = new BrokerActivityContactsProcess(Query);
                    database.executeBatch(brcp);
                    Test.StopTest();
                    System.assert(TRUE); //We should not get here 
                }
                                  
        }
*/
}