objects/Broker_Import_2_50__c.object
<CustomObject>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box will be check after the record has been processed and inserted or updated to respective destination</description>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <description>Holds the Broker Activity data</description>
    <label>Broker Import 2-50</label>
    <nameField>
        <displayFormat>BI2-50-{00000}</displayFormat>
        <label>Broker Import 2-50  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Import_2_50</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BrokerActivityDeleteProcess_Schedule.cls
//========================================================================================
//      Date: 08/26/2014
// Developer: Ashish Ojha 
//   Purpose: This class is the BrokerActivityDeleteProcess scheduler class.
//=========================================================================================
//                                 Update History
// Date       Developer      Description
//=========================================================================================
//  
//=========================================================================================
global class BrokerActivityDeleteProcess_Schedule implements Schedulable{
    global void execute(SchedulableContext SC){
        SObject_Records_Delete_Process bc = new SObject_Records_Delete_Process('Broker_Import_2_50__c',True,'Processed__c = true');
        database.executeBatch(bc);
   }
}