objects/Broker_Import_2_50__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Name of Entity</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Address Line</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City of Entity Address</description>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>County of Entity Address</description>
        <encryptionScheme>None</encryptionScheme>
        <label>County</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_ID__c</fullName>
        <description>Corresponding Entity Identifier</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Entity ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <description>Type of the Entity (SB, AG, GP,FSP)</description>
        <label>Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>FSP</fullName>
                </value>
                <value>
                    <fullName>GP</fullName>
                </value>
                <value>
                    <fullName>SB</fullName>
                </value>
                <value>
                    <fullName>PDB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Entity Phone Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State of Entity Address</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <description>Zipcode of Entity Address</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Zipcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <description>Holds the Broker Activity data</description>
    <label>Broker Import 2-50</label>
    <nameField>
        <displayFormat>BI2-50-{00000}</displayFormat>
        <label>Broker Import 2-50  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Import_2_50</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BrokerActivityAccountsProcess_TEST.cls
// this is a test class for BrokerActivityAccountsProcess
// 7/21/2014 :Ashish ojha / Tom Barrett
// 04/03/2016 : Ashish Ojha updated running user profile 
//              from 'System Administrator' to 'System Administrator - Custom'
// 12/30/2016  : Ashish Added TestUtil.createDynamicCodeDataStore() 

@isTest
public class BrokerActivityAccountsProcess_TEST{
    
    static testMethod void testBatch(){ 
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator - Custom']; 
                     User u = new User(Alias = 'standt', Email='spmss.process@carefirst.com.xxx', 
                     EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                     LocaleSidKey='en_US', ProfileId = p.Id, 
                     TimeZoneSidKey='America/Los_Angeles', UserName='spmss.process@carefirst.com.xxx');

            System.runAs(u) {
                TestUtil.createTestAccounts();
                TestUtil.CreateBrokerActivityData(); 
                TestUtil.createDynamicCodeDataStore();   
            }
        
            Test.StartTest(); 
            try {     
                BrokerActivityAccountsProcess brap = new BrokerActivityAccountsProcess(null);
                database.executeBatch(brap);
                Test.StopTest();
                             // veryfiy that the items got upserted
                System.assert(TRUE); //We should not get here 
            }catch( exception e ){
                RETURN;   
            }                      
        }
     static testMethod void testBatch1(){
                Test.StartTest(); 
 // Query used by the batch job but we are only selecting AG for this test           
                String Query = 'Select id, Name, Account_Name__c, Address_Line__c, City__c, County__c, Entity_ID__c, Entity_Type__c, Phone__c, State__c, Zipcode__c FROM Broker_Import_2_50__c where Entity_Type__c = \'AG\' limit 1';                        
                BrokerActivityAccountsProcess brap = new BrokerActivityAccountsProcess(Query);
                database.executeBatch(brap);
                Test.StopTest();
                System.assert(TRUE); //We should not get here 
                                  
        }
          
}