objects/Case.object
<CustomObject>
    <fields>
        <fullName>Broker_Status__c</fullName>
        <description>This formula field is derived from Status Field and will set customer status accordingly. If status is In-Queue, it will set it to open, if closed it will set it to closed and will set it to In-Progress for all other status</description>
        <formula>IF(ISPICKVAL(Status,'In-Queue'), 'Open',  IF(ISPICKVAL(Status,'Closed'), 'Closed', 'In-Progress') )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to Group Table to extract Group Info</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <description>Enter Subscriber ID</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Subscriber ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Group__c.object
<CustomObject>
    <description>This object will hold a Groups Relationship to its respective agent and FSP or GP. This table is only going to be used to establish this relationship which will be used in the Case Object</description>
    <label>Group-Agent</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups-Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Communities_Case_Model_Test.cls
@isTest
private class Communities_Case_Model_Test{

    // This test method can access private members of another class 
    // that are annotated with @TestVisible.
    static testmethod void Case_Model_Test() {
        Communities_Case_Model.CaseRecord  crec = new Communities_Case_Model.CaseRecord();
      crec.CaseNumber='cnumb';     // For Case Number
      crec.Subject ='Test Subject';        // For Subject    
      crec.GroupNameID='Gid';    // For Group__c
      crec.SubscriberID='sid';   // For Subscriber_ID__c
      crec.Status='status';         // For Broker_Status__c
      crec.Createdon= system.now();    // For CreatedDate
      crec.cid=null;                // For case ID
      crec.Origin='origin';         // For Case Origin
      crec.Closedon=system.now();     // Resolution Reson posted date/case closed date

        
        // Access private inner class
        Communities_Case_Model.HomePageSummary emp = 
            new Communities_Case_Model.HomePageSummary ();
            
      emp.myCases=1;             //used to get all Mycases 
      emp.openCases=1;           //used to get all Open cases 
      emp.INprogressCases=1;
      emp.closedCases=1;
      
      emp.AgencyCases=1;
      emp.AopenCases=1;
      emp.AresolvedCases=1;
      emp.AclosedCases=1; 
      // For My Cases Section 
      emp.caseList= new List<Communities_Case_Model.CaseRecord>{crec};
      emp.mycaseList=new List<Communities_Case_Model.CaseRecord>{crec};               //To get all list of case related to particular user
      emp.openCasesList= new List<Communities_Case_Model.CaseRecord>{crec};
      emp.INprogressCasesList= new List<Communities_Case_Model.CaseRecord>{crec};
      emp.closedCasesList= new List<Communities_Case_Model.CaseRecord>{crec};
      //For Agency Cases Section
      emp.AgencyCasesList= new List<Communities_Case_Model.CaseRecord>{crec}; 
      emp.AopenCasesList= new List<Communities_Case_Model.CaseRecord>{crec};
      emp.AINprogressCasesList= new List<Communities_Case_Model.CaseRecord>{crec};
      emp.AclosedCasesList= new List<Communities_Case_Model.CaseRecord>{crec};
      emp.isShowAgencyCasses= true;
      emp.isShowMyCasses= true;
      emp.user=null;    
        
        Communities_Case_Model.dummyMethod();
    }
    
    // This test method can throw private exception defined in another class
    
    
   
}