objects/Case.object
<CustomObject>
    <fields>
        <fullName>Broker_Service_Team__c</fullName>
        <description>Enter which service team the case belongs to</description>
        <label>Broker Service Team</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SLA_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Broker Sales MD</fullName>
                </value>
                <value>
                    <fullName>Broker Sales 4</fullName>
                </value>
                <value>
                    <fullName>Retro activity Request</fullName>
                </value>
                <value>
                    <fullName>SBC Project</fullName>
                </value>
                <value>
                    <fullName>BCS Specialist</fullName>
                </value>
                <value>
                    <fullName>Small Medium Group</fullName>
                </value>
                <value>
                    <fullName>Team Royal</fullName>
                </value>
                <value>
                    <fullName>Team Indigo</fullName>
                </value>
                <value>
                    <fullName>Team Ocean</fullName>
                </value>
                <value>
                    <fullName>Team Sapphire</fullName>
                </value>
                <value>
                    <fullName>Team Sky</fullName>
                </value>
                <value>
                    <fullName>Team Teal</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Broker Escalation</fullName>
                </value>
                <value>
                    <fullName>Elite</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>Preferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facets_Category__c</fullName>
        <label>Facets Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Facets_Subject__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ACYB - CYBERATTACK</fullName>
                </value>
                <value>
                    <fullName>BF01 - BlueFund set up issues</fullName>
                </value>
                <value>
                    <fullName>BF03 - BF link missing on My Account</fullName>
                </value>
                <value>
                    <fullName>BF05 - Blue Rewards Inquiries</fullName>
                </value>
                <value>
                    <fullName>BF07 - Complaint about the vendor</fullName>
                </value>
                <value>
                    <fullName>BF09 - Unable to loc grp/vendor systm</fullName>
                </value>
                <value>
                    <fullName>BF11 - Unable to loc mbr/vendor systm</fullName>
                </value>
                <value>
                    <fullName>BF13 - Welcome Kit Inquiry/HSA only</fullName>
                </value>
                <value>
                    <fullName>BP01 - Communities</fullName>
                </value>
                <value>
                    <fullName>BP02 - Gen Broker Portal Inquiry</fullName>
                </value>
                <value>
                    <fullName>BP03 - Gen Employee Portal Inquiry</fullName>
                </value>
                <value>
                    <fullName>BP04 - Gen Hub Inquiry</fullName>
                </value>
                <value>
                    <fullName>BP05 - Group Set-Up</fullName>
                </value>
                <value>
                    <fullName>BP06 - Provisioning</fullName>
                </value>
                <value>
                    <fullName>BP07 - Quoting</fullName>
                </value>
                <value>
                    <fullName>BSA1 - Prospect Inquiry</fullName>
                </value>
                <value>
                    <fullName>BSA2 - File Update Inquiry</fullName>
                </value>
                <value>
                    <fullName>BSA3 - BOR Inquiry</fullName>
                </value>
                <value>
                    <fullName>BSA4 - Transferred to Sales Rep</fullName>
                </value>
                <value>
                    <fullName>BSA5 - Transferred to another dept</fullName>
                </value>
                <value>
                    <fullName>BSQ1 - Quote-Off Cycle Request</fullName>
                </value>
                <value>
                    <fullName>BSQ2 - Quote-Renewal Request</fullName>
                </value>
                <value>
                    <fullName>BSQ3 - Quote-New Business Request</fullName>
                </value>
                <value>
                    <fullName>BSQ4 - Quote-Late Exception Request</fullName>
                </value>
                <value>
                    <fullName>BSQ5 - Quote-Alternative</fullName>
                </value>
                <value>
                    <fullName>BSQ6 - Quote-On Exchange</fullName>
                </value>
                <value>
                    <fullName>BSQ7 - Transferred to another dept</fullName>
                </value>
                <value>
                    <fullName>DC01 - Processed Correctly</fullName>
                </value>
                <value>
                    <fullName>DC02 - Processed Incorrectly</fullName>
                </value>
                <value>
                    <fullName>DC03 - Pended Claim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facets_Status__c</fullName>
        <description>Enter Facets case Status</description>
        <inlineHelpText>The Status of case in facets</inlineHelpText>
        <label>Facets Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facets_Subject__c</fullName>
        <label>Facets Subject</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACYB - CYBERATTACK</fullName>
                </value>
                <value>
                    <fullName>BRCP - CareFirst Portals</fullName>
                </value>
                <value>
                    <fullName>BRSA - Sales Assistance</fullName>
                </value>
                <value>
                    <fullName>BRSQ - Sales Quote</fullName>
                </value>
                <value>
                    <fullName>DCLM - Dental Claims</fullName>
                </value>
                <value>
                    <fullName>MAPP-M Appeal</fullName>
                </value>
                <value>
                    <fullName>MAUT-M Auth/Referral Inquiry</fullName>
                </value>
                <value>
                    <fullName>MBCC - Credit Card Inquiry</fullName>
                </value>
                <value>
                    <fullName>MBEI - EBill Inquiry</fullName>
                </value>
                <value>
                    <fullName>MBEN-M Benefits</fullName>
                </value>
                <value>
                    <fullName>MBFA - M BlueFund Administration</fullName>
                </value>
                <value>
                    <fullName>MBII - Invoice Inquiry</fullName>
                </value>
                <value>
                    <fullName>MBIL-M Billing</fullName>
                </value>
                <value>
                    <fullName>MBMP - Missing Payment</fullName>
                </value>
                <value>
                    <fullName>MBPA - Payment Arrangement</fullName>
                </value>
                <value>
                    <fullName>MBRR - Request to Reinstate</fullName>
                </value>
                <value>
                    <fullName>MBTI - Termination Inquiry</fullName>
                </value>
                <value>
                    <fullName>MCAC-M Credit &amp; Collection</fullName>
                </value>
                <value>
                    <fullName>MCDH-M CDH</fullName>
                </value>
                <value>
                    <fullName>MCHK-M Check Inquiry</fullName>
                </value>
                <value>
                    <fullName>MCLM-M Claim Status</fullName>
                </value>
                <value>
                    <fullName>MCMP-M Complaint Plan/Service</fullName>
                </value>
                <value>
                    <fullName>MCOB-M COB</fullName>
                </value>
                <value>
                    <fullName>MCOR - M Correspondence</fullName>
                </value>
                <value>
                    <fullName>MDED-M Deductible</fullName>
                </value>
                <value>
                    <fullName>MDEM-M Demographics</fullName>
                </value>
                <value>
                    <fullName>MDIQ-M Duplicate Inquiry</fullName>
                </value>
                <value>
                    <fullName>MDOC-M Document Request</fullName>
                </value>
                <value>
                    <fullName>MELG-M Eligibility</fullName>
                </value>
                <value>
                    <fullName>MENR - Enrollment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Group ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to tie a case to a 2-50 Group Account based on Facets Account Number. this is used in the back end for 360 degree view of case</description>
        <label>2-50 Group Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <infoMessage>Please enter name or Group Id and Check "All fields" to find the Group you are looking for</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Group Cases(2-50)</relationshipLabel>
        <relationshipName>Group_Cases_2_50</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Group_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>To be used when Group not found in Group Name lookup</inlineHelpText>
        <label>New Group ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Internal Reason Code</description>
        <label>Internal Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>C001-Closed First Contact</fullName>
                </value>
                <value>
                    <fullName>C002-Questions(s) Answered</fullName>
                </value>
                <value>
                    <fullName>C003-Adjustment Completed</fullName>
                </value>
                <value>
                    <fullName>C004-Materials/Documents Sent</fullName>
                </value>
                <value>
                    <fullName>C005-Information Received</fullName>
                </value>
                <value>
                    <fullName>C006-Information Not Received</fullName>
                </value>
                <value>
                    <fullName>C007-Letter Sent</fullName>
                </value>
                <value>
                    <fullName>C008-E-mail Response</fullName>
                </value>
                <value>
                    <fullName>C009-Executive Level Response</fullName>
                </value>
                <value>
                    <fullName>C010-No Response Necessary</fullName>
                </value>
                <value>
                    <fullName>C011-Returned Call</fullName>
                </value>
                <value>
                    <fullName>C012-No Record of Inquiry</fullName>
                </value>
                <value>
                    <fullName>C013-Received in Central Appeals</fullName>
                </value>
                <value>
                    <fullName>C014-Referred to Carefirst.com</fullName>
                </value>
                <value>
                    <fullName>C100-Other</fullName>
                </value>
                <value>
                    <fullName>CO01-Approved Exception</fullName>
                </value>
                <value>
                    <fullName>CO03-Billing discrepancies</fullName>
                </value>
                <value>
                    <fullName>CO06-Claim rejected in error</fullName>
                </value>
                <value>
                    <fullName>CO09-Corrected claim received</fullName>
                </value>
                <value>
                    <fullName>CO12-Enrollment discrepancies</fullName>
                </value>
                <value>
                    <fullName>CO15-EOB received</fullName>
                </value>
                <value>
                    <fullName>CO18-No Authorization of file</fullName>
                </value>
                <value>
                    <fullName>CO21-PAR Medical Rev-pay rej lines</fullName>
                </value>
                <value>
                    <fullName>CO24-Waiting period removed</fullName>
                </value>
                <value>
                    <fullName>CO25-CF Primary/newly identified</fullName>
                </value>
                <value>
                    <fullName>CO26-CF Secondary/newly identified</fullName>
                </value>
                <value>
                    <fullName>CO27-CF Primary/Prev identified</fullName>
                </value>
                <value>
                    <fullName>CO28-CF Secondary/Prev identified</fullName>
                </value>
                <value>
                    <fullName>CO29-Other, See Task Notes</fullName>
                </value>
                <value>
                    <fullName>CU01-Claim paid correctly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_Reason__c</fullName>
        <description>Enter External Notes that is to be viewed by external users</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Resolution Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FCI_SubmitCaseToFacetsController.cls
/********************************************************************************  
 *  Class            : FCI_SubmitCaseToFacetsController
 *  Author           : Ken Gill
 *  Version History  : 1.0
 *  Creation         : 09/18/15
 *  Description      : This controller will invoke the FCI_FacetsService.createCase service
 *                     
 *                                         
 ********************************************************************************
 *---------------------------------------------------------------------------------------------
 * Date        Developer        Description
 *---------------------------------------------------------------------------------------------
 *
 * 09/18/15 Ken Gill          Initial controller that supports the Submit To Facets custom button added to 
 *                            the Case page layout for Project 51 - Facets Integration
 ********************************************************************************/
 
public with sharing class FCI_SubmitCaseToFacetsController {

    public Case caseObject { get;set; }

   /*
    * The constructor retrieves fields required to build a CreateCase request which includes related objects Contact, Owner and CaseComments
    * The retrieved comments exclude comments received via updates from Facets based on notes added in that system to avoid duplicating those when the 
    * request is sent to Facets. 
    */
    public FCI_SubmitCaseToFacetsController(ApexPages.StandardController stdController) {
        /*
        caseObject =
            [SELECT Id, Group_ID__c,Facets_Category__c, 
                    Facets_Status__c, Facets_Subject__c, 
                    Reason__c, 
                    Subject, Description, 
                    Status, 
                    Origin,
                    Resolution_Reason__c,
                    Group_Name__c,
                    New_Group_ID__c,
                    Broker_Service_Team__c,
                    Broker_ID__c,
                    SLA_Category__c,
                    Facets_Satisfaction_Level__c,
                    Market_Segment__c,
                    Contact.LastName, Contact.FirstName,
                    Contact.Salutation,Contact.MailingCity,
                    Contact.MailingState, Contact.MailingCountry,
                    Contact.MailingPostalCode, Contact.MailingStreet,
                    Contact.Phone, Contact.Fax,Contact.Email,
                    OwnerId, Owner.Type,
                    CreatedDate,
                    ClosedDate,
                    Received_Date__c,
                    LastModifiedDate, 
                    Facets_case_ID__c,
                    (SELECT Id, IsPublished,LastModifiedDate, CreatedBy.FirstName, CreatedBy.LastName, CommentBody FROM CaseComments 
                            WHERE NOT ( CreatedBy.FirstName = 'Facets' AND CreatedBy.LastName = 'Integration') 
                            ORDER BY LastModifiedDate ASC)        
            FROM Case 
             WHERE ID =: stdController.getRecord().Id];
             */
         caseObject = FCI_Util.getCaseDetailsById(stdController.getRecord().Id);
    }

    /*
     * This function handles the event that occurs after the "Submit to Facets"
     * button is clicked.
     * Before submitting the request, a input check is made to ensure
     * a. The case is in a allowed status for submission to Facets
     * b. Required parameters are input on the case detail page.
     *
     * If there are input validation errors, appropriate messages are added to ApexPage and displayed to the user for corrective action
     */
    public PageReference submitCaseToFacets() {
        PageReference pageRef = null;
        try {
            // Enforce preconditions: 
            // SubmitToFacets only allowed if not submitted before (no FacetsCaseId assigned)
            // and case status = Assigned, Awaiting or In Progress
            // Note: for case status=Closed, the FCI_CaseTriggerHandler takes care of submitting the case to Facets for archival purposes
            /*
            Boolean preConditionsMet = true;
                // NOTE: caseObject.Status is a picklist type. Comparing Picklist values requires '==' operator. The .equals() method does not return correct results
            if( !( caseObject.Status == 'Assigned' || 
                    caseObject.Status == 'Awaiting' || 
                    caseObject.Status == 'In Progress' ||
                    caseObject.Status == 'Routed To Other Department' ||
                    caseObject.Status == 'Routed To Management'                 
            ) ) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Only a case with Status=Assigned, Awaiting, In Progress, Routed To Other Department or Routed to Management can be submitted to Facets'));
                preConditionsMet = false;
            }
            if( !String.isBlank(caseObject.Facets_case_ID__c)) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Case has already been submitted to Facets. Facets case id=' + caseObject.Facets_case_ID__c));
                preConditionsMet = false;
            }
            if(!preConditionsMet) {
                System.debug(ApexPages.getMessages());
                pageRef=null; 
                return pageRef;
            }    
            */              
            // Create the FacetsCreateCase request 
            FCI_CreateCaseRequest request = new FCI_CreateCaseRequest(caseObject); 
            
            // Validate request has all required fields to create a Facets case
            FCI_Validation validation = request.validateRequest();
            if( ! validation.isValid) {
                ApexPages.Message msg = 
                        new ApexPages.Message(ApexPages.Severity.ERROR, validation.getValidationMessagesAsHTML());
                ApexPages.addMessage(msg);
                System.debug(ApexPages.getMessages());
                pageRef=null; 
                return pageRef;                 
            }
            
            // Send request to FCI_FacetsService
            FCI_CreateCaseResponse response = FCI_FacetsService.send_FCI_CreateCaseRequest(request);
            
            if( response.isValid()) { 
                // Redirect the user back to the case detail page if no errors
                pageRef = new PageReference('/' + caseObject.Id);
                pageRef.setRedirect(true);
            } else {
                String responseString = 'The Facets system could not accept the case submission. Details:<br>' +
                                        'Status Code=' + response.statusCode + '<br>' +
                                        'Status =' + response.status + '<br>' +
                                        'Details: ' + response.statusDescription;                       
                ApexPages.Message msg = 
                        new ApexPages.Message(ApexPages.Severity.ERROR, responseString);
                ApexPages.addMessage(msg);
                System.debug(ApexPages.getMessages());
                pageRef=null; 
                return pageRef;                                         
            }           
        } catch (Exception e) {
            pageRef = null;
            ApexPages.addMessages(e);
            System.debug(ApexPages.getMessages());
        }
        return pageRef;
    }
    
}