objects/Case.object
<CustomObject>
    <fields>
        <fullName>Broker_Status__c</fullName>
        <description>This formula field is derived from Status Field and will set customer status accordingly. If status is In-Queue, it will set it to open, if closed it will set it to closed and will set it to In-Progress for all other status</description>
        <formula>IF(ISPICKVAL(Status,'In-Queue'), 'Open',  IF(ISPICKVAL(Status,'Closed'), 'Closed', 'In-Progress') )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Communitie_Group_ID__c</fullName>
        <formula>IF( ISBLANK( Group_ID__c ) , New_Group_ID__c , Group_ID__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Communitie Group ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Group ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to Group Table to extract Group Info</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resolution_Reason_Posted_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Resolution Reason Posted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <description>Enter Subscriber ID</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Subscriber ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Group_ID__c</fullName>
        <description>This field will hold the Group ID</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Group ID</label>
        <length>44</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>This object will hold a Groups Relationship to its respective agent and FSP or GP. This table is only going to be used to establish this relationship which will be used in the Case Object</description>
    <label>Group-Agent</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups-Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Broker_Role__c</fullName>
        <label>Broker Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Broker Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SBU_MyCasesPageController.cls
/* =========================================================================================
 * Date         : 08/01/2016
 * Developer    : Laveen Kattela
 * Purpose      : This Controller is for SBU_Communities_My_Cases_Page. It handles all the controller part of that page. 
 *                It has  My cases And Agency Cases Tab  
 *                1. "MY CASES"  - Which only visiable's to Broker Agent & Asiistant    -  Filters logic in place, you can filter the cases based on input value on the particular field  
 *                2. "AGENCY CASES" - (visiable to  Assistant)  - Filters logic in place
 *                3.  Eight fields are displayed for the quick view on the page
 *                   
 *=========================================================================================
 * Update History
 *  ---------------
 * Date       Developer         Description
 *===========+============+================================================================
 * 08/01/16   |  Ashish            | Initial Version 
 * 08/15/16   |  Laveen Kattela   | Added logic for My cases, Agency Cases & fields.                                     
 *===========+============+================================================================
 */
global with sharing class SBU_MyCasesPageController{
    
    //Query to get all case fields
    public final static String CASE_QUERY_FIELDS ='SELECT CaseNumber,ClosedDate,CreatedById,Communitie_Group_ID__c,Group__c,Group__r.Group_id__c,CreatedDate,Origin,IsClosed,OwnerId,Priority,Broker_Status__c,Resolution_Reason_Posted_Date__c,Reason,Status,Subject,Type,Group_ID__c,Subscriber_ID__c ';
    
    @RemoteAction
   global static Communities_Case_Model.HomePageSummary getCaseSummary() {
        Communities_Case_Model.HomePageSummary cm = new Communities_Case_Model.HomePageSummary();
        //Query user record to know if he is assitant or not - to show the user accordingly  to his role
        User user = [Select id, Broker_Role__c,ContactId from user where id =:UserInfo.getUserId() ];
        List<Communities_Case_Model.CaseRecord> caseRecords = new List<Communities_Case_Model.CaseRecord>();
        //checking the user based on their Role if he is assistant
        if(user.Broker_Role__c != null && user.Broker_Role__c == 'Assistant')
        {
                cm.isShowAgencyCasses = true;       //Shows the Agency cases - Making flag as true based on thrie role
                cm.isShowMyCasses = true;
                id uid = userinfo.getUserId();
                id conid = user.ContactId;                
                String QueryString = CASE_QUERY_FIELDS+' From Case where contactid = :conId ORDER BY CreatedDate DESC ';   //query the case with where claues & owner id records             
                List<Case> myclist = Database.query(QueryString);
                //created a list called Myclist which hold the values to pass to visual force page
                //Getting Values for For "My cases" Section 
                cm.caseList = Communities_HomePage.getCaseModelRecords(myclist);
                //storing that to List<CaseRecords> CaseList declared in Case_model class         
                cm.mycaseList = Communities_HomePage.getCaseModelRecords(myclist); 
                //Getting vaules for Agency Cases section
                List<Case> agentclist = Database.query(CASE_QUERY_FIELDS+' From Case ORDER BY CreatedDate DESC ');      // Query the case from case object with order by
                cm.AgencyCasesList = Communities_HomePage.getCaseModelRecords(agentclist); 
        }
        //If the user role is Broker Agent
        if(user.Broker_Role__c != null && user.Broker_Role__c == 'Broker Agent')
        {
            if(user.ContactId != null)
            {
                cm.isShowAgencyCasses = false;                                                //Setting the flag to false for agency cases
                cm.isShowMyCasses = true;                                                     //setting the flag to true for my cases
                String QueryString = CASE_QUERY_FIELDS+' From Case ORDER BY CreatedDate DESC';  //quering the records from the case 
                List<Case> myclist = Database.query(QueryString);                               //storing that list of records in Myclist
                cm.caseList = Communities_HomePage.getCaseModelRecords(myclist);             //Assigning that list to CaseList
                cm.mycaseList = Communities_HomePage.getCaseModelRecords(myclist);     
            
            }
        
        }        
        
        return cm;
     
   }
    global static String getContacts() {
     return JSON.serialize([select id, CaseNumber,Subject,Group_ID__c,Communitie_Group_ID__c, Subscriber_Id__c ,Status , createddate from case  ]);
   }
}