objects/Case.object
<CustomObject>
    <fields>
        <fullName>Broker_Status__c</fullName>
        <description>This formula field is derived from Status Field and will set customer status accordingly. If status is In-Queue, it will set it to open, if closed it will set it to closed and will set it to In-Progress for all other status</description>
        <formula>IF(ISPICKVAL(Status,'In-Queue'), 'Open',  IF(ISPICKVAL(Status,'Closed'), 'Closed', 'In-Progress') )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Communitie_Group_ID__c</fullName>
        <formula>IF( ISBLANK( Group_ID__c ) , New_Group_ID__c , Group_ID__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Communitie Group ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Group ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will look up to Group Table to extract Group Info</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resolution_Reason_Posted_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Resolution Reason Posted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subscriber_ID__c</fullName>
        <description>Enter Subscriber ID</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Subscriber ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Group_ID__c</fullName>
        <description>This field will hold the Group ID</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Group ID</label>
        <length>44</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>This object will hold a Groups Relationship to its respective agent and FSP or GP. This table is only going to be used to establish this relationship which will be used in the Case Object</description>
    <label>Group-Agent</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups-Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Broker_Role__c</fullName>
        <label>Broker Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Broker Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Communities_HomePage.cls
/* =========================================================================================
 * Date         : 08/01/2016
 * Developer    : Laveen Kattela
 * Purpose      : This Apex controller is for Communities_Homepage(VF Page). This class holds the total functionality of "community Home Page" body section.
 *                
 *                1.It has logic for "MY CASES" section to left side      -  logic for Open Cases , Resolved Cases & Closed Cases 
 *                2.It has logic for "AGENCY CASES" section to Right side  - logic for Open Cases , Resolved Cases & Closed Cases 
 *                3.It has Logic for "Recent Cases" section grid view - when the User logged in, it defaults to shows the Recently created Cases.
 *                4.It has Logic behind the The Grid View Contains list of fields to display - Case Number,Subject ,Group Name ID,Subscriber ID,Status & Created on.
 *                5.It has Logic behind the Click on "Case Number" or "Subject" Hyper link navigate to "Case Detail page"
 *                  
 *=========================================================================================
 * Update History
 *  ---------------
 * Date       Developer         Description
 *===========+============+================================================================
 * 08/01/16   |  Laveen Kattela    | Initial Version                                          
 *===========+============+================================================================
 */

global with sharing class Communities_HomePage {
    //Query to get all case fields
    public final static String CASE_QUERY_FIELDS ='SELECT CaseNumber,ClosedDate,CreatedById,Communitie_Group_ID__c,CreatedDate,Origin,IsClosed,OwnerId,Group__r.Group_id__c,Priority,Broker_Status__c,Resolution_Reason_Posted_Date__c,Group__c,Reason,Status,Subject,Type,Group_ID__c,Subscriber_ID__c ';
   
    // Remote action to get the data Dynamcially loaded at one go when ones the user entered into community
    @RemoteAction
    global static Communities_Case_Model.HomePageSummary getCaseSummary() {
    
        Communities_Case_Model.HomePageSummary cm = new Communities_Case_Model.HomePageSummary();
        //Query user record to know if he is assitant or not - to show the user accordingly  to his role
        User user = [Select id, Broker_Role__c,ContactId from user where id =:UserInfo.getUserId() ];
        List<Communities_Case_Model.CaseRecord> caseRecords = new List<Communities_Case_Model.CaseRecord>();
        
        //checking the user based on their Role if he is assistant
        if(user.Broker_Role__c != null && user.Broker_Role__c == 'Assistant')
        {
            if(user.ContactId != null)              //Checking user Contact exist or not
            {
                cm.isShowAgencyCasses = true;       //Shows the Agency cases - Making flag as true based on thrie role
                cm.isShowMyCasses = true;           //Shows the My cases - Making flag as true based on thrie role   
                // Recent cases : on load to show recent case for the Assistant.
               
                //getCaseRecords(cm); 
                //Getting the information of logged in User id 
                id uid = userinfo.getUserId();
                id conid = user.ContactId;
                String QueryString = CASE_QUERY_FIELDS+' From Case where Contactid = : conid ORDER BY CreatedDate DESC ';   //query the case with where claues & owner id records             
                List<Case> myclist = Database.query(QueryString);                                                      //created a list called Myclist which hold the values to pass to visual force page
                //Getting Values for For "My cases" Section 
                cm.caseList = getCaseModelRecords(myclist);                                                             //Getting all list of cases and storing that to List<CaseRecords> CaseList declared in Case_model class         
                cm.mycaseList = getCaseModelRecords(myclist);                                                           //Getting all list of user cases and storing that to List<CaseRecords> mycaseList 
                cm.openCasesList = getCaseModelRecords(myclist,'Open');                                                 //Getting all list of Open cases and storing that to List<CaseRecords> openCasesList 
                cm.INprogressCasesList = getCaseModelRecords(myclist,'In-Progress');                                    //Getting all list of In-Progress cases and storing that to List<CaseRecords> InprogressList 
                cm.closedCasesList = getCaseModelRecords(myclist,'Closed');                                             //Getting all list of Closed cases and storing that to List<CaseRecords> ClosedCasesList 
                
                //Getting vaules for Agency Cases section
                List<Case> agentclist = Database.query(CASE_QUERY_FIELDS+' From Case ORDER BY CreatedDate DESC ');      // Query the case from case object with order by
                cm.AgencyCasesList = getCaseModelRecords(agentclist);                                                   // Getting all list of Agency cases and storing that to List<CaseRecords> AgencyCasesList 
                cm.AopenCasesList = getCaseModelRecords(agentclist,'Open');                                             //Getting all list of open Agency cases and storing that to List<CaseRecords> AopenCasesList 
                cm.AINprogressCasesList = getCaseModelRecords(agentclist,'In-Progress');                                //Getting all list of In-progress Agency cases and storing that to List<CaseRecords> AInprogressCasesList 
                cm.AclosedCasesList = getCaseModelRecords(agentclist,'Closed');                                         //Getting all list of Closed Agency cases and storing that to List<CaseRecords> AclosedCasesList 
            }
        
        }
        
        //If the user role is Broker Agent
        if(user.Broker_Role__c != null && user.Broker_Role__c == 'Broker Agent')
        {
            if(user.ContactId != null)
            {
                cm.isShowAgencyCasses = false;                                                //Setting the flag to false for agency cases
                cm.isShowMyCasses = true;                                                     //setting the flag to true for my cases
                // Recent cases : on load to show recent case for the Broker Agent.
                //Set<id> cids = getRecentCaseVeiwRecords();              
               
                getCaseRecords(cm);            //Calling the method - where all the list of open, in-progess & closed cases from case object for that particular user 
            
            }
        
        }        
        
        return cm;
    }
    
    global static List<Communities_Case_Model.CaseRecord> getCaseModelRecords(List<Case> clist) {
        List<Communities_Case_Model.CaseRecord> caseRecords= new List<Communities_Case_Model.CaseRecord>();
        if(clist != null && clist.size()>0){
            for(Case cobj: clist ){
                caseRecords.add(getCaseModelRecord(cobj));
            }       
        }
        return caseRecords;
    }
    global static List<Communities_Case_Model.CaseRecord> getCaseModelRecords(List<Case> clist,String Status) {
        List<Communities_Case_Model.CaseRecord> caseRecords= new List<Communities_Case_Model.CaseRecord>();
        if(clist != null && clist.size()>0){
            for(Case cobj: clist ){
                if(cobj.Broker_Status__c == Status)
                {                   
                    caseRecords.add(getCaseModelRecord(cobj));
                }
            }       
        }
        return caseRecords;
    }
    
    
    public static void getCaseRecords(Communities_Case_Model.HomePageSummary  cm){
    
            String QueryString = CASE_QUERY_FIELDS+' From Case ORDER BY CreatedDate DESC';  //quering the records from the case 
            List<Case> myclist = Database.query(QueryString);                               //storing that list of records in Myclist
            cm.caseList = getCaseModelRecords(myclist);                                     //Assigning that list to CaseList
            cm.mycaseList = getCaseModelRecords(myclist);                                   //Assigning that to MycaseList
            cm.openCasesList = getCaseModelRecords(myclist,'Open');                         // Getting all the open cases and storing that to OpenCasesList
            cm.INprogressCasesList = getCaseModelRecords(myclist,'In-Progress');            // Getting all the In-progress cases and storing that to INprogressCasesList 
            cm.closedCasesList = getCaseModelRecords(myclist,'Closed');                     // Getting all the Closed cases and storing that to closedCasesList 
    }
    
    
    
    
    //Method to get the case records by passing the Case obj as parameter 
    public static Communities_Case_Model.CaseRecord getCaseModelRecord(Case cobj) {
        Communities_Case_Model.CaseRecord cr = new Communities_Case_Model.CaseRecord();   //Creating the instants
        cr.CaseNumber = cobj.CaseNumber;                                                  //Assigning the CaseNumber field API to "CaseNumber" declared in Case model class(CaseRecord - class)
        cr.Subject = cobj.Subject;                                                        //Assigning the Subject field  to "Subject " declared in Case model class(CaseRecord - class)
        cr.Status = cobj.Broker_Status__c;                                                //Assigning the Broker_Status__c field  to "Status " declared in Case model class(CaseRecord - class)
        cr.Createdon = cobj.CreatedDate;                                                  //Assigning the CreatedDate field  to "Createdon " declared in Case model class(CaseRecord - class)
        //cr.GroupNameID = cobj.Group__r.Group_id__c;                                                   //Assigning the Group__c field  to "GroupNameID " declared in Case model class(CaseRecord - class)
        cr.SubscriberID= cobj.Subscriber_ID__c;                                           //Assigning the Subscriber_ID__c field  to "SubscriberID" declared in Case model class(CaseRecord - class)
        cr.cid = cobj.id;                                                                 //Assigning the Case ID field  to "Cid" declared in Case model class
        cr.Origin = cobj.Origin;
        cr.Closedon = cobj.Resolution_Reason_Posted_Date__c;                              //Assigning the Resolution_Reason_Posted_Date__c field  to "Closedon " declared in Case model class(CaseRecord - class)
        cr.GroupNameID = cobj.Communitie_Group_ID__c;
        return cr;                                                                        // return the cr
        
    
    }
   
    
}