objects/CIAM_Import_Table__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Agent_ID__c</fullName>
        <description>This will be the concatination of Agency federal tax id and Agent SSN. this field needs to be unique too</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency_Agent_ID</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Agency Name</label>
        <length>99</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agent_First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Agent_First Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agent_ID__c</fullName>
        <description>this field will hold the Agent's entity Id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Agent ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agent_Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Agent Last Name</label>
        <length>99</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agent_Middle_Initial__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Agent Middle Initial</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agent_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Agent Name</label>
        <length>99</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Broker_Title__c</fullName>
        <label>Broker Title</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>General Broker</fullName>
                </value>
                <value>
                    <fullName>Direct Broker</fullName>
                </value>
                <value>
                    <fullName>Principal Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Federation_ID__c</fullName>
        <description>This field holds Federation ID/GUID provided by CIAM</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Federation ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>User ID</label>
        <length>99</length>
        <type>Text</type>
    </fields>
    <description>This will be a table to store CIAM data for the initial piece of user provisioning where data loaded into this table will be used to create the Community User contact and Community User records.</description>
    <label>CIAM Import Table</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CIAM Import Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIAM Import Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Agency_Agent_Id__c</fullName>
        <description>this is the concatination of Agency Id and Agent Id</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Agency Agent Id</label>
        <length>22</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Agent_ID__c</fullName>
        <description>This field will be used only by Community user contact record type.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Agent ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Federation_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Federation ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CIAM_User_Creation_Process_TEST.cls
/* =========================================================================================
 * Date         : 05/01/17
 * Developer    : Laveen Kattela
 * Purpose      : This test class is for CIAM USer creation process apex class. 
 *                
 *                   
 *=========================================================================================
 * Update History
 *  ---------------
 * Date       Developer         Description
 *===========+============+================================================================
 * 05/01/17   |  Laveen Kattela            | Initial Version                                       
 *===========+============+================================================================
 */
@isTest
public class CIAM_User_Creation_Process_TEST {

    static testmethod void testCIAM_User_Creation_Process() {
    
            CIAM_Import_Table__C cobj = new CIAM_Import_Table__C();
            cobj.Agency_Agent_ID__c ='TESTAGENTID';
            cobj.Agent_First_Name__c ='TESTFirst Name';
            cobj.Agent_Last_Name__c ='last name';
            cobj.Email_Address__c = 'test@test.com';
            cobj.Federation_ID__c='FEDID1111';
            insert cobj;
            
            CIAM_Import_Table__C cobj2 = new CIAM_Import_Table__C();
            cobj2.Agency_Agent_ID__c ='TESTAGENTID2';
            cobj2.Agent_First_Name__c ='TESTFirst Name';
            cobj2.Agent_Last_Name__c ='last name';
            cobj2.Email_Address__c = 'test@test.com';
            cobj2.Federation_ID__c='FEDID1111';
            insert cobj2;
    
            Account portalAccount = new Account(name = 'portalAccount');//create a portal account first
            insert portalAccount;
            Contact portalContact = new contact(LastName = 'portalContact', AccountId = portalAccount.Id,Agency_Agent_ID__c='TESTAGENTID',phone='11111111111',
                                                            email='test@test.com'); //create a portal contact
            insert portalContact;
            User u1 = new User( email='spmss.process@carefirst.com',
                profileid = System.label.Customer_Community_Plus_Login_User, 
                UserName='test.test@test123.com' , 
                Alias = 'GDS',
                TimeZoneSidKey='America/New_York',
                EmailEncodingKey='ISO-8859-1',
                LocaleSidKey='en_US', 
                LanguageLocaleKey='en_US',
                ContactId = portalContact.Id,
                PortalRole = 'Manager',
                FirstName = 'spmss',
                LastName = 'process');
                 String Query = 'SELECT id, Agent_First_Name__c, Agent_Last_Name__c, Agent_Middle_Initial__c, Agent_Name__c, Agency_Name__c, Broker_Title__c, Agent_ID__c, Email_Address__c, User_ID__c, Federation_ID__c, Agency_Agent_ID__c from CIAM_Import_Table__C LIMIT 5';
                  
                CIAM_User_Creation_Process sc = new CIAM_User_Creation_Process(query);
                Database.executeBatch(sc, 5);
        
 
    }
 
}