objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SBU_Market_Segment__c</fullName>
        <inlineHelpText>This field is used by the apex batch jobs to update the  values for the Qualtrics Surveys</inlineHelpText>
        <label>SBU/Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>200+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/DynamicCodeDataStore__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>NOTE: The name field should be updated with caution as code may be referencing its value.  The email field should be a valid email address.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Text_255__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Text_255</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Used as a general dynamic data store for code to use as opposed to hard coding values</description>
    <label>Dynamic Code Data Store</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GeneralProducer__c</fullName>
        <inlineHelpText>A GP is an agency that acts as the prim.contact and recipient of compensation and comm. on behalf of mult. brokers and/or agencies that are contracted. GPs are pd fees for their admin. services and commissions for sales made by the brokers they administer</inlineHelpText>
        <label>GeneralProducer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Benefit Design Group, LLC</fullName>
                </value>
                <value>
                    <fullName>BenefitMall</fullName>
                </value>
                <value>
                    <fullName>CBIZ</fullName>
                </value>
                <value>
                    <fullName>Crawford Advisors, LLC</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Employee Benefits Corporation of America</fullName>
                </value>
                <value>
                    <fullName>Group Benefit Services</fullName>
                </value>
                <value>
                    <fullName>Hamilton Insurance Agency</fullName>
                </value>
                <value>
                    <fullName>Insurance Marketing Center, Inc.</fullName>
                </value>
                <value>
                    <fullName>Kelly &amp; Associates Insurance Group</fullName>
                </value>
                <value>
                    <fullName>NCAS</fullName>
                </value>
                <value>
                    <fullName>Potomac Basin Group Assoc., Inc.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Segment_New__c</fullName>
        <description>This field is replacing the old Market_Segment__c field.  The old field label was changed to Market Segment History</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SBU__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>2-50</fullName>
                </value>
                <value>
                    <fullName>51-199</fullName>
                </value>
                <value>
                    <fullName>200-999</fullName>
                </value>
                <value>
                    <fullName>1000+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBU__c</fullName>
        <label>SBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Small/Medium</fullName>
                </value>
                <value>
                    <fullName>Large</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
                <value>
                    <fullName>FEHBP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Contacts__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Contacts</relationshipLabel>
        <relationshipName>Survey_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Survey Contacts</relationshipLabel>
        <relationshipName>Survey_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Surveys__c</fullName>
        <label>Surveys</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Executive</fullName>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Day to Day</fullName>
                </value>
                <value>
                    <fullName>Executive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Survey Contact</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Survey Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdateSurveyContacts_Test.cls
/*=========================================================================================
 * Date         : 05/07/2016
 * Developer    : Rajesh Pennam
 *              This class implements all unit tests for the batch classes in
 *              the Contact Updates. These tests are necessary in
 *              order to achieve the required code coverage levels by the
 *              Salesforce platform in order to allow production deployment
 *              of the code. 
 *
 *=========================================================================================
 *                                 Update History
 *                                 ---------------
 * Date       Developer         Description
 *===========+============+================================================================
 * 05/07/2016  |  Rajesh Pennam    | Initial Version                                         
 *           |        | 
 *=========================================================================================
 */
@isTest
public class UpdateSurveyContacts_Test{
    static testmethod void test() {
        /*string query = '';
        query += 'select Id,Contact__c from Survey_Contacts__c Where Contact__c != null';
        query += ' AND Opportunity__r.RecordType.Name = \'51+\'';
        query += ' AND (Opportunity__r.StageName = \'Proposal\' OR Opportunity__r.StageName = \'Sold\')';
        query += ' AND Opportunity__r.SBU__c = \'Large\'';
        query += ' AND (Opportunity__r.Market_Segment_New__c = \'200-999\' OR Opportunity__r.Market_Segment_New__c = \'1000+\')';
        query += ' AND Opportunity__r.Effective_Date__c <= Today';
        query += ' AND Opportunity__r.Contract_End_Date__c > Today';
        query += ' AND (Surveys__c = \'Executive;Day to Day\' OR Surveys__c = \'Executive\' OR Surveys__c = \'Day to Day\')';*/                         
        
        Account a = new Account(Name = 'sTest');
        insert a;
        
        Opportunity o = new Opportunity();
        o.Name = 'sOppTest';
        o.AccountId = a.id;
        o.RecordTypeId = '01260000000cWGC';
        o.SBU__c = 'Large';
        o.Market_Segment_New__c = '200-999';
        o.Effective_Date__c = system.today().toStartofMonth();
        o.GeneralProducer__c = 'Direct';
        o.Contract_End_Date__c = system.today()+24;
        o.StageName = 'Proposal';
        o.Contract_End_Date__c = o.Effective_Date__c.addMonths(1)-1;
        o.CloseDate = o.Effective_Date__c-1;
        insert o;
        
        Contact c = new Contact(LastName = 'sconTest',Phone = '1234',Email = 'test@gmail.com',accountid=a.id);
        insert c;
        
        Survey_Contacts__c sc = new Survey_Contacts__c();
        sc.Contact__c = c.id;
        sc.Opportunity__c = o.id;
        sc.Surveys__c = 'Executive';
        insert sc;
        
        
        DynamicCodeDataStore__c ccd=new DynamicCodeDataStore__c();
        ccd.name='sfdcTeamEmail';
        ccd.Email__c='sfdcteam@carefirst.com';
        ccd.Text_255__c='test sample';
        insert ccd;
        system.debug('---ccd--'+ccd);
   
        Test.startTest();
              
        UpdateSurveyContactsToValue usc1 = new UpdateSurveyContactsToValue();
        Database.executeBatch(usc1);
        
        Test.stopTest();
        list<string> ss=new list<string>();
        ss.add('test@gmail.com');
        Utils  uu=new Utils ();
        Utils.EmailUtil ee=new Utils.EmailUtil(ss);
        ee.toAddresses(ss);
        ee.bccAddresses(ss);
        //added by rajesh
         
            
    }
    
    static testmethod void test2() {
        /*string query = '';
        query += 'select Id,Contact__c from Survey_Contacts__c Where Contact__c != null';
        query += ' AND Opportunity__r.RecordType.Name = \'51+\'';
        query += ' AND (Opportunity__r.StageName = \'Proposal\' OR Opportunity__r.StageName = \'Sold\')';
        query += ' AND Opportunity__r.SBU__c = \'Large\'';
        query += ' AND (Opportunity__r.Market_Segment_New__c = \'200-999\' OR Opportunity__r.Market_Segment_New__c = \'1000+\')';
        query += ' AND Opportunity__r.Effective_Date__c <= Today';
        query += ' AND Opportunity__r.Contract_End_Date__c > Today';
        query += ' AND (Surveys__c = \'Executive;Day to Day\' OR Surveys__c = \'Executive\' OR Surveys__c = \'Day to Day\')';*/                         
        
        Account a = new Account(Name = 'sTest');
        insert a;
        
        Opportunity o = new Opportunity();
        o.Name = 'sOppTest';
        o.AccountId = a.id;
        o.RecordTypeId = '01260000000cWGC';
        o.SBU__c = 'Large';
        o.Market_Segment_New__c = '200-999';
        o.Effective_Date__c = system.today().toStartofMonth();
        o.GeneralProducer__c = 'Direct';
        o.Contract_End_Date__c = system.today()+24;
        o.StageName = 'Proposal';
        o.Contract_End_Date__c = o.Effective_Date__c.addMonths(1)-1;
        o.CloseDate = o.Effective_Date__c-1;
        insert o;
        
        Contact c = new Contact(LastName = 'sconTest',Phone = '1234',Email = 'test@gmail.com' ,SBU_Market_Segment__c ='200+',accountid=a.id );
        insert c;
        
        Survey_Contacts__c sc = new Survey_Contacts__c();
        sc.Contact__c = c.id;
        sc.Opportunity__c = o.id;
        sc.Surveys__c = 'Executive';
        insert sc;
        DynamicCodeDataStore__c ccd=new DynamicCodeDataStore__c();
        ccd.name='sfdcTeamEmail';
        ccd.Email__c='sfdcteam@carefirst.com';
        ccd.Text_255__c='test sample';
        insert ccd;
        system.debug('---ccd--'+ccd);
        Test.startTest();
        UpdateSurveyContactsToNull usc = new UpdateSurveyContactsToNull();
        Database.executeBatch(usc);
        
        Test.stopTest();
    }
}