objects/Enrollment_Recycle__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contracts__c</fullName>
        <label>Contracts</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Error Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Error Number</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Business_Indicator__c</fullName>
        <label>New Business Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>Y</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Processed_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Processed Type</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating_State__c</fullName>
        <label>Rating State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Risk</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rpt_dt__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Rpt dt</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Run_Dt__c</fullName>
        <description>Date that the import file was created</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Run Dt</label>
        <length>23</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Product__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SFDC Product</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Rep</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>System</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <description>Used to store/trap the enrollment records that did not get updated due to predefined errors</description>
    <label>Enrollment Recycle</label>
    <nameField>
        <displayFormat>ER-{00000}</displayFormat>
        <label>Error Recycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Recycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Error_Message__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Error Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Error_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Error Number</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>Used to store predefined error messages.</description>
    <label>Error Message</label>
    <nameField>
        <displayFormat>EM-{000}</displayFormat>
        <label>Error Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Enrollment_Manual_Arch_RecycContlExtTest.cls
/*****************************************************************************************************
*Date: 04-13-2017
*Developer: Rajesh Pennam
*Purpose: Code coverage for Enrollment_Manual_Arch_RecycContlExt Class 
*=========================================================================================
* Update History
* Date         Developer        Tag        Description
*==================================================================================
*09-16-2016    Rajesh Pennam    T01         Removed is all data true
*==================================================================================

*******************************************************************************************************/


@isTest
public class Enrollment_Manual_Arch_RecycContlExtTest {
    // Test with selected Recycle records
    public static boolean runningTest = false;
    static testMethod void testSelected(){ 
            testUtil.createEnrollmentTestData(); 
       
            List<Enrollment_Recycle__c> ers = [ SELECT id, Rpt_Dt__c, Account_Name__c, Account_Number__c, Contracts__c, Error_Message__c,
                                                       Sales_Rep__c, Error_Number__c, Processed_Type__c, SFDC_Product__c, Risk__c, Run_Dt__c, System__c, Rating_State__c, New_Business_Indicator__c  
                                                FROM Enrollment_Recycle__c ];                                                                                          

            System.assert(ers.size() > 0);    
            runningTest = TRUE;
        
        Test.StartTest();
            ApexPages.StandardSetController setCon = new ApexPages.standardSetController(ers);
            setCon.setSelected(ers);         
            Enrollment_Manual_Arch_Recycle_ContrlExt ext = new Enrollment_Manual_Arch_Recycle_ContrlExt(setCon);    
            ext.enrollmentList = null;
        	ext.NotRecycledList=null;
        	ext.getIsClassic();
        	ext.ArchiveSelection();
       	 	Test.StopTest();
    } 
    // Test without selected Recycle Records
    static testMethod void testNoneSelected() {
        List<Enrollment_Recycle__c> ers = [ SELECT id, Rpt_Dt__c, Account_Name__c, Account_Number__c, Contracts__c, Error_Message__c,
                                                   Sales_Rep__c, Error_Number__c, Processed_Type__c, SFDC_Product__c, Risk__c, Run_Dt__c, System__c, Rating_State__c, New_Business_Indicator__c  
                                            FROM Enrollment_Recycle__c Where Rpt_Dt__c = 'NO RECORDS' ];     
        ApexPages.StandardSetController setCon = new ApexPages.standardSetController(ers);
        Test.StartTest();     
            Enrollment_Manual_Arch_Recycle_ContrlExt ext = new Enrollment_Manual_Arch_Recycle_ContrlExt(setCon);
            ext.ArchiveSelection();
        Test.StopTest(); 
    }   
}