objects/Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Contracts__c</fullName>
        <label>Contracts</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Groups__c</fullName>
        <label>Groups</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rpt_Dt__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Rpt Dt</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <description>This object holds the actual enrollment data which is associated to the opportunity</description>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Enrollments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment_Import_2_50__c.object
<CustomObject>
    <fields>
        <fullName>Contracts__c</fullName>
        <label>Contracts</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rpt_dt__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Rpt dt</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <description>Holds the Enrollment Import information for 2_50 segment</description>
    <label>Enrollment Import 2-50</label>
    <nameField>
        <displayFormat>ENI2-50-{00000}</displayFormat>
        <label>Enrollment Import 2-50 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments Imports 2-50</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enrollment_Summary_51_Terms__c.object
<CustomObject>
    <fields>
        <fullName>Contracts__c</fullName>
        <description>Holds the current Termed Contract count for 51+.</description>
        <inlineHelpText>Holds the current Termed Contract count for 51+.</inlineHelpText>
        <label>Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Groups__c</fullName>
        <description>Holds the current value of Termed Groups for 51+.</description>
        <inlineHelpText>Holds the current Termed Contract count for 51+.</inlineHelpText>
        <label>Groups</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <description>Jurisdiction to which the total pertains.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Jurisdiction to which the total pertains.</inlineHelpText>
        <label>Jurisdiction</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the current # of Termed Contracts and Groups for 51+.</description>
    <label>Enrollment Summary 51+ Terms</label>
</CustomObject>

objects/Enrollment_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <description>Report Date, format is YYYYMM.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Report Date, format is YYYYMM.</inlineHelpText>
        <label>Date</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <label>Jurisdiction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>VA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Month_Name__c</fullName>
        <formula>CASE(RIGHT(Date__c, 2),
"01","Jan",
"02","Feb",
"03","Mar",
"04","Apr",
"05","May",
"06","Jun",
"07","Jul",
"08","Aug",
"09","Sep",
"10","Oct",
"11","Nov",
"12","Dec",


"")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Month Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Change_Contracts__c</fullName>
        <formula>Total_Termed_Contracts__c -  New_Contracts__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Change Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Net_Change_Groups__c</fullName>
        <formula>Total_Termed_Groups__c -  New_Groups__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Change Groups</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Net_Contract_Growth_Pct__c</fullName>
        <formula>Net_Change_Contracts__c /  On_Cycle_Contracts__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Contract Growth Pct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>New_Contract_Sales_Pct__c</fullName>
        <formula>New_Contracts__c /  On_Cycle_Contracts__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>New Contract Sales Pct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>New_Contracts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>New Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Groups__c</fullName>
        <defaultValue>0</defaultValue>
        <label>New Groups</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Off_Cycle_Contracts__c</fullName>
        <formula>Total_Contracts__c - On_Cycle_Contracts__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Off Cycle Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Off_Cycle_Groups__c</fullName>
        <formula>Total_Groups__c - On_Cycle_Groups__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Off Cycle Groups</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Off_Cycle_Termed_Contract_Pct__c</fullName>
        <formula>Off_Cycle_Termed_Contracts__c /  On_Cycle_Contracts__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Off Cycle Termed Contract Pct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Off_Cycle_Termed_Contracts__c</fullName>
        <formula>Total_Termed_Contracts__c - On_Cycle_Termed_Contracts__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Off Cycle Termed Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Off_Cycle_Termed_Groups__c</fullName>
        <formula>Total_Termed_Groups__c - On_Cycle_Termed_Groups__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Off Cycle Termed Groups</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>On_Cycle_Contracts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>On Cycle Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>On_Cycle_Groups__c</fullName>
        <defaultValue>0</defaultValue>
        <label>On Cycle Groups</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>On_Cycle_Termed_Contract_Pct__c</fullName>
        <formula>On_Cycle_Termed_Contracts__c /  On_Cycle_Contracts__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>On Cycle Termed Contract Pct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>On_Cycle_Termed_Contracts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>On Cycle Termed Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>On_Cycle_Termed_Groups__c</fullName>
        <defaultValue>0</defaultValue>
        <label>On Cycle Termed Groups</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Contract_Terms_Pct__c</fullName>
        <formula>Total_Termed_Contracts__c /  On_Cycle_Contracts__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Contract Terms Pct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Contracts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Groups__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Groups</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Termed_Contracts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Termed Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Termed_Groups__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Termed Groups</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>LEFT(Date__c,4)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Enrollment Summary</label>
    <nameField>
        <displayFormat>SE-{00000}</displayFormat>
        <label>Enrollment Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Summary_Enrollment_Jurisdiction__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Summary Enrollment Jurisdiction</label>
</CustomObject>

objects/Summary_Enrollment_Report_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Summary Enrollment Report Type</label>
</CustomObject>

objects/Summary_Enrollment_Start_Year__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Summary Enrollment Start Year</label>
</CustomObject>

classes/enrollmentFilters2_199.cls
//=========================================================================================
//     Date: 12/30/2014
//Developer: Enable Path
//  Purpose: 
//====================================================================================================
//                                 Update History
// Date          Developer      Description
//====================================================================================================
// 03/13/2017 Tom Barrett TPB   Made significant changes where code was reading the Enrollment__c
//                              object to get the latest Rpt_Dt__c date value.
//                              The replacement is to read the Enrollent_Import__c and the 
//                              Enrollment_Import_2_50__c objects instead.             
//====================================================================================================
public class enrollmentFilters2_199 {
    
    public string reportType {get;set;}
    public string month {get;set;}
    public string year {get;set;}
    public string jurisdiction {get;set;}
    public string recType {get;set;}
    public Decimal contractNumber {get;set;}
    public Decimal groupNumber {get;set;}
    public List<SelectOption> reportTypeList {get;set;}
    public List<SelectOption> monthList {get;set;}
    public List<SelectOption> years {get;set;}
    public List<SelectOption> jurisdictionList {get;set;}
    public List<SelectOption> recTypes {get;set;}
    public List<Summary_Enrollment_Jurisdiction__c> jurisdictions {get;set;}
    public List<String> jurisdictionTypes {get;set;}
    public Decimal totalStartingBalance {get;set;}
    public Decimal totalNew {get;set;}
    public Decimal totalTermed {get;set;}
    public Decimal totalMonthEndBalance {get;set;}
    public Boolean displayResults {get;set;}
    public map<string,Enrollment_Summary_51_Terms__c> customSettingMap {get;set;}
    
    public List<ResultsWrapper> results {get;set;}
    public List<totalWrapper> totals {get;set;}
    public List<String> total {get;set;}
    
    public enrollmentFilters2_199(ApexPages.StandardController controller) {
    
       displayResults = false;
        
        results = new List<ResultsWrapper>();
        customSettingMap = new map<string,Enrollment_Summary_51_Terms__c>();
        
        AggregateResult ar = [SELECT MAX(Date__c) MaxDate FROM Enrollment_Summary__c];
        if( null != ar ) {
            String sMaxDate = String.valueOf(ar.get('MaxDate'));
            year = sMaxDate.substring(0,4);
            month = sMaxDate.substring(4,6);
        }

        List<Summary_Enrollment_Report_Type__c> reportTypes = [SELECT Id, Name FROM Summary_Enrollment_Report_Type__c ORDER BY NAME];
        reportTypeList = new List<SelectOption>();
        
        for( Summary_Enrollment_Report_Type__c r : reportTypes ) {
            reportTypeList.add( new SelectOption( r.Name, r.Name ) );
        }
        
        jurisdictions = [SELECT Id, Name FROM Summary_Enrollment_Jurisdiction__c where Name != 'ALL' ORDER BY NAME];
        jurisdictionList = new List<SelectOption>();
        jurisdictionTypes = new List<String>();
        
        for( Summary_Enrollment_Jurisdiction__c j : jurisdictions ) {
            //jurisdictionList.add( new SelectOption( String.valueOf(j.Name), j.Name ) );
            jurisdictionTypes.add(j.name);
        }
        
        years = new List<SelectOption>();
        List<Summary_Enrollment_Start_Year__c> startYears = [SELECT Id, Name FROM Summary_Enrollment_Start_Year__c ORDER BY NAME];
        years = new List<SelectOption>();
        
        for( Summary_Enrollment_Start_Year__c s1 : startYears ) {
            years.add( new SelectOption( String.valueOf(s1.Name), s1.Name ) );
        }
        
        recTypes = new List<SelectOption>();
        recTypes.add(new SelectOption('2-50','2-50'));
        recTypes.add(new SelectOption('51+','51+'));
            
        List<Enrollment_Summary_51_Terms__c> terms = [Select Id, Contracts__c, Groups__c, Jurisdiction__c from Enrollment_Summary_51_Terms__c];        
        
        for(Enrollment_Summary_51_Terms__c cs : terms){
            customSettingMap.put(cs.Jurisdiction__c,cs);
        }
        
        // Months are pretty standard.  We don't need a custom setting for them.
        monthList = new List<SelectOption>();
        monthList.add( new SelectOption( '01', 'January' ) );
        monthList.add( new SelectOption( '02', 'February' ) );
        monthList.add( new SelectOption( '03', 'March' ) );
        monthList.add( new SelectOption( '04', 'April' ) );
        monthList.add( new SelectOption( '05', 'May' ) );
        monthList.add( new SelectOption( '06', 'June' ) );
        monthList.add( new SelectOption( '07', 'July' ) );
        monthList.add( new SelectOption( '08', 'August' ) );
        monthList.add( new SelectOption( '09', 'September' ) );
        monthList.add( new SelectOption( '10', 'October' ) );
        monthList.add( new SelectOption( '11', 'November' ) );
        monthList.add( new SelectOption( '12', 'December' ) );
    
    }
    
    public void go(){
    
        total = new List<String>();
        string s = '';
        total.add(s);
    
        if(results.size() > 0){
            results.clear();
        }
        
        List<Enrollment_Summary__c> allES = new list<Enrollment_Summary__c>();
        /*enrollment__c maxEnrollment = [Select Rpt_dt__c from enrollment__c where RecordType.Name = :recType order by Rpt_dt__c DESC limit 1];
        
        String maxDate = maxEnrollment.Rpt_dt__c;
       
        System.debug('maxDate = ' + maxDate);
        
        year = maxDate.substring(0,4);
        System.debug( 'year = ' + year );
        month = maxDate.substring(4);
        System.debug( 'month = ' + month );
        String filterDate = year + month;
        System.debug( 'Filter = ' + filterDate );
        System.debug( 'recType = ' + recType );*/
        
        if(recType == '51+'){
        //BEGIN CHANGE TPB 03/13/2017
        //enrollment__c maxEnrollment51 = [Select Rpt_dt__c from enrollment__c where RecordType.Name = :recType order by Rpt_dt__c DESC limit 1];
        
        //String maxDate51 = maxEnrollment51.Rpt_dt__c;
        
        String maxDate51 =  Enrollment_QueryBase.GetLatestEnrlRunDt51();
        //END CHANGE TPB 03/13/2017
       
        System.debug('maxDate = ' + maxDate51);
        
        year = maxDate51.substring(0,4);
        System.debug( 'year = ' + year );
        month = maxDate51.substring(4);
        System.debug( 'month = ' + month );
        String filterDate51 = year + month;
        System.debug( 'Filter = ' + filterDate51 );
        System.debug( 'recType = ' + recType );
        
        allES = [SELECT Id, Name, Date__c, Jurisdiction__c, Month_Name__c, Net_Change_Contracts__c, Net_Change_Groups__c, Net_Contract_Growth_Pct__c,
                                               New_Contracts__c, New_Contract_Sales_Pct__c, New_Groups__c, Off_Cycle_Contracts__c, Off_Cycle_Groups__c,
                                               Off_Cycle_Termed_Contract_Pct__c, Off_Cycle_Termed_Contracts__c, Off_Cycle_Termed_Groups__c, On_Cycle_Contracts__c,
                                               On_Cycle_Groups__c, On_Cycle_Termed_Contract_Pct__c, On_Cycle_Termed_Contracts__c, On_Cycle_Termed_Groups__c,
                                               Total_Contracts__c, Total_Contract_Terms_Pct__c, Total_Groups__c, Total_Termed_Contracts__c, Total_Termed_Groups__c,
                                               year__c, Recordtype.Name                                         
                                               FROM Enrollment_Summary__c
                                               WHERE Date__c = :filterDate51
                                               AND RecordType.Name = :recType
                                               order by Jurisdiction__c]; 
                                               
        }
        
        if(recType == '2-50'){
        //BEGIN CHANGE TPB 03/13/2017
        //enrollment__c maxEnrollment2_50 = [Select Rpt_dt__c from enrollment__c where RecordType.Name = :recType order by Rpt_dt__c DESC limit 1];
        
        //String maxDate2_50 = maxEnrollment2_50.Rpt_dt__c;
        
        String maxDate2_50 = Enrollment_QueryBase.GetLatestEnrlRunDt2_50();
        //END CHANGE TPB 03/13/2017
       
        System.debug('maxDate = ' + maxDate2_50);
        
        year = maxDate2_50.substring(0,4);
        System.debug( 'year = ' + year );
        month = maxDate2_50.substring(4);
        System.debug( 'month = ' + month );
        String filterDate2_50 = year + month;
        System.debug( 'Filter = ' + filterDate2_50 );
        System.debug( 'recType = ' + recType );
        
        allES = [SELECT Id, Name, Date__c, Jurisdiction__c, Month_Name__c, Net_Change_Contracts__c, Net_Change_Groups__c, Net_Contract_Growth_Pct__c,
                                               New_Contracts__c, New_Contract_Sales_Pct__c, New_Groups__c, Off_Cycle_Contracts__c, Off_Cycle_Groups__c,
                                               Off_Cycle_Termed_Contract_Pct__c, Off_Cycle_Termed_Contracts__c, Off_Cycle_Termed_Groups__c, On_Cycle_Contracts__c,
                                               On_Cycle_Groups__c, On_Cycle_Termed_Contract_Pct__c, On_Cycle_Termed_Contracts__c, On_Cycle_Termed_Groups__c,
                                               Total_Contracts__c, Total_Contract_Terms_Pct__c, Total_Groups__c, Total_Termed_Contracts__c, Total_Termed_Groups__c,
                                               year__c, Recordtype.Name                                         
                                               FROM Enrollment_Summary__c
                                               WHERE Date__c = :filterDate2_50 //WHERE Date__c >= '201301'
                                                AND RecordType.Name = :recType
                                               order by Jurisdiction__c];
        }
            
        system.debug('allES = '+allES.size());
           Map<string,List<Enrollment_Summary__c>> ESMap = new Map<string,List<Enrollment_Summary__c>>();
           
           Map<string,Enrollment_Summary__c> JurMap = new Map<string,Enrollment_Summary__c>();
           
           for(Enrollment_Summary__c ES : allES){
               system.debug('making maps');
               
                   JurMap.put(ES.Jurisdiction__c,ES);
           }
           
           for(String j : jurisdictionTypes){
               system.debug('assigning jurisdictions');
               if(JurMap.containsKey(j)) {
                   List<Enrollment_Summary__c> esList = new List<Enrollment_Summary__c>();
                   esList.add(JurMap.get(j));                  
                   
                   ESMap.put(j,esList);
               }           
           }
           
           for(string j : ESMap.keyset()){
               Decimal startingBalance = 0;
               Decimal newCount = 0;
               Decimal termed = 0;
               Decimal monthEndBalance = 0;
               
               List<Enrollment_Summary__c> esList = ESMap.get(j);
               system.debug('esList'+esList.size()); 
               
               Enrollment_Summary_51_Terms__c csNumbers = customSettingMap.get(j);
               
               for(Enrollment_Summary__c ES : esList){
                   system.debug('ES ID - '+ES.Id); 
                   system.debug('reportType - '+reportType);
                   if(reportType == 'Contracts'){
                       startingBalance = startingBalance + ES.Total_Contracts__c;
                       system.debug('startingBalance - '+ES.Id+' - '+startingBalance);
                  // 12-26-2014 jhm: Changed from Total_Termed_Contracts__c 
                       newCount = newCount + ES.New_Contracts__c;
                       system.debug('newCount - '+ES.Id+' - '+newCount);
                       termed = termed + ES.Total_Termed_Contracts__c;
                       system.debug('termed - '+ES.Id+' - '+termed);
                   }
                   
                   if(reportType == 'Groups'){
                       startingBalance = startingBalance + ES.Total_Groups__c;
                  // 12-26-2014 jhm: Changed from Total_Termed_Groups__c 
                       newCount = newCount + ES.New_Groups__c;
                       termed = termed + ES.Total_Termed_Groups__c;
                   }
               }
               
           
               if(reportType == 'Contracts' && null != csNumbers && recType == '51+'){
                   termed = termed + csNumbers.Contracts__c;
               }
                   
               if(reportType == 'Groups' && null != csNumbers && recType == '51+'){
                   termed = termed + csNumbers.Groups__c;
               }
                  
               monthEndBalance = (startingBalance + newCount) - termed;
                   
               ResultsWrapper rw = new ResultsWrapper();
               rw.startingBalance = startingBalance;
               rw.newCount = newCount;
               rw.termed = termed;
               rw.monthEndBalance = monthEndBalance;
               rw.jurisdiction = j;
              
               results.add(rw);  
           } 
           
           if(results.size() > 0){
               displayResults = true;
           }
           
           totalStartingBalance = calcTotals(results,'startingBalance');
           totalNew = calcTotals(results,'newCount');
           totalTermed = calcTotals(results,'termed');
           totalMonthEndBalance = calcTotals(results,'monthEndBalance');
        
            totals = new List<totalWrapper>();
            
        totalWrapper tw = new totalWrapper();
            tw.startingBalance = totalStartingBalance;
            tw.newCount = totalNew;
            tw.termed = totalTermed;
            tw.monthEndBalance = totalMonthEndBalance;
            
        totals.add(tw);
    }
    
    public Decimal calcTotals(List<ResultsWrapper> wraps, String field){
    
        Decimal d = 0;
        
        for(ResultsWrapper w : wraps){
            if(field == 'startingBalance'){
               d = d + w.startingBalance;
            }
            if(field == 'newCount'){
               d = d + w.newCount;
            }
            if(field == 'termed'){
               d = d + w.termed;
            }
            if(field == 'monthEndBalance'){
               d = d + w.monthEndBalance;
            }
        }
    
        return d;
    }
    
    public class ResultsWrapper{
        public Decimal startingBalance {get;set;}
        public Decimal newCount {get;set;}
        public Decimal termed {get;set;}
        public Decimal monthEndBalance {get;set;}
        public String jurisdiction {get;set;}
    }
    
    public class totalWrapper{
        public Decimal startingBalance {get;set;}
        public Decimal newCount {get;set;}
        public Decimal termed {get;set;}
        public Decimal monthEndBalance {get;set;}
        public String jurisdiction {get;set;}
    }
        
}