objects/EnvironmentVariable__c.object
<CustomObject>
    <fields>
        <fullName>IsEncrypted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if a variable's value should be encrypted, useful if storing passwords or other sensitive information</description>
        <inlineHelpText>Encrypts the variable's value</inlineHelpText>
        <label>Is Encrypted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Editable__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if the custom field is editable through the Environments tab interface</description>
        <inlineHelpText>This field determines if the custom field is editable through the Environments tab interface</inlineHelpText>
        <label>Is Editable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <label>Module</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Broker Express</fullName>
                    <default>true</default>
                    <label>Broker Express</label>
                </value>
                <value>
                    <fullName>EGP Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Variable_Name__c</fullName>
        <label>Variable Name</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Module__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Endpoint</fullName>
                </value>
                <value>
                    <fullName>RequestMethod</fullName>
                </value>
                <value>
                    <fullName>RequestTimeout</fullName>
                </value>
                <value>
                    <fullName>Environment</fullName>
                </value>
                <value>
                    <fullName>Transaction ID</fullName>
                </value>
                <value>
                    <fullName>EGP_EndPoint</fullName>
                </value>
                <value>
                    <fullName>EGP_ClientCertificateName</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Contains variables used in the code that need to be changed dynamically. Instead of making changes to the code in order to change a variable we can make the change via this portal without a code deployment.</description>
    <label>Environment Variable</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environment Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EnvironmentVariables.cls
public with sharing class EnvironmentVariables {
	
	/**
	 * Checks and returns true if an input map of environment variables (name, EnvironmentVariable__c) has a specified required set of environment variable names. If any are missing, an error message is appended to the 
	 * error message holder input string.
	 */
	public static  boolean validateEnvironmentVarsPresent(Map<String, EnvironmentVariable__c> variablesMapToCheck, Set<String> requiredVariables, String errorMessage) {
		boolean environmentVarsPresent = true;
		
		if(requiredVariables.isEmpty()) 	// if no required variables then result is true
			return environmentVarsPresent; 
			
		if(requiredVariables.isEmpty() && variablesMapToCheck.isEmpty())
			return environmentVarsPresent;
		
		Set<String> reqVars = requiredVariables.clone();
		errorMessage = '<h1><font color="blue">Missing required Environment variables:</font></h1><br/><br/>';

		if ( variablesMapToCheck.isEmpty() ) {
 			environmentVarsPresent = false;
			errorMessage += '<strong>All ' + requiredVariables.size() + ' environment variables are missing:</strong><br/>';
				
		} else if ( variablesMapToCheck.size() != requiredVariables.size() ) {
			environmentVarsPresent = false;
			// Remove the environment variables found to keep the ones missing
			for ( EnvironmentVariable__c var : variablesMapToCheck.values() ) {
				reqVars.remove(var.Variable_Name__c);
			}
			errorMessage += '<strong>The following environment variables are missing:</strong><br/>';
		}

		// Complete building the error message if one was found 
		if ( !environmentVarsPresent ) {
			// Add to the message the remaining/missing environment variables
			for ( String varName : reqVars ) {
				errorMessage += '<font color="red">' + varName + '</font><br/>';
			}
			errorMessage += '<br/><h1><font color="blue">Please contact a system admin.</font><h1/>';
			// if called from VisualForce page
			if(ApexPages.currentPage() != null) {
				ApexPages.Message msg = 
				new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage);
			ApexPages.addMessage(msg);
			}
			
			System.debug(LoggingLevel.DEBUG, errorMessage);
		}
		return environmentVarsPresent;
	}

	/**
	 * Gets the environment variables for a specified module in an easily accessible map
	 */
	public static Map<String, EnvironmentVariable__c> getEnvironmentVariablesForModule(String moduleName, Map<String, EnvironmentVariable__c> varMapHolder ) {
		System.debug('moduleName=' + moduleName);
		List<EnvironmentVariable__c> vars = [SELECT Variable_Name__c, Value__c, Module__c, Is_Required__c, Is_Editable__c, IsEncrypted__c FROM EnvironmentVariable__c WHERE Module__c = :moduleName];
		for ( EnvironmentVariable__c currVar : vars ) {
				varMapHolder.put(currVar.Variable_Name__c, currVar);
		}
		System.debug( 'Retrieved variable value in varMapHolder=' + varMapHolder);
		return varMapHolder;
	}
	

	/**
	 * Gets the environment variables for a specified module in an easily accessible map
	 */
	public static Map<String, EnvironmentVariable__c> getEnvironmentVariablesForModule(String moduleName ) {
		Map<String, EnvironmentVariable__c> soapVars = new Map<String, EnvironmentVariable__c>();
		System.debug('moduleName=' + moduleName);
		List<EnvironmentVariable__c> vars = [SELECT Variable_Name__c, Value__c, Module__c, Is_Required__c, Is_Editable__c, IsEncrypted__c FROM EnvironmentVariable__c WHERE Module__c = :moduleName];
		for ( EnvironmentVariable__c currVar : vars ) {
				soapVars.put(currVar.Variable_Name__c, currVar);
		}
		System.debug( 'Retrieved soapVars=' + soapVars);
		return soapVars;
	}
	

}