objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Market_Segment_New__c</fullName>
        <description>This field is replacing the old Market_Segment__c field.  The old field label was changed to Market Segment History</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SBU__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>2-50</fullName>
                </value>
                <value>
                    <fullName>51-199</fullName>
                </value>
                <value>
                    <fullName>200-999</fullName>
                </value>
                <value>
                    <fullName>1000+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBU__c</fullName>
        <label>SBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Small/Medium</fullName>
                </value>
                <value>
                    <fullName>Large</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
                <value>
                    <fullName>FEHBP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PicklistFieldControllerTest.cls
/*****************************************************************************************************
*Date: 07-23-2018
*Developer: Paritosh
*Purpose: Test class for PicklistFieldController
*=========================================================================================
* Update History
* Date         Developer               Description
*==================================================================================
*07-23-2018   Paritosh            Initial Development
*==================================================================================

*******************************************************************************************************/

@isTest
public class PicklistFieldControllerTest {
    
    @isTest
    public static void test1(){
        
        //correct parameters
        final Map<String,List<String>> result = PicklistFieldController.getDependentOptionsImpl('opportunity','SBU__c','Market_Segment_New__c');
        system.assertNotEquals(NULL, result);
        
        //incorrect parameters
        PicklistFieldController.getDependentOptionsImpl('nonexistingobj','SBU__c','Market_Segment_New__c');
        PicklistFieldController.getDependentOptionsImpl('opportunity','nonexistingfield','Market_Segment_New__c');
        PicklistFieldController.getDependentOptionsImpl('opportunity','SBU__c','nonexistingfield');
        PicklistFieldController.getDependentOptionsImpl('opportunity','SBU__c','SBU__c');
        
        //test wrapper class
        PicklistEntryWrapper wrapper = new PicklistEntryWrapper();
        String str = wrapper.active + wrapper.defaultValue + wrapper.label + wrapper.value + wrapper.validFor;

    }
}