objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <description>This field was deprecated during the Sales reorg effort. Became live on 1/1/2013.</description>
        <inlineHelpText>OBSOLETE: This field is superseded by a new fields: SBU, Market Segment, Division and Business Type as a unit.</inlineHelpText>
        <label>Business</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Segment__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1-50</fullName>
                </value>
                <value>
                    <fullName>51-199 Renewal Sales</fullName>
                </value>
                <value>
                    <fullName>CFA Renewal Sales</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>Ind Govt Programs</fullName>
                </value>
                <value>
                    <fullName>Labor New Business Sales</fullName>
                </value>
                <value>
                    <fullName>Labor Renewal Sales</fullName>
                </value>
                <value>
                    <fullName>Local Renewal Sales</fullName>
                </value>
                <value>
                    <fullName>National Renewal Sales</fullName>
                </value>
                <value>
                    <fullName>NCAS Renewal Sales</fullName>
                </value>
                <value>
                    <fullName>New Business Sales</fullName>
                </value>
                <value>
                    <fullName>Regional Renewal Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GeneralProducer__c</fullName>
        <inlineHelpText>A GP is an agency that acts as the prim.contact and recipient of compensation and comm. on behalf of mult. brokers and/or agencies that are contracted. GPs are pd fees for their admin. services and commissions for sales made by the brokers they administer</inlineHelpText>
        <label>GeneralProducer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Benefit Design Group, LLC</fullName>
                </value>
                <value>
                    <fullName>BenefitMall</fullName>
                </value>
                <value>
                    <fullName>CBIZ</fullName>
                </value>
                <value>
                    <fullName>Crawford Advisors, LLC</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Employee Benefits Corporation of America</fullName>
                </value>
                <value>
                    <fullName>Group Benefit Services</fullName>
                </value>
                <value>
                    <fullName>Hamilton Insurance Agency</fullName>
                </value>
                <value>
                    <fullName>Insurance Marketing Center, Inc.</fullName>
                </value>
                <value>
                    <fullName>Kelly &amp; Associates Insurance Group</fullName>
                </value>
                <value>
                    <fullName>NCAS</fullName>
                </value>
                <value>
                    <fullName>Potomac Basin Group Assoc., Inc.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Rep_Name_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up will be based off of the Lead Rep Name on the user record to be displayed on the Opportunity object.</description>
        <inlineHelpText>This look-up will be based off of the Lead Rep Name on the user record to be displayed on the Opportunity object.</inlineHelpText>
        <label>Lead Rep Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Lead_Rep__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Rep__c</fullName>
        <label>Lead Rep#</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Lead_Rep_Name__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>0007</fullName>
                </value>
                <value>
                    <fullName>0111</fullName>
                </value>
                <value>
                    <fullName>0151</fullName>
                </value>
                <value>
                    <fullName>0184</fullName>
                </value>
                <value>
                    <fullName>0189</fullName>
                </value>
                <value>
                    <fullName>0341</fullName>
                </value>
                <value>
                    <fullName>0355</fullName>
                </value>
                <value>
                    <fullName>0858</fullName>
                </value>
                <value>
                    <fullName>1002</fullName>
                </value>
                <value>
                    <fullName>1033</fullName>
                </value>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>1296</fullName>
                </value>
                <value>
                    <fullName>1334</fullName>
                </value>
                <value>
                    <fullName>1371</fullName>
                </value>
                <value>
                    <fullName>1680</fullName>
                </value>
                <value>
                    <fullName>1855</fullName>
                </value>
                <value>
                    <fullName>1870</fullName>
                </value>
                <value>
                    <fullName>2001</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2058</fullName>
                </value>
                <value>
                    <fullName>2185</fullName>
                </value>
                <value>
                    <fullName>2535</fullName>
                </value>
                <value>
                    <fullName>3025</fullName>
                </value>
                <value>
                    <fullName>3029</fullName>
                </value>
                <value>
                    <fullName>3186</fullName>
                </value>
                <value>
                    <fullName>3679</fullName>
                </value>
                <value>
                    <fullName>3829</fullName>
                </value>
                <value>
                    <fullName>3830</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Lead_Rep__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the user is a Lead Rep this field should remain check-marked so that the user will be available for selection as a Lead Rep on the Opportunity record.</description>
        <inlineHelpText>If the user is a Lead Rep this field should remain check-marked so that the user will be available for selection as a Lead Rep on the Opportunity record.</inlineHelpText>
        <label>Lead Rep</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CFCT_ProcessManager_TEST.cls
/*------------------------------------------------------------------------------------
 *                      ----===[ HISTORY ]===---
 * Date        Developer        Description
 *------------------------------------------------------------------------------------
 * 12/06/2012 Varun Nagarajan   Modified code where Business__c has been replaced with
                                Business_Type__c matching today's world requirements 
 *                              at CareFirst.  
 
 *06/27/2014 Ashish Ojha         Renamed Profile name from 
 *                              Standard user - Custom to Id = '00e60000000oSNM' 
 *************************************************************************************
 */
 
@isTEST
private class CFCT_ProcessManager_TEST {
    static testMethod void test_ownerLeadRepNoMatchEmailUsers_1() {
        //logged in as admin test and complete CFCT_QueryBase class test
        Profile p = [select id from profile where Id = '00e60000000oSNM'];
        User u = new User(alias = 'stduser2', email='standardUser1xyz@testorg.com',
        emailencodingkey='UTF-8', lastname='StandardUser1', languagelocalekey='en_US',
        localesidkey='en_US', profileid = p.Id, Lead_Rep__c = true,
        timezonesidkey='America/Los_Angeles', username='standarduser1xyz@testorg.com');        
        /* create another user to use as a lead rep */
        User u2 = new User(alias = 'leadRep', email='LeadRepUser@testorg.com',
        emailencodingkey='UTF-8', lastname='LeadRepTesting', languagelocalekey='en_US',
        localesidkey='en_US', profileid = p.Id, Lead_Rep__c = true,
        timezonesidkey='America/Los_Angeles', username='LeadRepUser@testorg.com'); 
        System.runAs(u) {
          //  System.Assert(CFCT_QueryBase.adminLoggedIn() == true, true);            
                      
            /* create account */  
            Account testAcc = new Account();
            testAcc.Name = 'Test Account';
            testAcc.OwnerId  = u.Id;     
            insert testAcc ;    
            /* create opportunity */
            Opportunity testOpp = new Opportunity();
            Date closedDate = date.newinstance(1900, 1, 1);
            Date EffectiveDate = date.newinstance(2050, 1, 1);            
            testOpp.Name = 'Test123 Opportunity';
            testOpp.AccountId = testAcc.Id ;
            testOpp.OwnerId = u.Id;
            testOpp.Lead_Rep_Name_User__c = u2.id;
            testOpp.StageName ='Proposal';
            testOpp.CloseDate = closedDate;
            testOpp.Effective_Date__c =  EffectiveDate;
            testOpp.GeneralProducer__c = 'Direct';
            //testOpp.Business__c = 'National Renewal Sales';   
            testOpp.Business_Type__c = 'Renewal';    
//TPB - 12/19/2013       
            testOpp.Effective_Date__c = EffectiveDate;
            Date contractEndDate = EffectiveDate+366;
            contractEndDate = Date.newInstance(contractEndDate.Year(), contractEndDate.Month(), 1);
            contractEndDate = contractEndDate.addDays(-1);
            testOpp.Contract_End_Date__c = contractEndDate;   
                         
            insert testOpp ;
            
            List<Opportunity> oppList = [ Select id, name, owner.id, owner.email, 
                                           owner.Name, Lead_Rep_Name_User__c
                                    From Opportunity
                                    Where Name = 'Test123 Opportunity' ];
            
            System.Assert(oppList.size() == 1, true);
            
            Test.StartTest();            
            CFCT_ProcessorManager.ownerLeadRepNoMatchEmailUsers(oppList);
            CFCT_ProcessorManager.opportunitiesWithoutPartnersEmailUsers(oppList);            
            CFCT_ProcessorManager.getDomainURL();
// AO 03/09/2015
            
            CFCT_ProcessorManager.BuildEmail(oppList[0].owner.id,'test date','<br/>htmlbody');
            CFCT_ProcessorManager.opportunitiesInProposalEmailUsers_200Plus(oppList);
            CFCT_ProcessorManager.opportunitiesInProposalEmailUsers_51to199(oppList);
            Test.StopTest();
        }
    }  
}