objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Market_Segment_New__c</fullName>
        <description>This field is replacing the old Market_Segment__c field.  The old field label was changed to Market Segment History</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SBU__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>2-50</fullName>
                </value>
                <value>
                    <fullName>51-199</fullName>
                </value>
                <value>
                    <fullName>200-999</fullName>
                </value>
                <value>
                    <fullName>1000+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBU__c</fullName>
        <label>SBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Small/Medium</fullName>
                </value>
                <value>
                    <fullName>Large</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
                <value>
                    <fullName>FEHBP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Dependent_Picklist_Test.cls
@isTest
public class Dependent_Picklist_Test {
    
    @isTest
    public static void testGetDependentOptionsImpl(){
        
        //correct parameters
        final Map<String,List<String>> result = Dependent_Picklist.getDependentOptionsImpl('opportunity','SBU__c','Market_Segment_New__c');
        system.assertNotEquals(NULL, result);
        
        //incorrect parameters
        Dependent_Picklist.getDependentOptionsImpl('nonexistingobj','SBU__c','Market_Segment_New__c');
        Dependent_Picklist.getDependentOptionsImpl('opportunity','nonexistingfield','Market_Segment_New__c');
        Dependent_Picklist.getDependentOptionsImpl('opportunity','SBU__c','nonexistingfield');
        Dependent_Picklist.getDependentOptionsImpl('opportunity','SBU__c','SBU__c');

    }
    
    @isTest
    public static void testGetselectOptions(){
        
        sObject sObj = new opportunity();
        final List<String> result = Dependent_Picklist.getselectOptions(sObj,'SBU__c');
        system.assertNotEquals(NULL, result);
    }

}