objects/Workplan_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Workplan_Stage__c</fullName>
        <formula>TEXT(Workplan_Type_Stage__r.Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Workplan Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workplan_Type_Stage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workplan Type Stage</label>
        <referenceTo>Workplan_Type_Stage__c</referenceTo>
        <relationshipName>Workplan_Type_Stage</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Workplan Stage</label>
    <nameField>
        <displayFormat>WS-{000000}</displayFormat>
        <label>Workplan Stage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Stage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
</CustomObject>

objects/Workplan_Type_Stage__c.object
<CustomObject>
    <label>Workplan Type Stage</label>
    <nameField>
        <displayFormat>WTS-{00000}</displayFormat>
        <label>Workplan Type Stage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Type Stage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
</CustomObject>

classes/AIA_WorkplanTypeStageTriggerHandler.cls
/*=========================================================================================
 * Date     : 07/22/2016
 * Developer    : Sandeep S
 * Purpose      : This class is the extension point of the Trigger Framework for adding WorkPlam Type Stage trigger handlers.
 *                
 *=========================================================================================
 *                                 Update History
 *                                 ---------------
 * Date       Developer         Description
 *===========+============+================================================================
 * 07/22/2016|  SS    | Initial Version  
 * 10/17/2017|  Raviteja Vadapalli  |	T-01      | Commented lines as per US 209
 *===========+============+================================================================
 */
public with sharing class AIA_WorkplanTypeStageTriggerHandler extends TriggerHandler{
/*	T-01 
     protected override void beforeDelete(){
        
         List<Workplan_Type_Stage__c> oldWptList=Trigger.old;
         List<Workplan_Type_Stage__c> workPlanTypeStageList=[select id,(select id from Workplan_Type_Stage__r) from Workplan_Type_Stage__c where id=:oldWptList];
         
         for(Workplan_Type_Stage__c awt:workPlanTypeStageList){
         	List<Workplan_Stage__c > wptsList=awt.Workplan_Type_Stage__r;
            If(wptsList!=null && wptsList.size()>0){
                if(Trigger.oldMap!=null && Trigger.oldMap.containsKey(awt.Id)){
                    Workplan_Type_Stage__c wtsc= (Workplan_Type_Stage__c)Trigger.oldMap.get(awt.Id);
                     wtsc.addError('Error Message - In process workplan type stage can\'t be deleted');
                }
               
            }
         }
	
     }
    T-01 - end */
}